// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
// Each board is validated to have a unique solution reachable by pure
// deduction (no guessing) at generation time.
import type { Level } from '../generator/types'
import level1 from './entries/1'
import level2 from './entries/2'
import level3 from './entries/3'
import level4 from './entries/4'
import level5 from './entries/5'
import level6 from './entries/6'
import level7 from './entries/7'
import level8 from './entries/8'
import level9 from './entries/9'
import level10 from './entries/10'
import level11 from './entries/11'
import level12 from './entries/12'
import level13 from './entries/13'
import level14 from './entries/14'
import level15 from './entries/15'
import level16 from './entries/16'
import level17 from './entries/17'
import level18 from './entries/18'
import level19 from './entries/19'
import level20 from './entries/20'
import level21 from './entries/21'
import level22 from './entries/22'
import level23 from './entries/23'
import level24 from './entries/24'
import level25 from './entries/25'
import level26 from './entries/26'
import level27 from './entries/27'
import level28 from './entries/28'
import level29 from './entries/29'
import level30 from './entries/30'
import level31 from './entries/31'
import level32 from './entries/32'
import level33 from './entries/33'
import level34 from './entries/34'
import level35 from './entries/35'
import level36 from './entries/36'
import level37 from './entries/37'
import level38 from './entries/38'
import level39 from './entries/39'
import level40 from './entries/40'
import level41 from './entries/41'
import level42 from './entries/42'
import level43 from './entries/43'
import level44 from './entries/44'
import level45 from './entries/45'
import level46 from './entries/46'
import level47 from './entries/47'
import level48 from './entries/48'
import level49 from './entries/49'
import level50 from './entries/50'

export const LEVELS: Level[] = [
  level1,
  level2,
  level3,
  level4,
  level5,
  level6,
  level7,
  level8,
  level9,
  level10,
  level11,
  level12,
  level13,
  level14,
  level15,
  level16,
  level17,
  level18,
  level19,
  level20,
  level21,
  level22,
  level23,
  level24,
  level25,
  level26,
  level27,
  level28,
  level29,
  level30,
  level31,
  level32,
  level33,
  level34,
  level35,
  level36,
  level37,
  level38,
  level39,
  level40,
  level41,
  level42,
  level43,
  level44,
  level45,
  level46,
  level47,
  level48,
  level49,
  level50,
]
