// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
// Each board is validated to have a unique solution reachable by pure
// deduction (no guessing) at generation time.
import type { Level } from '../generator/types'
import level1 from './entries/1'
import level2 from './entries/2'
import level3 from './entries/3'
import level4 from './entries/4'
import level5 from './entries/5'
import level6 from './entries/6'
import level7 from './entries/7'
import level8 from './entries/8'
import level9 from './entries/9'
import level10 from './entries/10'
import level11 from './entries/11'
import level12 from './entries/12'
import level13 from './entries/13'
import level14 from './entries/14'
import level15 from './entries/15'
import level16 from './entries/16'
import level17 from './entries/17'
import level18 from './entries/18'
import level19 from './entries/19'
import level20 from './entries/20'
import level21 from './entries/21'
import level22 from './entries/22'
import level23 from './entries/23'
import level24 from './entries/24'
import level25 from './entries/25'
import level26 from './entries/26'
import level27 from './entries/27'
import level28 from './entries/28'
import level29 from './entries/29'
import level30 from './entries/30'
import level31 from './entries/31'
import level32 from './entries/32'
import level33 from './entries/33'
import level34 from './entries/34'
import level35 from './entries/35'
import level36 from './entries/36'
import level37 from './entries/37'
import level38 from './entries/38'
import level39 from './entries/39'
import level40 from './entries/40'
import level41 from './entries/41'
import level42 from './entries/42'
import level43 from './entries/43'
import level44 from './entries/44'
import level45 from './entries/45'
import level46 from './entries/46'
import level47 from './entries/47'
import level48 from './entries/48'
import level49 from './entries/49'
import level50 from './entries/50'
import level51 from './entries/51'
import level52 from './entries/52'
import level53 from './entries/53'
import level54 from './entries/54'
import level55 from './entries/55'
import level56 from './entries/56'
import level57 from './entries/57'
import level58 from './entries/58'
import level59 from './entries/59'
import level60 from './entries/60'
import level61 from './entries/61'
import level62 from './entries/62'
import level63 from './entries/63'
import level64 from './entries/64'
import level65 from './entries/65'
import level66 from './entries/66'
import level67 from './entries/67'
import level68 from './entries/68'
import level69 from './entries/69'
import level70 from './entries/70'
import level71 from './entries/71'
import level72 from './entries/72'
import level73 from './entries/73'
import level74 from './entries/74'
import level75 from './entries/75'
import level76 from './entries/76'
import level77 from './entries/77'
import level78 from './entries/78'
import level79 from './entries/79'
import level80 from './entries/80'
import level81 from './entries/81'
import level82 from './entries/82'
import level83 from './entries/83'
import level84 from './entries/84'
import level85 from './entries/85'
import level86 from './entries/86'
import level87 from './entries/87'
import level88 from './entries/88'
import level89 from './entries/89'
import level90 from './entries/90'
import level91 from './entries/91'
import level92 from './entries/92'
import level93 from './entries/93'
import level94 from './entries/94'
import level95 from './entries/95'
import level96 from './entries/96'
import level97 from './entries/97'
import level98 from './entries/98'
import level99 from './entries/99'
import level100 from './entries/100'
import level101 from './entries/101'
import level102 from './entries/102'
import level103 from './entries/103'
import level104 from './entries/104'
import level105 from './entries/105'
import level106 from './entries/106'
import level107 from './entries/107'
import level108 from './entries/108'
import level109 from './entries/109'
import level110 from './entries/110'
import level111 from './entries/111'
import level112 from './entries/112'
import level113 from './entries/113'
import level114 from './entries/114'
import level115 from './entries/115'
import level116 from './entries/116'
import level117 from './entries/117'
import level118 from './entries/118'
import level119 from './entries/119'
import level120 from './entries/120'
import level121 from './entries/121'
import level122 from './entries/122'
import level123 from './entries/123'
import level124 from './entries/124'
import level125 from './entries/125'
import level126 from './entries/126'
import level127 from './entries/127'
import level128 from './entries/128'
import level129 from './entries/129'
import level130 from './entries/130'
import level131 from './entries/131'
import level132 from './entries/132'
import level133 from './entries/133'
import level134 from './entries/134'
import level135 from './entries/135'
import level136 from './entries/136'
import level137 from './entries/137'
import level138 from './entries/138'
import level139 from './entries/139'
import level140 from './entries/140'
import level141 from './entries/141'
import level142 from './entries/142'
import level143 from './entries/143'
import level144 from './entries/144'
import level145 from './entries/145'
import level146 from './entries/146'
import level147 from './entries/147'
import level148 from './entries/148'
import level149 from './entries/149'
import level150 from './entries/150'
import level151 from './entries/151'
import level152 from './entries/152'
import level153 from './entries/153'
import level154 from './entries/154'
import level155 from './entries/155'
import level156 from './entries/156'
import level157 from './entries/157'
import level158 from './entries/158'
import level159 from './entries/159'
import level160 from './entries/160'
import level161 from './entries/161'
import level162 from './entries/162'
import level163 from './entries/163'
import level164 from './entries/164'
import level165 from './entries/165'
import level166 from './entries/166'
import level167 from './entries/167'
import level168 from './entries/168'
import level169 from './entries/169'
import level170 from './entries/170'
import level171 from './entries/171'
import level172 from './entries/172'
import level173 from './entries/173'
import level174 from './entries/174'
import level175 from './entries/175'
import level176 from './entries/176'
import level177 from './entries/177'
import level178 from './entries/178'
import level179 from './entries/179'
import level180 from './entries/180'
import level181 from './entries/181'
import level182 from './entries/182'
import level183 from './entries/183'
import level184 from './entries/184'
import level185 from './entries/185'
import level186 from './entries/186'
import level187 from './entries/187'
import level188 from './entries/188'
import level189 from './entries/189'
import level190 from './entries/190'
import level191 from './entries/191'
import level192 from './entries/192'
import level193 from './entries/193'
import level194 from './entries/194'
import level195 from './entries/195'
import level196 from './entries/196'
import level197 from './entries/197'
import level198 from './entries/198'
import level199 from './entries/199'
import level200 from './entries/200'
import level201 from './entries/201'
import level202 from './entries/202'
import level203 from './entries/203'
import level204 from './entries/204'
import level205 from './entries/205'
import level206 from './entries/206'
import level207 from './entries/207'
import level208 from './entries/208'
import level209 from './entries/209'
import level210 from './entries/210'
import level211 from './entries/211'
import level212 from './entries/212'
import level213 from './entries/213'
import level214 from './entries/214'
import level215 from './entries/215'
import level216 from './entries/216'
import level217 from './entries/217'
import level218 from './entries/218'
import level219 from './entries/219'
import level220 from './entries/220'
import level221 from './entries/221'
import level222 from './entries/222'
import level223 from './entries/223'
import level224 from './entries/224'
import level225 from './entries/225'
import level226 from './entries/226'
import level227 from './entries/227'
import level228 from './entries/228'
import level229 from './entries/229'
import level230 from './entries/230'
import level231 from './entries/231'
import level232 from './entries/232'
import level233 from './entries/233'
import level234 from './entries/234'
import level235 from './entries/235'
import level236 from './entries/236'
import level237 from './entries/237'
import level238 from './entries/238'
import level239 from './entries/239'
import level240 from './entries/240'
import level241 from './entries/241'
import level242 from './entries/242'
import level243 from './entries/243'
import level244 from './entries/244'
import level245 from './entries/245'
import level246 from './entries/246'
import level247 from './entries/247'
import level248 from './entries/248'
import level249 from './entries/249'
import level250 from './entries/250'
import level251 from './entries/251'
import level252 from './entries/252'
import level253 from './entries/253'
import level254 from './entries/254'
import level255 from './entries/255'
import level256 from './entries/256'
import level257 from './entries/257'
import level258 from './entries/258'
import level259 from './entries/259'
import level260 from './entries/260'
import level261 from './entries/261'
import level262 from './entries/262'
import level263 from './entries/263'
import level264 from './entries/264'
import level265 from './entries/265'
import level266 from './entries/266'
import level267 from './entries/267'
import level268 from './entries/268'
import level269 from './entries/269'
import level270 from './entries/270'
import level271 from './entries/271'
import level272 from './entries/272'
import level273 from './entries/273'
import level274 from './entries/274'
import level275 from './entries/275'
import level276 from './entries/276'
import level277 from './entries/277'
import level278 from './entries/278'
import level279 from './entries/279'
import level280 from './entries/280'
import level281 from './entries/281'
import level282 from './entries/282'
import level283 from './entries/283'
import level284 from './entries/284'
import level285 from './entries/285'
import level286 from './entries/286'
import level287 from './entries/287'
import level288 from './entries/288'
import level289 from './entries/289'
import level290 from './entries/290'
import level291 from './entries/291'
import level292 from './entries/292'
import level293 from './entries/293'
import level294 from './entries/294'
import level295 from './entries/295'
import level296 from './entries/296'
import level297 from './entries/297'
import level298 from './entries/298'
import level299 from './entries/299'
import level300 from './entries/300'
import level301 from './entries/301'
import level302 from './entries/302'
import level303 from './entries/303'
import level304 from './entries/304'
import level305 from './entries/305'
import level306 from './entries/306'
import level307 from './entries/307'
import level308 from './entries/308'
import level309 from './entries/309'
import level310 from './entries/310'
import level311 from './entries/311'
import level312 from './entries/312'
import level313 from './entries/313'
import level314 from './entries/314'
import level315 from './entries/315'
import level316 from './entries/316'
import level317 from './entries/317'
import level318 from './entries/318'
import level319 from './entries/319'
import level320 from './entries/320'
import level321 from './entries/321'
import level322 from './entries/322'
import level323 from './entries/323'
import level324 from './entries/324'
import level325 from './entries/325'
import level326 from './entries/326'
import level327 from './entries/327'
import level328 from './entries/328'
import level329 from './entries/329'
import level330 from './entries/330'
import level331 from './entries/331'
import level332 from './entries/332'
import level333 from './entries/333'
import level334 from './entries/334'
import level335 from './entries/335'
import level336 from './entries/336'
import level337 from './entries/337'
import level338 from './entries/338'
import level339 from './entries/339'
import level340 from './entries/340'
import level341 from './entries/341'
import level342 from './entries/342'
import level343 from './entries/343'
import level344 from './entries/344'
import level345 from './entries/345'
import level346 from './entries/346'
import level347 from './entries/347'
import level348 from './entries/348'
import level349 from './entries/349'
import level350 from './entries/350'
import level351 from './entries/351'
import level352 from './entries/352'
import level353 from './entries/353'
import level354 from './entries/354'
import level355 from './entries/355'
import level356 from './entries/356'
import level357 from './entries/357'
import level358 from './entries/358'
import level359 from './entries/359'
import level360 from './entries/360'
import level361 from './entries/361'
import level362 from './entries/362'
import level363 from './entries/363'
import level364 from './entries/364'
import level365 from './entries/365'
import level366 from './entries/366'
import level367 from './entries/367'
import level368 from './entries/368'
import level369 from './entries/369'
import level370 from './entries/370'
import level371 from './entries/371'
import level372 from './entries/372'
import level373 from './entries/373'
import level374 from './entries/374'
import level375 from './entries/375'
import level376 from './entries/376'
import level377 from './entries/377'
import level378 from './entries/378'
import level379 from './entries/379'
import level380 from './entries/380'
import level381 from './entries/381'
import level382 from './entries/382'
import level383 from './entries/383'
import level384 from './entries/384'
import level385 from './entries/385'
import level386 from './entries/386'
import level387 from './entries/387'
import level388 from './entries/388'
import level389 from './entries/389'
import level390 from './entries/390'
import level391 from './entries/391'
import level392 from './entries/392'
import level393 from './entries/393'
import level394 from './entries/394'
import level395 from './entries/395'
import level396 from './entries/396'
import level397 from './entries/397'
import level398 from './entries/398'
import level399 from './entries/399'
import level400 from './entries/400'
import level401 from './entries/401'
import level402 from './entries/402'
import level403 from './entries/403'
import level404 from './entries/404'
import level405 from './entries/405'
import level406 from './entries/406'
import level407 from './entries/407'
import level408 from './entries/408'

export const LEVELS: Level[] = [
  level1,
  level2,
  level3,
  level4,
  level5,
  level6,
  level7,
  level8,
  level9,
  level10,
  level11,
  level12,
  level13,
  level14,
  level15,
  level16,
  level17,
  level18,
  level19,
  level20,
  level21,
  level22,
  level23,
  level24,
  level25,
  level26,
  level27,
  level28,
  level29,
  level30,
  level31,
  level32,
  level33,
  level34,
  level35,
  level36,
  level37,
  level38,
  level39,
  level40,
  level41,
  level42,
  level43,
  level44,
  level45,
  level46,
  level47,
  level48,
  level49,
  level50,
  level51,
  level52,
  level53,
  level54,
  level55,
  level56,
  level57,
  level58,
  level59,
  level60,
  level61,
  level62,
  level63,
  level64,
  level65,
  level66,
  level67,
  level68,
  level69,
  level70,
  level71,
  level72,
  level73,
  level74,
  level75,
  level76,
  level77,
  level78,
  level79,
  level80,
  level81,
  level82,
  level83,
  level84,
  level85,
  level86,
  level87,
  level88,
  level89,
  level90,
  level91,
  level92,
  level93,
  level94,
  level95,
  level96,
  level97,
  level98,
  level99,
  level100,
  level101,
  level102,
  level103,
  level104,
  level105,
  level106,
  level107,
  level108,
  level109,
  level110,
  level111,
  level112,
  level113,
  level114,
  level115,
  level116,
  level117,
  level118,
  level119,
  level120,
  level121,
  level122,
  level123,
  level124,
  level125,
  level126,
  level127,
  level128,
  level129,
  level130,
  level131,
  level132,
  level133,
  level134,
  level135,
  level136,
  level137,
  level138,
  level139,
  level140,
  level141,
  level142,
  level143,
  level144,
  level145,
  level146,
  level147,
  level148,
  level149,
  level150,
  level151,
  level152,
  level153,
  level154,
  level155,
  level156,
  level157,
  level158,
  level159,
  level160,
  level161,
  level162,
  level163,
  level164,
  level165,
  level166,
  level167,
  level168,
  level169,
  level170,
  level171,
  level172,
  level173,
  level174,
  level175,
  level176,
  level177,
  level178,
  level179,
  level180,
  level181,
  level182,
  level183,
  level184,
  level185,
  level186,
  level187,
  level188,
  level189,
  level190,
  level191,
  level192,
  level193,
  level194,
  level195,
  level196,
  level197,
  level198,
  level199,
  level200,
  level201,
  level202,
  level203,
  level204,
  level205,
  level206,
  level207,
  level208,
  level209,
  level210,
  level211,
  level212,
  level213,
  level214,
  level215,
  level216,
  level217,
  level218,
  level219,
  level220,
  level221,
  level222,
  level223,
  level224,
  level225,
  level226,
  level227,
  level228,
  level229,
  level230,
  level231,
  level232,
  level233,
  level234,
  level235,
  level236,
  level237,
  level238,
  level239,
  level240,
  level241,
  level242,
  level243,
  level244,
  level245,
  level246,
  level247,
  level248,
  level249,
  level250,
  level251,
  level252,
  level253,
  level254,
  level255,
  level256,
  level257,
  level258,
  level259,
  level260,
  level261,
  level262,
  level263,
  level264,
  level265,
  level266,
  level267,
  level268,
  level269,
  level270,
  level271,
  level272,
  level273,
  level274,
  level275,
  level276,
  level277,
  level278,
  level279,
  level280,
  level281,
  level282,
  level283,
  level284,
  level285,
  level286,
  level287,
  level288,
  level289,
  level290,
  level291,
  level292,
  level293,
  level294,
  level295,
  level296,
  level297,
  level298,
  level299,
  level300,
  level301,
  level302,
  level303,
  level304,
  level305,
  level306,
  level307,
  level308,
  level309,
  level310,
  level311,
  level312,
  level313,
  level314,
  level315,
  level316,
  level317,
  level318,
  level319,
  level320,
  level321,
  level322,
  level323,
  level324,
  level325,
  level326,
  level327,
  level328,
  level329,
  level330,
  level331,
  level332,
  level333,
  level334,
  level335,
  level336,
  level337,
  level338,
  level339,
  level340,
  level341,
  level342,
  level343,
  level344,
  level345,
  level346,
  level347,
  level348,
  level349,
  level350,
  level351,
  level352,
  level353,
  level354,
  level355,
  level356,
  level357,
  level358,
  level359,
  level360,
  level361,
  level362,
  level363,
  level364,
  level365,
  level366,
  level367,
  level368,
  level369,
  level370,
  level371,
  level372,
  level373,
  level374,
  level375,
  level376,
  level377,
  level378,
  level379,
  level380,
  level381,
  level382,
  level383,
  level384,
  level385,
  level386,
  level387,
  level388,
  level389,
  level390,
  level391,
  level392,
  level393,
  level394,
  level395,
  level396,
  level397,
  level398,
  level399,
  level400,
  level401,
  level402,
  level403,
  level404,
  level405,
  level406,
  level407,
  level408,
]
