// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
// Each board is validated to have a unique solution reachable by pure
// deduction (no guessing) at generation time.
import type { Level } from '../generator/types'
import level1 from './entries/1'
import level2 from './entries/2'
import level3 from './entries/3'
import level4 from './entries/4'
import level5 from './entries/5'
import level6 from './entries/6'
import level7 from './entries/7'
import level8 from './entries/8'
import level9 from './entries/9'
import level10 from './entries/10'
import level11 from './entries/11'
import level12 from './entries/12'
import level13 from './entries/13'
import level14 from './entries/14'
import level15 from './entries/15'
import level16 from './entries/16'
import level17 from './entries/17'
import level18 from './entries/18'
import level19 from './entries/19'
import level20 from './entries/20'

export const LEVELS: Level[] = [
  level1,
  level2,
  level3,
  level4,
  level5,
  level6,
  level7,
  level8,
  level9,
  level10,
  level11,
  level12,
  level13,
  level14,
  level15,
  level16,
  level17,
  level18,
  level19,
  level20,
]
