// Run with: npx tsx scripts/generate-levels.ts
// Generates static levels and (re)writes lib/levels/data.ts.
// Safe to re-run later (e.g. from a cron job) to append more levels —
// bump LEVEL_SIZES / start ids after the current max instead of
// overwriting when doing so.
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { generateLevel } from "../lib/generator/generate";

const MIN_SIZE = 5;
const MAX_SIZE = 18;
const LEVEL_COUNT = 5;

// Level difficulty (color count) is NOT ordered by level number — level 3
// might have more colors than level 4. Pick distinct random sizes so
// re-running (e.g. from a future cron job appending levels) doesn't
// produce a predictable ramp.
function randomSizes(count: number): number[] {
  const pool = Array.from({ length: MAX_SIZE - MIN_SIZE + 1 }, (_, i) => MIN_SIZE + i);
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, count);
}

function main() {
  const sizes = randomSizes(LEVEL_COUNT);
  const levels = sizes.map((size, i) => generateLevel(String(i + 1), size));

  const body = levels
    .map(
      (level) => `  {
    id: ${JSON.stringify(level.id)},
    size: ${level.size},
    colorCount: ${level.colorCount},
    regions: ${JSON.stringify(level.regions)},
  },`
    )
    .join("\n");

  const output = `// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
// Each board is validated to have exactly one solution at generation time.
import type { Level } from "../generator/types";

export const LEVELS: Level[] = [
${body}
];
`;

  const outPath = join(__dirname, "..", "lib", "levels", "data.ts");
  writeFileSync(outPath, output, "utf-8");
  console.log(`Wrote ${levels.length} levels to ${outPath}`);
  levels.forEach((l) => console.log(`  level ${l.id}: ${l.size}x${l.size}, ${l.colorCount} colors`));
}

main();
