// Run with: npx tsx scripts/generate-levels.ts [count]
// Generates `count` new levels in parallel (one child process per level,
// capped at the machine's core count) and writes each one to its own file
// under lib/levels/entries/ as soon as it finishes — no waiting for the
// whole batch. lib/levels/data.ts is a generated index over those files;
// it's rewritten after every individual level completes.
import { fork } from 'node:child_process'
import { mkdirSync, readdirSync, writeFileSync } from 'node:fs'
import { cpus } from 'node:os'
import { join } from 'node:path'
import type { Level } from '../lib/generator/types'

const MIN_SIZE = 5
const MAX_SIZE = 18

const entriesDir = join(__dirname, '..', 'lib', 'levels', 'entries')
const dataPath = join(__dirname, '..', 'lib', 'levels', 'data.ts')
const workerPath = join(__dirname, 'generate-level-worker.ts')

function existingIds(): number[] {
  mkdirSync(entriesDir, { recursive: true })
  return readdirSync(entriesDir)
    .filter(f => f.endsWith('.ts'))
    .map(f => Number(f.slice(0, -3)))
    .filter(n => Number.isFinite(n))
}

// Colors: level difficulty is NOT ordered by level number — a later level
// might have fewer colors than an earlier one. Picking a fresh random size
// each run (rather than ramping up) keeps that intentional, so a long-
// running cron job doesn't drift toward "level N = size N" predictability.
function randomSize(): number {
  return MIN_SIZE + Math.floor(Math.random() * (MAX_SIZE - MIN_SIZE + 1))
}

function entryFileSource(level: Level): string {
  return `// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: ${JSON.stringify(level.id)},
  regions: ${JSON.stringify(level.regions)},
  hasUniqueSolution: ${level.hasUniqueSolution},
}

export default level
`
}

function writeIndex(ids: number[]) {
  const sorted = [...ids].sort((a, b) => a - b)
  const imports = sorted.map(id => `import level${id} from './entries/${id}'`).join('\n')
  const body = sorted.map(id => `  level${id},`).join('\n')
  const output = `// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
// Each board is validated to have a unique solution reachable by pure
// deduction (no guessing) at generation time.
import type { Level } from '../generator/types'
${imports}

export const LEVELS: Level[] = [
${body}
]
`
  writeFileSync(dataPath, output, 'utf-8')
}

function runWorker(id: string, size: number): Promise<Level> {
  return new Promise((resolve, reject) => {
    const child = fork(workerPath, [id, String(size)], { execArgv: ['--require', 'tsx/cjs'] })
    child.on('message', (level: Level) => resolve(level))
    child.on('error', reject)
    child.on('exit', code => {
      if (code !== 0) reject(new Error(`worker for level ${id} exited with code ${code}`))
    })
  })
}

async function main() {
  const count = Number(process.argv[2]) || 1
  const ids = existingIds()
  const startId = Math.max(0, ...ids) + 1
  const tasks = Array.from({ length: count }, (_, i) => ({ id: String(startId + i), size: randomSize() }))

  const concurrency = Math.max(1, Math.min(cpus().length, tasks.length))
  let nextTask = 0

  async function worker() {
    while (nextTask < tasks.length) {
      const task = tasks[nextTask++]
      const level = await runWorker(task.id, task.size)
      writeFileSync(join(entriesDir, `${level.id}.ts`), entryFileSource(level), 'utf-8')
      ids.push(Number(level.id))
      writeIndex(ids)
      console.log(`Generated level ${level.id}: ${level.regions.length}x${level.regions.length}, ${level.regions.length} colors`)
    }
  }

  await Promise.all(Array.from({ length: concurrency }, worker))

  const endId = startId + count - 1
  const range = count > 1 ? `${startId}-${endId}` : String(startId)
  if (process.env.GITHUB_OUTPUT) {
    writeFileSync(process.env.GITHUB_OUTPUT, `level_range=${range}\n`, { flag: 'a' })
  }
}

main()
