// Run with: npx tsx scripts/generate-levels.ts [count]
// Appends `count` (default 1) new levels to lib/levels/data.ts, picking up
// ids after the current max. Meant to be safe to run unattended on a
// schedule (see .github/workflows/generate-level.yml) — each run only
// adds levels, it never touches the ones already there.
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { generateLevel } from '../lib/generator/generate'
import { LEVELS } from '../lib/levels/data'
import type { Level } from '../lib/generator/types'

const MIN_SIZE = 6
const MAX_SIZE = 11

function nextId(existing: Level[]): number {
  const maxId = existing.reduce((max, l) => Math.max(max, Number(l.id) || 0), 0)
  return maxId + 1
}

// Colors: level difficulty is NOT ordered by level number — a later level
// might have fewer colors than an earlier one. Picking a fresh random size
// each run (rather than ramping up) keeps that intentional, so a long-
// running cron job doesn't drift toward "level N = size N" predictability.
function randomSize(): number {
  return MIN_SIZE + Math.floor(Math.random() * (MAX_SIZE - MIN_SIZE + 1))
}

function main() {
  const count = Number(process.argv[2]) || 1
  const startId = nextId(LEVELS)

  const newLevels = Array.from({ length: count }, (_, i) => generateLevel(String(startId + i), randomSize()))
  const levels = [...LEVELS, ...newLevels]

  const body = levels
    .map(
      level => `  {
    id: ${JSON.stringify(level.id)},
    regions: ${JSON.stringify(level.regions)},
  },`
    )
    .join('\n')

  const output = `// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
// Each board is validated to have a unique solution reachable by pure
// deduction (no guessing) at generation time.
import type { Level } from "../generator/types";

export const LEVELS: Level[] = [
${body}
];
`

  const outPath = join(__dirname, '..', 'lib', 'levels', 'data.ts')
  writeFileSync(outPath, output, 'utf-8')
  console.log(`Appended ${newLevels.length} level(s) to ${outPath}`)
  newLevels.forEach(l => console.log(`  level ${l.id}: ${l.regions.length}x${l.regions.length}, ${l.regions.length} colors`))
}

main()
