// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '1',
  regions: [
    ['A', 'D', 'G', 'G', 'G', 'B', 'C'],
    ['A', 'D', 'G', 'B', 'B', 'B', 'C'],
    ['A', 'A', 'A', 'C', 'C', 'B', 'C'],
    ['A', 'A', 'A', 'C', 'C', 'C', 'C'],
    ['A', 'A', 'A', 'C', 'A', 'C', 'C'],
    ['E', 'F', 'A', 'A', 'A', 'C', 'C'],
    ['E', 'F', 'F', 'F', 'C', 'C', 'C']
  ],
  hasUniqueSolution: true
}

export default level
