// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "1",
  regions: [["D","B","A","A","A","C","E"],["D","B","A","C","C","C","E"],["D","D","D","E","E","C","E"],["D","D","D","E","E","E","E"],["D","D","D","E","D","E","E"],["F","G","D","D","D","E","E"],["F","G","G","G","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
