// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '10',
  regions: [
    ['A', 'A', 'I', 'I', 'I', 'I', 'I', 'I', 'I', 'N', 'K', 'K', 'K', 'K', 'K', 'K', 'K'],
    ['A', 'A', 'I', 'I', 'I', 'I', 'N', 'N', 'N', 'N', 'K', 'M', 'M', 'O', 'K', 'K', 'K'],
    ['I', 'A', 'A', 'A', 'I', 'I', 'N', 'N', 'N', 'N', 'K', 'M', 'O', 'O', 'O', 'O', 'K'],
    ['I', 'A', 'I', 'A', 'A', 'I', 'N', 'N', 'O', 'O', 'O', 'O', 'O', 'O', 'K', 'K', 'K'],
    ['I', 'I', 'I', 'I', 'I', 'I', 'I', 'N', 'N', 'O', 'O', 'O', 'D', 'O', 'O', 'K', 'K'],
    ['I', 'L', 'L', 'I', 'I', 'I', 'I', 'I', 'N', 'O', 'O', 'D', 'D', 'D', 'O', 'K', 'O'],
    ['I', 'I', 'L', 'L', 'I', 'N', 'I', 'N', 'N', 'O', 'O', 'D', 'D', 'O', 'O', 'O', 'O'],
    ['L', 'L', 'L', 'L', 'N', 'N', 'N', 'N', 'N', 'O', 'O', 'O', 'D', 'D', 'Q', 'Q', 'O'],
    ['L', 'E', 'E', 'L', 'L', 'N', 'N', 'N', 'D', 'D', 'J', 'J', 'C', 'D', 'Q', 'Q', 'Q'],
    ['L', 'F', 'E', 'E', 'L', 'L', 'L', 'N', 'N', 'D', 'C', 'C', 'C', 'D', 'D', 'D', 'Q'],
    ['L', 'F', 'F', 'F', 'L', 'F', 'L', 'N', 'N', 'D', 'D', 'C', 'D', 'D', 'H', 'D', 'Q'],
    ['L', 'L', 'F', 'F', 'F', 'F', 'L', 'L', 'N', 'N', 'D', 'D', 'D', 'D', 'H', 'D', 'G'],
    ['L', 'F', 'F', 'F', 'F', 'F', 'F', 'L', 'L', 'N', 'D', 'H', 'H', 'H', 'H', 'D', 'G'],
    ['L', 'F', 'L', 'F', 'L', 'F', 'F', 'L', 'L', 'D', 'D', 'D', 'H', 'D', 'D', 'D', 'G'],
    ['L', 'L', 'L', 'L', 'L', 'L', 'F', 'F', 'L', 'L', 'D', 'H', 'H', 'D', 'D', 'D', 'D'],
    ['L', 'P', 'L', 'L', 'L', 'F', 'F', 'B', 'B', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'D'],
    ['P', 'P', 'P', 'L', 'L', 'F', 'F', 'B', 'B', 'H', 'D', 'D', 'D', 'D', 'D', 'D', 'D']
  ],
  hasUniqueSolution: true
}

export default level
