// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '10',
  regions: [
    ['A', 'A', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'G', 'E', 'E', 'E', 'E', 'E', 'E', 'E'],
    ['A', 'A', 'C', 'C', 'C', 'C', 'G', 'G', 'G', 'G', 'E', 'B', 'B', 'D', 'E', 'E', 'E'],
    ['C', 'A', 'A', 'A', 'C', 'C', 'G', 'G', 'G', 'G', 'E', 'B', 'D', 'D', 'D', 'D', 'E'],
    ['C', 'A', 'C', 'A', 'A', 'C', 'G', 'G', 'D', 'D', 'D', 'D', 'D', 'D', 'E', 'E', 'E'],
    ['C', 'C', 'C', 'C', 'C', 'C', 'C', 'G', 'G', 'D', 'D', 'D', 'N', 'D', 'D', 'E', 'E'],
    ['C', 'F', 'F', 'C', 'C', 'C', 'C', 'C', 'G', 'D', 'D', 'N', 'N', 'N', 'D', 'E', 'D'],
    ['C', 'C', 'F', 'F', 'C', 'G', 'C', 'G', 'G', 'D', 'D', 'N', 'N', 'D', 'D', 'D', 'D'],
    ['F', 'F', 'F', 'F', 'G', 'G', 'G', 'G', 'G', 'D', 'D', 'D', 'N', 'N', 'H', 'H', 'D'],
    ['F', 'J', 'J', 'F', 'F', 'G', 'G', 'G', 'N', 'N', 'I', 'I', 'K', 'N', 'H', 'H', 'H'],
    ['F', 'O', 'J', 'J', 'F', 'F', 'F', 'G', 'G', 'N', 'K', 'K', 'K', 'N', 'N', 'N', 'H'],
    ['F', 'O', 'O', 'O', 'F', 'O', 'F', 'G', 'G', 'N', 'N', 'K', 'N', 'N', 'M', 'N', 'H'],
    ['F', 'F', 'O', 'O', 'O', 'O', 'F', 'F', 'G', 'G', 'N', 'N', 'N', 'N', 'M', 'N', 'L'],
    ['F', 'O', 'O', 'O', 'O', 'O', 'O', 'F', 'F', 'G', 'N', 'M', 'M', 'M', 'M', 'N', 'L'],
    ['F', 'O', 'F', 'O', 'F', 'O', 'O', 'F', 'F', 'N', 'N', 'N', 'M', 'N', 'N', 'N', 'L'],
    ['F', 'F', 'F', 'F', 'F', 'F', 'O', 'O', 'F', 'F', 'N', 'M', 'M', 'N', 'N', 'N', 'N'],
    ['F', 'P', 'F', 'F', 'F', 'O', 'O', 'Q', 'Q', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'N'],
    ['P', 'P', 'P', 'F', 'F', 'O', 'O', 'Q', 'Q', 'M', 'N', 'N', 'N', 'N', 'N', 'N', 'N']
  ],
  hasUniqueSolution: true
}

export default level
