// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "100",
  regions: [["H","H","H","H","M","M","M","M","M","M","M","M","M","M"],["H","H","H","F","F","M","M","M","F","F","M","F","F","M"],["H","F","F","F","F","F","F","F","F","F","F","F","M","M"],["H","F","H","F","C","C","C","C","C","C","F","L","M","M"],["H","H","H","C","C","A","C","G","G","C","F","L","L","M"],["H","H","H","H","C","A","A","G","G","B","B","B","L","B"],["H","H","C","H","C","N","A","A","G","G","B","B","B","B"],["H","C","C","C","C","N","B","B","B","G","G","B","B","I"],["H","C","C","C","C","N","J","J","B","G","G","B","B","I"],["H","H","H","H","C","B","B","B","B","B","B","B","B","I"],["H","H","H","C","C","C","B","B","B","B","E","I","I","I"],["D","H","D","D","D","C","B","K","B","E","E","B","I","B"],["D","H","D","D","C","C","K","K","B","B","B","B","B","B"],["D","D","D","C","C","K","K","K","K","K","K","K","B","B"]],
  hasUniqueSolution: true,
}

export default level
