// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "101",
  regions: [["C","C","C","I","I","I","I","E","E","E","E","E","F","F"],["C","C","I","I","I","I","E","E","E","K","K","E","E","F"],["C","C","C","C","I","I","E","E","D","L","L","L","E","F"],["C","J","C","C","C","E","E","D","D","D","L","L","L","F"],["C","J","C","C","C","J","E","D","D","L","L","N","F","F"],["C","J","C","C","C","J","H","D","D","L","D","N","F","F"],["C","J","C","J","J","J","H","H","D","D","D","N","N","F"],["C","I","J","J","G","G","G","G","D","F","F","F","F","F"],["C","J","J","J","J","J","G","G","D","D","F","F","G","F"],["C","J","J","J","J","J","G","G","G","G","M","F","G","F"],["C","B","B","J","J","J","J","J","J","G","M","F","G","F"],["C","C","B","B","B","B","J","J","G","G","F","F","G","F"],["B","C","C","C","B","J","J","J","J","G","G","F","G","G"],["B","B","B","B","B","J","A","A","A","G","G","G","G","G"]],
  hasUniqueSolution: true,
}

export default level
