// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "102",
  regions: [["I","I","I","I","I","H","H","A","A","H"],["C","C","C","H","H","H","H","H","A","H"],["C","C","C","C","H","F","H","H","H","H"],["E","C","C","C","F","F","F","J","J","H"],["E","E","C","C","C","F","F","J","H","H"],["B","B","D","C","C","C","F","F","F","H"],["B","D","D","D","C","F","F","H","H","H"],["B","B","D","G","F","F","H","H","H","H"],["B","D","D","G","F","H","H","H","H","F"],["B","D","G","G","F","F","F","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
