// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "103",
  regions: [["E","E","E","E","E","E","E","B"],["F","F","D","D","B","B","E","B"],["F","D","D","A","B","E","E","B"],["F","D","C","A","B","B","B","B"],["D","D","C","C","C","B","B","B"],["D","D","C","C","C","B","C","B"],["D","G","C","H","C","C","C","C"],["G","G","H","H","H","H","C","C"]],
  hasUniqueSolution: true,
}

export default level
