// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "104",
  regions: [["B","B","B","E","E","E"],["B","B","B","E","E","E"],["B","B","F","F","F","D"],["C","C","F","D","D","D"],["C","A","F","D","D","D"],["C","A","A","D","D","D"]],
  hasUniqueSolution: false,
}

export default level
