// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "105",
  regions: [["K","K","K","K","K","C","C","C","C","C","F","F","F"],["K","K","K","K","K","C","C","C","C","B","F","F","F"],["K","K","K","K","C","C","C","C","C","B","B","F","F"],["K","K","K","K","C","C","C","C","C","B","B","E","F"],["K","J","J","J","L","L","L","M","M","B","B","E","F"],["K","J","J","J","L","A","L","M","M","B","B","E","E"],["K","H","D","D","A","A","L","M","M","B","B","B","E"],["H","H","D","D","A","A","A","M","M","B","I","I","I"],["H","D","D","D","A","A","A","M","M","B","B","B","I"],["H","D","D","D","A","A","A","M","M","B","I","I","I"],["H","D","D","G","G","A","A","A","M","B","I","I","I"],["H","H","H","G","G","G","G","A","M","B","M","I","I"],["H","H","H","H","G","G","G","A","M","M","M","M","M"]],
  hasUniqueSolution: false,
}

export default level
