// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "106",
  regions: [["B","N","N","N","N","N","K","K","K","A","A","A","A","A"],["B","B","N","D","D","N","N","N","K","K","K","A","G","A"],["B","N","N","N","D","N","D","A","A","K","K","A","G","A"],["B","N","D","N","D","D","D","A","K","K","A","A","I","A"],["N","N","D","D","D","L","D","A","A","A","A","A","I","I"],["N","D","D","D","L","L","D","D","D","D","D","A","E","E"],["L","D","L","L","L","L","D","D","D","C","D","A","F","E"],["L","L","L","L","L","D","D","D","C","C","F","F","F","E"],["L","L","L","L","L","D","D","D","C","C","F","F","C","E"],["L","M","L","L","C","C","C","C","C","C","C","C","C","E"],["L","M","L","L","C","M","M","C","C","C","E","C","E","E"],["L","M","M","M","M","M","M","J","J","C","E","H","H","E"],["L","M","M","J","J","J","J","J","E","E","E","E","E","E"],["L","L","M","M","J","J","J","J","J","E","E","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
