// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "107",
  regions: [["E","E","D","D","D","D","O","O","O","O","O","O","O","O","O","D","D"],["E","E","L","K","K","D","D","D","D","O","D","D","O","D","D","D","D"],["G","E","L","L","K","K","K","D","D","D","D","D","D","D","K","D","D"],["G","G","G","L","K","K","K","K","K","K","K","D","D","K","K","D","D"],["G","L","L","L","L","K","K","P","K","K","K","K","K","K","K","D","D"],["G","L","L","G","L","K","P","P","K","P","K","K","K","P","D","D","D"],["G","L","G","G","L","L","G","P","K","P","P","P","K","P","D","D","B"],["G","L","G","G","L","G","G","P","P","P","P","P","P","P","D","B","B"],["G","G","G","G","L","G","C","C","C","C","P","C","P","P","P","P","C"],["G","G","G","L","L","G","C","H","C","C","C","C","P","P","P","C","C"],["G","G","G","L","L","G","H","H","G","G","G","C","C","C","C","C","M"],["G","G","G","G","G","G","G","G","G","G","G","F","C","C","M","M","M"],["G","N","N","N","N","G","G","N","G","I","I","F","C","C","C","M","C"],["G","N","N","N","N","N","N","N","G","G","I","F","A","A","C","C","C"],["G","G","N","N","Q","Q","Q","Q","Q","Q","I","F","A","A","C","C","C"],["G","N","N","N","N","N","N","Q","F","F","F","F","Q","Q","Q","Q","C"],["G","N","N","N","N","N","N","Q","K","Q","Q","Q","Q","J","J","J","C"]],
  hasUniqueSolution: true,
}

export default level
