// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "108",
  regions: [["D","B","B","B","C","C","C"],["D","G","G","C","C","C","E"],["D","G","G","C","F","F","E"],["G","G","G","C","G","G","E"],["G","G","G","G","G","G","E"],["G","A","A","A","G","G","E"],["G","G","G","A","A","A","E"]],
  hasUniqueSolution: true,
}

export default level
