// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "109",
  regions: [["H","H","E","E","B","F","F","F","D"],["H","H","C","E","B","F","F","D","D"],["C","H","C","B","B","D","D","D","D"],["C","H","C","B","B","B","D","D","D"],["C","C","C","C","C","B","B","D","D"],["C","C","C","A","A","B","B","D","D"],["C","G","G","A","B","B","I","D","D"],["C","A","A","A","A","D","I","D","D"],["A","A","A","A","D","D","D","D","D"]],
  hasUniqueSolution: true,
}

export default level
