// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '11',
  regions: [
    ['L', 'L', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'D', 'D'],
    ['L', 'A', 'A', 'L', 'L', 'A', 'A', 'A', 'G', 'G', 'K', 'D'],
    ['L', 'L', 'L', 'L', 'A', 'A', 'C', 'A', 'A', 'D', 'K', 'D'],
    ['L', 'A', 'A', 'A', 'A', 'L', 'C', 'C', 'D', 'D', 'D', 'D'],
    ['L', 'L', 'A', 'A', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'D'],
    ['J', 'L', 'L', 'L', 'L', 'H', 'L', 'L', 'D', 'L', 'D', 'D'],
    ['J', 'J', 'L', 'H', 'H', 'H', 'H', 'D', 'D', 'D', 'D', 'F'],
    ['B', 'J', 'L', 'H', 'B', 'B', 'H', 'H', 'D', 'D', 'D', 'F'],
    ['B', 'J', 'L', 'L', 'L', 'B', 'B', 'H', 'H', 'H', 'H', 'F'],
    ['B', 'B', 'B', 'B', 'L', 'B', 'F', 'H', 'H', 'F', 'F', 'F'],
    ['B', 'E', 'B', 'B', 'B', 'B', 'F', 'F', 'F', 'F', 'I', 'F'],
    ['B', 'E', 'E', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'I', 'I']
  ],
  hasUniqueSolution: true
}

export default level
