// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '11',
  regions: [
    ['E', 'E', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'G', 'G'],
    ['E', 'A', 'A', 'E', 'E', 'A', 'A', 'A', 'B', 'B', 'C', 'G'],
    ['E', 'E', 'E', 'E', 'A', 'A', 'D', 'A', 'A', 'G', 'C', 'G'],
    ['E', 'A', 'A', 'A', 'A', 'E', 'D', 'D', 'G', 'G', 'G', 'G'],
    ['E', 'E', 'A', 'A', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'G'],
    ['F', 'E', 'E', 'E', 'E', 'H', 'E', 'E', 'G', 'E', 'G', 'G'],
    ['F', 'F', 'E', 'H', 'H', 'H', 'H', 'G', 'G', 'G', 'G', 'J'],
    ['I', 'F', 'E', 'H', 'I', 'I', 'H', 'H', 'G', 'G', 'G', 'J'],
    ['I', 'F', 'E', 'E', 'E', 'I', 'I', 'H', 'H', 'H', 'H', 'J'],
    ['I', 'I', 'I', 'I', 'E', 'I', 'J', 'H', 'H', 'J', 'J', 'J'],
    ['I', 'K', 'I', 'I', 'I', 'I', 'J', 'J', 'J', 'J', 'L', 'J'],
    ['I', 'K', 'K', 'I', 'I', 'I', 'I', 'I', 'I', 'I', 'L', 'L']
  ],
  hasUniqueSolution: true
}

export default level
