// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "110",
  regions: [["J","J","J","J","B","B","B","B","B","B","B"],["J","E","E","J","J","J","B","B","C","C","B"],["E","E","E","E","J","B","B","B","F","C","F"],["E","E","E","E","E","B","H","F","F","F","F"],["E","G","G","E","E","H","H","F","K","F","F"],["E","G","I","I","E","E","F","F","K","F","F"],["E","E","I","I","E","E","E","F","K","K","F"],["E","E","E","I","I","E","E","K","K","K","K"],["E","I","I","I","I","E","E","K","A","K","K"],["E","E","I","I","I","E","K","K","A","A","D"],["E","E","I","I","E","E","E","K","A","A","D"]],
  hasUniqueSolution: true,
}

export default level
