// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "111",
  regions: [["E","A","A","A","A"],["E","A","A","A","A"],["B","B","A","C","A"],["B","B","D","C","C"],["D","D","D","D","C"]],
  hasUniqueSolution: true,
}

export default level
