// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "112",
  regions: [["G","G","G","G","G","I","I","I","I","I"],["G","D","D","G","G","F","E","E","I","I"],["G","G","D","B","G","F","F","F","F","I"],["G","G","D","B","G","G","F","D","I","I"],["J","G","D","D","D","D","D","D","D","D"],["J","G","D","C","C","D","D","D","D","D"],["J","G","D","C","A","A","A","A","D","D"],["J","D","D","C","A","C","C","H","D","H"],["J","D","J","C","C","C","C","H","H","H"],["J","J","J","J","C","C","C","C","C","H"]],
  hasUniqueSolution: true,
}

export default level
