// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "113",
  regions: [["A","A","A","A","A","A","A","J","D","D","D"],["E","E","E","E","A","A","H","J","D","G","G"],["E","A","A","A","A","A","H","H","D","G","G"],["E","E","F","A","C","A","C","G","D","G","G"],["E","F","F","C","C","C","C","G","G","G","K"],["E","F","F","F","C","C","G","G","G","G","K"],["E","F","F","F","C","C","C","G","C","C","K"],["E","F","F","F","B","C","C","C","C","K","K"],["E","E","F","I","B","B","B","B","B","B","B"],["E","E","F","I","I","I","B","B","B","B","B"],["E","E","I","I","I","I","I","I","I","B","B"]],
  hasUniqueSolution: true,
}

export default level
