// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "114",
  regions: [["B","B","B","F","L","L","L","L","L","L","L","L"],["C","C","B","F","E","E","E","L","E","E","L","E"],["B","B","B","B","B","E","L","L","E","E","E","E"],["B","B","B","K","K","E","E","E","E","E","E","E"],["B","K","K","K","K","K","K","E","I","E","E","E"],["B","K","K","J","J","K","I","I","I","I","I","E"],["B","B","K","J","J","K","K","G","G","I","I","J"],["B","B","K","J","J","K","D","G","G","I","J","J"],["K","K","K","K","J","J","D","G","I","I","J","J"],["H","K","K","K","J","J","J","I","I","I","A","J"],["H","H","K","K","K","J","J","J","J","J","A","J"],["K","K","K","K","K","J","J","J","J","J","J","J"]],
  hasUniqueSolution: true,
}

export default level
