// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "115",
  regions: [["D","D","D","A","A","G","O","O","O","O","O","O","E","E","E","E"],["D","N","A","A","G","G","O","H","E","E","O","E","E","E","B","B"],["N","N","A","A","G","G","G","H","H","E","E","E","E","E","B","B"],["N","A","A","F","G","G","H","H","E","E","E","E","E","E","E","M"],["N","A","F","F","F","F","H","H","H","H","H","E","E","E","P","M"],["N","N","N","N","N","F","F","H","H","H","H","E","E","P","P","M"],["K","K","K","K","N","F","F","F","F","H","H","H","P","P","P","M"],["J","J","K","K","N","F","N","N","F","F","H","H","H","H","M","M"],["J","K","K","N","N","N","N","N","F","H","H","M","M","M","M","M"],["J","J","K","N","F","F","F","F","F","F","M","M","M","M","M","M"],["J","K","K","N","N","I","I","F","F","F","M","M","M","M","C","M"],["J","J","K","N","I","I","I","F","I","I","M","I","M","M","C","C"],["J","J","K","N","I","I","F","F","F","I","I","I","M","C","C","C"],["J","N","N","N","I","I","I","I","I","I","I","I","M","C","C","C"],["J","J","N","I","I","J","I","I","M","I","I","M","M","C","L","C"],["J","J","J","J","J","J","J","M","M","M","M","M","C","C","L","L"]],
  hasUniqueSolution: true,
}

export default level
