// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "116",
  regions: [["C","C","C","C","C","E","E","G","G","G","B","B","B","B"],["C","C","C","C","C","E","E","E","G","G","B","B","B","B"],["C","I","I","I","I","E","E","E","E","E","B","B","B","B"],["C","I","I","I","I","I","I","E","E","A","A","A","A","B"],["C","I","I","I","I","I","I","J","J","A","A","B","B","B"],["N","I","I","I","I","I","J","J","J","F","F","B","K","B"],["N","N","I","I","I","J","J","J","J","F","F","B","K","B"],["N","N","N","N","N","J","J","J","J","J","F","F","K","K"],["N","N","N","N","N","J","J","J","J","J","F","F","F","K"],["N","H","H","H","J","J","D","J","F","F","F","F","F","F"],["N","N","H","H","J","D","D","F","F","F","F","F","F","F"],["N","N","H","M","M","M","F","F","L","L","L","L","L","L"],["N","H","H","M","M","M","M","L","L","L","L","L","L","L"],["N","N","H","M","M","M","M","L","L","L","L","L","L","L"]],
  hasUniqueSolution: false,
}

export default level
