// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "117",
  regions: [["J","J","H","H","C","C","C","E","E","E","E"],["J","H","H","C","C","C","C","E","E","E","E"],["J","J","J","C","C","C","E","I","I","E","E"],["J","J","J","J","C","C","E","E","I","E","E"],["J","J","J","J","C","C","E","E","E","E","E"],["J","J","J","F","C","G","G","K","K","K","K"],["J","A","A","F","F","G","G","G","K","B","B"],["J","A","A","A","A","G","G","K","K","B","B"],["A","A","A","A","A","G","G","G","B","B","B"],["A","A","A","D","D","G","G","G","B","B","B"],["A","A","A","D","D","G","G","G","B","B","B"]],
  hasUniqueSolution: false,
}

export default level
