// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "118",
  regions: [["C","C","J","J","J","J","B","B","B","B"],["C","C","C","J","J","J","B","E","E","B"],["D","D","C","C","C","C","C","E","E","E"],["A","A","A","A","C","C","C","E","E","E"],["A","A","H","H","H","H","H","G","E","E"],["A","A","H","H","H","H","H","G","E","E"],["F","F","F","H","H","H","G","G","G","E"],["F","F","F","H","H","G","G","G","G","E"],["F","F","F","F","G","G","I","G","G","G"],["F","F","F","F","G","G","I","I","I","G"]],
  hasUniqueSolution: false,
}

export default level
