// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "119",
  regions: [["A","B","B","B","D","F"],["A","A","D","D","D","F"],["A","A","D","D","F","F"],["A","A","C","D","F","E"],["A","C","C","C","F","E"],["A","C","C","E","E","E"]],
  hasUniqueSolution: false,
}

export default level
