// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '12',
  regions: [
    ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'G', 'G', 'G'],
    ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'G'],
    ['F', 'F', 'B', 'F', 'E', 'E', 'J', 'J', 'G', 'G', 'G'],
    ['F', 'F', 'B', 'F', 'E', 'J', 'J', 'G', 'G', 'G', 'G'],
    ['F', 'F', 'B', 'F', 'A', 'A', 'J', 'H', 'G', 'G', 'G'],
    ['B', 'F', 'B', 'A', 'A', 'A', 'J', 'H', 'G', 'G', 'G'],
    ['B', 'B', 'B', 'A', 'D', 'A', 'A', 'A', 'A', 'A', 'A'],
    ['B', 'B', 'A', 'A', 'D', 'D', 'D', 'C', 'A', 'A', 'A'],
    ['K', 'D', 'D', 'D', 'D', 'I', 'I', 'C', 'A', 'A', 'A'],
    ['K', 'I', 'I', 'D', 'I', 'I', 'I', 'C', 'A', 'A', 'A'],
    ['K', 'I', 'I', 'I', 'I', 'I', 'I', 'C', 'C', 'C', 'A']
  ],
  hasUniqueSolution: true
}

export default level
