// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "120",
  regions: [["D","E","E","E","E","F","F","F","F"],["D","D","E","E","E","F","F","F","F"],["A","A","E","E","B","B","B","B","B"],["A","A","A","A","A","I","G","G","B"],["A","A","A","H","A","I","I","G","B"],["A","H","H","H","I","I","I","G","B"],["A","H","H","H","C","C","I","I","B"],["A","H","H","H","C","C","I","I","B"],["A","H","H","H","H","I","I","B","B"]],
  hasUniqueSolution: false,
}

export default level
