// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "121",
  regions: [["F","F","C","C","C","H","H","H","H"],["F","F","D","D","C","C","H","H","H"],["F","F","F","F","F","C","H","I","I"],["F","F","F","F","F","F","G","F","I"],["F","F","G","G","G","F","F","F","I"],["G","G","G","F","F","F","F","F","A"],["G","G","G","G","G","G","F","A","A"],["E","G","F","F","F","F","F","F","B"],["E","F","F","F","F","B","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
