// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "122",
  regions: [["G","G","G","E","F","F","F","F","B"],["G","D","G","E","F","F","F","F","B"],["G","D","G","E","E","F","F","B","B"],["G","G","G","A","A","F","F","F","B"],["G","G","F","F","F","F","F","F","B"],["G","G","G","G","H","F","C","F","B"],["G","G","G","H","H","C","C","F","F"],["G","G","H","H","H","C","C","C","I"],["G","C","C","C","C","C","C","C","I"]],
  hasUniqueSolution: true,
}

export default level
