// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "123",
  regions: [["E","F","F","F","F","J","J","J","J","J","J"],["E","E","E","F","I","D","D","K","J","K","K"],["E","E","E","F","I","I","K","K","K","K","K"],["E","E","F","F","E","I","K","K","A","E","K"],["E","E","E","F","E","E","K","K","A","E","K"],["E","E","E","E","E","E","E","K","E","E","K"],["E","E","E","E","B","E","E","E","E","K","K"],["B","H","E","B","B","B","B","E","E","E","K"],["B","H","E","E","E","E","B","B","E","E","K"],["B","B","B","B","B","B","B","B","E","C","K"],["G","G","B","B","B","B","B","C","C","C","B"]],
  hasUniqueSolution: true,
}

export default level
