// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "124",
  regions: [["C","C","C","C","C","C","C","C","I","I","I","I","I","I","I","I"],["C","C","K","K","K","K","A","A","A","K","K","K","I","H","H","H"],["C","C","C","C","C","K","K","K","K","K","K","I","I","H","L","H"],["D","D","D","C","C","O","O","O","I","I","I","I","L","L","L","H"],["J","J","D","D","D","O","O","P","P","I","I","I","I","I","L","L"],["J","D","D","D","D","D","O","I","I","I","I","F","F","I","I","L"],["D","D","D","D","B","D","O","O","I","L","L","F","F","L","L","L"],["D","B","B","D","B","B","O","O","O","O","L","L","F","L","L","L"],["B","B","B","B","B","B","B","O","L","L","L","L","F","L","L","L"],["B","B","M","M","B","B","O","O","L","O","L","F","F","F","F","L"],["B","B","O","O","O","O","O","L","L","O","L","L","L","L","F","L"],["B","O","O","O","N","O","O","O","O","O","L","G","G","L","L","L"],["B","O","O","O","N","O","N","O","O","L","L","L","O","L","L","O"],["B","B","O","N","N","N","N","O","O","O","O","O","O","O","O","O"],["B","B","B","N","O","O","O","O","O","O","O","O","O","O","E","E"],["N","N","N","N","N","N","N","N","N","O","O","O","O","O","O","E"]],
  hasUniqueSolution: true,
}

export default level
