// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "125",
  regions: [["Q","Q","Q","Q","Q","Q","A","B","B","B","I","K","K","K","K","K","K","K"],["Q","A","A","A","Q","A","A","B","I","I","I","K","P","P","P","K","P","K"],["Q","Q","A","Q","Q","A","A","A","A","I","P","K","K","P","P","P","P","C"],["Q","Q","A","A","A","A","I","A","I","I","P","P","P","P","R","P","C","C"],["Q","A","A","O","O","O","I","I","I","I","I","P","P","R","R","P","P","C"],["Q","Q","A","O","I","I","I","I","R","R","I","P","R","R","P","P","P","C"],["Q","Q","A","O","I","I","I","I","I","R","R","R","R","P","P","C","C","C"],["Q","Q","A","O","I","I","I","O","I","I","I","J","P","P","P","C","C","C"],["Q","O","A","O","O","O","O","O","I","I","I","J","P","E","E","C","M","M"],["O","O","O","O","G","G","O","O","O","O","I","P","P","P","E","F","F","M"],["H","H","O","O","G","G","G","G","O","O","I","I","I","E","E","E","E","E"],["H","L","L","O","G","G","G","G","G","G","I","D","D","D","E","E","E","E"],["O","O","O","O","G","G","N","G","D","G","I","D","E","E","E","D","E","E"],["O","O","N","O","O","N","N","G","D","D","D","D","E","E","D","D","D","E"],["O","N","N","O","O","O","N","G","G","D","D","E","E","D","D","D","E","E"],["O","N","N","N","N","N","N","N","N","D","D","E","D","D","D","D","E","E"],["O","O","O","N","N","N","N","N","N","N","D","D","D","D","D","D","D","E"],["O","O","O","N","N","N","D","D","D","D","D","D","D","E","E","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
