// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "126",
  regions: [["C","C","C","B","F","A","A","A","A"],["C","I","C","B","F","F","A","A","A"],["G","I","C","B","F","F","F","A","A"],["G","I","C","F","F","E","E","D","D"],["G","I","C","C","E","E","E","D","D"],["G","I","I","C","E","E","H","D","D"],["G","G","C","C","E","E","H","D","D"],["G","G","G","D","D","E","H","D","D"],["G","G","G","G","D","D","D","D","D"]],
  hasUniqueSolution: false,
}

export default level
