// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "127",
  regions: [["G","E","E","A","A","A","A"],["G","E","E","A","A","B","B"],["C","C","E","B","A","A","B"],["C","E","E","B","B","B","B"],["C","E","E","B","B","B","B"],["C","B","B","B","D","B","D"],["F","F","F","F","D","D","D"]],
  hasUniqueSolution: true,
}

export default level
