// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "128",
  regions: [["C","G","G","G","G","G","G","G","G"],["C","C","C","C","G","G","G","G","G"],["C","C","C","E","E","E","F","F","F"],["C","H","H","H","H","E","E","E","D"],["C","C","H","H","H","E","E","E","D"],["C","C","H","E","E","E","E","E","E"],["C","E","E","E","B","B","E","E","I"],["C","C","C","A","A","E","E","I","I"],["C","C","C","C","A","E","E","E","I"]],
  hasUniqueSolution: true,
}

export default level
