// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "129",
  regions: [["B","B","B","B","B","A","A"],["B","F","F","F","B","A","G"],["C","C","C","F","A","A","G"],["C","C","C","C","G","G","G"],["C","C","C","C","C","C","C"],["C","E","E","E","C","D","D"],["C","C","E","C","C","C","D"]],
  hasUniqueSolution: true,
}

export default level
