// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '13',
  regions: [
    ['F', 'C', 'A', 'A', 'A', 'A'],
    ['D', 'C', 'C', 'A', 'A', 'A'],
    ['F', 'E', 'E', 'A', 'A', 'A'],
    ['F', 'E', 'E', 'E', 'A', 'A'],
    ['B', 'E', 'E', 'D', 'D', 'D'],
    ['B', 'B', 'D', 'D', 'D', 'D']
  ],
  hasUniqueSolution: true
}

export default level
