// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "130",
  regions: [["D","D","E","E","E","B","F","F","F","B"],["D","D","G","E","G","B","B","B","F","B"],["G","D","G","G","G","G","G","B","B","B"],["G","G","G","G","G","G","H","H","B","J"],["G","C","C","C","J","G","H","J","J","J"],["G","G","C","C","C","J","J","J","J","J"],["C","G","C","I","I","J","A","A","A","J"],["C","G","C","J","J","J","J","J","A","J"],["C","C","C","J","C","J","C","C","A","A"],["C","C","C","C","C","C","C","A","A","A"]],
  hasUniqueSolution: true,
}

export default level
