// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "131",
  regions: [["C","C","C","C","N","N","N","N","N","N","N","B","B","B"],["G","G","C","C","C","N","N","N","B","B","B","B","B","B"],["G","C","C","N","N","N","J","N","B","B","B","B","L","B"],["G","C","N","N","N","J","J","J","J","J","B","L","L","B"],["G","G","N","N","J","J","J","A","J","B","B","B","L","L"],["G","N","N","N","J","J","A","A","J","B","B","B","L","L"],["G","G","G","D","D","J","J","B","B","B","B","B","L","L"],["G","G","G","M","E","B","B","B","B","F","B","L","L","L"],["G","G","M","M","E","B","B","H","B","F","B","B","L","L"],["G","G","G","M","H","H","B","H","F","F","B","B","B","L"],["K","G","M","M","M","H","H","H","F","F","F","B","L","L"],["K","G","K","K","K","K","H","F","F","F","F","B","L","L"],["K","K","K","H","H","H","H","H","H","H","F","L","L","F"],["H","H","H","H","I","I","I","I","I","H","F","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
