// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "132",
  regions: [["C","C","N","N","N","N","N","N","N","N","N","H","H","H"],["C","C","N","F","N","N","E","E","H","H","N","N","N","H"],["C","N","N","F","N","C","C","E","H","N","N","N","H","H"],["C","N","N","N","C","C","C","E","H","H","H","H","H","H"],["C","N","C","C","C","C","C","E","E","E","E","E","E","H"],["C","C","C","C","M","C","C","C","E","G","G","J","E","E"],["C","C","C","M","M","C","C","C","C","G","J","J","E","E"],["C","C","M","M","M","M","C","C","G","G","G","J","J","E"],["C","C","C","M","M","M","M","C","G","K","G","G","J","J"],["A","C","C","C","C","M","M","M","K","K","G","J","J","J"],["A","A","A","C","C","C","C","M","K","K","G","G","L","L"],["A","I","A","A","A","I","I","I","I","K","B","B","L","L"],["I","I","A","I","I","I","I","D","D","I","B","B","B","I"],["I","I","I","I","I","I","I","I","I","I","I","I","I","I"]],
  hasUniqueSolution: true,
}

export default level
