// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "133",
  regions: [["I","I","I","I","I","I","I","I","D"],["I","I","I","C","I","G","I","I","D"],["I","I","C","C","I","G","G","D","D"],["I","A","C","G","G","G","G","D","F"],["I","A","C","C","C","G","G","G","F"],["I","A","C","F","F","G","F","G","F"],["I","A","C","B","F","F","F","F","F"],["I","A","C","B","B","B","B","B","H"],["I","B","B","B","E","E","E","E","H"]],
  hasUniqueSolution: true,
}

export default level
