// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "134",
  regions: [["C","C","C","A","A","B","B","B","H","H"],["C","F","C","C","C","B","B","B","H","B"],["C","F","F","F","F","F","B","B","H","B"],["C","C","C","F","F","B","B","B","B","B"],["F","F","C","C","F","B","F","F","F","B"],["F","F","F","F","F","F","F","D","D","B"],["F","J","J","F","G","F","D","D","B","B"],["F","J","E","E","G","G","J","J","J","B"],["F","J","J","J","J","G","G","J","J","B"],["J","J","I","I","J","J","J","J","J","J"]],
  hasUniqueSolution: true,
}

export default level
