// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "135",
  regions: [["K","B","B","A","J","J","J","J","J","J","D"],["K","B","B","A","A","A","A","J","J","D","D"],["K","B","B","B","A","F","F","J","D","D","D"],["K","K","B","A","A","F","J","J","J","J","D"],["A","B","B","B","A","A","E","E","A","J","D"],["A","A","A","A","A","A","A","A","A","G","D"],["H","A","A","A","C","I","I","A","A","G","D"],["H","H","A","C","C","I","I","I","A","G","G"],["C","C","C","C","C","C","I","A","A","I","G"],["C","C","C","C","C","I","I","I","I","I","I"],["C","C","C","C","C","C","C","C","I","I","I"]],
  hasUniqueSolution: true,
}

export default level
