// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "136",
  regions: [["H","H","J","J","E","E","E","D","D","D","I","I"],["H","H","H","J","E","J","E","J","D","D","D","I"],["H","J","J","J","E","J","J","J","D","G","D","C"],["J","J","B","J","J","J","D","J","D","G","D","C"],["J","K","B","B","J","J","D","D","D","G","G","G"],["J","K","B","B","J","J","D","A","D","G","G","G"],["J","B","B","J","J","G","D","A","A","G","G","G"],["J","B","B","G","G","G","G","G","A","G","G","G"],["J","J","B","B","B","B","G","G","G","G","G","G"],["B","L","B","B","E","B","B","G","F","G","F","G"],["B","L","L","L","B","G","B","G","F","F","F","G"],["B","B","B","B","B","G","G","G","G","G","G","G"]],
  hasUniqueSolution: true,
}

export default level
