// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "137",
  regions: [["G","G","D","D","D","D","D","E","E"],["D","D","D","D","B","D","E","E","E"],["D","H","D","D","B","E","E","A","A"],["D","H","D","B","B","B","E","F","A"],["D","D","B","B","B","B","B","F","A"],["D","D","D","B","B","I","F","F","A"],["B","B","D","B","I","I","F","F","A"],["B","B","B","B","B","I","C","F","F"],["B","B","B","B","I","I","C","F","F"]],
  hasUniqueSolution: true,
}

export default level
