// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "138",
  regions: [["C","C","C","C","C","C","F","K","G","G","G","G"],["C","D","C","C","C","C","F","K","G","A","G","G"],["C","D","C","C","J","J","F","K","G","A","G","G"],["C","D","D","D","K","K","K","K","G","G","G","G"],["I","D","D","D","K","D","K","K","G","G","K","K"],["I","D","D","D","D","D","K","K","K","K","K","L"],["I","I","I","D","E","D","E","K","L","K","L","L"],["E","E","D","D","E","E","E","L","L","L","L","L"],["E","D","D","D","D","E","E","E","L","H","L","L"],["E","E","E","D","E","E","L","L","L","H","L","L"],["E","D","D","D","E","B","B","B","L","H","H","H"],["E","E","E","E","E","E","B","B","H","H","H","H"]],
  hasUniqueSolution: true,
}

export default level
