// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "139",
  regions: [["D","D","D","G","G","G","G","G","G","G"],["D","D","D","D","D","G","G","G","G","G"],["I","J","D","J","D","J","E","E","G","G"],["I","J","J","J","J","J","J","E","G","G"],["I","I","C","C","J","J","J","E","G","G"],["I","I","I","C","F","F","J","E","G","G"],["C","C","I","C","F","E","E","E","G","E"],["C","C","C","C","C","A","E","E","E","E"],["C","C","C","C","C","A","A","H","E","E"],["B","B","C","C","C","H","H","H","H","E"]],
  hasUniqueSolution: true,
}

export default level
