// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '14',
  regions: [
    ['J', 'J', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H'],
    ['J', 'D', 'D', 'J', 'J', 'J', 'A', 'A', 'A', 'H'],
    ['J', 'J', 'J', 'J', 'B', 'J', 'A', 'A', 'J', 'H'],
    ['J', 'J', 'B', 'J', 'B', 'J', 'J', 'A', 'A', 'A'],
    ['J', 'B', 'B', 'B', 'B', 'J', 'J', 'A', 'A', 'A'],
    ['J', 'J', 'B', 'J', 'B', 'J', 'I', 'I', 'A', 'A'],
    ['C', 'J', 'J', 'J', 'B', 'E', 'I', 'I', 'I', 'A'],
    ['C', 'J', 'B', 'B', 'B', 'E', 'E', 'I', 'I', 'I'],
    ['F', 'F', 'B', 'E', 'E', 'E', 'G', 'G', 'G', 'I'],
    ['F', 'F', 'B', 'E', 'E', 'E', 'E', 'G', 'I', 'I']
  ],
  hasUniqueSolution: true
}

export default level
