// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "140",
  regions: [["B","B","C","C","C","C","C","C","J","J","J","J","J","N"],["B","B","F","C","I","J","J","J","J","G","N","N","N","N"],["B","F","F","C","I","J","C","C","C","G","G","G","G","G"],["B","B","C","C","I","J","C","C","C","G","G","G","L","L"],["H","H","H","C","I","C","C","C","C","G","G","G","G","L"],["H","H","H","C","C","C","D","D","C","C","G","C","G","L"],["H","H","C","C","C","M","M","M","C","C","C","C","G","L"],["K","H","H","H","C","C","M","M","M","C","A","C","C","L"],["K","H","H","M","C","M","M","A","A","A","A","A","A","L"],["K","H","H","M","M","M","M","A","E","E","E","L","A","L"],["K","H","H","M","E","E","E","E","E","E","L","L","L","L"],["H","H","H","M","M","M","E","E","E","L","L","L","E","L"],["H","M","H","H","H","M","E","E","E","E","L","E","E","E"],["H","M","M","M","M","M","E","E","E","E","E","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
