// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "141",
  regions: [["E","G","G","B","B","F","F","F","F"],["E","A","B","B","B","B","C","F","F"],["E","A","A","B","C","C","C","C","D"],["E","A","A","B","B","C","I","I","D"],["A","A","B","B","B","C","I","I","I"],["A","A","B","B","B","I","I","I","I"],["A","A","A","B","B","B","I","I","I"],["A","H","H","H","B","I","I","I","I"],["H","H","H","H","I","I","I","I","I"]],
  hasUniqueSolution: true,
}

export default level
