// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "142",
  regions: [["H","H","H","H","G","G","G","C","K","K","K"],["H","H","J","J","G","C","C","C","C","C","K"],["H","J","J","J","G","C","C","C","C","C","K"],["J","J","J","G","G","C","C","E","C","C","K"],["J","B","B","B","D","D","E","E","C","C","C"],["J","J","I","B","D","F","F","E","E","E","C"],["A","J","I","B","B","B","E","E","C","C","C"],["A","J","J","B","B","B","B","E","E","E","C"],["A","A","J","B","B","B","B","E","B","E","C"],["A","D","J","J","B","B","B","B","B","E","E"],["A","A","B","B","B","B","B","E","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
