// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "143",
  regions: [["B","B","B","B","B","B","K","G","G","G","J"],["I","I","B","F","F","K","K","G","G","G","J"],["I","B","B","B","F","K","K","K","K","G","J"],["I","B","B","B","F","K","K","K","G","G","J"],["B","B","B","B","B","H","K","J","J","J","J"],["A","B","B","H","H","H","K","K","K","J","J"],["A","D","D","H","H","H","H","H","K","J","J"],["D","D","H","H","E","E","H","E","K","K","K"],["D","H","H","E","E","E","E","E","K","E","K"],["H","H","E","E","E","E","E","E","K","E","K"],["H","H","H","H","E","C","C","E","E","E","K"]],
  hasUniqueSolution: true,
}

export default level
