// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "144",
  regions: [["N","N","N","N","N","N","N","N","N","C","C","C","C","C","O"],["N","N","E","N","N","N","E","E","E","F","F","C","C","C","O"],["N","N","E","E","E","N","N","E","E","E","F","F","C","C","O"],["N","N","N","E","E","E","E","E","F","F","F","F","C","O","O"],["N","N","N","N","E","E","J","E","E","E","E","F","C","O","I"],["M","M","N","N","E","J","J","E","J","L","E","F","F","O","I"],["M","N","N","N","E","E","J","J","J","L","E","F","F","O","I"],["M","M","E","E","E","E","J","L","L","L","E","F","B","B","I"],["M","G","G","E","G","G","J","J","J","L","L","F","F","B","I"],["M","M","G","E","E","G","G","G","L","L","L","F","F","I","I"],["M","M","G","E","E","G","G","G","F","F","L","F","K","I","I"],["M","G","G","G","G","G","A","G","F","F","F","F","K","K","I"],["M","G","G","G","H","G","A","G","F","F","F","I","I","I","I"],["M","G","H","G","H","H","H","G","H","H","H","D","D","D","I"],["G","G","H","H","H","H","H","H","H","H","D","D","D","I","I"]],
  hasUniqueSolution: true,
}

export default level
