// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "145",
  regions: [["A","A","A","A","A","F"],["A","D","D","C","F","F"],["A","C","C","C","C","F"],["A","A","C","B","C","F"],["A","B","B","B","C","F"],["A","A","E","E","C","F"]],
  hasUniqueSolution: true,
}

export default level
