// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "146",
  regions: [["E","E","E","B","B"],["B","E","B","B","B"],["B","B","B","C","C"],["B","A","A","D","D"],["A","A","A","A","D"]],
  hasUniqueSolution: true,
}

export default level
