// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "147",
  regions: [["D","G","G","G","G","G","G"],["D","B","G","G","G","G","G"],["D","B","B","B","B","G","G"],["D","D","A","A","A","A","F"],["C","D","D","A","A","A","F"],["C","A","A","A","E","A","E"],["C","C","C","C","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
