// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "148",
  regions: [["I","H","H","I","I","I","A","E","E"],["I","I","I","I","I","I","A","E","E"],["B","I","D","I","C","I","I","E","E"],["B","I","D","I","C","C","I","C","C"],["B","I","D","G","G","C","C","C","C"],["B","G","D","D","G","G","C","G","G"],["G","G","D","D","D","G","C","C","G"],["F","G","G","G","D","G","G","C","G"],["F","F","G","G","G","G","G","G","G"]],
  hasUniqueSolution: true,
}

export default level
