// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "149",
  regions: [["D","A","A","A","A","A","A"],["D","F","A","G","A","C","C"],["G","F","A","G","A","A","A"],["G","F","B","G","B","B","E"],["G","G","G","G","G","B","E"],["G","E","E","E","E","B","E"],["G","E","E","E","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
