// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '15',
  regions: [
    ['D', 'D', 'A', 'B', 'B'],
    ['A', 'A', 'A', 'A', 'B'],
    ['A', 'A', 'E', 'B', 'B'],
    ['A', 'A', 'E', 'B', 'B'],
    ['A', 'A', 'A', 'C', 'C']
  ],
  hasUniqueSolution: true
}

export default level
