// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "15",
  regions: [["A","A","D","B","B"],["D","D","D","D","B"],["D","D","C","B","B"],["D","D","C","B","B"],["D","D","D","E","E"]],
  hasUniqueSolution: true,
}

export default level
