// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "150",
  regions: [["E","E","A","A","A","A","A","A"],["E","E","A","A","E","F","F","A"],["E","E","E","E","E","A","A","A"],["E","E","D","D","E","A","A","A"],["E","C","D","G","G","H","H","A"],["E","C","D","G","G","G","G","A"],["E","E","E","G","B","G","G","B"],["E","E","B","B","B","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
