// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "151",
  regions: [["F","F","F","B","C","C","C","C","C"],["F","F","E","B","C","I","C","C","C"],["F","E","E","E","E","I","C","C","H"],["F","F","F","E","E","E","C","H","H"],["D","D","F","F","F","C","C","C","H"],["D","F","F","F","G","G","G","H","H"],["D","F","F","F","G","G","H","H","H"],["D","D","D","D","G","A","A","H","H"],["D","D","D","D","H","H","H","H","H"]],
  hasUniqueSolution: true,
}

export default level
