// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "152",
  regions: [["G","H","C","A","A","A","A","A","B"],["G","H","C","G","G","A","E","B","B"],["G","H","C","C","G","A","E","E","B"],["G","G","G","G","G","A","D","D","B"],["G","I","G","I","G","G","D","B","B"],["I","I","I","I","I","D","D","B","I"],["I","I","F","I","D","D","B","B","I"],["I","F","F","I","I","D","B","B","I"],["I","F","I","I","I","I","I","I","I"]],
  hasUniqueSolution: true,
}

export default level
