// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "153",
  regions: [["B","B","H","H","B","B","B","A","A","F","F","F"],["B","B","B","B","B","B","B","A","A","F","F","A"],["B","K","B","B","K","K","B","B","A","A","A","A"],["B","K","K","B","B","K","K","K","K","K","A","A"],["B","K","K","K","K","K","J","K","K","K","K","A"],["I","I","K","J","J","J","J","K","K","K","A","A"],["E","E","K","K","K","J","K","K","K","A","A","A"],["E","K","K","J","J","J","A","A","A","A","A","A"],["E","K","K","K","J","J","A","A","D","A","L","A"],["G","K","K","K","K","J","A","D","D","A","L","A"],["G","G","G","J","K","J","J","D","L","L","L","A"],["J","J","J","J","J","J","J","J","C","C","L","L"]],
  hasUniqueSolution: true,
}

export default level
