// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "154",
  regions: [["K","K","K","K","K","K","K","K","K","K","K","D","D","H"],["K","K","E","E","N","N","K","K","I","K","K","K","D","H"],["E","E","E","K","K","K","K","I","I","I","K","H","H","H"],["E","I","K","K","I","I","I","I","I","K","K","H","H","H"],["E","I","I","I","I","A","J","I","I","I","K","K","H","H"],["E","I","A","A","A","A","J","J","J","I","K","K","H","H"],["E","F","A","A","G","G","G","J","J","J","J","K","H","H"],["E","F","F","A","A","G","G","C","C","C","J","J","H","A"],["E","A","A","A","G","G","J","J","J","J","J","J","M","H"],["E","A","A","G","G","G","G","G","M","M","J","M","M","H"],["E","A","M","M","G","G","G","G","G","M","J","M","M","M"],["A","A","A","M","G","G","G","G","G","M","M","M","M","M"],["A","L","A","M","M","G","G","G","G","M","M","M","M","B"],["L","L","M","M","M","M","M","M","M","M","B","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
