// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "155",
  regions: [["B","B","B","C","C","C","E","E","E"],["B","B","B","C","C","E","E","E","E"],["H","H","A","C","C","E","E","E","D"],["H","H","A","G","C","E","D","D","D"],["H","H","A","G","C","E","E","D","D"],["H","A","A","C","C","C","E","E","E"],["A","A","F","F","C","C","I","E","E"],["A","A","F","F","F","C","I","I","E"],["A","F","F","F","F","C","C","I","E"]],
  hasUniqueSolution: false,
}

export default level
