// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "156",
  regions: [["G","C","C","A","A","A","A"],["G","C","C","A","A","A","A"],["G","C","C","C","C","C","F"],["E","C","C","B","F","F","F"],["E","B","B","B","B","F","F"],["E","E","B","B","B","D","F"],["E","E","B","D","D","D","D"]],
  hasUniqueSolution: false,
}

export default level
