// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "157",
  regions: [["G","G","G","G","G","F","F","F","F","F"],["G","E","B","B","F","F","F","F","F","F"],["G","E","E","B","F","F","F","I","I","F"],["G","E","E","B","F","F","F","I","I","F"],["G","A","E","B","F","F","F","I","I","I"],["D","A","B","B","F","F","F","C","I","I"],["D","A","A","H","H","H","H","C","C","I"],["D","A","A","A","J","H","H","I","I","I"],["D","D","J","J","J","H","J","J","J","J"],["D","D","D","J","J","J","J","J","J","J"]],
  hasUniqueSolution: false,
}

export default level
