// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "158",
  regions: [["G","C","C","C","C","C","B"],["G","G","G","G","G","C","C"],["G","G","F","F","G","G","C"],["G","F","F","F","D","C","C"],["D","F","F","D","D","E","E"],["D","D","D","D","A","A","E"],["D","E","E","E","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
