// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "159",
  regions: [["I","I","B","F","F","C","C","C","C"],["I","I","B","B","F","C","H","C","C"],["I","I","A","F","F","F","F","C","C"],["I","I","A","I","I","I","I","C","C"],["I","I","I","I","H","I","I","I","C"],["G","G","H","H","H","H","I","I","C"],["H","G","G","G","H","H","D","D","E"],["H","H","H","G","H","H","D","D","E"],["H","H","H","H","H","H","D","D","D"]],
  hasUniqueSolution: true,
}

export default level
