// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "16",
  regions: [["L","L","L","L","L","L","L","C","C","C","B","B","B","B","A","A"],["L","C","L","C","C","C","C","C","B","B","B","B","B","A","A","A"],["L","C","C","C","L","L","F","F","F","F","F","B","B","B","B","A"],["L","L","L","C","L","F","F","D","D","E","E","B","B","A","A","A"],["L","L","L","L","L","F","F","E","E","E","E","B","A","A","A","A"],["L","L","L","F","L","L","F","F","E","A","E","A","A","A","A","A"],["L","F","F","F","F","F","F","F","A","A","E","E","A","I","G","A"],["L","L","L","L","F","H","H","H","A","A","A","A","A","I","G","A"],["J","L","L","L","F","F","F","H","H","H","I","A","I","I","A","A"],["J","J","L","L","J","J","J","H","H","H","I","I","I","I","A","I"],["J","J","L","J","J","J","J","H","H","K","K","K","I","I","I","I"],["J","J","L","L","L","J","J","H","H","H","K","I","I","K","I","I"],["J","J","J","L","L","J","M","H","K","K","K","K","I","K","I","I"],["J","J","J","J","J","J","M","H","H","K","N","K","K","K","K","K"],["J","J","O","O","J","M","M","H","M","N","N","K","K","K","P","K"],["J","J","O","O","J","J","M","M","M","K","K","K","K","P","P","K"]],
  hasUniqueSolution: true,
}

export default level
