// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '16',
  regions: [
    ['G', 'G', 'G', 'G', 'G', 'G', 'G', 'P', 'P', 'P', 'H', 'H', 'H', 'H', 'J', 'J'],
    ['G', 'P', 'G', 'P', 'P', 'P', 'P', 'P', 'H', 'H', 'H', 'H', 'H', 'J', 'J', 'J'],
    ['G', 'P', 'P', 'P', 'G', 'G', 'L', 'L', 'L', 'L', 'L', 'H', 'H', 'H', 'H', 'J'],
    ['G', 'G', 'G', 'P', 'G', 'L', 'L', 'N', 'N', 'M', 'M', 'H', 'H', 'J', 'J', 'J'],
    ['G', 'G', 'G', 'G', 'G', 'L', 'L', 'M', 'M', 'M', 'M', 'H', 'J', 'J', 'J', 'J'],
    ['G', 'G', 'G', 'L', 'G', 'G', 'L', 'L', 'M', 'J', 'M', 'J', 'J', 'J', 'J', 'J'],
    ['G', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'J', 'J', 'M', 'M', 'J', 'E', 'I', 'J'],
    ['G', 'G', 'G', 'G', 'L', 'D', 'D', 'D', 'J', 'J', 'J', 'J', 'J', 'E', 'I', 'J'],
    ['C', 'G', 'G', 'G', 'L', 'L', 'L', 'D', 'D', 'D', 'E', 'J', 'E', 'E', 'J', 'J'],
    ['C', 'C', 'G', 'G', 'C', 'C', 'C', 'D', 'D', 'D', 'E', 'E', 'E', 'E', 'J', 'E'],
    ['C', 'C', 'G', 'C', 'C', 'C', 'C', 'D', 'D', 'O', 'O', 'O', 'E', 'E', 'E', 'E'],
    ['C', 'C', 'G', 'G', 'G', 'C', 'C', 'D', 'D', 'D', 'O', 'E', 'E', 'O', 'E', 'E'],
    ['C', 'C', 'C', 'G', 'G', 'C', 'F', 'D', 'O', 'O', 'O', 'O', 'E', 'O', 'E', 'E'],
    ['C', 'C', 'C', 'C', 'C', 'C', 'F', 'D', 'D', 'O', 'K', 'O', 'O', 'O', 'O', 'O'],
    ['C', 'C', 'B', 'B', 'C', 'F', 'F', 'D', 'F', 'K', 'K', 'O', 'O', 'O', 'A', 'O'],
    ['C', 'C', 'B', 'B', 'C', 'C', 'F', 'F', 'F', 'O', 'O', 'O', 'O', 'A', 'A', 'O']
  ],
  hasUniqueSolution: true
}

export default level
