// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "160",
  regions: [["G","G","G","G","G","A","A","A","E"],["G","G","G","G","G","G","G","G","E"],["G","F","G","G","G","G","G","E","E"],["I","F","G","G","G","G","E","E","C"],["I","G","G","G","G","G","C","C","C"],["I","I","I","G","G","G","G","H","H"],["I","I","I","D","D","D","H","H","H"],["I","D","D","D","H","H","H","B","H"],["I","I","D","D","H","B","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
