// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "161",
  regions: [["E","E","E","E","E","E","E","E","E"],["D","E","E","E","E","I","A","A","E"],["D","E","E","C","E","I","A","E","E"],["G","E","E","C","E","E","A","A","E"],["G","C","C","C","E","E","A","A","A"],["G","C","G","C","F","A","A","A","A"],["G","G","G","C","F","F","F","A","A"],["G","G","G","G","H","H","H","H","A"],["G","G","G","G","G","H","B","B","A"]],
  hasUniqueSolution: true,
}

export default level
