// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "162",
  regions: [["I","I","I","I","I","I","I","I","I","I"],["I","I","I","A","I","I","I","I","I","G"],["I","A","I","A","A","I","I","I","I","G"],["H","A","A","A","C","C","J","J","I","F"],["H","A","B","B","C","C","J","I","I","F"],["E","A","B","B","B","C","J","I","J","F"],["E","A","B","D","C","C","J","J","J","F"],["E","E","B","D","C","J","J","J","F","F"],["E","E","B","B","C","C","C","J","J","F"],["E","B","B","B","B","B","C","C","J","J"]],
  hasUniqueSolution: true,
}

export default level
