// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "163",
  regions: [["B","B","D","D","D","D","D","D","D","D","D"],["B","B","H","H","G","G","H","H","D","D","D"],["B","B","H","H","H","G","H","H","H","D","D"],["B","B","B","H","H","H","H","K","H","K","D"],["B","H","B","B","B","B","H","K","F","F","D"],["B","H","B","B","B","H","H","I","F","F","D"],["B","H","H","B","B","H","H","I","I","I","D"],["B","B","H","H","H","H","H","I","E","E","J"],["B","B","H","A","H","C","I","I","E","J","J"],["A","B","B","A","C","C","C","I","E","E","J"],["A","A","A","A","C","E","E","E","E","E","J"]],
  hasUniqueSolution: true,
}

export default level
