// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "164",
  regions: [["D","D","D","D","D","D","D","L","L","F","F","F","F"],["D","D","B","D","H","H","L","L","L","L","L","F","F"],["D","B","B","B","B","L","L","A","A","A","F","F","K"],["D","D","D","D","B","L","A","A","F","A","A","F","K"],["D","C","C","D","L","L","L","A","F","A","A","F","K"],["D","C","D","D","E","L","L","A","F","F","F","F","K"],["E","C","C","E","E","A","A","A","A","A","F","F","K"],["E","E","C","E","E","A","J","J","A","A","F","K","K"],["E","E","E","E","E","J","J","A","A","A","K","K","K"],["E","M","M","E","E","E","J","A","I","H","I","I","K"],["E","E","G","E","E","E","J","A","I","I","K","K","K"],["G","G","G","E","E","E","J","A","A","I","I","K","K"],["G","G","G","G","E","E","E","A","I","I","K","K","K"]],
  hasUniqueSolution: true,
}

export default level
