// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "165",
  regions: [["C","D","D","A","A","A"],["C","D","E","D","D","A"],["D","D","D","D","A","A"],["B","B","E","D","D","A"],["B","E","E","F","F","A"],["B","B","F","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
