// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "166",
  regions: [["E","E","F","F","F","F","F","F"],["E","F","F","F","F","F","B","F"],["E","H","H","F","F","B","B","F"],["E","H","H","H","F","F","B","B"],["E","E","H","C","D","F","D","B"],["E","G","G","C","D","D","D","B"],["A","A","G","C","B","B","D","B"],["G","G","G","C","C","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
