// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "167",
  regions: [["G","G","G","G","G","G","G","G","G"],["G","G","G","G","G","G","D","D","D"],["F","F","F","G","G","G","G","G","D"],["F","C","C","I","G","D","D","D","D"],["C","C","I","I","D","D","E","D","D"],["I","I","I","A","A","A","E","D","D"],["I","I","I","A","H","E","E","H","D"],["A","A","A","A","H","H","H","H","D"],["A","B","B","B","H","H","H","H","D"]],
  hasUniqueSolution: true,
}

export default level
