// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "168",
  regions: [["I","I","I","I","D","D","D","D","D","D"],["D","D","D","D","D","D","J","J","J","D"],["D","C","C","H","D","D","D","J","J","D"],["D","C","H","H","H","J","J","J","D","D"],["H","B","H","J","J","J","G","J","J","J"],["H","B","H","H","G","G","G","J","J","E"],["H","H","H","G","G","G","G","G","E","E"],["H","H","F","A","A","A","E","E","E","E"],["H","H","F","F","F","E","E","E","E","E"],["H","H","H","E","E","E","E","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
