// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "169",
  regions: [["D","J","J","D","D","D","D","D","D","D"],["D","D","D","D","E","E","D","H","H","D"],["D","I","C","D","D","E","D","H","G","G"],["D","D","C","D","D","E","E","F","G","G"],["D","E","E","E","D","D","E","F","G","A"],["D","E","D","E","E","E","E","G","G","A"],["D","D","D","E","B","B","B","G","G","A"],["E","E","E","E","B","B","B","B","G","A"],["E","I","I","I","B","B","B","G","G","A"],["E","E","I","I","I","B","A","A","A","A"]],
  hasUniqueSolution: true,
}

export default level
