// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '17',
  regions: [
    ['E', 'E', 'E', 'E', 'E', 'M', 'M', 'B', 'J', 'J', 'J', 'J', 'J', 'J', 'G'],
    ['A', 'E', 'E', 'E', 'M', 'M', 'M', 'B', 'J', 'F', 'J', 'J', 'G', 'G', 'G'],
    ['A', 'E', 'E', 'E', 'E', 'E', 'L', 'F', 'F', 'F', 'F', 'J', 'J', 'J', 'G'],
    ['A', 'A', 'E', 'E', 'L', 'L', 'L', 'F', 'F', 'J', 'N', 'N', 'J', 'G', 'G'],
    ['A', 'A', 'A', 'E', 'E', 'L', 'L', 'F', 'J', 'J', 'J', 'J', 'J', 'J', 'G'],
    ['A', 'E', 'A', 'A', 'E', 'L', 'F', 'F', 'J', 'L', 'L', 'L', 'J', 'G', 'G'],
    ['A', 'E', 'E', 'E', 'E', 'L', 'L', 'L', 'L', 'L', 'L', 'G', 'G', 'G', 'G'],
    ['A', 'A', 'E', 'I', 'I', 'L', 'I', 'I', 'I', 'I', 'L', 'G', 'H', 'G', 'G'],
    ['A', 'A', 'I', 'I', 'I', 'I', 'I', 'C', 'I', 'I', 'L', 'G', 'H', 'C', 'C'],
    ['A', 'A', 'I', 'I', 'C', 'C', 'I', 'C', 'I', 'I', 'L', 'H', 'H', 'K', 'C'],
    ['A', 'A', 'I', 'I', 'C', 'C', 'I', 'C', 'I', 'L', 'L', 'H', 'H', 'K', 'C'],
    ['A', 'A', 'I', 'C', 'C', 'C', 'C', 'C', 'I', 'I', 'C', 'H', 'K', 'K', 'C'],
    ['A', 'A', 'A', 'A', 'C', 'C', 'I', 'I', 'I', 'C', 'C', 'H', 'C', 'C', 'C'],
    ['C', 'A', 'C', 'C', 'C', 'D', 'D', 'D', 'C', 'C', 'C', 'C', 'C', 'O', 'O'],
    ['C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'O']
  ],
  hasUniqueSolution: true
}

export default level
