// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "17",
  regions: [["C","C","C","C","C","B","B","A","E","E","E","E","E","E","G"],["H","C","C","C","B","B","B","A","E","F","E","E","G","G","G"],["H","C","C","C","C","C","K","F","F","F","F","E","E","E","G"],["H","H","C","C","K","K","K","F","F","E","D","D","E","G","G"],["H","H","H","C","C","K","K","F","E","E","E","E","E","E","G"],["H","C","H","H","C","K","F","F","E","K","K","K","E","G","G"],["H","C","C","C","C","K","K","K","K","K","K","G","G","G","G"],["H","H","C","I","I","K","I","I","I","I","K","G","M","G","G"],["H","H","I","I","I","I","I","L","I","I","K","G","M","L","L"],["H","H","I","I","L","L","I","L","I","I","K","M","M","J","L"],["H","H","I","I","L","L","I","L","I","K","K","M","M","J","L"],["H","H","I","L","L","L","L","L","I","I","L","M","J","J","L"],["H","H","H","H","L","L","I","I","I","L","L","M","L","L","L"],["L","H","L","L","L","N","N","N","L","L","L","L","L","O","O"],["L","L","L","L","L","L","L","L","L","L","L","L","L","L","O"]],
  hasUniqueSolution: true,
}

export default level
