// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "170",
  regions: [["F","F","F","F","F","F","F","E","B","B"],["F","F","F","F","F","F","E","E","B","B"],["F","I","I","F","F","E","E","E","B","B"],["F","I","I","I","I","E","E","E","H","B"],["I","I","G","I","I","E","E","H","H","H"],["G","G","G","G","I","I","E","H","H","H"],["D","D","D","D","I","I","E","E","H","H"],["C","C","D","I","I","A","A","A","A","A"],["C","C","I","I","I","A","A","A","A","A"],["J","J","J","J","J","J","A","A","A","A"]],
  hasUniqueSolution: false,
}

export default level
