// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "171",
  regions: [["D","D","D","D","C","C"],["D","D","F","F","F","F"],["B","F","F","F","F","F"],["B","A","F","F","F","F"],["E","A","A","A","A","F"],["E","E","E","E","F","F"]],
  hasUniqueSolution: true,
}

export default level
