// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "172",
  regions: [["B","B","B","B","B","B"],["F","F","B","F","B","B"],["F","F","F","F","F","E"],["F","A","F","C","F","E"],["F","A","C","C","D","D"],["F","A","D","D","D","F"]],
  hasUniqueSolution: true,
}

export default level
