// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "173",
  regions: [["A","A","A","A","A","A","A","A","A"],["A","A","A","A","A","I","A","H","A"],["E","E","A","E","E","I","A","H","A"],["E","E","E","E","I","I","I","I","F"],["E","B","E","E","B","I","F","I","F"],["E","B","B","B","B","G","F","F","F"],["E","E","F","C","G","G","F","D","F"],["E","E","F","C","F","F","D","D","F"],["E","E","F","F","F","F","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
