// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "174",
  regions: [["A","A","A","A","A","A","A","A","A","A","A","A","A","A","E","E"],["A","A","M","A","P","P","A","A","A","P","P","A","A","A","E","N"],["C","A","M","M","P","P","P","P","A","P","A","A","A","N","N","N"],["C","A","M","M","M","A","A","P","A","P","P","A","L","L","N","N"],["C","A","A","M","A","A","F","P","P","P","P","A","L","L","N","N"],["C","A","M","M","A","F","F","F","B","A","A","A","A","L","N","L"],["C","A","A","A","A","F","F","B","B","A","A","L","A","L","N","L"],["C","A","A","F","F","F","B","B","B","A","L","L","A","L","L","L"],["C","C","A","F","A","F","F","F","F","L","L","H","H","H","H","L"],["C","C","A","F","A","F","F","F","F","L","L","L","L","L","H","L"],["G","C","A","A","A","F","F","L","L","L","L","F","F","L","L","L"],["G","A","A","G","A","I","F","F","F","F","F","F","F","L","L","O"],["G","A","A","G","I","I","I","F","F","F","D","D","F","F","O","O"],["G","G","A","G","K","K","I","I","F","D","D","D","F","F","F","O"],["J","G","G","G","K","K","K","I","I","I","O","D","D","O","F","O"],["J","J","J","K","K","K","I","I","O","O","O","O","O","O","O","O"]],
  hasUniqueSolution: true,
}

export default level
