// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "175",
  regions: [["G","G","F","F","F","B","B"],["G","G","F","F","E","B","B"],["G","G","F","E","E","B","B"],["G","G","E","E","E","E","B"],["C","C","A","A","A","A","B"],["C","C","A","A","A","A","A"],["C","C","A","D","D","A","A"]],
  hasUniqueSolution: false,
}

export default level
