// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "176",
  regions: [["A","A","A","E","E","E","E"],["A","A","A","C","E","C","C"],["A","A","C","C","C","C","C"],["D","A","A","B","C","C","C"],["D","B","B","B","B","G","C"],["D","D","D","B","B","G","F"],["D","D","D","D","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
