// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "177",
  regions: [["D","H","H","H","H","H","H","H"],["D","D","D","A","A","H","F","H"],["G","G","D","D","A","C","F","H"],["G","G","D","D","A","C","H","H"],["G","G","G","D","D","C","H","H"],["G","G","G","C","C","C","C","H"],["G","G","B","B","E","E","E","H"],["G","G","G","G","G","E","H","H"]],
  hasUniqueSolution: true,
}

export default level
