// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "178",
  regions: [["A","B","F","F","F","F","F","F","D","D"],["A","B","B","F","J","J","F","F","D","C"],["A","B","F","F","F","J","F","D","D","C"],["A","B","B","F","F","J","F","J","D","D"],["B","B","F","F","F","J","J","J","J","D"],["B","F","F","G","F","F","F","J","D","D"],["G","G","G","G","F","J","J","J","D","I"],["G","G","H","F","F","F","F","F","D","I"],["H","H","H","F","F","E","E","F","I","I"],["H","H","H","F","F","F","E","F","F","I"]],
  hasUniqueSolution: true,
}

export default level
