// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "179",
  regions: [["J","J","J","J","J","B","B","B","G","G","G"],["J","H","H","J","J","J","J","B","B","B","B"],["J","J","H","H","H","J","B","B","B","B","B"],["J","J","J","J","H","J","J","K","K","H","B"],["E","E","J","J","H","J","K","K","K","H","B"],["E","E","J","H","H","K","K","H","H","H","B"],["E","E","E","H","H","H","B","H","C","B","B"],["F","C","C","C","C","C","C","C","C","C","B"],["F","F","C","A","A","D","C","B","B","B","B"],["F","F","C","D","D","D","C","B","B","I","B"],["F","F","F","F","C","C","C","C","B","I","B"]],
  hasUniqueSolution: true,
}

export default level
