// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '18',
  regions: [
    ['F', 'F', 'F', 'E', 'E', 'E', 'E', 'E', 'G', 'G', 'G'],
    ['K', 'F', 'F', 'F', 'F', 'F', 'F', 'E', 'E', 'G', 'G'],
    ['K', 'F', 'F', 'G', 'G', 'G', 'F', 'G', 'E', 'E', 'G'],
    ['K', 'K', 'F', 'F', 'F', 'G', 'G', 'G', 'G', 'G', 'G'],
    ['F', 'K', 'F', 'J', 'G', 'G', 'J', 'G', 'J', 'G', 'G'],
    ['F', 'K', 'F', 'J', 'J', 'J', 'J', 'J', 'J', 'A', 'G'],
    ['F', 'K', 'F', 'J', 'F', 'I', 'I', 'H', 'A', 'A', 'G'],
    ['F', 'F', 'F', 'J', 'F', 'F', 'I', 'H', 'B', 'B', 'G'],
    ['F', 'D', 'F', 'J', 'F', 'I', 'I', 'I', 'I', 'B', 'B'],
    ['C', 'D', 'F', 'F', 'F', 'I', 'I', 'I', 'B', 'B', 'B'],
    ['C', 'D', 'D', 'D', 'B', 'B', 'B', 'B', 'B', 'B', 'B']
  ],
  hasUniqueSolution: true
}

export default level
