// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "180",
  regions: [["D","D","D","D","F","F","F"],["D","C","C","D","F","G","F"],["D","C","C","C","F","G","F"],["C","C","E","C","F","F","F"],["A","A","E","C","C","C","C"],["C","C","C","C","C","B","C"],["C","B","B","B","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
