// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "181",
  regions: [["J","E","E","E","G","G","G","D","D","D","D"],["J","J","E","J","J","G","D","D","D","D","B"],["F","J","J","J","G","G","D","D","D","B","B"],["F","J","J","A","G","D","D","D","B","B","B"],["C","C","C","A","G","D","D","D","D","B","B"],["C","C","C","A","A","A","A","D","D","D","B"],["C","C","C","I","I","A","D","D","D","B","B"],["C","C","C","I","I","D","D","D","D","H","K"],["I","I","I","I","D","D","D","D","D","H","K"],["I","I","I","I","I","I","D","D","D","H","H"],["I","I","I","I","I","I","D","D","D","D","D"]],
  hasUniqueSolution: true,
}

export default level
