// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "182",
  regions: [["A","A","A","D","D","D","G","G","G"],["I","D","D","D","C","C","C","G","G"],["I","I","D","D","D","B","B","G","G"],["I","F","D","D","D","H","B","G","G"],["F","F","F","F","D","H","G","G","G"],["F","E","H","H","H","H","G","G","G"],["E","E","E","H","H","H","G","G","G"],["H","E","E","E","E","A","H","H","G"],["H","H","H","H","H","H","H","H","G"]],
  hasUniqueSolution: true,
}

export default level
