// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "183",
  regions: [["A","A","A","A","A","A","A","A","H","H"],["F","A","J","A","A","A","H","H","H","G"],["F","A","J","H","H","A","H","H","H","G"],["F","A","A","A","H","H","H","H","H","H"],["F","F","F","A","E","E","A","B","B","B"],["F","F","F","A","E","F","A","A","A","B"],["I","I","F","A","A","A","A","A","A","B"],["I","F","F","A","A","D","D","A","A","B"],["I","A","F","A","A","C","B","B","A","B"],["A","A","A","A","C","C","B","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
