// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "184",
  regions: [["J","J","F","F","F","F","F","F","I","I","I","I"],["J","J","F","F","F","I","I","I","I","I","A","I"],["D","D","D","B","F","I","I","A","A","I","A","I"],["D","D","D","B","F","I","A","A","A","A","A","A"],["D","G","D","F","F","A","A","A","A","E","E","E"],["D","G","K","F","K","K","A","A","E","E","E","E"],["D","G","K","K","K","L","L","A","E","E","E","E"],["G","G","G","K","K","L","L","A","A","A","A","E"],["K","K","K","K","C","L","L","H","H","H","A","E"],["K","K","C","C","C","L","H","H","H","H","H","E"],["K","K","K","C","L","L","H","H","E","E","E","E"],["K","K","K","K","L","L","L","H","H","H","E","E"]],
  hasUniqueSolution: true,
}

export default level
