// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "185",
  regions: [["A","A","A","D","E"],["A","E","E","D","E"],["A","A","E","E","E"],["A","E","E","B","B"],["C","C","C","B","B"]],
  hasUniqueSolution: true,
}

export default level
