// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "186",
  regions: [["H","H","H","H","H","H","H","H","H","H","H","H","H"],["H","H","H","H","H","I","H","I","H","H","H","H","H"],["L","H","H","H","H","I","H","I","H","H","I","H","E"],["L","H","H","H","J","I","I","I","H","H","I","H","E"],["L","H","H","J","J","J","I","I","I","I","I","D","E"],["G","G","J","J","C","C","A","A","A","A","D","D","E"],["G","G","J","J","J","C","A","E","E","A","D","D","E"],["G","M","M","J","J","C","A","A","E","E","D","E","E"],["G","M","J","J","E","E","A","E","E","E","E","E","B"],["M","M","J","K","K","E","E","E","K","F","F","E","B"],["J","J","J","J","K","K","K","K","K","K","F","E","B"],["J","K","K","K","K","F","F","K","F","F","F","E","E"],["J","K","K","F","F","F","F","F","F","F","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
