// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "187",
  regions: [["E","B","F","F","F","F"],["E","B","B","B","D","F"],["C","B","D","D","D","F"],["C","C","C","A","D","D"],["C","C","E","A","A","D"],["C","A","A","A","D","D"]],
  hasUniqueSolution: true,
}

export default level
