// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "188",
  regions: [["E","A","A","A","C","C"],["E","A","A","C","C","B"],["E","E","B","B","B","B"],["B","E","B","B","B","B"],["B","B","B","F","C","D"],["B","B","B","F","D","D"]],
  hasUniqueSolution: true,
}

export default level
