// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "189",
  regions: [["A","C","C","C","C","C","C","C","I"],["A","C","I","I","I","I","I","C","I"],["C","C","I","I","I","I","I","I","I"],["C","C","C","C","C","E","I","I","I"],["B","B","C","C","C","E","E","I","I"],["B","G","G","H","H","E","E","I","I"],["B","G","G","G","H","G","I","I","I"],["D","G","G","G","G","G","G","F","I"],["D","D","D","D","G","G","G","F","F"]],
  hasUniqueSolution: true,
}

export default level
