// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '19',
  regions: [
    ['G', 'G', 'D', 'E', 'E', 'B', 'H', 'H', 'H', 'H'],
    ['G', 'D', 'D', 'D', 'E', 'B', 'C', 'C', 'C', 'H'],
    ['G', 'D', 'E', 'E', 'E', 'E', 'E', 'C', 'H', 'H'],
    ['G', 'G', 'E', 'F', 'F', 'F', 'E', 'H', 'H', 'H'],
    ['G', 'A', 'A', 'A', 'A', 'F', 'F', 'F', 'A', 'H'],
    ['G', 'G', 'G', 'G', 'A', 'F', 'A', 'F', 'A', 'H'],
    ['G', 'G', 'G', 'A', 'A', 'A', 'A', 'A', 'A', 'H'],
    ['G', 'G', 'A', 'A', 'A', 'I', 'A', 'J', 'J', 'H'],
    ['G', 'A', 'A', 'A', 'I', 'I', 'I', 'I', 'H', 'H'],
    ['G', 'G', 'A', 'A', 'A', 'F', 'I', 'I', 'I', 'I']
  ],
  hasUniqueSolution: true
}

export default level
