// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "190",
  regions: [["L","L","L","L","L","I","I","I","H","H","N","H","H","H"],["L","L","L","G","L","L","L","L","L","H","H","H","H","H"],["J","L","L","G","L","L","L","H","H","H","H","N","N","N"],["J","L","G","G","L","L","L","L","L","L","H","H","H","N"],["L","L","G","G","G","C","C","L","H","H","H","H","H","N"],["L","L","G","G","G","C","C","L","L","H","H","H","H","N"],["G","G","G","G","C","C","C","C","C","H","H","H","H","N"],["D","G","G","C","C","M","C","C","C","C","H","H","H","N"],["D","G","C","C","C","M","M","C","M","M","B","H","H","N"],["D","G","G","D","E","M","M","M","M","B","B","N","H","N"],["D","D","G","D","E","E","M","M","M","M","N","N","N","N"],["D","D","D","D","A","E","E","E","E","M","M","M","M","K"],["D","D","D","A","A","A","A","A","E","E","A","A","A","K"],["D","D","D","D","A","F","F","A","A","A","A","K","K","K"]],
  hasUniqueSolution: true,
}

export default level
