// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "191",
  regions: [["C","C","C","F","A","A","A","D","D","D"],["C","C","F","F","D","D","D","D","D","D"],["C","F","F","D","D","E","E","D","G","D"],["C","C","F","H","D","D","E","G","G","J"],["C","C","C","H","H","D","I","G","J","J"],["C","H","H","H","H","D","I","H","H","J"],["H","H","H","H","H","H","I","H","J","J"],["H","H","B","H","H","H","H","H","J","H"],["B","H","B","B","B","H","H","H","H","H"],["B","B","B","B","B","H","H","H","H","H"]],
  hasUniqueSolution: true,
}

export default level
