// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "192",
  regions: [["I","M","M","M","E","E","E","E","E","E","D","D","D"],["I","I","M","E","E","C","C","C","D","D","D","D","D"],["I","B","M","E","E","E","C","C","D","D","D","D","D"],["I","B","E","E","C","C","C","C","D","D","D","D","K"],["I","B","E","E","E","E","C","C","D","H","D","K","K"],["I","B","I","E","C","E","E","C","C","H","C","K","K"],["I","I","I","E","C","C","C","C","C","H","C","C","K"],["E","E","E","E","E","C","E","C","H","H","C","A","K"],["J","J","E","E","E","E","E","C","C","C","C","A","A"],["L","L","L","E","E","E","E","E","C","G","G","G","L"],["L","E","E","E","E","F","F","C","C","G","G","L","L"],["L","L","L","E","L","L","L","C","C","C","C","C","L"],["L","L","L","L","L","L","L","L","L","L","L","L","L"]],
  hasUniqueSolution: true,
}

export default level
