// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "193",
  regions: [["F","F","G","C","C","C","I","I","I","I"],["F","G","G","C","C","C","I","I","I","J"],["F","G","I","I","I","C","C","I","I","J"],["F","G","F","F","I","I","I","I","I","J"],["F","F","F","D","I","I","I","I","I","H"],["F","D","D","D","D","I","I","I","I","H"],["B","A","E","E","E","I","I","I","H","H"],["B","A","E","E","E","E","I","I","E","E"],["A","A","E","E","E","E","I","I","I","E"],["A","A","A","E","E","E","E","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
