// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "194",
  regions: [["B","M","M","G","G","G","G","G","G","G","G","G","E"],["E","M","B","G","G","G","G","B","G","E","E","E","E"],["B","B","B","B","B","A","A","B","H","E","E","E","E"],["B","H","H","H","B","B","B","B","H","E","H","E","E"],["B","H","B","H","H","B","B","B","H","E","H","H","E"],["B","L","B","B","H","H","B","H","H","E","H","H","E"],["B","L","B","F","F","H","H","H","H","H","H","H","E"],["B","B","B","B","F","H","H","H","H","K","H","H","H"],["B","F","F","F","F","D","H","H","K","K","K","K","K"],["B","F","F","F","J","D","H","H","H","H","H","H","H"],["B","B","B","B","J","H","H","C","C","H","H","H","H"],["J","J","J","J","J","H","I","I","C","C","C","C","H"],["J","J","J","J","J","H","H","H","H","C","C","H","H"]],
  hasUniqueSolution: true,
}

export default level
