// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "195",
  regions: [["H","H","H","H","H","H","F","F","F","F"],["H","H","H","G","G","F","F","I","F","F"],["H","H","H","G","G","F","F","I","I","I"],["H","C","C","C","G","F","F","I","I","I"],["C","C","C","A","A","A","A","I","I","I"],["B","B","C","B","I","I","I","I","I","I"],["B","B","B","B","I","I","I","I","I","I"],["B","E","E","D","I","D","D","J","J","J"],["B","E","E","D","D","D","D","D","J","J"],["B","B","E","E","D","D","D","D","D","D"]],
  hasUniqueSolution: false,
}

export default level
