// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "196",
  regions: [["C","C","E","E","F","B"],["C","E","E","E","F","B"],["E","E","D","B","B","B"],["E","E","D","A","A","B"],["E","E","D","A","A","A"],["D","D","D","D","D","A"]],
  hasUniqueSolution: true,
}

export default level
