// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "197",
  regions: [["E","C","C","B","B","B","G"],["E","E","C","A","A","A","G"],["E","D","C","C","G","G","G"],["D","E","G","G","G","G","G"],["D","E","F","F","G","F","G"],["D","D","F","F","F","F","G"],["D","D","D","F","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
