// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "198",
  regions: [["G","G","G","G","G","G","E","E","E","K","K","K","K"],["G","J","J","G","J","G","E","E","K","K","E","E","K"],["G","J","J","J","J","J","J","E","E","E","E","E","K"],["J","J","J","J","E","E","J","E","E","E","B","B","A"],["J","L","L","L","L","E","E","E","E","E","B","B","A"],["J","J","L","J","L","L","L","E","E","F","B","B","M"],["J","J","J","J","J","L","L","L","F","F","B","M","M"],["J","C","C","J","L","L","C","L","L","B","B","B","B"],["J","J","C","C","C","C","C","C","C","D","D","B","D"],["C","C","C","C","I","C","I","D","D","D","B","B","D"],["H","H","H","C","I","I","I","D","B","B","B","D","D"],["C","C","C","C","C","C","C","D","D","D","D","D","D"],["C","C","D","D","D","D","D","D","D","D","D","D","D"]],
  hasUniqueSolution: true,
}

export default level
