// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "199",
  regions: [["E","E","C","C","C"],["B","B","C","D","A"],["B","B","D","D","A"],["B","B","D","A","A"],["D","D","D","D","D"]],
  hasUniqueSolution: true,
}

export default level
