// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '2',
  regions: [
    ['B', 'B', 'B', 'B', 'B', 'B', 'B'],
    ['G', 'G', 'B', 'B', 'B', 'B', 'B'],
    ['G', 'B', 'B', 'B', 'B', 'B', 'E'],
    ['G', 'G', 'F', 'F', 'F', 'B', 'E'],
    ['F', 'F', 'F', 'F', 'D', 'D', 'D'],
    ['A', 'F', 'A', 'A', 'C', 'C', 'D'],
    ['A', 'A', 'A', 'A', 'C', 'D', 'D']
  ],
  hasUniqueSolution: true
}

export default level
