// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '2',
  regions: [
    ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
    ['B', 'B', 'A', 'A', 'A', 'A', 'A'],
    ['B', 'A', 'A', 'A', 'A', 'A', 'C'],
    ['B', 'B', 'D', 'D', 'D', 'A', 'C'],
    ['D', 'D', 'D', 'D', 'E', 'E', 'E'],
    ['F', 'D', 'F', 'F', 'G', 'G', 'E'],
    ['F', 'F', 'F', 'F', 'G', 'E', 'E']
  ],
  hasUniqueSolution: true
}

export default level
