// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '20',
  regions: [
    ['K', 'K', 'N', 'N', 'N', 'N', 'N', 'N', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D'],
    ['K', 'K', 'K', 'K', 'K', 'N', 'N', 'N', 'D', 'D', 'N', 'N', 'N', 'N', 'N', 'D', 'D', 'D'],
    ['A', 'K', 'L', 'K', 'N', 'N', 'K', 'N', 'N', 'N', 'N', 'N', 'C', 'J', 'J', 'J', 'J', 'D'],
    ['A', 'A', 'L', 'K', 'K', 'K', 'K', 'K', 'K', 'N', 'K', 'N', 'C', 'J', 'J', 'J', 'J', 'D'],
    ['Q', 'A', 'L', 'L', 'K', 'L', 'K', 'K', 'K', 'K', 'K', 'N', 'C', 'J', 'J', 'J', 'D', 'D'],
    ['Q', 'A', 'A', 'L', 'L', 'L', 'L', 'L', 'K', 'K', 'C', 'C', 'C', 'C', 'J', 'J', 'D', 'D'],
    ['Q', 'A', 'L', 'L', 'C', 'L', 'C', 'L', 'C', 'K', 'C', 'F', 'F', 'C', 'C', 'J', 'D', 'D'],
    ['L', 'L', 'L', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'F', 'F', 'C', 'J', 'J', 'J'],
    ['L', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'F', 'B', 'J'],
    ['L', 'L', 'L', 'C', 'M', 'M', 'C', 'M', 'C', 'C', 'F', 'F', 'P', 'F', 'F', 'F', 'B', 'B'],
    ['O', 'O', 'L', 'M', 'M', 'C', 'C', 'M', 'M', 'C', 'F', 'M', 'P', 'P', 'F', 'F', 'F', 'F'],
    ['O', 'L', 'L', 'M', 'M', 'C', 'C', 'C', 'M', 'M', 'M', 'M', 'M', 'P', 'P', 'P', 'P', 'F'],
    ['O', 'L', 'L', 'M', 'M', 'M', 'C', 'C', 'M', 'E', 'E', 'M', 'M', 'M', 'P', 'M', 'P', 'F'],
    ['O', 'O', 'L', 'L', 'M', 'M', 'M', 'M', 'M', 'M', 'E', 'M', 'G', 'M', 'M', 'M', 'P', 'P'],
    ['O', 'O', 'L', 'L', 'R', 'M', 'M', 'M', 'M', 'E', 'E', 'M', 'G', 'G', 'M', 'M', 'P', 'P'],
    ['O', 'O', 'L', 'R', 'R', 'M', 'M', 'E', 'E', 'E', 'M', 'M', 'M', 'G', 'G', 'M', 'M', 'P'],
    ['R', 'R', 'L', 'L', 'R', 'M', 'I', 'I', 'E', 'E', 'G', 'M', 'G', 'G', 'G', 'G', 'M', 'P'],
    ['R', 'R', 'R', 'R', 'R', 'H', 'H', 'E', 'E', 'G', 'G', 'G', 'G', 'G', 'M', 'M', 'M', 'P']
  ],
  hasUniqueSolution: true
}

export default level
