// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "20",
  regions: [["C","C","B","B","B","B","B","B","A","A","A","A","A","A","A","A","A","A"],["C","C","C","C","C","B","B","B","A","A","B","B","B","B","B","A","A","A"],["F","C","N","C","B","B","C","B","B","B","B","B","H","D","D","D","D","A"],["F","F","N","C","C","C","C","C","C","B","C","B","H","D","D","D","D","A"],["E","F","N","N","C","N","C","C","C","C","C","B","H","D","D","D","A","A"],["E","F","F","N","N","N","N","N","C","C","H","H","H","H","D","D","A","A"],["E","F","N","N","H","N","H","N","H","C","H","G","G","H","H","D","A","A"],["N","N","N","H","H","H","H","H","H","H","H","H","G","G","H","D","D","D"],["N","H","H","H","H","H","H","H","H","H","G","G","G","G","G","G","I","D"],["N","N","N","H","L","L","H","L","H","H","G","G","J","G","G","G","I","I"],["K","K","N","L","L","H","H","L","L","H","G","L","J","J","G","G","G","G"],["K","N","N","L","L","H","H","H","L","L","L","L","L","J","J","J","J","G"],["K","N","N","L","L","L","H","H","L","M","M","L","L","L","J","L","J","G"],["K","K","N","N","L","L","L","L","L","L","M","L","O","L","L","L","J","J"],["K","K","N","N","P","L","L","L","L","M","M","L","O","O","L","L","J","J"],["K","K","N","P","P","L","L","M","M","M","L","L","L","O","O","L","L","J"],["P","P","N","N","P","L","Q","Q","M","M","O","L","O","O","O","O","L","J"],["P","P","P","P","P","R","R","M","M","O","O","O","O","O","L","L","L","J"]],
  hasUniqueSolution: true,
}

export default level
