// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "200",
  regions: [["A","A","A","A","A","D"],["A","B","A","A","A","D"],["E","B","F","A","A","A"],["E","B","F","F","A","A"],["E","F","F","C","A","A"],["E","E","F","C","A","A"]],
  hasUniqueSolution: true,
}

export default level
