// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "201",
  regions: [["G","G","G","G","G","G","B","D","E"],["G","A","G","E","G","G","B","D","E"],["A","A","G","E","E","B","B","I","E"],["A","A","G","E","E","B","I","I","E"],["A","G","G","E","H","E","E","I","E"],["A","A","E","E","H","E","I","I","E"],["E","E","E","E","E","E","E","E","E"],["E","E","C","E","E","E","E","C","E"],["F","F","C","C","C","C","C","C","E"]],
  hasUniqueSolution: true,
}

export default level
