// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "202",
  regions: [["F","F","B","B","B","B","B","B","B","B","B","B","B","I","I"],["C","F","F","F","F","C","O","E","E","E","E","B","B","B","I"],["C","F","F","C","F","C","O","O","O","E","E","E","I","I","I"],["C","C","C","C","F","C","C","O","E","E","E","E","E","I","I"],["C","E","C","C","C","C","C","O","O","E","H","J","J","J","J"],["C","E","C","K","K","K","C","O","O","E","H","H","J","N","J"],["C","E","C","E","E","E","C","C","C","E","H","H","A","N","J"],["E","E","C","E","E","E","C","C","E","E","H","H","A","N","N"],["E","E","E","E","G","E","E","E","E","E","E","E","A","D","N"],["E","E","E","E","G","G","E","E","E","E","A","A","A","D","D"],["G","G","G","G","G","G","E","E","A","E","A","A","A","A","D"],["G","G","E","G","E","G","E","L","A","A","A","A","A","D","D"],["G","E","E","E","E","E","E","L","L","L","A","A","A","A","L"],["E","E","E","E","E","E","E","E","L","L","L","L","L","L","L"],["E","E","E","L","L","L","L","L","L","M","M","M","M","L","L"]],
  hasUniqueSolution: true,
}

export default level
