// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "203",
  regions: [["A","A","A","A","A","A"],["A","A","F","F","E","E"],["B","B","F","F","E","E"],["D","D","F","F","C","C"],["D","D","C","C","C","D"],["D","D","D","D","D","D"]],
  hasUniqueSolution: true,
}

export default level
