// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "204",
  regions: [["A","A","F","F","B","B","B","B"],["A","F","F","F","B","B","B","H"],["A","A","F","F","F","B","H","H"],["G","G","F","F","F","B","F","H"],["G","F","F","G","F","F","F","F"],["G","G","G","G","F","F","C","C"],["D","D","D","G","F","E","E","C"],["D","D","D","G","F","F","F","C"]],
  hasUniqueSolution: true,
}

export default level
