// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "205",
  regions: [["A","G","E","E","G","G","F"],["G","G","G","G","G","G","F"],["C","G","G","G","A","G","F"],["C","G","G","A","A","G","F"],["G","G","G","G","A","A","A"],["G","G","G","B","D","D","A"],["G","G","G","B","A","A","A"]],
  hasUniqueSolution: true,
}

export default level
