// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "206",
  regions: [["C","C","H","H","H","H","H","H","I","I","I"],["C","C","H","H","B","J","J","H","H","H","I"],["C","C","H","C","B","J","G","G","G","H","I"],["C","C","C","C","A","A","A","G","G","I","I"],["C","K","C","D","A","A","G","G","G","I","I"],["C","K","D","D","D","D","G","F","F","F","I"],["C","K","D","D","F","F","F","F","F","F","F"],["D","K","K","D","D","F","E","E","F","E","F"],["D","D","K","D","F","F","E","E","E","E","F"],["D","D","K","D","D","F","E","E","E","E","F"],["D","D","D","D","D","F","F","E","E","E","F"]],
  hasUniqueSolution: true,
}

export default level
