// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "207",
  regions: [["A","A","B","B","B","B","I","I","I"],["A","A","B","B","I","I","I","I","I"],["A","I","I","I","I","E","H","H","G"],["A","I","D","C","C","E","H","H","G"],["A","I","D","D","C","C","H","G","G"],["A","I","F","F","C","H","H","H","G"],["A","I","I","I","C","C","C","H","G"],["A","I","I","C","C","H","C","H","G"],["A","A","I","C","H","H","H","H","G"]],
  hasUniqueSolution: true,
}

export default level
