// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "208",
  regions: [["I","I","I","H","C","C","C","C","C","E","E"],["I","I","H","H","H","F","F","E","E","E","E"],["A","I","D","D","H","F","D","D","D","D","E"],["A","I","D","D","D","D","D","D","D","E","E"],["I","I","I","I","I","J","E","D","E","E","E"],["J","J","J","I","J","J","E","E","E","E","E"],["B","J","J","J","J","J","J","J","E","E","E"],["B","B","B","B","B","J","J","J","J","J","E"],["G","G","B","G","B","B","B","K","K","E","E"],["G","G","G","G","G","B","B","K","E","E","E"],["G","G","G","G","G","G","G","G","G","G","E"]],
  hasUniqueSolution: true,
}

export default level
