// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "209",
  regions: [["E","E","E","E","E","E","E","E","E","A","A"],["E","E","E","E","D","F","E","F","F","F","A"],["E","E","E","D","D","F","F","F","K","A","A"],["E","E","E","F","F","F","F","K","K","A","A"],["E","E","E","E","F","F","A","A","A","A","A"],["H","E","H","E","F","A","A","A","A","A","A"],["H","E","H","E","F","A","A","G","I","J","J"],["H","H","H","C","C","C","G","G","I","J","B"],["H","H","C","C","H","C","C","J","I","J","B"],["H","H","C","H","H","J","J","J","J","J","B"],["H","H","H","H","H","H","J","J","J","J","B"]],
  hasUniqueSolution: true,
}

export default level
