// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '21',
  regions: [
    ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
    ['A', 'C', 'C', 'B', 'B', 'B', 'B', 'A', 'A', 'D', 'A', 'A'],
    ['A', 'A', 'C', 'C', 'B', 'A', 'A', 'A', 'A', 'D', 'A', 'D'],
    ['F', 'A', 'A', 'C', 'B', 'A', 'A', 'A', 'D', 'D', 'D', 'D'],
    ['F', 'A', 'A', 'C', 'B', 'B', 'B', 'B', 'B', 'B', 'D', 'E'],
    ['F', 'F', 'F', 'C', 'C', 'C', 'C', 'B', 'I', 'I', 'E', 'E'],
    ['F', 'H', 'F', 'F', 'I', 'I', 'C', 'B', 'I', 'G', 'I', 'E'],
    ['F', 'H', 'H', 'F', 'H', 'I', 'B', 'B', 'I', 'G', 'I', 'I'],
    ['F', 'F', 'H', 'H', 'H', 'I', 'I', 'I', 'I', 'I', 'I', 'I'],
    ['J', 'J', 'J', 'H', 'I', 'I', 'I', 'I', 'F', 'I', 'I', 'I'],
    ['K', 'K', 'J', 'H', 'H', 'J', 'I', 'I', 'I', 'I', 'I', 'I'],
    ['K', 'J', 'J', 'J', 'J', 'J', 'I', 'I', 'I', 'L', 'L', 'L']
  ],
  hasUniqueSolution: true
}

export default level
