// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '21',
  regions: [
    ['B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B'],
    ['B', 'K', 'K', 'J', 'J', 'J', 'J', 'B', 'B', 'A', 'B', 'B'],
    ['B', 'B', 'K', 'K', 'J', 'B', 'B', 'B', 'B', 'A', 'B', 'A'],
    ['C', 'B', 'B', 'K', 'J', 'B', 'B', 'B', 'A', 'A', 'A', 'A'],
    ['C', 'B', 'B', 'K', 'J', 'J', 'J', 'J', 'J', 'J', 'A', 'L'],
    ['C', 'C', 'C', 'K', 'K', 'K', 'K', 'J', 'F', 'F', 'L', 'L'],
    ['C', 'I', 'C', 'C', 'F', 'F', 'K', 'J', 'F', 'D', 'F', 'L'],
    ['C', 'I', 'I', 'C', 'I', 'F', 'J', 'J', 'F', 'D', 'F', 'F'],
    ['C', 'C', 'I', 'I', 'I', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
    ['H', 'H', 'H', 'I', 'F', 'F', 'F', 'F', 'C', 'F', 'F', 'F'],
    ['G', 'G', 'H', 'I', 'I', 'H', 'F', 'F', 'F', 'F', 'F', 'F'],
    ['G', 'H', 'H', 'H', 'H', 'H', 'F', 'F', 'F', 'E', 'E', 'E']
  ],
  hasUniqueSolution: true
}

export default level
