// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "210",
  regions: [["K","K","K","K","K","K","K","K","K","K","I","I","I","I"],["L","M","M","K","M","K","N","N","N","I","I","I","I","I"],["L","L","M","M","M","K","K","K","N","N","N","G","I","G"],["L","M","M","L","M","K","K","K","K","N","N","G","G","G"],["L","L","M","L","M","M","M","K","N","N","N","N","N","D"],["L","L","L","C","L","M","M","K","N","N","N","N","D","D"],["L","C","C","L","L","L","M","D","D","B","B","N","D","D"],["L","L","C","J","J","J","M","D","D","B","B","N","D","D"],["L","L","C","J","J","M","M","D","B","B","N","N","D","D"],["L","L","L","J","J","M","M","D","D","D","D","N","D","D"],["L","L","L","L","J","J","M","A","A","J","D","D","D","E"],["L","L","L","J","J","M","M","J","J","J","J","J","D","E"],["L","H","H","H","J","J","M","J","J","F","J","F","F","F"],["L","L","H","J","J","J","J","J","J","F","F","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
