// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "211",
  regions: [["B","B","C","C","F","F","F"],["B","B","C","C","F","E","F"],["B","B","A","A","A","E","E"],["A","A","A","A","D","E","E"],["G","G","G","D","D","E","E"],["G","G","G","D","E","E","E"],["G","G","G","D","D","E","E"]],
  hasUniqueSolution: false,
}

export default level
