// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "212",
  regions: [["H","H","B","B","B","B","B","B","B"],["A","I","I","I","I","B","B","B","B"],["A","A","I","F","I","I","I","F","B"],["A","F","F","F","F","F","F","F","B"],["A","G","A","A","F","F","F","F","B"],["A","G","A","A","F","F","B","F","B"],["A","A","A","E","C","F","B","B","B"],["A","E","A","E","C","D","D","D","D"],["A","E","E","E","E","D","D","D","D"]],
  hasUniqueSolution: true,
}

export default level
