// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "213",
  regions: [["J","J","J","J","F","F","F","F","F","F"],["J","J","J","J","J","F","G","F","F","F"],["J","J","F","F","F","F","G","G","G","F"],["F","F","F","A","A","C","C","G","G","F"],["F","F","F","F","A","A","A","G","G","B"],["F","F","F","A","A","A","G","G","B","B"],["A","A","A","A","I","D","D","G","G","B"],["I","I","I","I","I","D","E","E","B","B"],["H","I","I","I","D","D","I","I","I","B"],["H","H","H","I","I","I","I","I","I","B"]],
  hasUniqueSolution: true,
}

export default level
