// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "214",
  regions: [["E","E","C","D","F","F","I","I","I","I"],["E","E","C","D","I","I","I","J","D","I"],["G","E","E","D","D","I","J","J","D","I"],["G","G","E","E","D","D","D","J","D","D"],["G","G","E","E","D","D","D","D","D","A"],["H","G","G","H","H","D","H","H","H","A"],["H","G","H","H","H","H","H","B","A","A"],["H","G","G","G","H","H","H","B","B","A"],["H","H","G","H","H","H","B","B","A","A"],["H","H","H","H","H","H","H","A","A","A"]],
  hasUniqueSolution: true,
}

export default level
