// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "215",
  regions: [["A","A","E","E","F","F"],["A","C","E","F","F","F"],["A","C","C","F","F","F"],["A","C","C","C","F","F"],["B","B","C","C","D","D"],["B","B","B","C","D","D"]],
  hasUniqueSolution: false,
}

export default level
