// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "216",
  regions: [["G","G","A","A","A","A","A","D","E"],["G","G","A","A","A","A","D","D","E"],["G","G","A","I","I","I","D","E","E"],["G","B","B","B","F","I","D","E","E"],["C","B","B","B","F","D","D","E","E"],["C","B","B","B","F","F","F","H","H"],["C","C","C","B","F","F","F","H","H"],["C","C","C","C","H","H","H","H","H"],["C","C","C","C","H","H","H","H","H"]],
  hasUniqueSolution: false,
}

export default level
