// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "217",
  regions: [["B","B","B","B","B","B","B","G"],["B","E","B","E","B","B","H","G"],["F","E","E","E","B","H","H","G"],["F","E","B","B","B","G","G","G"],["E","E","E","E","G","G","G","G"],["E","E","D","E","G","G","G","G"],["E","E","D","A","C","C","G","G"],["E","E","E","A","A","G","G","G"]],
  hasUniqueSolution: true,
}

export default level
