// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "218",
  regions: [["C","C","F","F","B","B","B","B"],["G","F","F","B","B","B","B","B"],["G","E","F","B","B","B","B","B"],["G","E","F","F","F","D","B","B"],["G","E","E","A","A","D","D","B"],["E","E","E","A","D","D","B","B"],["A","E","A","A","D","D","B","B"],["A","A","A","A","A","H","H","B"]],
  hasUniqueSolution: true,
}

export default level
