// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "219",
  regions: [["D","D","D","F","F","G","G","C"],["D","D","D","F","F","A","A","C"],["D","D","D","D","F","A","A","C"],["H","H","D","D","A","A","B","C"],["H","H","E","E","A","D","B","B"],["H","E","E","E","A","A","B","B"],["H","H","H","E","E","E","E","B"],["H","H","E","E","E","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
