// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '22',
  regions: [
    ['L', 'L', 'L', 'C', 'C', 'C', 'C', 'C', 'D', 'D', 'D', 'D', 'D', 'P', 'K', 'K'],
    ['L', 'L', 'L', 'C', 'C', 'C', 'C', 'C', 'C', 'D', 'D', 'D', 'P', 'P', 'K', 'F'],
    ['L', 'L', 'C', 'C', 'L', 'L', 'L', 'L', 'C', 'C', 'D', 'P', 'P', 'K', 'K', 'F'],
    ['J', 'L', 'C', 'L', 'L', 'J', 'J', 'L', 'C', 'C', 'C', 'N', 'P', 'K', 'K', 'F'],
    ['J', 'L', 'L', 'L', 'L', 'J', 'J', 'L', 'L', 'C', 'N', 'N', 'P', 'P', 'K', 'I'],
    ['J', 'J', 'J', 'J', 'J', 'J', 'L', 'L', 'L', 'C', 'C', 'N', 'P', 'P', 'P', 'I'],
    ['J', 'J', 'H', 'H', 'H', 'J', 'J', 'J', 'L', 'L', 'C', 'N', 'N', 'I', 'I', 'I'],
    ['J', 'J', 'H', 'E', 'H', 'L', 'J', 'J', 'L', 'L', 'L', 'L', 'N', 'N', 'N', 'I'],
    ['J', 'H', 'H', 'E', 'H', 'L', 'J', 'J', 'J', 'L', 'L', 'L', 'N', 'N', 'I', 'I'],
    ['J', 'J', 'H', 'E', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'N', 'N', 'I'],
    ['E', 'E', 'H', 'E', 'L', 'E', 'L', 'N', 'L', 'L', 'N', 'N', 'N', 'N', 'N', 'N'],
    ['G', 'E', 'E', 'E', 'E', 'E', 'N', 'N', 'N', 'N', 'N', 'N', 'M', 'A', 'A', 'N'],
    ['G', 'E', 'E', 'G', 'G', 'E', 'E', 'N', 'M', 'N', 'N', 'M', 'M', 'A', 'A', 'N'],
    ['G', 'G', 'G', 'G', 'B', 'O', 'O', 'O', 'M', 'M', 'M', 'M', 'A', 'A', 'A', 'N'],
    ['G', 'B', 'G', 'G', 'B', 'B', 'B', 'O', 'O', 'M', 'M', 'M', 'M', 'A', 'M', 'M'],
    ['B', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M']
  ],
  hasUniqueSolution: true
}

export default level
