// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "22",
  regions: [["J","J","J","D","D","D","D","D","A","A","A","A","A","C","E","E"],["J","J","J","D","D","D","D","D","D","A","A","A","C","C","E","B"],["J","J","D","D","J","J","J","J","D","D","A","C","C","E","E","B"],["F","J","D","J","J","F","F","J","D","D","D","K","C","E","E","B"],["F","J","J","J","J","F","F","J","J","D","K","K","C","C","E","G"],["F","F","F","F","F","F","J","J","J","D","D","K","C","C","C","G"],["F","F","I","I","I","F","F","F","J","J","D","K","K","G","G","G"],["F","F","I","H","I","J","F","F","J","J","J","J","K","K","K","G"],["F","I","I","H","I","J","F","F","F","J","J","J","K","K","G","G"],["F","F","I","H","J","J","J","J","J","J","J","J","J","K","K","G"],["H","H","I","H","J","H","J","K","J","J","K","K","K","K","K","K"],["L","H","H","H","H","H","K","K","K","K","K","K","M","N","N","K"],["L","H","H","L","L","H","H","K","M","K","K","M","M","N","N","K"],["L","L","L","L","P","O","O","O","M","M","M","M","N","N","N","K"],["L","P","L","L","P","P","P","O","O","M","M","M","M","N","M","M"],["P","P","P","P","P","M","M","M","M","M","M","M","M","M","M","M"]],
  hasUniqueSolution: true,
}

export default level
