// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "220",
  regions: [["B","B","B","B","B","F","F"],["B","B","B","B","B","B","F"],["A","B","E","E","F","F","F"],["A","C","C","E","F","E","F"],["A","C","C","E","F","E","D"],["C","C","C","E","E","E","D"],["C","G","G","E","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
