// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "221",
  regions: [["C","C","C","C","C","G","G","G","I","I"],["C","C","C","C","C","C","G","G","G","G"],["C","C","E","E","G","G","G","G","G","G"],["C","C","E","E","E","G","G","G","H","G"],["C","C","C","E","E","F","H","D","H","G"],["D","C","E","E","F","F","H","H","H","G"],["D","C","C","C","J","J","J","H","H","H"],["D","D","D","C","J","J","J","H","H","B"],["D","D","C","C","J","J","J","A","A","B"],["D","D","D","J","J","J","J","A","A","A"]],
  hasUniqueSolution: true,
}

export default level
