// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "222",
  regions: [["D","D","D","D","B","B","E","E","E","E"],["D","D","D","D","D","F","F","F","C","E"],["C","F","F","F","D","F","F","C","C","C"],["C","C","H","F","F","F","F","C","C","C"],["C","C","H","F","F","C","C","C","C","I"],["C","C","C","C","C","C","G","C","J","I"],["A","C","G","C","G","G","G","C","J","I"],["A","A","G","C","G","G","G","G","G","I"],["A","A","G","G","G","G","G","G","I","I"],["A","A","A","A","A","A","A","I","I","I"]],
  hasUniqueSolution: true,
}

export default level
