// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "223",
  regions: [["A","A","A","A","A","E","E","E"],["C","C","C","A","A","E","A","E"],["C","D","A","A","A","A","A","E"],["C","D","D","D","F","F","F","E"],["D","D","D","F","F","F","F","G"],["D","F","F","F","F","B","B","G"],["D","F","H","H","F","F","F","F"],["D","H","H","F","F","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
