// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "224",
  regions: [["H","H","D","D","D","D","D","D","A","A"],["H","J","D","D","D","D","D","D","D","A"],["H","J","D","I","I","D","D","C","A","A"],["H","J","J","D","D","D","D","C","A","A"],["H","H","J","J","J","J","D","B","B","A"],["H","J","J","B","B","B","D","B","A","A"],["H","H","F","E","E","B","B","B","F","A"],["H","F","F","F","F","F","F","F","F","A"],["H","F","H","H","H","G","G","G","F","A"],["H","H","H","H","G","G","F","F","F","A"]],
  hasUniqueSolution: true,
}

export default level
