// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "225",
  regions: [["C","C","C","C","C","D","D","D","D","D","D"],["K","C","K","C","C","D","C","D","D","D","D"],["K","K","K","C","C","C","C","B","B","D","D"],["F","K","K","C","C","C","B","B","B","B","D"],["F","F","K","C","K","C","B","B","B","D","D"],["F","F","K","K","K","B","B","I","I","E","E"],["H","H","H","H","K","K","B","I","E","E","B"],["J","J","H","G","G","K","B","B","B","B","B"],["J","G","G","G","G","K","B","B","G","G","B"],["J","J","G","G","A","A","G","G","G","B","B"],["J","J","G","G","G","G","G","G","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
