// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "226",
  regions: [["I","E","E","E","B","B","C","C","L","L","K","L","L","J"],["I","E","I","E","A","B","B","B","E","L","K","L","J","J"],["I","E","I","I","A","B","L","L","L","L","L","L","D","J"],["I","I","I","A","A","B","L","L","L","D","D","L","D","J"],["F","I","I","A","B","B","L","D","L","L","D","D","D","J"],["F","I","L","A","L","L","L","D","L","D","D","D","J","J"],["F","I","L","A","L","D","L","D","D","D","D","D","D","J"],["F","I","L","L","L","D","D","D","G","G","D","M","J","J"],["F","L","L","D","D","D","F","F","D","D","D","M","J","J"],["F","F","F","F","F","F","F","F","M","M","M","M","M","J"],["F","H","F","F","F","F","M","M","M","M","M","M","M","J"],["F","H","H","H","F","F","M","M","M","N","M","M","M","J"],["F","H","H","H","F","F","F","M","M","N","N","N","M","M"],["F","H","H","H","H","H","H","N","N","N","N","N","M","M"]],
  hasUniqueSolution: true,
}

export default level
