// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "227",
  regions: [["C","B","B","B","B","B","B","B"],["C","B","B","B","B","B","A","A"],["C","C","F","F","B","B","A","G"],["C","F","F","F","F","B","A","G"],["C","C","C","E","E","E","E","G"],["C","C","C","C","C","E","E","D"],["H","C","C","C","H","H","D","D"],["H","H","H","H","H","D","D","D"]],
  hasUniqueSolution: true,
}

export default level
