// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "228",
  regions: [["E","E","E","E","E","E","E"],["E","E","E","E","E","C","E"],["E","E","D","D","C","C","C"],["D","D","D","D","F","C","C"],["B","B","B","D","F","F","F"],["G","G","B","B","A","F","A"],["G","B","B","A","A","A","A"]],
  hasUniqueSolution: true,
}

export default level
