// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "229",
  regions: [["A","A","A","I","B","B","B","B","B","B","B"],["F","A","I","I","B","B","B","C","B","B","B"],["F","F","I","I","I","B","C","C","B","C","B"],["J","F","I","K","I","B","B","C","B","C","B"],["J","J","I","K","K","C","C","C","B","C","B"],["J","I","I","C","C","C","C","C","C","C","C"],["J","I","C","C","I","C","C","I","C","C","C"],["I","I","I","C","I","I","I","I","E","C","E"],["D","D","I","I","I","H","E","E","E","C","E"],["D","I","I","D","I","H","H","E","E","E","E"],["D","D","D","D","I","I","H","E","E","G","G"]],
  hasUniqueSolution: true,
}

export default level
