// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "23",
  regions: [["B","B","B","B","A","A","A","A","A","A","A","A","A","A","A","A","A","A"],["B","A","A","B","A","A","B","B","B","A","B","A","A","A","A","A","E","A"],["B","B","A","A","A","B","B","D","D","D","B","A","C","C","C","A","E","A"],["B","A","A","A","B","B","B","D","B","B","B","A","A","C","A","A","E","A"],["B","B","B","B","B","B","B","B","B","C","C","A","A","C","E","E","E","A"],["B","B","F","B","B","B","B","B","C","C","C","A","C","C","C","E","E","E"],["B","B","F","F","F","F","B","G","G","C","C","C","C","E","C","E","C","E"],["H","B","F","F","F","B","B","F","C","C","C","C","C","E","C","C","C","E"],["H","H","J","F","F","F","F","F","F","C","C","C","I","E","E","E","C","E"],["H","J","J","F","K","K","K","F","F","C","I","I","I","I","E","C","C","E"],["H","F","F","F","N","K","K","F","I","I","I","L","L","E","E","E","C","E"],["R","R","N","N","N","K","K","F","F","I","I","L","L","L","E","C","C","E"],["R","R","R","N","N","N","N","F","I","I","I","M","M","O","E","E","C","E"],["R","R","R","R","R","R","N","I","I","I","O","O","O","O","O","E","E","E"],["R","P","P","P","R","N","N","I","I","O","O","O","O","O","O","Q","E","E"],["R","P","P","P","R","R","I","I","R","R","R","R","E","Q","Q","Q","Q","E"],["R","P","R","P","R","I","I","I","R","R","R","R","E","E","Q","E","Q","E"],["R","P","R","R","R","R","R","R","R","R","R","R","E","E","E","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
