// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '23',
  regions: [
    ['G', 'G', 'G', 'G', 'I', 'I', 'I', 'I', 'I', 'I', 'I', 'I', 'I', 'I', 'I', 'I', 'I', 'I'],
    ['G', 'I', 'I', 'G', 'I', 'I', 'G', 'G', 'G', 'I', 'G', 'I', 'I', 'I', 'I', 'I', 'K', 'I'],
    ['G', 'G', 'I', 'I', 'I', 'G', 'G', 'Q', 'Q', 'Q', 'G', 'I', 'O', 'O', 'O', 'I', 'K', 'I'],
    ['G', 'I', 'I', 'I', 'G', 'G', 'G', 'Q', 'G', 'G', 'G', 'I', 'I', 'O', 'I', 'I', 'K', 'I'],
    ['G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'O', 'O', 'I', 'I', 'O', 'K', 'K', 'K', 'I'],
    ['G', 'G', 'R', 'G', 'G', 'G', 'G', 'G', 'O', 'O', 'O', 'I', 'O', 'O', 'O', 'K', 'K', 'K'],
    ['G', 'G', 'R', 'R', 'R', 'R', 'G', 'N', 'N', 'O', 'O', 'O', 'O', 'K', 'O', 'K', 'O', 'K'],
    ['D', 'G', 'R', 'R', 'R', 'G', 'G', 'R', 'O', 'O', 'O', 'O', 'O', 'K', 'O', 'O', 'O', 'K'],
    ['D', 'D', 'F', 'R', 'R', 'R', 'R', 'R', 'R', 'O', 'O', 'O', 'B', 'K', 'K', 'K', 'O', 'K'],
    ['D', 'F', 'F', 'R', 'P', 'P', 'P', 'R', 'R', 'O', 'B', 'B', 'B', 'B', 'K', 'O', 'O', 'K'],
    ['D', 'R', 'R', 'R', 'C', 'P', 'P', 'R', 'B', 'B', 'B', 'J', 'J', 'K', 'K', 'K', 'O', 'K'],
    ['A', 'A', 'C', 'C', 'C', 'P', 'P', 'R', 'R', 'B', 'B', 'J', 'J', 'J', 'K', 'O', 'O', 'K'],
    ['A', 'A', 'A', 'C', 'C', 'C', 'C', 'R', 'B', 'B', 'B', 'E', 'E', 'H', 'K', 'K', 'O', 'K'],
    ['A', 'A', 'A', 'A', 'A', 'A', 'C', 'B', 'B', 'B', 'H', 'H', 'H', 'H', 'H', 'K', 'K', 'K'],
    ['A', 'L', 'L', 'L', 'A', 'C', 'C', 'B', 'B', 'H', 'H', 'H', 'H', 'H', 'H', 'M', 'K', 'K'],
    ['A', 'L', 'L', 'L', 'A', 'A', 'B', 'B', 'A', 'A', 'A', 'A', 'K', 'M', 'M', 'M', 'M', 'K'],
    ['A', 'L', 'A', 'L', 'A', 'B', 'B', 'B', 'A', 'A', 'A', 'A', 'K', 'K', 'M', 'K', 'M', 'K'],
    ['A', 'L', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'K', 'K', 'K', 'K', 'K', 'K']
  ],
  hasUniqueSolution: true
}

export default level
