// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "230",
  regions: [["B","B","B","E","E","E","C"],["B","B","B","E","E","C","C"],["A","A","A","E","E","E","C"],["F","A","A","E","E","E","E"],["F","F","A","G","G","G","G"],["A","F","A","G","G","G","D"],["A","A","A","D","D","D","D"]],
  hasUniqueSolution: false,
}

export default level
