// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "231",
  regions: [["B","B","B","B","B","B","B","F","F","F"],["J","G","G","G","B","B","C","C","C","F"],["J","G","G","G","B","B","H","F","F","F"],["G","G","G","G","G","B","H","F","H","F"],["G","G","G","G","H","H","H","F","H","H"],["G","G","H","H","H","H","H","H","H","H"],["G","H","H","E","I","E","E","D","H","H"],["H","H","H","C","I","E","H","D","H","A"],["H","H","H","E","E","E","H","H","H","A"],["H","H","H","H","H","E","E","E","A","A"]],
  hasUniqueSolution: true,
}

export default level
