// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "232",
  regions: [["C","C","C","F","E","E"],["C","C","C","F","E","E"],["D","C","F","F","A","E"],["D","B","B","F","A","E"],["D","D","B","F","A","E"],["D","D","B","B","B","B"]],
  hasUniqueSolution: false,
}

export default level
