// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "233",
  regions: [["I","I","I","I","I","E","E","E","G"],["I","I","I","I","I","E","E","C","G"],["I","I","E","E","E","E","C","C","G"],["I","I","I","B","B","B","C","C","C"],["B","I","B","B","B","B","H","H","H"],["B","B","B","A","A","A","A","H","H"],["B","B","A","A","H","H","H","H","H"],["B","B","A","B","H","D","D","F","H"],["B","E","B","B","D","D","D","F","F"]],
  hasUniqueSolution: true,
}

export default level
