// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "234",
  regions: [["C","C","C","C","C","C","C","C","C"],["C","C","C","H","H","H","H","C","C"],["C","E","I","I","I","I","H","H","H"],["C","E","C","B","I","H","H","D","D"],["C","C","C","B","I","F","H","H","D"],["C","B","B","B","I","F","H","H","G"],["C","B","C","B","I","I","H","H","G"],["C","C","C","B","I","B","B","B","B"],["C","B","B","B","B","B","A","A","B"]],
  hasUniqueSolution: true,
}

export default level
