// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "235",
  regions: [["F","F","F","F","F","E","E","D","D","D"],["F","I","F","I","G","G","G","G","D","D"],["I","I","I","I","D","D","G","G","D","D"],["I","J","D","D","D","D","D","G","D","D"],["I","J","B","B","C","C","D","D","D","D"],["I","J","J","B","F","D","D","D","D","A"],["I","C","C","C","C","H","H","H","H","A"],["I","I","A","A","A","H","A","A","A","A"],["I","I","I","I","A","A","A","A","I","A"],["I","I","I","I","I","I","I","I","I","A"]],
  hasUniqueSolution: true,
}

export default level
