// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "236",
  regions: [["F","E","E","B","B","E"],["F","F","E","E","E","E"],["C","C","C","C","C","E"],["C","C","A","C","C","C"],["C","A","A","A","C","C"],["C","D","D","C","C","C"]],
  hasUniqueSolution: true,
}

export default level
