// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "237",
  regions: [["D","D","D","D","G","G","B","B","B"],["D","D","D","B","G","B","B","H","B"],["D","A","B","B","B","B","B","H","B"],["A","A","A","E","E","I","I","H","B"],["A","E","E","E","E","E","I","I","I"],["A","A","A","F","E","E","E","I","E"],["A","C","A","F","E","F","E","E","E"],["C","C","F","F","F","F","F","F","F"],["C","F","F","F","F","F","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
