// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "238",
  regions: [["D","D","D","D","A","A"],["D","B","D","D","D","A"],["B","B","B","D","D","A"],["D","B","F","E","E","A"],["F","B","F","C","C","A"],["F","F","F","F","C","A"]],
  hasUniqueSolution: true,
}

export default level
