// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "239",
  regions: [["A","A","A","D","C","C","C"],["A","A","A","D","D","D","C"],["F","A","A","C","C","C","C"],["F","A","B","B","A","A","C"],["F","A","A","A","A","G","C"],["A","A","A","E","E","G","C"],["A","C","C","C","C","C","C"]],
  hasUniqueSolution: true,
}

export default level
