// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '24',
  regions: [
    ['L', 'L', 'A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B'],
    ['I', 'L', 'A', 'G', 'A', 'A', 'A', 'B', 'B', 'G', 'G', 'G'],
    ['I', 'L', 'A', 'G', 'A', 'A', 'G', 'G', 'G', 'G', 'G', 'C'],
    ['A', 'A', 'A', 'G', 'G', 'G', 'G', 'J', 'G', 'G', 'C', 'C'],
    ['G', 'G', 'G', 'G', 'K', 'G', 'J', 'J', 'G', 'G', 'G', 'C'],
    ['K', 'K', 'G', 'K', 'K', 'G', 'G', 'J', 'J', 'G', 'G', 'F'],
    ['K', 'K', 'G', 'K', 'K', 'G', 'H', 'J', 'J', 'F', 'F', 'F'],
    ['D', 'K', 'K', 'K', 'G', 'G', 'H', 'J', 'J', 'F', 'J', 'F'],
    ['D', 'K', 'K', 'G', 'G', 'J', 'J', 'J', 'J', 'J', 'J', 'F'],
    ['D', 'K', 'K', 'G', 'D', 'J', 'J', 'J', 'F', 'F', 'F', 'F'],
    ['D', 'D', 'K', 'D', 'D', 'J', 'J', 'J', 'J', 'J', 'E', 'F'],
    ['D', 'D', 'D', 'D', 'J', 'J', 'J', 'J', 'J', 'J', 'E', 'E']
  ],
  hasUniqueSolution: true
}

export default level
