// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '24',
  regions: [
    ['A', 'A', 'D', 'D', 'D', 'D', 'D', 'D', 'B', 'B', 'B', 'B'],
    ['C', 'A', 'D', 'F', 'D', 'D', 'D', 'B', 'B', 'F', 'F', 'F'],
    ['C', 'A', 'D', 'F', 'D', 'D', 'F', 'F', 'F', 'F', 'F', 'E'],
    ['D', 'D', 'D', 'F', 'F', 'F', 'F', 'I', 'F', 'F', 'E', 'E'],
    ['F', 'F', 'F', 'F', 'H', 'F', 'I', 'I', 'F', 'F', 'F', 'E'],
    ['H', 'H', 'F', 'H', 'H', 'F', 'F', 'I', 'I', 'F', 'F', 'J'],
    ['H', 'H', 'F', 'H', 'H', 'F', 'G', 'I', 'I', 'J', 'J', 'J'],
    ['K', 'H', 'H', 'H', 'F', 'F', 'G', 'I', 'I', 'J', 'I', 'J'],
    ['K', 'H', 'H', 'F', 'F', 'I', 'I', 'I', 'I', 'I', 'I', 'J'],
    ['K', 'H', 'H', 'F', 'K', 'I', 'I', 'I', 'J', 'J', 'J', 'J'],
    ['K', 'K', 'H', 'K', 'K', 'I', 'I', 'I', 'I', 'I', 'L', 'J'],
    ['K', 'K', 'K', 'K', 'I', 'I', 'I', 'I', 'I', 'I', 'L', 'L']
  ],
  hasUniqueSolution: true
}

export default level
