// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "240",
  regions: [["C","C","D","D","C","C","C","C","C","G"],["C","D","D","D","C","C","C","G","C","G"],["C","C","C","C","C","A","A","G","G","G"],["C","C","J","I","C","C","A","G","C","G"],["C","J","J","I","I","C","C","C","C","C"],["C","C","F","I","I","I","H","H","C","C"],["C","F","F","I","C","C","C","C","C","C"],["C","F","F","F","F","F","C","C","C","C"],["C","F","B","B","B","F","F","F","C","C"],["C","C","B","E","E","E","E","E","E","C"]],
  hasUniqueSolution: true,
}

export default level
