// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "241",
  regions: [["B","B","I","I","I","I","I","K","K","K","K","K","K"],["H","A","A","A","I","I","I","J","K","K","K","J","J"],["H","H","H","A","A","A","I","K","K","J","J","J","J"],["H","H","A","A","A","A","I","K","K","K","J","J","J"],["H","A","A","A","A","K","D","K","K","J","J","J","J"],["H","A","A","K","A","K","D","D","K","K","J","J","J"],["H","A","A","K","K","K","K","K","K","J","J","J","J"],["A","A","A","A","A","A","K","C","C","C","J","J","J"],["A","E","E","E","K","K","K","K","C","C","C","C","C"],["F","F","E","K","K","M","M","M","M","M","C","C","C"],["F","E","E","E","E","F","F","C","M","C","C","C","C"],["F","E","F","F","F","F","C","C","C","C","L","L","C"],["F","F","F","F","F","F","C","G","G","C","L","C","C"]],
  hasUniqueSolution: true,
}

export default level
