// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "242",
  regions: [["E","E","E","E","E","E","E"],["F","E","E","E","E","E","E"],["F","B","B","E","E","C","C"],["F","B","G","E","E","D","C"],["F","G","G","E","D","D","D"],["F","G","E","E","A","A","D"],["F","G","E","E","A","A","D"]],
  hasUniqueSolution: true,
}

export default level
