// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "243",
  regions: [["D","D","D","D","A","A","A","A"],["D","D","D","A","A","A","G","A"],["D","D","D","D","G","G","G","G"],["D","C","C","G","G","G","G","G"],["H","H","C","C","G","G","E","E"],["C","C","C","G","G","E","E","E"],["C","C","G","G","B","B","B","F"],["C","C","C","C","C","B","B","F"]],
  hasUniqueSolution: true,
}

export default level
