// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "244",
  regions: [["C","C","C","C","C","C","C","A","A","J","J"],["C","C","F","F","F","K","C","C","A","J","J"],["D","C","C","C","F","K","C","C","A","J","J"],["D","D","C","F","F","C","C","J","J","J","J"],["F","D","C","F","F","C","C","H","E","J","J"],["F","D","D","F","C","C","H","H","E","E","J"],["F","D","F","F","C","C","H","E","E","J","J"],["F","F","F","F","F","F","F","J","J","J","J"],["F","I","F","J","J","J","J","J","J","J","J"],["G","I","F","F","F","J","B","J","B","B","J"],["G","G","F","J","J","J","B","B","B","J","J"]],
  hasUniqueSolution: true,
}

export default level
