// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "245",
  regions: [["K","K","K","D","D","D","D","D","D","D","E","E","G"],["K","J","K","K","K","D","C","C","C","E","E","E","G"],["K","J","K","D","D","D","C","E","E","E","E","G","G"],["J","J","K","D","C","C","C","E","I","I","E","E","G"],["J","K","K","D","C","E","E","E","E","E","E","G","G"],["J","D","D","D","C","C","E","E","L","G","G","G","G"],["J","J","D","H","H","H","H","E","L","G","G","G","G"],["M","J","D","D","H","H","E","E","E","G","G","G","G"],["M","J","J","D","H","H","H","H","E","E","E","E","G"],["M","J","D","D","D","F","F","H","H","E","H","E","G"],["J","J","J","A","A","F","H","H","H","H","H","E","E"],["J","J","J","J","A","H","H","J","J","J","E","E","E"],["J","B","B","J","J","J","J","J","J","E","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
