// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "246",
  regions: [["H","H","H","H","H","H","H","B","B"],["I","I","I","I","I","H","B","B","D"],["I","I","H","H","H","H","H","B","D"],["F","I","I","A","D","D","D","D","D"],["F","I","A","A","A","G","G","G","C"],["E","E","E","C","A","G","C","G","C"],["E","E","C","C","C","G","C","G","C"],["E","E","C","C","C","C","C","C","C"],["E","C","C","C","C","C","C","C","C"]],
  hasUniqueSolution: true,
}

export default level
