// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "247",
  regions: [["E","E","I","I","I","I","I","I","I","I"],["E","E","E","E","E","E","E","E","I","I"],["E","J","J","J","E","E","C","D","D","I"],["E","B","J","E","E","E","H","D","D","I"],["E","B","E","E","B","E","H","D","I","I"],["E","B","B","B","B","E","B","D","I","D"],["B","B","B","G","B","E","B","D","D","D"],["B","G","G","G","B","B","B","D","D","C"],["B","B","B","B","A","A","C","C","C","C"],["B","B","F","F","F","A","A","C","C","C"]],
  hasUniqueSolution: true,
}

export default level
