// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "248",
  regions: [["B","A","A","F","F","F","F","F","F","F","F"],["B","B","B","F","G","G","G","F","G","F","F"],["K","B","F","F","B","G","G","G","G","G","F"],["K","B","B","B","B","G","G","J","H","G","G"],["K","B","K","B","J","J","J","J","H","H","C"],["K","K","K","B","B","B","J","J","H","H","C"],["K","D","E","E","B","J","J","J","H","H","C"],["D","D","D","D","B","B","J","J","J","H","J"],["D","D","D","D","D","B","B","J","J","J","J"],["D","D","D","D","B","B","J","J","J","J","J"],["I","I","B","B","B","J","J","J","J","J","J"]],
  hasUniqueSolution: true,
}

export default level
