// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "249",
  regions: [["I","I","A","A","B","B","B","B","B","A","A","A","A","C"],["I","A","A","A","B","B","A","A","B","A","C","A","A","C"],["I","A","I","A","B","A","A","A","A","A","C","C","C","C"],["I","I","I","A","B","A","C","C","C","C","C","H","H","L"],["G","I","I","A","A","A","A","A","A","A","C","C","C","L"],["G","G","I","I","I","A","A","A","K","K","C","C","L","L"],["G","I","I","I","I","A","A","K","K","C","C","C","L","L"],["G","G","I","A","A","A","A","K","K","K","C","D","L","J"],["G","I","I","K","K","K","K","K","C","C","C","D","L","J"],["G","G","G","G","G","K","K","K","K","C","N","N","J","J"],["F","G","K","K","K","K","K","J","K","C","N","N","J","J"],["F","F","K","F","F","F","F","J","J","J","J","J","J","J"],["F","F","K","F","M","J","J","J","E","E","E","E","J","J"],["F","F","F","F","M","J","J","J","J","J","J","J","J","J"]],
  hasUniqueSolution: true,
}

export default level
