// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '25',
  regions: [
    ['J', 'J', 'J', 'J', 'K', 'K', 'K', 'K', 'G', 'G', 'G', 'E', 'G'],
    ['J', 'B', 'J', 'J', 'J', 'J', 'K', 'K', 'K', 'G', 'G', 'E', 'G'],
    ['J', 'B', 'B', 'B', 'B', 'J', 'J', 'K', 'K', 'G', 'G', 'G', 'G'],
    ['D', 'D', 'D', 'D', 'B', 'J', 'K', 'K', 'K', 'K', 'K', 'K', 'G'],
    ['D', 'K', 'K', 'D', 'D', 'K', 'K', 'G', 'G', 'G', 'G', 'G', 'G'],
    ['D', 'D', 'K', 'K', 'K', 'K', 'I', 'G', 'I', 'G', 'G', 'G', 'G'],
    ['D', 'D', 'D', 'K', 'K', 'K', 'I', 'I', 'I', 'G', 'I', 'G', 'G'],
    ['H', 'H', 'H', 'H', 'L', 'K', 'K', 'I', 'I', 'I', 'I', 'I', 'G'],
    ['H', 'L', 'L', 'L', 'L', 'K', 'K', 'I', 'I', 'I', 'I', 'G', 'G'],
    ['L', 'L', 'M', 'M', 'M', 'M', 'K', 'F', 'F', 'F', 'I', 'I', 'G'],
    ['L', 'A', 'M', 'F', 'F', 'F', 'K', 'K', 'F', 'G', 'G', 'G', 'G'],
    ['L', 'A', 'A', 'A', 'A', 'F', 'F', 'F', 'F', 'G', 'C', 'C', 'G'],
    ['L', 'L', 'L', 'A', 'F', 'F', 'F', 'F', 'G', 'G', 'G', 'G', 'G']
  ],
  hasUniqueSolution: true
}

export default level
