// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "25",
  regions: [["C","C","C","C","D","D","D","D","F","F","F","A","F"],["C","B","C","C","C","C","D","D","D","F","F","A","F"],["C","B","B","B","B","C","C","D","D","F","F","F","F"],["E","E","E","E","B","C","D","D","D","D","D","D","F"],["E","D","D","E","E","D","D","F","F","F","F","F","F"],["E","E","D","D","D","D","G","F","G","F","F","F","F"],["E","E","E","D","D","D","G","G","G","F","G","F","F"],["H","H","H","H","I","D","D","G","G","G","G","G","F"],["H","I","I","I","I","D","D","G","G","G","G","F","F"],["I","I","J","J","J","J","D","K","K","K","G","G","F"],["I","M","J","K","K","K","D","D","K","F","F","F","F"],["I","M","M","M","M","K","K","K","K","F","L","L","F"],["I","I","I","M","K","K","K","K","F","F","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
