// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "250",
  regions: [["F","F","F","C","C","C"],["F","B","F","A","A","C"],["F","B","B","B","A","E"],["F","F","F","E","E","E"],["F","E","E","E","D","D"],["F","F","F","E","D","D"]],
  hasUniqueSolution: true,
}

export default level
