// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "251",
  regions: [["E","E","E","E","E"],["E","E","A","B","E"],["C","A","A","B","B"],["C","A","B","B","B"],["C","D","D","B","B"]],
  hasUniqueSolution: true,
}

export default level
