// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "252",
  regions: [["D","D","D","D","D","D","B","B","B","E","E"],["D","D","C","D","D","B","B","B","E","E","E"],["D","D","C","C","D","D","B","E","E","E","E"],["D","D","G","C","C","E","K","K","E","E","E"],["G","G","G","C","E","E","E","E","E","E","E"],["G","G","G","I","I","I","E","I","I","I","E"],["G","I","I","I","I","I","I","I","I","E","E"],["G","I","F","J","J","I","I","I","I","E","E"],["G","G","F","J","H","I","H","H","C","E","E"],["A","G","G","J","H","H","H","E","E","E","E"],["A","A","A","J","E","E","E","E","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
