// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "253",
  regions: [["C","C","C","C","D","D","D","D","D","D","F","M","M","M"],["C","D","C","C","D","D","D","D","D","D","F","M","N","M"],["C","D","D","D","D","D","D","C","C","D","M","M","N","M"],["C","C","I","I","C","D","C","C","M","D","D","M","N","N"],["C","C","C","C","C","C","C","J","M","D","M","M","N","N"],["G","C","E","E","C","J","J","J","M","M","M","M","N","N"],["G","C","E","C","C","J","H","J","H","N","N","N","N","N"],["C","C","E","H","H","H","H","J","H","H","H","H","H","N"],["H","C","C","H","A","H","H","J","H","B","B","H","H","H"],["H","C","C","H","A","A","H","H","H","H","B","B","B","K"],["H","H","H","H","H","A","H","A","H","H","H","H","B","K"],["H","H","A","A","A","A","H","A","H","H","H","B","B","B"],["H","H","H","A","A","A","H","A","A","H","H","B","L","L"],["H","H","H","A","A","A","A","A","A","H","H","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
