// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "254",
  regions: [["C","C","E","E","B"],["C","C","C","A","B"],["C","C","A","A","B"],["D","D","C","B","B"],["D","B","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
