// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "255",
  regions: [["G","G","A","A","A","F","F"],["G","A","A","E","A","E","E"],["G","E","E","E","E","E","E"],["E","E","D","E","B","B","E"],["E","D","D","D","D","B","E"],["E","E","C","D","D","B","E"],["E","E","C","B","B","B","E"]],
  hasUniqueSolution: true,
}

export default level
