// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "256",
  regions: [["C","C","C","C","C","C","C","C","C"],["A","A","C","A","A","C","A","I","I"],["A","A","C","C","A","A","A","D","D"],["A","A","A","A","A","A","D","D","D"],["A","A","A","B","B","B","D","B","B"],["E","G","E","B","E","B","D","D","B"],["E","G","E","E","E","B","B","D","B"],["E","E","E","H","H","B","B","B","B"],["E","E","E","E","E","F","F","B","B"]],
  hasUniqueSolution: true,
}

export default level
