// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "257",
  regions: [["E","E","F","F","B","B","B","B","B"],["E","F","F","B","B","F","F","B","B"],["E","E","F","B","B","B","F","B","B"],["A","E","F","F","F","F","F","B","B"],["A","E","F","F","F","D","D","C","B"],["A","E","F","G","F","F","D","C","I"],["A","G","G","G","F","I","I","I","I"],["A","G","A","F","F","I","I","I","H"],["A","A","A","A","A","H","H","H","H"]],
  hasUniqueSolution: true,
}

export default level
