// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "258",
  regions: [["E","E","E","E","B","G","G","G","A","A"],["E","J","E","B","B","B","B","G","G","A"],["E","J","J","B","B","H","G","G","G","A"],["E","E","E","B","H","H","H","H","H","A"],["E","E","E","B","H","A","A","H","H","A"],["E","E","E","E","H","H","A","A","A","A"],["E","E","E","E","H","A","A","A","A","D"],["E","C","F","I","I","A","A","D","D","D"],["E","C","F","I","D","H","D","D","D","D"],["C","C","I","I","I","I","I","D","D","D"]],
  hasUniqueSolution: true,
}

export default level
