// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "259",
  regions: [["G","G","J","J","J","G","G","G","G","K","K","K","K","K"],["G","J","J","J","J","J","G","K","K","K","C","C","F","K"],["G","G","G","G","G","G","G","G","K","K","K","I","F","F"],["G","G","K","K","K","K","K","K","K","K","K","I","F","F"],["G","G","G","G","K","G","G","G","G","G","K","K","F","N"],["G","G","G","G","G","G","K","K","K","K","K","F","F","N"],["G","G","G","G","K","K","K","K","K","F","F","F","N","N"],["G","G","G","H","H","K","N","N","N","N","N","F","F","N"],["G","G","G","K","K","K","A","A","N","A","N","N","N","N"],["G","G","G","G","G","A","A","A","A","A","N","N","M","M"],["B","G","G","E","E","E","E","A","A","A","A","N","N","M"],["B","G","G","E","A","A","A","A","A","A","A","L","N","M"],["B","B","B","E","E","A","A","A","L","A","L","L","N","M"],["B","E","E","E","E","E","D","D","L","L","L","M","M","M"]],
  hasUniqueSolution: true,
}

export default level
