// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '26',
  regions: [
    ['F', 'F', 'H', 'H', 'H', 'H', 'H', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O'],
    ['F', 'F', 'H', 'F', 'H', 'H', 'H', 'H', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O'],
    ['F', 'F', 'F', 'F', 'F', 'H', 'H', 'C', 'C', 'C', 'C', 'O', 'O', 'M', 'M', 'O', 'O', 'I'],
    ['D', 'F', 'F', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'O', 'O', 'O', 'M', 'O', 'O', 'I'],
    ['D', 'D', 'F', 'H', 'F', 'F', 'H', 'H', 'H', 'C', 'E', 'E', 'E', 'O', 'I', 'I', 'I', 'I'],
    ['F', 'F', 'F', 'F', 'F', 'F', 'H', 'H', 'H', 'C', 'C', 'B', 'B', 'O', 'I', 'I', 'O', 'I'],
    ['A', 'F', 'A', 'F', 'F', 'H', 'H', 'F', 'F', 'F', 'B', 'B', 'O', 'O', 'I', 'O', 'O', 'O'],
    ['A', 'A', 'A', 'F', 'H', 'H', 'H', 'H', 'H', 'F', 'F', 'B', 'O', 'O', 'O', 'O', 'J', 'O'],
    ['A', 'A', 'A', 'F', 'F', 'F', 'H', 'F', 'F', 'F', 'B', 'B', 'B', 'B', 'O', 'O', 'J', 'O'],
    ['F', 'A', 'A', 'A', 'F', 'F', 'F', 'F', 'B', 'B', 'B', 'B', 'J', 'B', 'O', 'J', 'J', 'O'],
    ['Q', 'F', 'F', 'A', 'F', 'F', 'F', 'F', 'F', 'B', 'B', 'J', 'J', 'J', 'O', 'O', 'J', 'O'],
    ['G', 'G', 'F', 'F', 'F', 'F', 'F', 'B', 'B', 'B', 'B', 'B', 'J', 'O', 'O', 'J', 'J', 'J'],
    ['G', 'F', 'F', 'G', 'K', 'F', 'B', 'B', 'K', 'K', 'K', 'B', 'J', 'J', 'J', 'J', 'J', 'J'],
    ['G', 'G', 'G', 'G', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'B', 'N', 'N', 'R', 'J', 'R', 'J'],
    ['G', 'Q', 'G', 'G', 'G', 'G', 'G', 'G', 'K', 'K', 'K', 'N', 'N', 'N', 'R', 'J', 'R', 'R'],
    ['G', 'Q', 'Q', 'L', 'G', 'G', 'K', 'K', 'K', 'K', 'P', 'P', 'P', 'N', 'R', 'R', 'R', 'R'],
    ['Q', 'Q', 'Q', 'L', 'G', 'L', 'L', 'L', 'N', 'N', 'N', 'P', 'P', 'N', 'N', 'R', 'R', 'R'],
    ['Q', 'Q', 'L', 'L', 'L', 'L', 'L', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'R', 'R']
  ],
  hasUniqueSolution: true
}

export default level
