// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "26",
  regions: [["I","I","B","B","B","B","B","A","A","A","A","A","A","A","A","A","A","A"],["I","I","B","I","B","B","B","B","A","A","A","A","A","A","A","A","A","A"],["I","I","I","I","I","B","B","F","F","F","F","A","A","C","C","A","A","G"],["D","I","I","B","B","B","B","B","F","F","F","A","A","A","C","A","A","G"],["D","D","I","B","I","I","B","B","B","F","E","E","E","A","G","G","G","G"],["I","I","I","I","I","I","B","B","B","F","F","J","J","A","G","G","A","G"],["K","I","K","I","I","B","B","I","I","I","J","J","A","A","G","A","A","A"],["K","K","K","I","B","B","B","B","B","I","I","J","A","A","A","A","H","A"],["K","K","K","I","I","I","B","I","I","I","J","J","J","J","A","A","H","A"],["I","K","K","K","I","I","I","I","J","J","J","J","H","J","A","H","H","A"],["Q","I","I","K","I","I","I","I","I","J","J","H","H","H","A","A","H","A"],["L","L","I","I","I","I","I","J","J","J","J","J","H","A","A","H","H","H"],["L","I","I","L","M","I","J","J","M","M","M","J","H","H","H","H","H","H"],["L","L","L","L","M","M","M","M","M","M","M","J","N","N","O","H","O","H"],["L","Q","L","L","L","L","L","L","M","M","M","N","N","N","O","H","O","O"],["L","Q","Q","R","L","L","M","M","M","M","P","P","P","N","O","O","O","O"],["Q","Q","Q","R","L","R","R","R","N","N","N","P","P","N","N","O","O","O"],["Q","Q","R","R","R","R","R","N","N","N","N","N","N","N","N","N","O","O"]],
  hasUniqueSolution: true,
}

export default level
