// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "260",
  regions: [["G","G","G","G","G","G","O","O","O","O","O","O","E","E","E"],["G","A","A","A","G","O","O","O","I","I","O","O","J","J","E"],["G","A","A","G","G","O","G","I","I","O","O","O","O","E","E"],["G","G","A","A","G","G","G","G","G","O","O","O","O","E","D"],["G","G","G","A","G","B","B","B","G","G","O","O","E","E","D"],["G","A","G","A","G","B","G","G","G","G","G","O","O","N","N"],["A","A","A","A","B","B","K","K","G","O","O","O","N","N","N"],["A","A","A","C","M","B","G","G","G","G","O","N","N","O","N"],["C","A","C","C","M","B","B","B","B","H","O","O","O","O","N"],["C","A","A","C","M","B","B","H","H","H","J","O","O","N","N"],["C","C","C","C","M","M","B","B","O","O","O","F","O","O","N"],["C","M","M","M","M","B","B","B","O","F","F","F","N","N","N"],["C","C","C","M","B","B","B","O","O","F","O","N","N","O","O"],["C","M","C","M","B","L","L","L","O","O","O","N","N","O","O"],["C","M","M","M","M","L","L","L","O","O","O","O","O","O","O"]],
  hasUniqueSolution: true,
}

export default level
