// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "261",
  regions: [["A","A","A","A","I","I","I","I","I","I","I","I","I","I","I"],["A","L","A","A","A","G","G","G","G","I","I","G","G","G","G"],["A","L","A","A","A","G","F","F","G","G","G","G","H","H","G"],["A","L","E","A","A","A","F","A","H","H","H","H","H","H","G"],["L","L","E","E","A","A","A","A","H","H","G","G","G","G","G"],["L","L","A","E","A","H","H","H","H","H","G","G","K","G","K"],["L","L","A","E","A","A","H","H","H","H","H","G","K","K","K"],["L","A","A","A","A","A","H","A","A","H","A","G","G","K","C"],["L","L","L","A","A","A","A","A","H","H","A","G","G","K","C"],["L","A","A","A","D","D","D","A","A","A","A","M","G","G","C"],["L","L","L","A","A","A","D","A","B","M","M","M","M","G","C"],["L","N","N","N","A","A","D","C","B","M","M","C","M","C","C"],["L","L","L","A","A","A","D","C","C","C","C","C","C","C","J"],["L","A","A","A","D","D","D","C","O","O","O","O","C","J","J"],["L","L","L","L","L","L","C","C","O","O","O","C","C","C","J"]],
  hasUniqueSolution: true,
}

export default level
