// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "262",
  regions: [["J","J","J","B","L","L","A","A","A","A","E","F","F"],["J","J","B","B","L","L","A","A","A","A","E","E","F"],["J","J","B","L","L","L","A","A","G","G","E","E","F"],["J","J","B","B","L","L","A","A","A","G","G","E","F"],["J","B","B","B","L","L","L","A","G","G","G","E","E"],["J","B","B","B","L","L","L","A","G","G","G","E","E"],["J","B","B","I","D","D","A","A","K","G","G","E","K"],["I","I","I","I","I","D","A","K","K","K","K","K","K"],["I","D","D","D","D","D","A","K","K","H","K","K","K"],["I","D","D","K","D","D","K","K","H","H","M","M","M"],["I","D","D","K","K","K","K","K","H","H","M","M","M"],["D","D","D","K","K","K","K","K","C","C","M","M","M"],["D","D","D","K","K","K","K","C","C","C","M","M","M"]],
  hasUniqueSolution: false,
}

export default level
