// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "263",
  regions: [["A","A","H","H","H","H","D","B","B"],["A","H","H","H","H","D","D","B","B"],["A","H","H","A","A","G","G","B","B"],["A","A","A","A","A","G","G","G","B"],["A","A","A","A","A","G","G","G","B"],["E","E","A","A","F","G","G","G","B"],["I","E","E","E","F","F","F","F","C"],["I","I","E","E","F","F","C","C","C"],["I","I","I","E","E","F","C","C","C"]],
  hasUniqueSolution: false,
}

export default level
