// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "264",
  regions: [["B","B","B","B","B","F","F","F","F","G","G"],["B","B","B","B","B","F","F","F","F","G","G"],["K","H","H","H","H","F","F","F","C","C","G"],["K","K","H","H","H","H","F","F","C","G","G"],["K","K","K","K","K","H","C","C","C","G","G"],["A","K","K","K","K","K","C","C","C","D","D"],["A","A","K","K","K","K","I","I","I","I","D"],["A","A","A","K","K","K","I","I","I","I","I"],["A","A","A","J","J","I","I","I","I","I","I"],["A","A","A","J","J","I","I","E","E","I","I"],["A","A","A","A","J","I","I","E","E","I","I"]],
  hasUniqueSolution: false,
}

export default level
