// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "265",
  regions: [["G","G","C","C","C","C","C","C","C","E","E"],["C","C","C","C","I","I","I","C","E","E","E"],["I","I","I","C","I","J","I","E","E","B","E"],["I","K","I","I","I","J","I","B","B","B","B"],["I","K","K","K","I","J","I","B","A","A","B"],["I","I","I","K","I","K","B","B","A","A","A"],["H","K","I","K","K","K","A","A","A","A","A"],["H","K","I","I","K","A","A","A","A","A","A"],["K","K","K","K","K","A","D","A","A","A","A"],["K","F","K","K","K","D","D","A","A","A","A"],["K","F","F","K","K","K","D","D","D","D","D"]],
  hasUniqueSolution: true,
}

export default level
