// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "266",
  regions: [["J","J","G","G","E","D","D","D","E","E"],["J","J","G","G","E","E","D","D","D","E"],["J","J","J","G","G","E","I","D","E","E"],["J","J","J","G","E","E","I","E","E","E"],["J","G","G","G","E","E","E","E","A","E"],["J","G","G","G","G","E","B","A","A","E"],["J","J","J","B","G","B","B","A","A","A"],["F","F","B","B","B","B","A","C","C","A"],["F","F","H","H","B","A","A","A","A","A"],["F","F","F","H","B","B","B","A","A","A"]],
  hasUniqueSolution: true,
}

export default level
