// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "267",
  regions: [["C","C","C","C","C","C","C","C","C","D","E","E"],["C","C","C","C","C","G","C","G","D","D","E","E"],["C","C","C","C","C","G","G","G","G","D","I","I"],["C","C","C","G","C","C","G","G","G","D","I","I"],["C","C","C","G","G","G","G","F","G","D","I","I"],["C","L","C","G","G","G","G","F","D","D","D","I"],["L","L","C","C","D","A","A","D","D","I","I","I"],["L","C","C","C","D","D","A","A","D","D","D","D"],["L","L","C","C","D","D","D","D","D","D","D","B"],["L","L","L","J","J","J","J","J","D","D","D","B"],["H","H","J","J","K","J","K","K","K","D","B","B"],["J","J","J","J","K","K","K","D","D","D","D","D"]],
  hasUniqueSolution: true,
}

export default level
