// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "268",
  regions: [["C","C","C","C","A","A","A","A","A","A","A","D"],["C","C","H","A","A","A","A","A","K","K","A","D"],["H","H","H","A","A","A","K","K","K","K","D","D"],["E","H","E","G","G","A","K","K","D","D","D","D"],["E","E","E","E","E","I","I","K","K","D","D","L"],["J","E","K","E","I","I","K","K","K","K","L","L"],["J","E","K","K","K","K","K","F","F","F","L","L"],["J","J","K","K","K","K","K","F","L","F","F","L"],["F","J","K","B","B","F","F","F","L","L","L","L"],["F","J","J","J","B","F","B","F","F","L","L","L"],["F","J","F","F","B","B","B","B","F","F","F","L"],["F","F","F","F","F","F","F","F","F","F","L","L"]],
  hasUniqueSolution: true,
}

export default level
