// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "269",
  regions: [["G","G","G","J","J","B","B","J","J","J","J","J","A","A"],["K","K","G","G","J","B","J","J","A","A","J","J","A","A"],["K","G","G","J","J","J","J","J","A","A","A","J","J","A"],["G","G","J","J","M","J","J","J","A","A","A","J","A","A"],["G","G","G","J","M","J","J","J","A","E","A","A","A","A"],["G","G","I","J","M","M","M","J","A","E","C","A","A","A"],["G","G","I","M","M","M","J","J","A","E","C","A","A","A"],["G","G","G","G","M","M","M","J","J","E","C","C","A","A"],["G","G","G","G","M","N","M","J","J","E","C","C","A","A"],["G","G","M","G","M","N","N","N","E","E","C","A","A","F"],["G","M","M","G","M","M","N","N","N","N","C","C","C","F"],["G","G","M","M","M","M","L","H","N","N","N","F","C","F"],["G","G","M","M","L","L","L","H","L","N","N","F","F","F"],["G","M","M","M","L","L","L","L","L","N","D","D","F","F"]],
  hasUniqueSolution: true,
}

export default level
