// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '27',
  regions: [
    ['A', 'A', 'D', 'C', 'B'],
    ['A', 'A', 'D', 'C', 'B'],
    ['A', 'A', 'D', 'C', 'B'],
    ['A', 'B', 'B', 'B', 'B'],
    ['B', 'B', 'B', 'E', 'E']
  ],
  hasUniqueSolution: true
}

export default level
