// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "27",
  regions: [["B","B","A","C","D"],["B","B","A","C","D"],["B","B","A","C","D"],["B","D","D","D","D"],["D","D","D","E","E"]],
  hasUniqueSolution: true,
}

export default level
