// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "270",
  regions: [["B","A","A","A","A"],["B","B","D","A","A"],["B","D","D","C","A"],["D","D","C","C","C"],["D","C","C","E","E"]],
  hasUniqueSolution: true,
}

export default level
