// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "271",
  regions: [["A","A","A","E","E","E","E","E","E"],["A","A","A","A","E","E","E","E","E"],["A","A","I","F","F","G","G","G","E"],["I","I","I","F","F","G","G","G","H"],["I","F","F","F","F","C","C","G","H"],["I","D","F","F","F","C","C","H","H"],["I","D","D","F","F","B","C","H","H"],["I","I","I","B","B","B","C","C","C"],["I","I","I","I","I","I","C","C","C"]],
  hasUniqueSolution: false,
}

export default level
