// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "272",
  regions: [["A","B","B","C","D"],["A","B","C","C","D"],["A","A","C","D","D"],["A","A","A","E","D"],["A","A","A","E","E"]],
  hasUniqueSolution: true,
}

export default level
