// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "273",
  regions: [["G","G","G","A","D","D","D","D"],["G","G","G","A","D","C","C","D"],["G","G","D","D","D","D","G","D"],["G","G","G","G","G","G","G","D"],["G","G","F","G","E","E","D","D"],["G","F","F","F","B","D","D","D"],["H","H","H","F","B","F","D","D"],["H","F","F","F","F","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
