// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "274",
  regions: [["I","I","B","B","B","B","B","B","A","A"],["I","H","H","H","H","H","H","B","B","A"],["I","E","E","G","G","G","H","B","J","A"],["I","E","E","G","G","G","H","B","J","A"],["I","E","G","G","G","G","H","C","C","C"],["I","E","E","G","G","H","H","H","H","C"],["I","I","E","G","G","G","G","H","C","C"],["D","D","E","E","F","F","G","C","C","F"],["D","E","E","F","F","F","F","C","F","F"],["E","E","E","E","E","E","F","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
