// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "275",
  regions: [["I","I","I","J","J","J","H","H","C","C"],["I","A","A","J","B","J","J","H","H","C"],["I","A","A","B","B","B","B","B","C","C"],["I","A","A","B","B","A","A","B","B","G"],["A","A","A","A","A","A","G","B","G","G"],["A","E","E","E","A","A","G","G","G","D"],["A","E","E","E","A","A","G","F","G","D"],["A","E","E","E","E","F","F","F","G","D"],["A","E","E","E","E","E","F","D","G","D"],["A","E","D","D","D","D","D","D","D","D"]],
  hasUniqueSolution: true,
}

export default level
