// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "276",
  regions: [["C","C","H","H","H","H","F","F","F"],["C","H","H","B","B","B","B","F","F"],["C","B","B","B","B","A","A","F","F"],["C","C","B","B","B","B","F","F","E"],["G","B","B","B","B","F","F","F","E"],["G","B","B","B","F","F","F","F","F"],["I","I","B","B","F","F","F","F","F"],["I","B","B","F","F","F","D","F","F"],["I","I","I","F","F","D","D","D","F"]],
  hasUniqueSolution: true,
}

export default level
