// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "277",
  regions: [["I","I","I","B","B","P","P","P","P","P","P","P","P","P","P","P","P"],["I","G","I","B","B","P","D","P","P","D","P","P","D","P","P","P","P"],["I","G","I","I","B","P","D","D","D","D","D","P","D","D","P","P","P"],["G","G","I","B","B","P","B","B","D","D","D","D","D","D","P","L","P"],["G","I","I","B","P","P","B","B","D","D","D","D","D","D","P","L","L"],["G","I","B","B","B","B","B","D","D","M","D","P","P","P","P","L","L"],["G","I","I","I","I","E","D","D","M","M","D","P","P","P","P","P","L"],["G","G","E","I","E","E","E","M","M","M","D","D","K","P","P","L","L"],["E","G","E","E","E","H","E","M","H","H","D","L","K","P","P","P","L"],["E","E","E","E","E","H","H","H","H","L","L","L","L","L","L","L","L"],["E","C","H","H","E","E","H","H","L","L","F","L","Q","Q","L","L","N"],["C","C","H","H","H","E","H","J","L","L","F","F","Q","L","L","F","N"],["C","H","H","H","H","H","H","J","J","L","C","F","F","L","L","F","F"],["C","C","C","H","H","H","J","J","J","C","C","C","F","L","L","L","F"],["C","H","H","H","H","H","J","C","J","J","C","C","F","F","F","F","F"],["C","C","C","C","C","H","J","C","C","C","C","C","O","F","F","O","F"],["A","A","A","C","C","C","C","C","C","C","C","O","O","O","O","O","F"]],
  hasUniqueSolution: true,
}

export default level
