// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "278",
  regions: [["E","E","E","E","E","E","B","B","F","F","F","C","C","J","J"],["E","E","E","E","B","B","B","B","B","B","F","C","C","J","J"],["E","E","B","B","B","E","B","E","E","B","F","F","C","C","C"],["E","B","B","B","E","E","E","E","O","O","F","F","C","I","C"],["E","G","B","E","E","O","O","O","O","F","F","I","I","I","C"],["E","G","E","E","E","O","E","E","O","O","I","I","C","C","C"],["E","E","E","E","E","E","E","O","O","O","O","I","I","C","C"],["E","E","E","O","E","E","E","E","O","O","O","I","C","C","C"],["E","A","E","O","E","E","E","O","O","I","O","I","I","D","C"],["E","A","A","O","O","O","E","O","I","I","I","I","D","D","C"],["E","E","A","O","O","O","O","O","M","I","D","D","D","C","C"],["E","A","A","A","A","L","L","L","M","I","D","K","K","K","C"],["E","H","A","H","A","L","A","A","M","M","D","D","D","K","C"],["H","H","H","H","A","A","A","D","D","D","D","A","D","A","A"],["H","H","H","N","N","A","A","A","A","A","A","A","A","A","A"]],
  hasUniqueSolution: true,
}

export default level
