// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "279",
  regions: [["J","J","J","J","F","F","F","F","F","F","F","F","C","L","L","L","L"],["F","J","F","F","F","F","F","F","F","F","C","C","C","F","L","L","L"],["F","F","F","A","A","F","F","A","F","F","F","F","F","F","L","L","L"],["E","F","A","A","A","A","A","A","F","F","F","F","L","F","L","L","M"],["E","F","F","H","H","H","H","A","F","L","L","L","L","L","L","L","M"],["E","E","F","H","H","A","A","A","A","L","L","D","D","D","M","M","M"],["H","E","E","H","H","H","A","A","L","L","L","D","O","O","M","M","I"],["H","H","E","H","H","H","A","A","A","L","L","D","O","L","M","I","I"],["H","H","H","H","A","H","H","A","A","L","L","L","L","L","M","M","I"],["H","H","H","H","A","A","A","A","A","L","P","P","P","P","P","I","I"],["H","H","H","H","H","H","H","H","A","P","P","P","I","I","I","I","I"],["H","H","H","A","A","A","H","A","A","A","A","P","P","I","K","I","I"],["H","B","H","H","A","A","A","A","A","I","A","P","I","I","K","I","I"],["H","B","H","H","H","I","A","A","I","I","A","A","I","I","K","K","I"],["B","B","B","H","I","I","I","I","I","I","A","I","I","N","N","K","I"],["B","B","B","H","I","I","I","G","Q","I","A","A","I","K","K","K","I"],["G","G","G","G","G","G","G","G","Q","I","I","I","I","I","I","K","K"]],
  hasUniqueSolution: true,
}

export default level
