// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '28',
  regions: [
    ['D', 'I', 'I', 'E', 'E', 'E', 'B', 'B', 'A', 'A'],
    ['D', 'D', 'I', 'E', 'E', 'E', 'E', 'E', 'E', 'A'],
    ['D', 'D', 'H', 'E', 'H', 'H', 'E', 'C', 'C', 'A'],
    ['F', 'D', 'H', 'H', 'H', 'E', 'E', 'C', 'J', 'J'],
    ['F', 'F', 'F', 'F', 'H', 'H', 'E', 'C', 'J', 'J'],
    ['F', 'H', 'H', 'F', 'H', 'E', 'E', 'J', 'J', 'J'],
    ['F', 'H', 'H', 'H', 'H', 'E', 'J', 'J', 'J', 'J'],
    ['F', 'F', 'H', 'G', 'G', 'E', 'E', 'J', 'G', 'J'],
    ['H', 'H', 'H', 'H', 'G', 'G', 'J', 'J', 'G', 'J'],
    ['H', 'H', 'H', 'G', 'G', 'G', 'G', 'G', 'G', 'G']
  ],
  hasUniqueSolution: true
}

export default level
