// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "280",
  regions: [["F","F","B","B","B","I","A","A","A","A"],["F","F","F","B","B","I","A","A","A","A"],["E","E","E","B","B","I","A","A","A","G"],["E","E","B","B","B","B","G","G","G","G"],["E","E","E","E","E","B","G","G","G","G"],["E","D","E","E","E","G","G","G","C","C"],["E","D","D","D","J","G","H","H","C","C"],["E","D","D","J","J","G","H","H","H","H"],["E","E","J","J","J","G","G","G","G","H"],["J","J","J","J","J","J","J","G","G","H"]],
  hasUniqueSolution: false,
}

export default level
