// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "281",
  regions: [["B","B","B","B","B","F"],["A","E","D","B","B","F"],["A","E","D","D","B","F"],["A","E","E","E","A","A"],["A","A","A","A","A","C"],["A","A","A","C","C","C"]],
  hasUniqueSolution: true,
}

export default level
