// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "282",
  regions: [["J","J","K","K","K","K","K","K","K","D","D","B"],["J","J","J","J","K","K","K","K","K","D","B","B"],["J","J","J","J","I","K","K","K","D","D","B","B"],["J","J","J","J","I","I","B","B","D","D","B","B"],["J","J","J","F","I","I","B","B","B","B","B","G"],["J","J","F","F","I","E","E","E","G","G","G","G"],["C","F","F","I","I","E","E","E","E","G","G","G"],["C","C","F","I","E","E","E","L","L","L","G","G"],["C","F","F","I","I","E","E","L","L","L","L","L"],["F","F","F","F","H","H","H","L","L","L","L","L"],["F","F","A","F","F","F","H","H","H","L","L","L"],["F","F","A","F","F","F","H","H","H","L","L","L"]],
  hasUniqueSolution: false,
}

export default level
