// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "283",
  regions: [["H","H","H","H","H","H","G","A","A","A","A","A"],["H","C","C","C","H","G","G","A","A","A","A","A"],["L","C","C","C","H","H","A","A","A","A","A","A"],["L","C","C","C","C","A","A","A","A","A","A","A"],["L","C","C","C","C","B","B","B","J","J","A","A"],["L","L","C","I","I","B","B","B","J","J","J","J"],["C","C","C","I","I","B","B","B","J","J","J","J"],["C","C","I","I","I","B","K","K","K","J","J","J"],["C","C","F","K","K","K","K","E","E","E","E","J"],["F","F","F","K","K","K","K","E","E","D","D","J"],["F","F","K","K","K","E","K","E","E","D","D","D"],["F","E","E","E","E","E","E","E","E","D","D","D"]],
  hasUniqueSolution: false,
}

export default level
