// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "284",
  regions: [["B","B","B","E","E","E","E","E"],["B","B","B","B","B","B","E","E"],["B","H","H","H","B","B","E","E"],["H","H","B","B","B","B","G","G"],["A","H","A","A","A","A","A","G"],["A","A","A","D","A","G","G","G"],["A","C","C","D","A","G","F","G"],["A","A","C","D","D","D","F","F"]],
  hasUniqueSolution: true,
}

export default level
