// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "285",
  regions: [["F","F","F","F","A","F"],["F","E","E","F","A","F"],["B","B","B","F","F","F"],["B","B","C","C","F","F"],["C","B","C","F","F","F"],["C","C","C","C","D","D"]],
  hasUniqueSolution: true,
}

export default level
