// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "286",
  regions: [["E","C","C","C","C","F","F","F","F","A"],["E","C","E","E","C","A","B","B","F","A"],["E","E","E","E","E","A","A","B","B","A"],["E","I","I","E","E","A","A","B","B","A"],["E","E","G","E","A","A","A","A","A","A"],["E","G","G","G","G","G","A","A","D","A"],["E","G","E","E","G","H","A","A","D","A"],["E","E","E","G","G","H","J","J","D","A"],["E","E","E","E","G","H","H","J","D","D"],["E","E","E","E","G","G","G","G","G","D"]],
  hasUniqueSolution: true,
}

export default level
