// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "287",
  regions: [["A","G","G","G","G","G","G","G","I","I"],["A","G","G","I","G","I","E","E","E","I"],["G","G","G","I","I","I","I","I","I","I"],["G","G","G","I","J","J","I","H","I","I"],["B","G","G","J","J","I","I","H","H","I"],["B","B","G","J","J","I","I","I","H","I"],["D","B","G","J","J","I","F","H","H","H"],["D","B","G","G","J","F","F","H","H","H"],["D","D","G","J","J","J","C","C","H","C"],["D","D","D","J","J","C","C","C","C","C"]],
  hasUniqueSolution: true,
}

export default level
