// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "288",
  regions: [["M","M","M","M","M","M","M","H","H","B","B","B","B","C","C"],["M","A","A","M","N","N","M","M","B","B","C","C","C","C","C"],["M","A","A","M","N","N","N","M","M","B","B","C","B","C","C"],["M","M","A","A","A","A","A","M","M","B","B","B","B","B","C"],["M","M","A","L","A","A","M","M","O","B","B","B","C","B","C"],["M","A","A","L","A","A","M","O","O","B","B","B","C","C","C"],["M","L","A","L","A","A","M","O","O","B","B","B","B","C","C"],["L","L","A","L","A","I","M","M","O","B","B","C","C","C","C"],["L","A","A","L","I","I","M","M","O","B","F","F","C","F","C"],["L","A","L","L","O","O","M","M","O","O","F","F","F","F","F"],["L","L","L","O","O","O","O","O","O","O","F","F","F","D","F"],["L","E","E","E","J","J","O","O","O","O","O","G","D","D","F"],["L","E","L","E","E","E","O","O","O","D","G","G","D","D","F"],["L","L","L","K","K","E","O","D","D","D","D","D","D","D","F"],["E","E","E","E","E","E","O","O","D","D","D","D","D","F","F"]],
  hasUniqueSolution: true,
}

export default level
