// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "289",
  regions: [["G","G","G","G","G","G","L","L","M","M","M","M","M","M","M"],["G","G","G","G","J","K","K","I","I","I","I","O","F","M","M"],["G","G","J","J","A","K","I","I","I","O","O","O","F","F","M"],["G","J","J","K","J","K","I","O","O","O","F","O","F","M","M"],["J","J","K","K","K","K","K","O","F","F","F","F","F","M","M"],["J","K","K","E","K","O","O","O","O","O","F","M","M","M","M"],["J","J","J","E","K","E","O","O","O","O","F","F","F","M","M"],["J","J","E","E","K","E","O","O","O","O","F","F","M","M","M"],["H","J","J","E","E","E","O","M","O","O","F","M","M","M","M"],["H","J","E","E","E","E","O","M","M","M","M","M","M","M","M"],["J","J","E","E","C","E","M","M","N","M","B","B","M","M","M"],["C","E","E","C","C","C","C","C","N","M","A","B","M","B","M"],["C","D","C","C","N","N","N","N","N","M","A","B","B","B","B"],["C","D","C","C","N","N","N","C","N","N","A","A","B","B","B"],["C","C","C","C","C","C","C","C","C","B","B","B","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
