// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "29",
  regions: [["D","D","D","D","C","C","B","C","A","A","A","C","C"],["D","D","D","C","C","C","B","C","C","C","C","C","C"],["D","C","C","C","C","C","C","C","D","C","H","C","C"],["D","D","D","D","E","D","C","D","D","H","H","C","C"],["D","D","D","D","E","D","D","D","H","H","H","C","C"],["D","F","D","D","D","D","H","H","H","H","H","C","C"],["F","F","D","G","G","D","H","H","H","H","H","H","H"],["F","D","D","I","D","D","I","I","I","I","I","I","H"],["F","D","D","I","I","I","I","I","H","H","I","H","H"],["F","F","F","F","J","I","I","J","H","H","H","H","H"],["F","F","F","J","J","I","J","J","H","K","K","L","L"],["F","F","F","F","J","I","J","H","H","K","K","L","L"],["F","J","J","J","J","J","J","M","M","K","L","L","L"]],
  hasUniqueSolution: true,
}

export default level
