// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '29',
  regions: [
    ['G', 'G', 'G', 'G', 'D', 'D', 'H', 'D', 'M', 'M', 'M', 'D', 'D'],
    ['G', 'G', 'G', 'D', 'D', 'D', 'H', 'D', 'D', 'D', 'D', 'D', 'D'],
    ['G', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'G', 'D', 'A', 'D', 'D'],
    ['G', 'G', 'G', 'G', 'E', 'G', 'D', 'G', 'G', 'A', 'A', 'D', 'D'],
    ['G', 'G', 'G', 'G', 'E', 'G', 'G', 'G', 'A', 'A', 'A', 'D', 'D'],
    ['G', 'C', 'G', 'G', 'G', 'G', 'A', 'A', 'A', 'A', 'A', 'D', 'D'],
    ['C', 'C', 'G', 'I', 'I', 'G', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
    ['C', 'G', 'G', 'B', 'G', 'G', 'B', 'B', 'B', 'B', 'B', 'B', 'A'],
    ['C', 'G', 'G', 'B', 'B', 'B', 'B', 'B', 'A', 'A', 'B', 'A', 'A'],
    ['C', 'C', 'C', 'C', 'K', 'B', 'B', 'K', 'A', 'A', 'A', 'A', 'A'],
    ['C', 'C', 'C', 'K', 'K', 'B', 'K', 'K', 'A', 'L', 'L', 'F', 'F'],
    ['C', 'C', 'C', 'C', 'K', 'B', 'K', 'A', 'A', 'L', 'L', 'F', 'F'],
    ['C', 'K', 'K', 'K', 'K', 'K', 'K', 'J', 'J', 'L', 'F', 'F', 'F']
  ],
  hasUniqueSolution: true
}

export default level
