// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "290",
  regions: [["B","B","B","D","A","A","A"],["B","B","B","D","A","C","C"],["G","B","B","B","A","A","C"],["G","B","E","B","B","A","A"],["E","E","E","E","B","B","A"],["F","F","E","E","B","B","B"],["E","E","E","E","E","E","B"]],
  hasUniqueSolution: true,
}

export default level
