// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "291",
  regions: [["A","H","H","H","H","H","H","H"],["A","A","H","H","E","H","B","B"],["D","H","H","H","E","H","H","B"],["D","D","D","D","E","E","E","F"],["D","G","G","G","G","G","G","F"],["D","D","G","D","C","G","G","C"],["D","D","G","D","C","G","C","C"],["D","D","D","D","C","C","C","C"]],
  hasUniqueSolution: true,
}

export default level
