// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "292",
  regions: [["D","E","E","E","E","E","E"],["D","D","E","B","B","E","E"],["F","D","E","E","B","E","E"],["F","B","B","B","B","C","C"],["F","F","B","B","B","C","C"],["F","A","A","B","B","G","G"],["F","A","B","B","B","E","G"]],
  hasUniqueSolution: true,
}

export default level
