// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "293",
  regions: [["G","G","G","G","H","H","E","E"],["A","H","H","H","H","H","E","E"],["A","H","H","H","H","C","C","E"],["H","H","F","H","H","F","D","E"],["H","H","F","B","H","F","D","D"],["H","H","F","B","H","F","D","D"],["F","H","F","F","F","F","F","F"],["F","F","F","F","F","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
