// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "294",
  regions: [["B","G","G","G","G","G","D","D","D"],["B","G","G","G","H","D","D","I","I"],["B","B","G","G","H","D","F","I","I"],["B","B","B","G","E","E","F","F","I"],["A","A","B","A","A","E","E","F","F"],["C","A","A","A","A","A","E","F","F"],["C","C","A","A","A","F","E","F","F"],["C","A","A","F","A","F","F","F","F"],["A","A","F","F","F","F","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
