// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "295",
  regions: [["A","A","K","K","K","C","C","C","D","D","G"],["A","A","A","K","K","K","K","C","C","D","G"],["B","A","K","K","K","C","C","C","C","D","G"],["B","B","K","K","K","C","C","J","D","D","G"],["I","B","K","K","K","C","D","J","D","G","G"],["I","E","E","K","K","C","D","D","D","G","G"],["E","E","F","F","F","C","D","C","C","C","G"],["E","E","F","F","F","C","C","C","C","E","E"],["E","E","F","E","C","C","E","E","E","E","E"],["E","E","E","E","E","C","E","E","E","H","H"],["E","E","E","E","E","E","E","E","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
