// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "296",
  regions: [["B","B","I","I","G","G","G","J","J","J"],["B","I","I","G","G","G","G","G","J","G"],["B","B","I","I","I","G","E","G","G","G"],["A","B","G","G","G","G","E","G","E","E"],["A","B","D","G","E","E","E","E","E","E"],["F","F","D","G","E","E","E","E","E","E"],["F","D","D","D","D","D","E","E","E","E"],["F","C","C","C","D","H","E","E","E","E"],["F","F","C","C","H","H","H","H","E","E"],["F","F","F","C","H","H","H","H","E","E"]],
  hasUniqueSolution: true,
}

export default level
