// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "297",
  regions: [["J","J","J","J","J","J","G","G","G","G","G"],["J","C","J","J","J","H","G","G","G","I","I"],["J","C","C","J","K","H","H","H","G","G","I"],["J","C","J","K","K","H","H","H","G","A","A"],["J","J","J","J","K","H","G","H","G","G","J"],["J","J","H","H","K","H","G","G","G","G","A"],["J","J","J","H","H","H","H","H","H","H","H"],["F","J","J","F","E","E","E","E","B","B","H"],["F","F","F","F","E","H","H","E","E","E","H"],["D","D","F","F","H","H","H","H","H","E","H"],["D","F","F","F","F","F","H","H","H","H","H"]],
  hasUniqueSolution: true,
}

export default level
