// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "298",
  regions: [["G","G","G","B","L","L","L","J","J","I","I","I"],["G","H","G","B","B","B","L","L","I","I","I","I"],["H","H","G","G","B","I","I","I","I","I","I","I"],["H","G","G","C","C","C","I","F","F","I","F","I"],["H","H","G","G","G","C","C","F","F","F","F","I"],["H","H","G","F","F","F","F","F","G","F","F","F"],["H","G","G","G","G","F","G","G","G","F","F","F"],["G","G","K","K","G","G","G","G","G","G","G","F"],["G","D","D","D","D","G","D","G","F","F","F","F"],["G","D","A","A","D","D","D","E","F","F","E","F"],["G","G","A","E","E","E","E","E","F","E","E","F"],["G","G","G","G","G","E","E","E","E","E","F","F"]],
  hasUniqueSolution: true,
}

export default level
