// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "299",
  regions: [["C","C","B","B","B","B","B","B","B","B","B","B","N","N"],["C","G","B","B","B","B","N","N","B","B","B","N","N","N"],["C","G","B","B","B","B","B","N","N","N","N","N","E","K"],["C","F","A","A","B","B","B","H","H","H","H","E","E","K"],["C","F","F","A","B","B","I","I","I","H","H","H","E","K"],["F","F","F","F","B","B","I","H","H","H","E","E","E","K"],["H","F","F","F","F","F","M","M","H","H","E","E","K","K"],["H","F","F","H","F","H","H","H","H","H","E","E","E","K"],["H","F","H","H","H","H","H","L","L","H","H","E","H","K"],["H","H","H","L","L","L","H","L","L","L","H","H","H","K"],["H","L","L","L","L","L","L","L","L","L","H","H","K","K"],["H","H","L","J","J","L","L","L","L","L","L","K","K","K"],["H","H","L","D","D","D","D","D","D","L","K","K","L","K"],["H","H","H","H","D","D","L","L","L","L","L","L","L","L"]],
  hasUniqueSolution: true,
}

export default level
