// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '3',
  regions: [
    ['D', 'D', 'D', 'D', 'A', 'A'],
    ['D', 'E', 'A', 'D', 'D', 'A'],
    ['E', 'E', 'A', 'A', 'A', 'A'],
    ['B', 'B', 'B', 'B', 'A', 'A'],
    ['B', 'C', 'B', 'A', 'A', 'A'],
    ['B', 'C', 'A', 'A', 'F', 'F']
  ],
  hasUniqueSolution: true
}

export default level
