// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '30',
  regions: [
    ['C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'A', 'A', 'A', 'D', 'D', 'D', 'D', 'G'],
    ['C', 'B', 'B', 'C', 'H', 'H', 'C', 'A', 'A', 'A', 'A', 'D', 'D', 'D', 'D', 'D', 'G'],
    ['C', 'H', 'C', 'C', 'H', 'H', 'A', 'A', 'A', 'A', 'D', 'D', 'D', 'D', 'D', 'D', 'G'],
    ['H', 'H', 'C', 'H', 'H', 'I', 'I', 'E', 'D', 'D', 'D', 'F', 'D', 'G', 'D', 'D', 'G'],
    ['H', 'H', 'C', 'C', 'H', 'H', 'I', 'E', 'G', 'G', 'F', 'F', 'D', 'G', 'G', 'D', 'G'],
    ['H', 'H', 'C', 'H', 'H', 'H', 'I', 'I', 'G', 'G', 'F', 'D', 'D', 'G', 'G', 'G', 'G'],
    ['H', 'H', 'H', 'H', 'I', 'I', 'I', 'I', 'I', 'G', 'G', 'D', 'G', 'G', 'G', 'G', 'G'],
    ['H', 'I', 'H', 'H', 'H', 'I', 'I', 'I', 'I', 'G', 'G', 'D', 'G', 'G', 'G', 'G', 'G'],
    ['H', 'I', 'I', 'H', 'I', 'I', 'I', 'K', 'I', 'I', 'G', 'G', 'G', 'G', 'G', 'G', 'G'],
    ['H', 'I', 'I', 'I', 'I', 'K', 'K', 'K', 'K', 'I', 'I', 'I', 'I', 'I', 'I', 'J', 'G'],
    ['H', 'H', 'H', 'I', 'I', 'I', 'I', 'K', 'K', 'I', 'I', 'I', 'J', 'J', 'J', 'J', 'G'],
    ['H', 'L', 'L', 'I', 'I', 'I', 'I', 'K', 'K', 'J', 'J', 'J', 'J', 'J', 'J', 'G', 'G'],
    ['H', 'M', 'M', 'M', 'I', 'I', 'I', 'J', 'J', 'J', 'J', 'N', 'N', 'J', 'G', 'G', 'G'],
    ['H', 'M', 'M', 'Q', 'Q', 'P', 'P', 'O', 'J', 'P', 'P', 'P', 'N', 'J', 'G', 'G', 'J'],
    ['H', 'M', 'Q', 'Q', 'Q', 'P', 'O', 'O', 'J', 'P', 'P', 'N', 'N', 'J', 'G', 'J', 'J'],
    ['M', 'M', 'Q', 'P', 'P', 'P', 'P', 'O', 'J', 'J', 'P', 'N', 'N', 'J', 'J', 'J', 'P'],
    ['M', 'M', 'Q', 'Q', 'Q', 'Q', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P']
  ],
  hasUniqueSolution: true
}

export default level
