// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '30',
  regions: [
    ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'G', 'G', 'G', 'O', 'O', 'O', 'O', 'Q'],
    ['A', 'M', 'M', 'A', 'L', 'L', 'A', 'G', 'G', 'G', 'G', 'O', 'O', 'O', 'O', 'O', 'Q'],
    ['A', 'L', 'A', 'A', 'L', 'L', 'G', 'G', 'G', 'G', 'O', 'O', 'O', 'O', 'O', 'O', 'Q'],
    ['L', 'L', 'A', 'L', 'L', 'J', 'J', 'P', 'O', 'O', 'O', 'K', 'O', 'Q', 'O', 'O', 'Q'],
    ['L', 'L', 'A', 'A', 'L', 'L', 'J', 'P', 'Q', 'Q', 'K', 'K', 'O', 'Q', 'Q', 'O', 'Q'],
    ['L', 'L', 'A', 'L', 'L', 'L', 'J', 'J', 'Q', 'Q', 'K', 'O', 'O', 'Q', 'Q', 'Q', 'Q'],
    ['L', 'L', 'L', 'L', 'J', 'J', 'J', 'J', 'J', 'Q', 'Q', 'O', 'Q', 'Q', 'Q', 'Q', 'Q'],
    ['L', 'J', 'L', 'L', 'L', 'J', 'J', 'J', 'J', 'Q', 'Q', 'O', 'Q', 'Q', 'Q', 'Q', 'Q'],
    ['L', 'J', 'J', 'L', 'J', 'J', 'J', 'N', 'J', 'J', 'Q', 'Q', 'Q', 'Q', 'Q', 'Q', 'Q'],
    ['L', 'J', 'J', 'J', 'J', 'N', 'N', 'N', 'N', 'J', 'J', 'J', 'J', 'J', 'J', 'I', 'Q'],
    ['L', 'L', 'L', 'J', 'J', 'J', 'J', 'N', 'N', 'J', 'J', 'J', 'I', 'I', 'I', 'I', 'Q'],
    ['L', 'E', 'E', 'J', 'J', 'J', 'J', 'N', 'N', 'I', 'I', 'I', 'I', 'I', 'I', 'Q', 'Q'],
    ['L', 'C', 'C', 'C', 'J', 'J', 'J', 'I', 'I', 'I', 'I', 'H', 'H', 'I', 'Q', 'Q', 'Q'],
    ['L', 'C', 'C', 'D', 'D', 'B', 'B', 'F', 'I', 'B', 'B', 'B', 'H', 'I', 'Q', 'Q', 'I'],
    ['L', 'C', 'D', 'D', 'D', 'B', 'F', 'F', 'I', 'B', 'B', 'H', 'H', 'I', 'Q', 'I', 'I'],
    ['C', 'C', 'D', 'B', 'B', 'B', 'B', 'F', 'I', 'I', 'B', 'H', 'H', 'I', 'I', 'I', 'B'],
    ['C', 'C', 'D', 'D', 'D', 'D', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B']
  ],
  hasUniqueSolution: true
}

export default level
