// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "300",
  regions: [["E","E","D","D","D"],["C","E","D","D","D"],["C","C","C","C","D"],["B","B","C","A","D"],["B","B","A","A","D"]],
  hasUniqueSolution: false,
}

export default level
