// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "301",
  regions: [["E","D","D","F","H","H","H","H"],["E","D","D","F","F","F","F","H"],["E","D","D","D","D","F","H","H"],["E","D","D","D","F","F","D","D"],["E","C","B","D","D","D","D","G"],["E","C","B","A","D","D","G","G"],["E","C","A","A","G","D","G","G"],["E","C","C","C","G","G","G","G"]],
  hasUniqueSolution: true,
}

export default level
