// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "302",
  regions: [["G","G","F","B","B","B","B","B"],["G","G","F","B","H","H","A","A"],["G","G","F","F","H","H","A","A"],["G","G","F","F","F","H","H","H"],["G","G","F","F","F","F","H","H"],["C","C","F","F","F","E","H","H"],["C","D","D","D","D","E","H","H"],["C","C","C","C","C","E","E","E"]],
  hasUniqueSolution: false,
}

export default level
