// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "303",
  regions: [["C","C","C","C","C","C","C","F","F","F","F","F"],["C","C","C","F","F","F","F","F","K","F","B","F"],["C","C","I","I","I","F","F","H","K","K","B","F"],["C","C","E","E","I","E","H","H","B","B","B","F"],["C","C","E","E","E","E","H","H","H","B","B","J"],["C","E","E","E","H","H","H","H","H","B","B","J"],["C","E","A","E","H","H","H","B","B","B","B","B"],["C","A","A","A","C","H","H","H","H","G","G","B"],["C","C","C","C","C","C","C","C","C","G","B","B"],["C","C","L","C","C","C","C","H","C","G","B","B"],["C","C","L","D","D","G","G","C","C","G","B","B"],["C","D","D","D","D","G","G","G","G","G","B","B"]],
  hasUniqueSolution: true,
}

export default level
