// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "304",
  regions: [["E","J","J","J","F","A","A","G","G","G"],["E","E","J","J","F","A","A","A","A","G"],["E","B","B","J","F","F","F","A","G","G"],["E","E","B","B","B","B","F","A","A","G"],["E","E","H","B","D","B","F","F","A","A"],["E","E","H","H","D","D","D","I","I","A"],["E","E","H","C","C","I","I","I","A","A"],["E","E","C","C","I","I","A","A","A","A"],["E","E","C","I","I","I","I","A","A","A"],["A","A","A","A","A","A","A","A","A","A"]],
  hasUniqueSolution: true,
}

export default level
