// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "305",
  regions: [["F","F","F","F","F","F","A","A","A","A"],["F","F","F","F","A","A","A","G","G","A"],["F","B","B","F","F","F","F","G","A","A"],["F","B","B","B","F","D","D","D","D","A"],["B","B","C","B","F","F","D","J","A","A"],["B","C","C","C","D","D","D","J","J","A"],["B","B","B","H","H","H","D","I","I","E"],["B","B","B","H","H","H","D","D","I","E"],["H","B","B","B","H","D","D","I","I","I"],["H","H","H","H","H","H","I","I","I","I"]],
  hasUniqueSolution: true,
}

export default level
