// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "306",
  regions: [["G","G","G","G","G","G","G","G","G","G","E","E","E"],["G","G","G","G","C","G","C","G","C","G","E","E","D"],["G","G","G","C","C","G","C","C","C","D","D","D","D"],["G","G","C","C","C","C","C","D","D","D","D","M","D"],["G","G","F","C","F","C","D","D","D","H","D","M","D"],["G","G","F","C","F","D","D","K","K","H","D","D","D"],["G","G","F","F","F","B","D","D","K","H","H","D","D"],["G","G","F","F","A","B","J","J","K","K","H","D","D"],["G","F","F","A","A","A","J","K","K","H","H","D","D"],["G","F","F","F","F","J","J","K","H","H","H","D","D"],["G","G","F","L","F","J","F","K","K","H","H","H","D"],["F","G","G","L","F","J","F","H","H","H","I","I","D"],["F","F","F","F","F","F","F","F","I","I","I","I","I"]],
  hasUniqueSolution: true,
}

export default level
