// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "307",
  regions: [["D","D","D","D","D","D","D","C","C","C","C","C","C","C","C","C"],["K","K","K","D","D","D","D","D","C","C","C","J","J","J","C","C"],["K","K","D","D","I","C","C","C","C","C","C","J","J","J","C","C"],["N","N","N","D","I","I","C","I","C","C","C","J","J","J","C","C"],["N","G","N","I","I","I","I","I","I","I","I","I","J","J","J","C"],["G","G","N","N","N","I","G","G","G","E","I","J","J","C","C","C"],["D","N","N","I","I","I","G","L","L","E","E","J","J","J","C","C"],["G","G","N","N","G","I","G","L","L","L","L","J","J","J","J","C"],["G","G","G","G","G","G","G","L","H","L","J","J","J","J","C","C"],["O","G","G","H","H","H","G","L","H","L","L","J","F","J","C","C"],["O","G","G","H","H","H","G","H","H","H","L","A","F","J","J","C"],["G","G","G","G","H","H","G","H","H","L","L","A","A","A","J","C"],["H","G","H","H","H","H","H","H","L","L","A","A","A","J","J","C"],["H","H","H","M","H","B","H","H","H","B","A","A","B","B","J","C"],["P","P","P","M","H","B","B","B","B","B","B","B","B","B","J","C"],["H","H","H","H","H","H","H","H","H","B","B","B","J","J","J","J"]],
  hasUniqueSolution: true,
}

export default level
