// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "308",
  regions: [["N","N","N","N","N","O","O","O","O","O","O","O","O","O","O"],["N","L","L","N","N","O","N","N","O","N","O","O","O","O","O"],["N","N","L","L","N","N","N","N","N","N","N","O","O","O","O"],["N","N","D","L","L","N","N","G","N","O","O","O","O","C","O"],["N","N","D","L","N","N","G","G","G","O","O","O","F","C","C"],["N","L","L","L","N","L","L","G","O","O","G","O","F","A","C"],["N","L","L","L","N","N","L","G","G","G","G","A","A","A","C"],["N","L","L","L","L","N","L","G","B","G","G","G","C","C","C"],["N","K","K","K","L","L","L","B","B","G","J","C","C","C","C"],["N","K","K","H","H","L","L","L","B","G","J","J","J","C","E"],["N","N","K","H","H","H","H","B","B","G","J","G","G","C","E"],["K","N","K","H","C","C","H","B","B","G","G","G","G","C","C"],["K","K","K","H","H","C","C","C","C","C","C","G","G","G","C"],["I","K","I","I","H","H","H","M","M","H","C","C","G","C","C"],["I","I","I","I","I","I","H","H","H","H","C","C","C","C","C"]],
  hasUniqueSolution: true,
}

export default level
