// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "309",
  regions: [["F","F","F","F","F","F","F","F","F","F","F","C","C","C","C","C"],["F","F","F","F","B","B","F","B","F","F","B","C","G","G","G","G"],["F","H","F","F","B","B","B","B","B","B","B","C","C","D","D","D"],["H","H","F","B","B","F","F","F","F","F","B","C","A","A","D","J"],["H","F","F","F","F","F","F","C","C","C","C","C","C","A","J","J"],["H","F","F","F","F","F","F","F","C","P","P","C","C","C","P","J"],["F","F","P","F","I","I","I","C","C","C","P","C","P","P","P","J"],["F","P","P","F","I","I","P","C","C","P","P","P","P","P","P","J"],["F","P","F","F","I","P","P","C","C","C","P","J","J","J","P","J"],["F","P","F","F","I","P","P","P","P","P","P","O","J","J","J","J"],["F","P","P","P","P","P","P","N","N","P","N","O","J","O","O","J"],["F","P","P","M","M","P","M","N","N","N","N","O","O","O","O","J"],["F","F","P","M","K","K","M","N","E","N","O","O","L","L","J","J"],["P","F","P","M","M","M","M","E","E","N","N","O","O","L","L","J"],["P","F","P","M","M","P","M","M","M","O","O","O","O","L","L","J"],["P","P","P","P","P","P","M","M","M","M","O","O","L","L","J","J"]],
  hasUniqueSolution: true,
}

export default level
