// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '31',
  regions: [
    ['H', 'A', 'A', 'A', 'B', 'J', 'J', 'J', 'G', 'G', 'G'],
    ['H', 'A', 'A', 'A', 'B', 'J', 'G', 'G', 'G', 'G', 'G'],
    ['B', 'A', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'G'],
    ['B', 'B', 'B', 'B', 'B', 'G', 'G', 'G', 'G', 'G', 'G'],
    ['K', 'K', 'D', 'D', 'D', 'D', 'C', 'I', 'G', 'G', 'G'],
    ['K', 'K', 'K', 'D', 'D', 'D', 'C', 'I', 'G', 'E', 'G'],
    ['K', 'F', 'F', 'D', 'F', 'D', 'D', 'I', 'G', 'E', 'G'],
    ['K', 'K', 'F', 'F', 'F', 'D', 'I', 'I', 'E', 'E', 'G'],
    ['K', 'K', 'F', 'F', 'F', 'F', 'I', 'I', 'E', 'E', 'E'],
    ['K', 'K', 'F', 'F', 'K', 'F', 'F', 'F', 'F', 'E', 'E'],
    ['K', 'K', 'K', 'K', 'K', 'F', 'F', 'F', 'E', 'E', 'E']
  ],
  hasUniqueSolution: true
}

export default level
