// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "310",
  regions: [["E","E","K","K","K","K","K","O","O","O","O","J","J","J","J"],["E","E","E","K","K","K","K","O","O","O","O","J","J","J","J"],["E","E","E","D","K","K","K","O","O","O","O","O","O","J","J"],["E","E","F","D","D","D","K","D","O","O","O","O","J","J","J"],["G","E","F","F","F","D","D","D","D","O","O","O","J","J","D"],["G","G","G","F","F","F","F","F","D","D","D","D","J","J","D"],["G","G","G","F","F","F","F","L","L","D","D","D","D","D","D"],["G","G","G","G","F","F","F","L","L","C","C","D","D","N","N"],["G","G","G","L","F","L","L","L","L","C","C","C","C","N","N"],["G","G","G","L","L","L","M","L","L","C","A","A","C","N","N"],["G","B","G","G","L","M","M","L","L","A","A","A","H","H","N"],["B","B","G","G","L","M","M","I","I","A","A","H","H","H","N"],["B","B","B","G","L","I","I","I","I","I","H","H","H","H","N"],["B","B","B","L","L","I","I","I","I","I","I","I","I","I","I"],["B","B","B","L","L","L","I","I","I","I","I","I","I","I","I"]],
  hasUniqueSolution: false,
}

export default level
