// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "311",
  regions: [["E","E","A","A","A"],["E","E","A","A","A"],["C","D","D","A","A"],["C","C","D","D","D"],["B","B","B","D","D"]],
  hasUniqueSolution: true,
}

export default level
