// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "312",
  regions: [["F","F","C","F","A","A","A"],["B","B","F","F","E","A","A"],["B","E","E","E","E","A","A"],["B","E","E","D","A","A","A"],["B","B","E","D","D","A","C"],["G","B","E","D","A","A","C"],["G","B","B","D","A","A","A"]],
  hasUniqueSolution: true,
}

export default level
