// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "313",
  regions: [["F","C","C","D","D","D"],["F","F","F","D","D","D"],["F","F","E","E","A","D"],["F","E","E","E","A","D"],["F","F","E","E","E","E"],["F","F","E","B","B","E"]],
  hasUniqueSolution: true,
}

export default level
