// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "314",
  regions: [["I","I","I","N","N","N","N","N","N","N","E","E","E","O","O"],["I","N","N","N","N","N","N","E","E","E","E","E","E","O","O"],["I","C","I","I","A","K","N","N","N","N","E","E","E","E","O"],["I","I","B","B","A","K","K","A","N","N","E","N","N","N","O"],["A","I","I","B","A","A","A","A","A","N","E","E","N","O","O"],["A","I","A","B","A","A","O","A","N","N","E","N","N","N","O"],["A","A","A","A","A","A","O","O","O","N","N","N","O","O","O"],["A","C","A","C","C","C","C","C","O","N","N","N","O","O","D"],["A","C","C","C","L","C","C","C","O","O","O","O","O","D","D"],["A","C","C","C","L","L","C","L","O","H","H","O","O","H","D"],["M","M","M","L","L","L","L","L","O","O","H","O","O","H","H"],["J","J","M","L","L","L","L","O","O","H","H","O","O","H","H"],["L","L","L","L","L","H","H","O","O","H","O","O","O","H","H"],["F","L","F","F","F","F","H","H","O","H","O","O","H","H","G"],["F","F","F","H","H","H","H","H","H","H","H","H","H","H","G"]],
  hasUniqueSolution: true,
}

export default level
