// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "315",
  regions: [["F","F","F","F","F","D","D","D"],["F","F","F","A","F","F","F","F"],["F","F","A","A","A","A","A","E"],["F","F","A","H","A","C","E","E"],["A","A","A","H","H","C","C","C"],["B","B","B","G","G","G","B","C"],["B","B","B","B","G","B","B","B"],["B","B","B","B","B","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
