// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "316",
  regions: [["B","B","B","B","E","E","E","E","C"],["B","A","B","G","G","E","E","C","C"],["B","A","A","A","A","E","E","C","C"],["B","B","A","A","A","A","E","E","C"],["B","A","A","A","A","A","E","E","E"],["B","B","I","I","E","E","E","E","E"],["B","B","B","I","I","I","I","D","D"],["B","I","I","I","H","I","I","F","D"],["B","B","B","H","H","F","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
