// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "317",
  regions: [["G","G","G","G","F","D","D","F"],["G","H","H","G","F","F","F","F"],["G","G","G","G","F","B","F","B"],["G","F","F","F","F","B","F","B"],["A","F","C","F","F","B","F","B"],["A","C","C","C","C","B","F","B"],["A","C","E","E","B","B","B","B"],["A","A","B","B","B","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
