// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "318",
  regions: [["J","J","J","J","G","G","G","G","G","G","G"],["J","J","F","J","J","J","J","J","J","G","G"],["J","J","F","F","J","J","K","J","G","G","E"],["J","A","A","F","F","J","K","K","K","G","E"],["J","C","F","F","J","J","J","K","G","G","H"],["C","C","K","F","K","K","K","K","G","I","H"],["C","C","C","K","K","K","K","K","C","I","H"],["C","D","C","K","C","K","C","C","C","C","H"],["C","D","C","C","C","C","C","C","C","H","H"],["D","D","C","C","H","H","H","H","C","H","H"],["D","C","C","C","H","B","B","H","H","H","H"]],
  hasUniqueSolution: true,
}

export default level
