// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "319",
  regions: [["G","I","H","H","L","L","K","F","F","F","F","J"],["G","I","I","H","K","K","K","K","F","K","K","J"],["G","G","I","H","K","K","K","K","K","K","K","J"],["G","I","I","K","K","K","E","K","K","A","A","J"],["G","I","I","K","K","K","E","E","K","K","A","A"],["I","I","I","K","K","K","E","E","A","A","A","A"],["I","I","I","I","K","I","E","A","A","A","A","A"],["C","I","I","I","I","I","E","A","A","A","A","A"],["C","C","I","I","D","D","E","E","E","A","B","B"],["C","C","I","I","I","D","E","E","E","A","A","B"],["C","C","C","I","I","D","D","E","A","A","A","B"],["C","C","I","I","I","I","E","E","E","A","A","A"]],
  hasUniqueSolution: true,
}

export default level
