// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '32',
  regions: [
    ['C', 'C', 'C', 'C', 'C', 'C', 'C', 'D', 'D', 'D'],
    ['C', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'D', 'B'],
    ['C', 'H', 'H', 'C', 'E', 'E', 'E', 'B', 'B', 'B'],
    ['C', 'C', 'H', 'C', 'H', 'B', 'B', 'B', 'B', 'B'],
    ['G', 'C', 'H', 'H', 'H', 'B', 'B', 'B', 'J', 'J'],
    ['G', 'A', 'A', 'H', 'B', 'B', 'B', 'B', 'B', 'J'],
    ['G', 'G', 'G', 'H', 'H', 'B', 'B', 'I', 'B', 'I'],
    ['I', 'F', 'F', 'F', 'F', 'F', 'B', 'I', 'B', 'I'],
    ['I', 'I', 'F', 'I', 'I', 'F', 'I', 'I', 'I', 'I'],
    ['I', 'I', 'I', 'I', 'I', 'I', 'I', 'I', 'I', 'I']
  ],
  hasUniqueSolution: true
}

export default level
