// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '32',
  regions: [
    ['B', 'B', 'B', 'B', 'B', 'B', 'B', 'A', 'A', 'A'],
    ['B', 'D', 'B', 'B', 'B', 'B', 'B', 'B', 'A', 'H'],
    ['B', 'D', 'D', 'B', 'C', 'C', 'C', 'H', 'H', 'H'],
    ['B', 'B', 'D', 'B', 'D', 'H', 'H', 'H', 'H', 'H'],
    ['G', 'B', 'D', 'D', 'D', 'H', 'H', 'H', 'E', 'E'],
    ['G', 'F', 'F', 'D', 'H', 'H', 'H', 'H', 'H', 'E'],
    ['G', 'G', 'G', 'D', 'D', 'H', 'H', 'J', 'H', 'J'],
    ['J', 'I', 'I', 'I', 'I', 'I', 'H', 'J', 'H', 'J'],
    ['J', 'J', 'I', 'J', 'J', 'I', 'J', 'J', 'J', 'J'],
    ['J', 'J', 'J', 'J', 'J', 'J', 'J', 'J', 'J', 'J']
  ],
  hasUniqueSolution: true
}

export default level
