// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "320",
  regions: [["F","F","G","G","B","A","A"],["E","F","F","C","B","A","A"],["E","E","E","C","B","A","A"],["E","C","E","C","A","A","D"],["E","C","C","C","A","A","D"],["E","C","E","E","A","D","D"],["E","E","E","A","A","A","A"]],
  hasUniqueSolution: true,
}

export default level
