// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "321",
  regions: [["F","B","B","A","A","A","A","A","J","J","J"],["F","F","B","A","K","K","K","A","A","C","J"],["F","F","A","A","K","C","K","C","C","C","I"],["F","F","D","F","K","C","C","C","I","I","I"],["F","K","K","K","K","K","C","C","I","I","I"],["F","F","F","F","C","C","C","C","I","G","I"],["H","H","H","F","C","I","I","I","I","G","I"],["D","D","H","H","C","I","I","G","G","G","I"],["H","H","H","E","E","I","I","I","G","I","I"],["H","H","H","H","H","H","I","I","G","I","I"],["H","H","H","H","H","H","H","G","G","G","G"]],
  hasUniqueSolution: true,
}

export default level
