// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "322",
  regions: [["I","I","I","I","I","I","I","D","D","D","D","D"],["I","I","I","I","I","L","I","I","L","L","D","D"],["I","E","A","I","L","L","I","L","L","L","L","D"],["A","E","A","I","L","L","I","L","L","L","C","F"],["A","A","A","I","I","L","I","L","L","L","C","F"],["A","K","K","I","I","L","L","L","L","K","F","F"],["K","K","K","K","K","K","K","L","K","K","K","K"],["K","J","J","B","B","B","K","K","K","G","G","G"],["K","J","H","H","H","B","K","K","G","G","G","G"],["J","J","H","B","H","B","B","K","G","B","B","G"],["B","B","B","B","H","B","K","K","G","B","B","G"],["B","B","B","B","B","B","B","B","B","B","B","G"]],
  hasUniqueSolution: true,
}

export default level
