// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "323",
  regions: [["M","M","I","E","C","C","L","J","J","J","J","J","J","J"],["I","I","I","E","C","L","L","J","J","J","J","J","J","J"],["I","I","E","E","C","C","L","A","A","J","J","J","J","J"],["I","I","I","I","L","C","L","G","A","A","A","A","A","J"],["I","I","I","I","L","C","L","G","G","A","A","A","J","J"],["I","I","H","I","L","L","L","G","G","A","A","J","J","J"],["I","I","H","G","L","L","G","G","G","G","A","A","J","J"],["I","I","I","G","G","D","D","D","G","A","A","A","A","A"],["I","G","G","G","G","G","D","D","G","G","A","N","A","F"],["I","I","I","I","I","G","D","D","D","G","N","N","A","F"],["B","I","I","F","I","G","G","G","G","G","N","N","A","F"],["B","I","I","F","G","G","G","G","G","N","N","A","A","F"],["B","I","I","F","F","K","K","K","N","N","N","F","A","F"],["I","I","F","F","F","F","F","F","F","F","F","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
