// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "324",
  regions: [["B","B","B","B","B","B","H","H","H","H","H","H"],["B","B","B","B","B","H","H","A","H","A","H","H"],["B","B","B","D","H","H","A","A","H","A","E","H"],["F","B","B","D","H","G","G","A","A","A","E","H"],["F","B","D","D","D","G","G","A","E","E","E","H"],["B","B","B","B","B","G","A","A","A","A","E","E"],["C","B","B","L","L","G","G","J","A","E","E","E"],["C","C","C","C","C","G","G","J","G","G","G","E"],["G","G","C","C","G","G","G","G","G","E","G","E"],["G","G","G","C","G","I","I","I","E","E","G","E"],["K","K","G","G","G","I","I","I","E","E","E","E"],["K","K","G","E","E","E","E","E","E","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
