// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "325",
  regions: [["B","B","G","G","G","G","G","E","E"],["B","B","G","G","A","A","G","G","E"],["B","G","G","G","A","E","G","E","E"],["B","C","C","C","C","E","E","E","H"],["B","B","F","C","C","C","C","I","H"],["B","I","F","F","F","F","C","I","D"],["B","I","F","I","I","I","I","I","D"],["I","I","I","I","I","I","I","D","D"],["I","I","I","I","I","I","I","I","D"]],
  hasUniqueSolution: true,
}

export default level
