// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "326",
  regions: [["D","D","D","D","D","D","D"],["D","D","B","C","D","D","D"],["A","B","B","C","D","D","D"],["A","A","A","B","G","D","D"],["A","F","A","F","G","G","G"],["A","F","F","F","G","G","E"],["A","A","A","F","F","F","E"]],
  hasUniqueSolution: true,
}

export default level
