// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "327",
  regions: [["F","F","F","B","B","B","B"],["F","C","B","B","D","D","B"],["F","C","B","B","E","D","B"],["C","C","C","B","E","D","A"],["G","G","B","B","E","A","A"],["B","B","B","B","A","A","A"],["B","B","B","A","A","A","A"]],
  hasUniqueSolution: true,
}

export default level
