// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "328",
  regions: [["E","E","E","E","E","E","E","I","I","I","I","B"],["E","K","F","F","E","E","I","I","B","I","I","B"],["E","K","K","F","E","E","I","I","B","B","B","B"],["E","K","K","F","E","E","I","I","B","B","B","B"],["G","G","K","E","E","E","E","I","I","I","C","B"],["G","G","E","E","E","E","D","L","I","C","C","B"],["G","G","E","E","A","A","D","L","B","B","B","B"],["G","G","H","E","E","A","A","L","B","J","B","J"],["G","G","H","H","H","H","A","L","B","J","B","J"],["J","G","H","J","A","A","A","J","B","J","J","J"],["J","G","J","J","J","J","J","J","J","J","J","J"],["J","J","J","J","J","J","J","J","J","J","J","J"]],
  hasUniqueSolution: true,
}

export default level
