// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "329",
  regions: [["M","M","M","M","M","M","J","J","E","E","E","N","N","N","N","N"],["M","L","L","L","L","M","M","J","G","E","E","P","P","N","N","N"],["M","M","L","L","M","M","M","J","G","G","E","E","P","P","N","N"],["M","L","L","M","M","L","G","G","G","E","E","P","P","P","N","N"],["L","L","M","M","L","L","C","C","E","E","E","P","P","P","P","N"],["L","H","H","L","L","K","K","C","E","F","E","E","F","F","P","N"],["L","H","H","L","L","C","C","C","C","F","F","F","F","F","F","N"],["L","H","H","L","L","C","F","F","F","F","C","F","F","F","F","D"],["L","H","L","L","L","C","F","C","C","C","C","C","F","F","F","D"],["L","H","L","L","C","C","C","C","O","C","C","D","D","F","F","D"],["L","L","L","L","L","C","O","O","O","C","C","I","D","F","F","D"],["L","L","L","C","C","C","O","C","O","O","O","I","D","D","D","D"],["L","L","L","L","C","C","C","C","O","O","O","O","O","D","O","D"],["L","C","C","C","C","L","C","L","B","O","O","O","O","O","O","D"],["L","L","C","L","L","L","L","L","B","O","O","O","A","O","O","D"],["L","L","L","L","O","O","O","O","O","O","A","A","A","O","O","O"]],
  hasUniqueSolution: true,
}

export default level
