// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '33',
  regions: [
    ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'D', 'D'],
    ['A', 'C', 'A', 'A', 'A', 'A', 'B', 'A', 'A', 'A', 'D', 'D'],
    ['A', 'C', 'C', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'D', 'D'],
    ['A', 'A', 'C', 'C', 'C', 'C', 'C', 'C', 'B', 'D', 'D', 'D'],
    ['C', 'C', 'C', 'C', 'C', 'F', 'F', 'C', 'C', 'D', 'D', 'E'],
    ['C', 'G', 'G', 'F', 'F', 'F', 'F', 'C', 'C', 'D', 'D', 'E'],
    ['C', 'G', 'F', 'F', 'F', 'F', 'F', 'L', 'L', 'L', 'L', 'L'],
    ['C', 'G', 'H', 'F', 'H', 'H', 'H', 'H', 'L', 'J', 'J', 'L'],
    ['C', 'H', 'H', 'H', 'H', 'H', 'I', 'I', 'J', 'J', 'K', 'L'],
    ['C', 'K', 'K', 'K', 'K', 'J', 'J', 'J', 'J', 'J', 'K', 'L'],
    ['C', 'K', 'K', 'K', 'K', 'K', 'J', 'K', 'K', 'K', 'K', 'L'],
    ['K', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'L', 'L']
  ],
  hasUniqueSolution: true
}

export default level
