// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '33',
  regions: [
    ['J', 'J', 'J', 'J', 'J', 'J', 'J', 'J', 'J', 'J', 'H', 'H'],
    ['J', 'L', 'J', 'J', 'J', 'J', 'E', 'J', 'J', 'J', 'H', 'H'],
    ['J', 'L', 'L', 'J', 'J', 'J', 'E', 'E', 'E', 'E', 'H', 'H'],
    ['J', 'J', 'L', 'L', 'L', 'L', 'L', 'L', 'E', 'H', 'H', 'H'],
    ['L', 'L', 'L', 'L', 'L', 'C', 'C', 'L', 'L', 'H', 'H', 'I'],
    ['L', 'D', 'D', 'C', 'C', 'C', 'C', 'L', 'L', 'H', 'H', 'I'],
    ['L', 'D', 'C', 'C', 'C', 'C', 'C', 'B', 'B', 'B', 'B', 'B'],
    ['L', 'D', 'K', 'C', 'K', 'K', 'K', 'K', 'B', 'A', 'A', 'B'],
    ['L', 'K', 'K', 'K', 'K', 'K', 'F', 'F', 'A', 'A', 'G', 'B'],
    ['L', 'G', 'G', 'G', 'G', 'A', 'A', 'A', 'A', 'A', 'G', 'B'],
    ['L', 'G', 'G', 'G', 'G', 'G', 'A', 'G', 'G', 'G', 'G', 'B'],
    ['G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'B', 'B']
  ],
  hasUniqueSolution: true
}

export default level
