// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "330",
  regions: [["D","D","D","D","C","A","H","H","H"],["D","C","D","D","C","A","A","H","H"],["A","C","C","C","C","A","H","H","H"],["A","C","C","C","A","A","A","A","E"],["A","A","A","A","A","B","B","E","E"],["F","F","G","G","B","B","B","E","E"],["F","F","G","G","B","B","B","B","E"],["F","F","B","B","B","I","I","I","I"],["F","F","B","B","B","I","I","I","I"]],
  hasUniqueSolution: false,
}

export default level
