// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "331",
  regions: [["C","F","F","F","E","E","E"],["C","B","B","B","D","E","E"],["B","B","B","D","D","A","E"],["B","B","B","D","D","A","E"],["B","D","D","D","D","D","E"],["B","D","B","B","B","D","G"],["B","B","B","B","G","G","G"]],
  hasUniqueSolution: true,
}

export default level
