// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "332",
  regions: [["D","I","I","A","A","A","A","A","A"],["D","D","I","A","I","A","A","G","A"],["H","I","I","I","I","E","A","G","A"],["H","H","H","H","I","E","A","G","A"],["B","H","H","I","I","E","A","A","A"],["B","I","I","I","I","E","E","A","A"],["B","I","I","I","E","E","E","A","A"],["B","B","B","E","E","E","E","F","F"],["C","C","C","E","E","E","E","E","F"]],
  hasUniqueSolution: true,
}

export default level
