// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "333",
  regions: [["H","H","H","I","I","I","I","I","I","I","I","K"],["A","A","A","A","I","I","J","I","I","K","I","K"],["B","B","A","C","I","I","J","I","K","K","I","K"],["B","A","A","C","I","C","J","J","K","K","K","K"],["E","A","D","C","C","C","C","C","C","K","E","E"],["E","D","D","C","D","C","K","K","K","K","K","E"],["E","E","D","D","D","D","D","K","E","E","E","E"],["E","E","E","G","G","D","D","D","D","D","E","E"],["E","E","E","E","G","E","E","E","E","E","E","E"],["E","L","E","E","E","E","F","E","F","F","F","E"],["E","L","E","E","L","E","F","F","F","F","F","F"],["E","L","L","L","L","E","E","E","E","E","E","F"]],
  hasUniqueSolution: true,
}

export default level
