// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "334",
  regions: [["I","I","E","E","E","E","E","E","E","E","E","E","E","E"],["I","E","E","E","E","E","E","J","J","J","J","D","D","E"],["I","J","J","J","E","E","J","J","J","E","J","J","J","E"],["I","J","E","E","E","J","J","E","E","E","E","E","J","E"],["I","J","J","J","J","J","J","J","N","E","N","E","E","E"],["I","G","J","N","N","N","J","N","N","N","N","N","B","B"],["I","G","G","G","N","N","N","N","N","N","A","A","B","A"],["I","I","G","G","L","N","N","A","A","A","A","A","A","A"],["N","N","N","L","L","N","N","N","A","K","K","H","H","H"],["M","N","L","L","L","N","N","N","A","K","K","H","H","H"],["M","N","L","N","L","L","N","N","N","N","K","K","H","H"],["M","N","N","N","N","N","N","C","N","N","H","F","H","H"],["M","N","N","M","M","M","M","C","N","H","H","F","H","H"],["M","M","M","M","M","M","C","C","N","H","H","H","H","H"]],
  hasUniqueSolution: true,
}

export default level
