// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "335",
  regions: [["C","D","D","A","A"],["C","C","D","E","A"],["E","E","E","E","A"],["E","B","E","B","A"],["E","B","B","B","A"]],
  hasUniqueSolution: true,
}

export default level
