// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "336",
  regions: [["G","G","G","G","G","G","G"],["G","G","B","B","G","G","D"],["G","G","G","G","G","E","D"],["A","A","A","G","E","E","E"],["A","A","A","G","E","G","E"],["A","F","A","G","G","G","E"],["A","F","C","C","G","G","E"]],
  hasUniqueSolution: true,
}

export default level
