// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "337",
  regions: [["F","C","E","E","E","E","B","B"],["F","C","E","E","E","H","H","B"],["F","F","E","E","H","H","A","B"],["E","F","E","E","A","A","A","B"],["E","F","E","E","E","A","A","A"],["E","F","E","G","D","D","D","A"],["E","F","E","G","G","D","A","A"],["E","E","E","G","G","D","A","A"]],
  hasUniqueSolution: true,
}

export default level
