// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "338",
  regions: [["G","G","G","G","G","H","H","H","A","A","C"],["G","G","G","G","H","H","H","H","H","C","C"],["G","G","J","G","H","I","I","H","B","B","C"],["G","I","J","J","H","H","I","H","B","B","B"],["G","I","I","J","H","I","I","I","B","B","B"],["I","I","J","J","I","I","I","I","B","B","B"],["I","I","I","I","I","I","I","B","B","B","E"],["I","D","F","F","I","E","E","B","E","E","E"],["I","D","I","F","I","I","E","E","E","E","K"],["I","D","I","F","F","I","E","E","E","K","K"],["I","I","I","I","F","I","I","E","E","E","K"]],
  hasUniqueSolution: true,
}

export default level
