// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "339",
  regions: [["M","M","M","M","M","M","M","M","M","M","M","M","M","M","M","M"],["M","N","N","M","K","M","M","M","M","M","K","K","M","M","M","M"],["M","N","N","N","K","K","K","M","M","M","M","K","M","M","M","B"],["M","M","E","N","K","N","K","M","M","K","K","K","M","M","B","B"],["E","M","E","N","N","N","K","K","K","K","L","M","M","B","B","B"],["E","E","E","E","N","N","K","K","K","K","L","M","M","B","B","B"],["E","N","N","N","N","N","N","K","N","K","L","C","M","B","B","B"],["N","N","H","H","G","N","N","N","N","N","L","C","M","B","A","A"],["N","N","J","G","G","N","N","C","C","C","C","C","C","A","A","A"],["N","J","J","J","N","N","N","N","N","N","C","C","C","C","C","A"],["P","P","P","J","J","N","I","N","N","J","J","J","C","A","A","A"],["J","P","P","J","N","N","I","J","J","J","J","J","C","A","A","A"],["J","P","J","J","N","J","J","J","J","D","D","D","D","A","D","A"],["J","J","J","J","J","J","J","O","J","D","D","F","D","D","D","A"],["O","O","O","J","J","O","O","O","J","D","F","F","F","D","D","D"],["O","O","O","O","O","O","O","J","J","D","F","F","D","D","D","D"]],
  hasUniqueSolution: true,
}

export default level
