// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '34',
  regions: [
    ['D', 'D', 'D', 'D', 'D', 'E', 'E', 'I', 'I', 'F', 'F', 'F', 'F', 'F', 'F'],
    ['A', 'A', 'D', 'L', 'D', 'D', 'E', 'E', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
    ['A', 'L', 'L', 'L', 'D', 'D', 'D', 'E', 'F', 'C', 'C', 'C', 'C', 'C', 'C'],
    ['A', 'L', 'A', 'L', 'D', 'L', 'D', 'E', 'F', 'F', 'C', 'C', 'C', 'C', 'C'],
    ['A', 'L', 'A', 'L', 'L', 'L', 'D', 'E', 'E', 'F', 'F', 'G', 'G', 'C', 'C'],
    ['A', 'A', 'A', 'D', 'L', 'D', 'D', 'D', 'E', 'F', 'F', 'C', 'C', 'C', 'C'],
    ['A', 'D', 'D', 'D', 'D', 'D', 'B', 'D', 'D', 'D', 'F', 'C', 'C', 'C', 'C'],
    ['A', 'A', 'O', 'D', 'O', 'B', 'B', 'B', 'D', 'F', 'F', 'F', 'C', 'C', 'C'],
    ['A', 'A', 'O', 'O', 'O', 'B', 'B', 'B', 'F', 'F', 'F', 'F', 'F', 'F', 'C'],
    ['A', 'N', 'N', 'N', 'N', 'N', 'N', 'B', 'F', 'C', 'C', 'C', 'C', 'C', 'C'],
    ['A', 'A', 'A', 'A', 'N', 'N', 'N', 'N', 'N', 'C', 'C', 'C', 'N', 'C', 'C'],
    ['A', 'A', 'N', 'N', 'N', 'N', 'N', 'K', 'N', 'N', 'C', 'N', 'N', 'C', 'C'],
    ['A', 'A', 'A', 'N', 'N', 'N', 'K', 'K', 'K', 'N', 'N', 'H', 'C', 'C', 'M'],
    ['A', 'J', 'A', 'A', 'N', 'N', 'N', 'H', 'H', 'H', 'M', 'N', 'N', 'M', 'M'],
    ['J', 'J', 'A', 'A', 'A', 'N', 'N', 'N', 'N', 'M', 'M', 'M', 'M', 'M', 'M']
  ],
  hasUniqueSolution: true
}

export default level
