// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "34",
  regions: [["D","D","D","D","D","B","B","A","A","G","G","G","G","G","G"],["J","J","D","C","D","D","B","B","G","G","G","G","G","G","G"],["J","C","C","C","D","D","D","B","G","F","F","F","F","F","F"],["J","C","J","C","D","C","D","B","G","G","F","F","F","F","F"],["J","C","J","C","C","C","D","B","B","G","G","E","E","F","F"],["J","J","J","D","C","D","D","D","B","G","G","F","F","F","F"],["J","D","D","D","D","D","H","D","D","D","G","F","F","F","F"],["J","J","I","D","I","H","H","H","D","G","G","G","F","F","F"],["J","J","I","I","I","H","H","H","G","G","G","G","G","G","F"],["J","K","K","K","K","K","K","H","G","F","F","F","F","F","F"],["J","J","J","J","K","K","K","K","K","F","F","F","K","F","F"],["J","J","K","K","K","K","K","L","K","K","F","K","K","F","F"],["J","J","J","K","K","K","L","L","L","K","K","N","F","F","M"],["J","O","J","J","K","K","K","N","N","N","M","K","K","M","M"],["O","O","J","J","J","K","K","K","K","M","M","M","M","M","M"]],
  hasUniqueSolution: true,
}

export default level
