// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "340",
  regions: [["K","K","K","G","G","G","G","B","E","E","E"],["K","G","G","G","G","G","G","B","E","E","E"],["K","K","K","B","B","B","B","B","E","E","E"],["K","K","K","B","B","B","C","C","C","C","C"],["K","K","A","A","B","C","C","C","H","H","H"],["K","D","D","A","C","C","C","H","H","H","H"],["K","D","D","D","D","F","F","H","H","J","H"],["J","D","D","D","F","F","F","H","H","J","H"],["J","D","D","D","J","J","J","J","J","J","H"],["J","D","D","J","J","I","I","I","I","I","I"],["J","J","J","J","J","I","I","I","I","I","I"]],
  hasUniqueSolution: false,
}

export default level
