// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "341",
  regions: [["E","E","E","E","E","E","E"],["B","D","E","D","C","C","E"],["B","D","E","D","D","E","E"],["D","D","D","D","G","E","E"],["D","G","G","G","G","F","E"],["D","G","A","A","G","F","E"],["D","D","D","A","A","F","E"]],
  hasUniqueSolution: true,
}

export default level
