// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "342",
  regions: [["J","B","B","B","B","B","B","E","E","E"],["J","J","J","G","B","B","B","B","E","E"],["J","C","C","G","G","B","H","H","H","E"],["J","C","C","G","C","C","C","C","C","C"],["J","J","C","C","C","C","C","I","I","I"],["J","J","J","C","I","I","C","C","I","F"],["J","J","C","C","D","I","I","C","I","F"],["J","J","D","D","D","I","I","I","I","I"],["J","J","J","D","D","D","D","A","A","I"],["J","J","J","D","D","D","D","D","D","I"]],
  hasUniqueSolution: true,
}

export default level
