// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "343",
  regions: [["C","D","D","D","G","G","G","G","J","J","J","J"],["C","D","D","D","D","G","G","J","J","G","J","J"],["C","C","D","D","D","G","G","G","G","G","I","J"],["C","D","D","G","G","G","G","G","I","I","I","J"],["D","D","G","G","D","G","D","G","G","I","I","J"],["F","D","D","I","D","D","D","I","I","I","J","J"],["F","D","D","E","D","D","D","D","J","I","I","J"],["F","F","D","E","E","L","D","D","J","J","J","J"],["F","F","D","E","A","L","L","A","A","J","B","J"],["F","F","A","A","A","A","A","A","A","H","B","K"],["A","F","F","F","A","A","K","K","K","H","B","K"],["A","A","A","A","A","A","A","A","K","K","K","K"]],
  hasUniqueSolution: true,
}

export default level
