// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "344",
  regions: [["L","L","L","L","L","L","L","L","L","L","L","L"],["G","G","L","A","A","A","A","L","K","K","L","E"],["L","L","L","L","L","A","A","A","A","K","L","E"],["L","F","L","F","L","L","A","A","K","C","L","E"],["L","F","F","F","A","A","D","A","L","L","L","E"],["I","I","A","F","F","A","D","A","L","L","L","E"],["I","I","A","A","A","A","A","A","A","A","E","E"],["I","I","I","I","I","A","A","A","A","C","C","C"],["I","C","C","I","C","A","A","A","A","C","C","C"],["I","I","C","C","C","A","A","A","A","C","J","C"],["H","I","I","I","C","C","C","C","C","C","J","C"],["H","H","I","B","B","C","C","J","J","J","J","J"]],
  hasUniqueSolution: true,
}

export default level
