// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "345",
  regions: [["F","F","D","A","A","A","D"],["F","D","D","D","D","D","D"],["E","D","G","G","D","D","D"],["E","E","G","D","D","D","D"],["E","G","G","D","D","D","C"],["E","G","G","C","C","D","C"],["B","B","B","C","C","C","C"]],
  hasUniqueSolution: true,
}

export default level
