// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "346",
  regions: [["J","J","J","H","H","H","H","H","I","I","I"],["J","H","H","H","H","H","I","I","I","I","I"],["J","J","J","H","E","H","H","H","H","I","I"],["J","B","B","E","E","A","H","D","D","D","I"],["J","J","B","C","C","A","H","D","I","I","I"],["B","B","B","B","C","C","C","D","I","I","I"],["B","B","B","B","C","D","D","D","D","D","I"],["F","F","B","C","C","K","K","G","I","I","I"],["F","F","B","G","G","K","G","G","G","I","I"],["F","G","G","G","G","K","G","I","I","I","I"],["F","G","G","G","G","G","G","G","G","G","I"]],
  hasUniqueSolution: true,
}

export default level
