// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "347",
  regions: [["G","G","G","E","E","E","E","E","E","E","E"],["G","G","C","E","E","I","I","H","H","H","E"],["G","G","C","C","E","I","H","H","H","E","E"],["C","G","C","I","I","I","I","H","H","H","E"],["C","C","C","I","I","J","I","I","I","H","E"],["C","J","J","J","J","J","I","H","H","H","H"],["J","J","J","D","D","I","I","H","H","A","H"],["F","J","J","I","I","I","B","H","H","A","B"],["F","J","J","I","I","I","B","H","H","B","B"],["F","J","J","J","I","B","B","H","B","B","B"],["K","K","I","I","I","I","B","B","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
