// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "348",
  regions: [["E","E","E","E","E","E","I","I","I","J"],["E","E","E","G","E","C","D","I","I","J"],["E","G","G","G","G","C","D","D","I","I"],["E","E","E","B","G","C","C","C","C","I"],["E","E","B","B","B","C","C","C","C","I"],["E","E","E","E","B","B","B","C","C","I"],["H","E","E","B","B","B","A","C","C","I"],["H","E","E","B","B","B","A","I","I","I"],["H","E","B","B","F","F","A","A","A","I"],["E","E","B","B","B","B","B","A","I","I"]],
  hasUniqueSolution: true,
}

export default level
