// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "349",
  regions: [["J","J","L","L","L","L","L","L","L","A","A","C"],["J","J","L","C","C","C","L","C","L","L","C","C"],["J","L","L","C","C","C","C","C","L","E","E","C"],["F","F","F","C","K","D","D","C","L","C","E","C"],["F","C","F","C","K","D","C","C","C","C","C","C"],["F","C","C","C","C","D","D","C","C","C","C","C"],["F","F","C","C","C","C","D","C","G","C","C","H"],["I","C","C","D","D","D","D","C","G","G","G","H"],["I","C","B","B","D","H","H","H","H","G","G","H"],["I","I","I","B","D","B","B","H","H","H","G","H"],["I","I","B","B","D","D","B","B","H","G","G","H"],["B","B","B","B","B","B","B","H","H","H","H","H"]],
  hasUniqueSolution: true,
}

export default level
