// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '35',
  regions: [
    ['A', 'A', 'D', 'D', 'D'],
    ['A', 'A', 'D', 'D', 'C'],
    ['A', 'A', 'A', 'D', 'C'],
    ['B', 'B', 'C', 'C', 'C'],
    ['E', 'E', 'E', 'C', 'C']
  ],
  hasUniqueSolution: true
}

export default level
