// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "350",
  regions: [["B","B","D","D","D","D","D","G","G"],["B","D","D","C","C","D","G","G","G"],["B","D","D","C","C","I","I","G","G"],["B","B","D","D","C","C","I","I","G"],["B","F","D","D","D","C","I","G","G"],["B","F","F","D","C","C","I","G","G"],["B","F","F","F","C","H","I","I","G"],["E","E","A","F","H","H","I","H","H"],["E","E","A","A","H","H","H","H","H"]],
  hasUniqueSolution: true,
}

export default level
