// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "351",
  regions: [["H","H","H","H","H","H","H","H"],["A","A","H","B","B","H","H","H"],["H","H","H","H","B","H","E","E"],["B","B","H","B","B","H","E","E"],["C","B","B","B","B","H","C","D"],["C","C","C","B","C","C","C","D"],["C","G","C","C","C","C","F","D"],["C","G","G","G","C","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
