// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "352",
  regions: [["F","J","J","J","E","E","E","E","E","E"],["F","J","F","J","E","E","F","F","F","E"],["F","F","F","J","E","F","F","F","E","E"],["F","F","F","F","F","F","G","E","E","G"],["I","G","G","G","G","G","G","G","G","G"],["I","I","C","C","H","G","G","G","D","D"],["C","C","C","H","H","D","D","G","G","D"],["C","C","C","D","D","D","D","G","D","D"],["C","C","D","D","D","D","D","D","D","A"],["B","B","D","D","D","D","D","A","A","A"]],
  hasUniqueSolution: true,
}

export default level
