// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "353",
  regions: [["E","E","E","E","E","E","A","D","D","D","D","D"],["E","A","E","E","A","A","A","A","D","J","J","J"],["E","A","E","E","E","A","A","D","D","J","J","J"],["A","A","A","A","A","A","L","D","D","D","D","J"],["A","A","A","L","L","L","L","L","J","J","J","J"],["A","K","A","A","A","A","L","J","J","J","J","J"],["A","K","K","L","L","L","L","J","J","J","H","H"],["A","K","K","L","L","B","B","J","J","J","J","G"],["A","B","B","B","B","B","B","J","I","J","J","G"],["A","A","F","B","I","I","I","J","I","J","C","G"],["A","F","F","F","I","I","I","I","I","C","C","G"],["A","A","I","I","I","I","I","I","I","I","C","G"]],
  hasUniqueSolution: true,
}

export default level
