// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "354",
  regions: [["J","J","J","J","J","G","G","G","G","G","G","G","G","N"],["J","J","J","J","J","J","J","J","G","N","N","N","N","N"],["J","J","G","G","J","G","G","G","G","N","N","N","N","I"],["J","J","J","G","J","G","B","B","B","B","B","N","N","I"],["J","G","G","G","J","G","G","B","B","B","N","N","K","K"],["J","G","G","G","G","G","B","B","K","K","K","K","K","K"],["J","J","G","G","B","B","B","B","K","D","K","K","D","K"],["E","G","G","B","B","E","K","K","K","D","D","K","D","D"],["E","E","E","E","E","E","H","H","K","K","D","D","D","D"],["E","A","A","A","E","A","H","K","K","K","D","D","C","D"],["E","A","M","A","E","A","A","A","K","A","C","C","C","L"],["A","A","M","A","E","A","A","A","A","A","C","C","L","L"],["A","A","F","A","E","A","A","A","C","C","C","C","C","C"],["F","F","F","A","A","A","A","A","A","A","C","C","C","C"]],
  hasUniqueSolution: true,
}

export default level
