// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "355",
  regions: [["D","F","F","A","A","F","F","F"],["D","F","F","F","H","F","F","F"],["D","F","C","F","G","G","F","F"],["D","B","C","C","C","C","H","H"],["D","B","B","B","E","H","H","H"],["D","E","E","E","E","H","H","H"],["D","D","D","E","E","H","H","H"],["D","D","E","E","E","E","H","H"]],
  hasUniqueSolution: true,
}

export default level
