// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "356",
  regions: [["B","B","B","B","B","D","D","D","D","D","J","J","J","J"],["F","F","B","B","B","A","A","D","D","D","D","D","J","J"],["F","F","F","B","B","A","A","D","D","M","D","D","J","J"],["F","F","F","B","I","I","I","M","M","M","J","J","J","J"],["F","F","B","B","B","B","M","M","M","J","J","N","J","J"],["F","C","B","B","M","M","M","N","N","N","N","N","J","J"],["F","C","C","C","M","M","M","M","N","N","E","E","G","G"],["F","C","C","C","C","E","E","M","M","N","E","G","G","G"],["F","F","F","C","C","E","M","M","M","N","E","G","G","G"],["F","F","F","C","C","E","M","E","E","E","E","G","G","G"],["F","H","H","C","C","E","E","E","E","E","G","G","G","G"],["F","H","H","H","H","H","E","E","E","E","G","L","K","K"],["H","H","H","H","H","H","H","H","L","L","L","L","L","K"],["H","H","H","H","H","H","H","H","L","L","L","L","L","L"]],
  hasUniqueSolution: false,
}

export default level
