// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "357",
  regions: [["A","A","A","A","A","A","A","A"],["A","A","G","A","A","G","F","A"],["H","A","G","G","G","G","F","G"],["H","C","C","C","C","G","G","G"],["B","C","D","G","G","G","G","G"],["B","C","D","G","E","E","E","G"],["B","D","D","G","G","D","E","G"],["B","B","D","D","D","D","E","G"]],
  hasUniqueSolution: true,
}

export default level
