// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "358",
  regions: [["E","E","E","A","A","A","A","A","F"],["E","E","E","H","H","H","H","F","F"],["E","F","F","F","H","H","G","F","F"],["E","E","E","F","F","F","G","F","F"],["E","E","E","E","F","F","H","F","F"],["B","B","E","E","E","E","E","E","F"],["B","B","E","D","D","D","E","C","F"],["B","E","E","D","I","I","E","C","F"],["E","E","E","E","E","E","E","C","C"]],
  hasUniqueSolution: true,
}

export default level
