// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "359",
  regions: [["H","H","H","H","H","C","C","C","C","C","C","C"],["H","C","C","C","C","C","D","D","C","C","C","E"],["D","D","D","D","C","C","D","D","D","D","D","E"],["D","C","C","C","C","C","C","D","K","K","K","E"],["D","C","C","D","C","D","C","D","D","D","D","E"],["D","D","D","D","D","D","D","D","L","L","D","E"],["D","F","B","D","B","D","D","L","L","L","L","E"],["J","F","B","B","B","B","D","D","L","G","E","E"],["J","A","A","A","B","D","D","D","L","G","G","E"],["A","A","A","A","B","D","I","D","D","E","E","E"],["A","A","A","A","B","D","I","D","D","D","E","E"],["A","A","A","A","A","A","A","A","D","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
