// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '36',
  regions: [
    ['C', 'F', 'F', 'F', 'B', 'E', 'E', 'E'],
    ['C', 'C', 'C', 'F', 'B', 'B', 'B', 'E'],
    ['C', 'F', 'F', 'F', 'F', 'F', 'B', 'E'],
    ['G', 'G', 'D', 'D', 'E', 'E', 'E', 'E'],
    ['H', 'H', 'D', 'E', 'E', 'E', 'A', 'A'],
    ['H', 'H', 'D', 'D', 'E', 'E', 'E', 'A'],
    ['H', 'D', 'D', 'D', 'D', 'A', 'A', 'A'],
    ['H', 'D', 'D', 'D', 'D', 'D', 'D', 'A']
  ],
  hasUniqueSolution: true
}

export default level
