// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "36",
  regions: [["B","C","C","C","A","E","E","E"],["B","B","B","C","A","A","A","E"],["B","C","C","C","C","C","A","E"],["D","D","H","H","E","E","E","E"],["G","G","H","E","E","E","F","F"],["G","G","H","H","E","E","E","F"],["G","H","H","H","H","F","F","F"],["G","H","H","H","H","H","H","F"]],
  hasUniqueSolution: true,
}

export default level
