// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "360",
  regions: [["E","E","B","B","A","A","G","G"],["E","E","B","A","A","A","G","G"],["E","C","C","C","A","A","G","G"],["E","C","C","F","F","G","G","G"],["D","C","F","F","F","F","G","G"],["D","D","F","F","F","F","G","G"],["F","F","F","F","F","F","H","H"],["F","F","F","F","F","F","H","H"]],
  hasUniqueSolution: false,
}

export default level
