// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "361",
  regions: [["H","H","H","H","H","H","H","H"],["H","H","A","H","H","E","H","H"],["A","H","A","A","H","E","H","H"],["A","A","A","G","G","H","H","H"],["A","A","C","C","G","G","B","H"],["A","A","C","F","G","B","B","B"],["A","F","F","F","B","B","D","D"],["A","A","F","F","B","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
