// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "362",
  regions: [["I","I","I","I","I","C","C","D","D"],["A","A","I","B","I","I","C","C","D"],["I","I","I","B","B","I","D","D","D"],["B","B","B","B","I","I","I","I","D"],["B","B","B","B","B","I","I","I","D"],["B","B","B","B","B","B","F","G","D"],["B","B","B","B","B","E","F","G","G"],["E","B","E","E","E","E","G","G","G"],["E","E","E","H","H","H","G","G","G"]],
  hasUniqueSolution: true,
}

export default level
