// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "363",
  regions: [["D","D","F","F","F","A","A","A","A"],["D","D","D","D","D","D","D","A","E"],["D","D","G","G","D","E","E","E","E"],["C","D","D","G","I","I","I","H","H"],["C","D","G","G","I","B","I","H","H"],["C","D","G","G","G","B","B","G","H"],["C","C","G","C","G","G","G","G","H"],["C","C","C","C","C","C","C","G","H"],["C","C","C","C","G","G","G","G","G"]],
  hasUniqueSolution: true,
}

export default level
