// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "364",
  regions: [["F","F","F","F","E","E","E","E","E","J","J","J","G","G","L","M"],["N","F","E","E","E","E","J","E","E","E","J","G","G","G","M","M"],["N","F","E","E","E","E","J","J","J","E","J","M","M","G","M","M"],["N","F","E","E","E","E","E","J","E","E","J","M","M","M","M","M"],["N","F","F","F","F","F","E","J","J","J","J","M","D","M","P","M"],["N","F","F","E","E","F","E","E","E","M","M","M","D","D","P","P"],["N","F","F","E","E","E","E","M","M","M","B","M","D","P","P","P"],["N","F","F","F","N","E","M","M","M","M","B","M","M","M","H","P"],["N","F","F","F","N","E","E","E","E","B","B","M","C","L","H","P"],["N","F","N","N","N","E","E","E","E","B","B","C","C","L","H","P"],["N","F","F","N","N","I","E","E","B","B","B","C","L","L","H","P"],["N","N","N","N","N","I","I","O","B","C","C","C","K","L","H","P"],["A","N","I","I","I","I","O","O","B","B","K","K","K","L","P","P"],["A","N","I","I","N","I","I","O","O","B","K","B","K","L","B","B"],["N","N","N","N","N","O","O","O","B","B","K","B","L","L","L","B"],["N","N","N","O","O","O","O","O","O","B","B","B","B","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
