// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "365",
  regions: [["I","I","I","I","I","D","D","C","C","C"],["I","I","I","I","D","D","D","D","C","C"],["I","I","I","I","H","H","H","C","C","C"],["E","E","E","I","H","H","H","H","H","C"],["E","E","E","I","A","A","A","A","H","H"],["E","E","E","A","A","A","A","G","G","H"],["F","F","F","A","A","A","B","G","G","H"],["F","F","F","A","B","B","B","B","G","H"],["F","F","F","B","B","B","B","B","B","J"],["F","F","F","B","B","B","B","B","J","J"]],
  hasUniqueSolution: false,
}

export default level
