// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "366",
  regions: [["J","J","J","J","J","J","C","C","C","E","E","E","H","H","H"],["J","J","J","J","J","J","C","C","E","E","E","H","H","H","H"],["J","J","J","J","J","J","C","C","E","E","E","M","M","M","A"],["K","K","I","J","J","F","F","E","E","E","E","M","M","M","A"],["K","K","I","I","I","F","F","E","E","E","M","M","M","M","A"],["K","K","B","B","I","I","F","F","F","F","M","N","N","A","A"],["K","K","B","B","B","I","F","F","F","F","N","N","N","A","A"],["K","K","B","B","B","I","I","F","F","F","N","N","N","A","A"],["K","K","K","B","B","B","B","B","B","F","N","N","N","A","A"],["K","K","K","D","B","B","B","B","B","F","N","N","N","A","A"],["K","K","D","D","B","B","B","N","N","N","N","N","N","L","A"],["K","K","D","D","B","B","B","O","O","O","O","L","L","L","A"],["K","K","K","K","B","B","B","O","O","L","L","L","L","L","A"],["K","G","G","G","G","B","B","O","O","L","L","L","L","L","L"],["K","O","O","O","O","O","O","O","O","O","L","L","L","L","L"]],
  hasUniqueSolution: false,
}

export default level
