// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "367",
  regions: [["B","B","N","N","N","N","N","N","N","A","A","K","K","K","K"],["B","B","B","B","N","N","G","G","G","A","A","A","K","K","K"],["C","C","B","B","B","B","G","G","G","A","K","K","K","K","K"],["C","C","B","H","B","G","G","G","G","A","K","K","F","F","K"],["C","C","B","H","H","G","G","G","K","K","K","K","F","F","F"],["B","B","B","H","H","G","G","E","E","K","K","K","K","I","F"],["L","L","L","H","E","E","E","E","E","E","E","K","K","I","I"],["L","L","L","L","L","E","E","E","E","E","E","K","I","I","I"],["L","L","L","L","L","L","D","D","E","E","I","I","I","I","I"],["M","M","L","L","L","D","D","D","E","E","I","I","I","I","I"],["M","M","L","L","L","D","D","D","D","E","E","I","I","I","I"],["M","M","L","L","L","D","D","D","E","E","E","I","I","I","I"],["M","M","L","L","D","D","D","J","J","J","J","J","I","I","I"],["L","L","L","L","J","J","J","J","O","J","O","J","J","I","I"],["L","L","J","J","J","J","J","J","O","O","O","O","J","I","I"]],
  hasUniqueSolution: false,
}

export default level
