// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "368",
  regions: [["A","A","A","B","B","B","F"],["A","G","G","G","F","F","F"],["A","G","G","G","G","D","C"],["G","G","G","G","G","D","C"],["G","G","G","G","G","D","C"],["G","G","D","D","D","D","C"],["G","G","E","E","E","E","C"]],
  hasUniqueSolution: true,
}

export default level
