// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "369",
  regions: [["G","G","G","G","G","G","G","G","G","G","G"],["G","G","G","E","G","D","D","C","F","H","H"],["E","E","E","E","G","C","D","C","F","H","F"],["E","E","K","K","G","C","C","C","F","H","F"],["A","K","K","K","G","G","G","C","F","F","F"],["A","A","K","G","G","G","C","C","F","F","F"],["K","K","K","G","G","C","C","C","C","I","F"],["K","B","B","G","G","G","J","C","C","I","F"],["K","B","G","G","J","G","J","J","C","J","F"],["K","B","G","G","J","J","J","C","C","J","F"],["B","B","B","B","B","J","J","J","J","J","J"]],
  hasUniqueSolution: true,
}

export default level
