// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '37',
  regions: [
    ['I', 'I', 'I', 'I', 'I', 'I', 'I', 'J', 'A', 'A', 'K'],
    ['I', 'H', 'H', 'H', 'H', 'I', 'I', 'J', 'A', 'K', 'K'],
    ['I', 'H', 'I', 'H', 'H', 'I', 'H', 'J', 'J', 'K', 'B'],
    ['I', 'I', 'I', 'I', 'H', 'H', 'H', 'J', 'K', 'K', 'B'],
    ['I', 'I', 'H', 'H', 'H', 'H', 'H', 'J', 'D', 'D', 'D'],
    ['F', 'I', 'F', 'H', 'E', 'E', 'E', 'D', 'D', 'E', 'D'],
    ['F', 'I', 'F', 'H', 'E', 'E', 'D', 'D', 'E', 'E', 'D'],
    ['F', 'F', 'F', 'H', 'G', 'E', 'E', 'E', 'E', 'E', 'F'],
    ['F', 'C', 'C', 'F', 'G', 'G', 'E', 'F', 'F', 'E', 'F'],
    ['F', 'C', 'F', 'F', 'F', 'G', 'G', 'F', 'F', 'E', 'F'],
    ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F']
  ],
  hasUniqueSolution: true
}

export default level
