// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '37',
  regions: [
    ['E', 'E', 'E', 'E', 'E', 'E', 'E', 'B', 'A', 'A', 'D'],
    ['E', 'H', 'H', 'H', 'H', 'E', 'E', 'B', 'A', 'D', 'D'],
    ['E', 'H', 'E', 'H', 'H', 'E', 'H', 'B', 'B', 'D', 'C'],
    ['E', 'E', 'E', 'E', 'H', 'H', 'H', 'B', 'D', 'D', 'C'],
    ['E', 'E', 'H', 'H', 'H', 'H', 'H', 'B', 'G', 'G', 'G'],
    ['K', 'E', 'K', 'H', 'F', 'F', 'F', 'G', 'G', 'F', 'G'],
    ['K', 'E', 'K', 'H', 'F', 'F', 'G', 'G', 'F', 'F', 'G'],
    ['K', 'K', 'K', 'H', 'J', 'F', 'F', 'F', 'F', 'F', 'K'],
    ['K', 'I', 'I', 'K', 'J', 'J', 'F', 'K', 'K', 'F', 'K'],
    ['K', 'I', 'K', 'K', 'K', 'J', 'J', 'K', 'K', 'F', 'K'],
    ['K', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'K']
  ],
  hasUniqueSolution: true
}

export default level
