// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "370",
  regions: [["C","A","B","D","D"],["C","A","B","D","D"],["C","C","B","D","D"],["C","C","C","E","E"],["C","C","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
