// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "371",
  regions: [["C","A","A","F","F","F","B"],["C","C","F","F","F","F","B"],["D","C","E","F","E","F","F"],["D","C","E","E","E","E","F"],["D","E","E","G","G","E","G"],["D","D","E","G","E","E","G"],["G","G","G","G","G","G","G"]],
  hasUniqueSolution: true,
}

export default level
