// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "372",
  regions: [["H","H","H","H","H","H","H","H","H","H"],["H","H","H","H","H","C","C","H","C","C"],["F","H","H","H","H","C","C","H","C","C"],["F","B","H","H","G","C","C","C","C","C"],["F","B","B","H","G","G","G","G","G","C"],["F","G","G","G","G","G","E","G","G","C"],["D","D","D","D","G","D","E","E","E","E"],["D","I","I","D","G","D","E","E","A","A"],["I","I","D","D","D","D","E","E","E","A"],["I","I","D","D","D","J","J","A","A","A"]],
  hasUniqueSolution: true,
}

export default level
