// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "373",
  regions: [["A","A","A","A","G","G","G","G","G"],["A","H","A","G","G","G","G","C","G"],["A","H","A","A","A","G","G","C","G"],["H","H","H","H","H","H","C","C","G"],["H","H","F","F","E","H","F","C","C"],["H","H","H","F","E","F","G","C","C"],["H","F","F","F","F","F","F","C","B"],["H","F","F","I","D","D","F","C","B"],["H","F","F","I","I","I","F","F","B"]],
  hasUniqueSolution: true,
}

export default level
