// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "374",
  regions: [["P","P","P","I","I","I","I","Q","Q","Q","Q","Q","Q","Q","G","G","Q"],["P","P","P","I","P","I","C","C","C","C","C","C","Q","G","G","Q","Q"],["P","P","P","P","P","P","P","P","C","C","C","C","Q","Q","G","Q","Q"],["P","K","P","P","C","C","P","C","C","C","Q","Q","Q","Q","Q","Q","N"],["P","K","P","P","P","C","P","P","P","C","B","B","B","Q","B","Q","N"],["P","K","K","K","P","C","C","C","C","C","C","B","B","B","B","Q","N"],["P","K","P","K","P","P","C","B","B","B","C","B","B","B","B","A","N"],["P","K","P","K","P","C","C","C","C","B","B","B","B","A","A","A","A"],["P","M","P","P","P","P","P","B","C","C","B","C","B","A","A","A","L"],["M","M","M","P","D","P","B","B","C","M","C","C","B","A","A","A","L"],["M","E","E","D","D","D","D","B","B","B","B","B","B","A","L","A","L"],["M","M","E","E","E","E","D","B","J","J","J","J","J","A","L","L","L"],["M","M","M","M","M","E","D","B","B","J","D","J","J","A","A","L","L"],["M","M","M","M","E","E","D","B","D","J","D","J","A","A","A","A","L"],["M","E","E","E","E","E","D","D","D","D","D","A","A","A","L","F","L"],["M","E","E","E","E","E","D","D","E","H","D","A","A","L","L","F","L"],["E","E","E","O","O","E","E","E","E","H","H","L","L","L","L","L","L"]],
  hasUniqueSolution: true,
}

export default level
