// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "375",
  regions: [["D","D","D","D","D"],["D","A","A","B","C"],["D","A","A","B","C"],["A","A","A","E","C"],["A","E","E","B","B"]],
  hasUniqueSolution: true,
}

export default level
