// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "376",
  regions: [["E","F","F","F","F","B"],["E","F","B","B","B","B"],["C","F","B","B","A","C"],["C","C","C","A","A","C"],["D","D","C","C","A","C"],["C","C","C","C","C","C"]],
  hasUniqueSolution: true,
}

export default level
