// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "377",
  regions: [["B","B","B","B","B","B"],["C","E","B","E","F","B"],["C","E","E","E","F","B"],["E","E","F","F","F","F"],["E","F","F","F","F","A"],["E","D","D","A","A","A"]],
  hasUniqueSolution: true,
}

export default level
