// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "378",
  regions: [["C","C","A","A","D","D","A","A","A"],["C","C","C","A","A","A","A","E","A"],["C","G","G","B","A","A","E","E","A"],["C","C","G","B","B","E","E","E","A"],["C","C","G","G","G","C","C","E","A"],["C","C","C","C","C","C","A","A","A"],["H","H","H","H","A","A","A","H","A"],["H","F","I","H","H","H","H","H","A"],["F","F","I","A","A","A","A","A","A"]],
  hasUniqueSolution: true,
}

export default level
