// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "379",
  regions: [["M","M","M","M","M","M","M","M","M","D","C","C","C","N"],["M","M","M","M","M","K","D","D","D","D","C","C","N","N"],["M","M","J","J","M","K","D","D","C","D","C","C","C","N"],["M","M","J","J","M","J","J","D","C","D","C","N","N","N"],["M","J","J","M","M","M","J","B","C","C","C","N","N","G"],["J","J","J","J","J","M","J","B","C","A","A","N","N","G"],["J","J","E","E","J","M","J","B","C","N","N","N","N","G"],["J","J","E","E","J","J","J","J","G","N","N","G","G","G"],["F","J","J","E","J","J","G","G","G","N","N","G","G","G"],["F","J","E","E","E","J","J","G","N","N","G","G","I","E"],["J","J","E","L","E","E","J","G","G","G","G","G","I","E"],["L","L","E","L","L","E","J","E","E","E","E","G","G","E"],["L","L","L","L","E","E","E","E","E","H","E","G","G","E"],["L","L","L","E","E","E","E","E","E","H","E","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
