// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '38',
  regions: [
    ['D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D'],
    ['E', 'E', 'D', 'D', 'C', 'C', 'A', 'J', 'J', 'D'],
    ['E', 'E', 'E', 'E', 'C', 'C', 'A', 'D', 'D', 'D'],
    ['A', 'A', 'E', 'E', 'E', 'A', 'A', 'A', 'A', 'D'],
    ['A', 'A', 'A', 'E', 'E', 'A', 'F', 'F', 'H', 'D'],
    ['A', 'A', 'E', 'E', 'E', 'A', 'A', 'F', 'H', 'D'],
    ['A', 'A', 'A', 'I', 'I', 'A', 'F', 'F', 'D', 'D'],
    ['A', 'G', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'D'],
    ['A', 'G', 'A', 'G', 'A', 'B', 'B', 'G', 'D', 'D'],
    ['G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'D']
  ],
  hasUniqueSolution: true
}

export default level
