// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "380",
  regions: [["D","D","D","D","D","A","C","C"],["D","D","A","A","D","A","A","C"],["D","D","A","A","D","A","A","B"],["F","D","F","A","A","A","B","B"],["F","D","E","G","G","A","B","H"],["D","D","E","A","A","A","B","H"],["E","E","E","A","A","H","H","H"],["A","A","A","A","A","A","H","H"]],
  hasUniqueSolution: true,
}

export default level
