// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "381",
  regions: [["H","H","A","A","D","D","D","D"],["H","B","B","B","H","H","H","D"],["H","B","H","H","H","H","H","G"],["H","H","H","H","C","H","G","G"],["H","C","C","C","C","C","C","G"],["H","H","H","C","C","E","E","E"],["C","C","C","C","C","F","E","E"],["C","D","F","F","F","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
