// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "382",
  regions: [["A","A","B","B","C","C","C"],["F","A","A","A","C","C","C"],["F","A","C","C","C","C","C"],["F","F","F","F","F","F","F"],["F","F","F","F","F","D","G"],["F","F","D","D","D","D","G"],["F","F","F","E","E","G","G"]],
  hasUniqueSolution: true,
}

export default level
