// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "383",
  regions: [["C","C","C","C","C","I","I","I","I","I"],["C","C","I","I","I","I","I","C","I","I"],["C","C","B","C","C","C","C","C","C","I"],["C","B","B","C","I","G","G","C","I","I"],["C","C","B","C","I","I","I","I","I","D"],["D","C","B","C","H","I","I","I","D","D"],["C","C","C","C","H","J","F","D","D","J"],["A","A","C","C","H","J","F","D","D","J"],["E","A","A","C","H","J","J","J","D","J"],["E","A","C","C","H","J","J","J","J","J"]],
  hasUniqueSolution: true,
}

export default level
