// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "384",
  regions: [["A","A","A","A","A","A","A","D","D","K","K","K"],["G","A","A","A","A","A","B","D","D","D","K","K"],["G","A","A","B","B","B","D","F","I","I","I","K"],["G","A","A","A","B","B","I","F","I","K","K","K"],["G","G","A","B","B","I","I","I","I","H","H","K"],["G","J","J","J","B","B","B","B","I","K","K","K"],["G","J","G","J","J","B","L","L","I","I","K","K"],["G","G","G","J","B","B","B","I","I","K","K","B"],["C","C","G","B","B","B","B","B","K","K","B","B"],["C","C","B","B","B","C","B","B","B","K","K","B"],["C","C","C","C","C","C","B","B","B","B","K","B"],["C","C","E","E","B","B","B","B","B","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
