// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "385",
  regions: [["C","C","C","C","C","C","C","C","C"],["C","E","C","C","C","C","C","C","C"],["C","E","E","E","G","G","C","F","F"],["C","E","A","A","C","C","C","F","H"],["C","E","E","B","C","B","B","F","H"],["C","C","B","B","C","B","B","F","F"],["C","D","D","B","B","B","B","F","F"],["C","D","B","B","I","I","B","F","B"],["I","I","I","I","I","B","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
