// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "386",
  regions: [["I","I","I","I","I","I","I","I","A","A"],["I","H","H","H","I","I","I","J","A","A"],["I","I","H","H","H","I","J","J","J","F"],["I","I","H","J","J","J","J","F","J","F"],["I","H","H","H","H","H","J","F","F","F"],["I","G","H","H","H","H","J","J","F","F"],["I","G","G","G","H","J","J","J","B","E"],["I","I","G","G","H","J","B","B","B","E"],["C","G","G","G","G","J","J","J","B","B"],["C","C","C","C","G","D","D","D","D","B"]],
  hasUniqueSolution: true,
}

export default level
