// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "387",
  regions: [["K","K","K","K","G","G","J","J","J","J","J"],["K","A","A","I","G","I","I","I","J","J","F"],["K","C","A","I","I","I","I","I","I","I","F"],["K","C","A","A","I","I","I","F","F","F","F"],["K","A","A","I","I","I","F","F","F","F","I"],["K","A","A","A","A","I","F","I","I","I","I"],["A","A","E","I","I","I","F","I","I","D","D"],["A","A","E","E","I","I","I","I","D","B","D"],["A","A","E","I","I","I","D","D","D","B","D"],["A","E","E","E","I","D","D","D","D","D","D"],["H","H","H","E","D","D","D","D","D","D","D"]],
  hasUniqueSolution: true,
}

export default level
