// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "388",
  regions: [["F","F","F","F","F","F","F","F","F","F","H"],["F","I","F","F","F","F","F","H","F","H","H"],["F","I","F","F","F","A","F","H","H","H","G"],["I","I","I","I","I","A","A","A","H","J","G"],["I","I","I","J","I","I","J","J","J","J","G"],["D","I","J","J","I","B","J","G","G","G","G"],["D","D","D","J","I","B","J","J","G","G","G"],["C","C","D","J","I","I","J","J","G","J","J"],["C","E","E","J","I","I","I","J","G","J","K"],["C","C","C","J","I","I","J","J","J","J","K"],["C","J","J","J","J","J","J","J","J","K","K"]],
  hasUniqueSolution: true,
}

export default level
