// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "389",
  regions: [["H","H","N","N","N","N","L","L","A","A","B","B","B","K","K"],["H","I","I","N","N","L","L","L","A","B","B","E","B","B","K"],["I","I","I","N","N","L","L","A","A","B","B","E","E","K","K"],["I","N","N","N","J","J","L","A","A","B","B","K","K","K","K"],["I","I","I","I","J","L","L","B","B","B","B","K","L","K","K"],["I","D","D","I","L","L","L","L","B","B","L","K","L","F","F"],["I","D","D","I","L","L","L","L","B","L","L","L","L","L","F"],["I","I","D","I","I","I","I","L","L","L","L","G","G","G","F"],["I","D","D","D","D","I","I","I","L","G","G","G","F","F","F"],["I","I","I","D","D","I","G","I","G","G","G","G","G","F","F"],["I","D","D","D","G","G","G","I","G","G","G","M","G","G","F"],["D","D","D","D","D","D","G","G","G","G","G","M","G","F","F"],["M","M","M","C","C","D","G","D","G","M","M","M","M","F","F"],["O","O","M","M","M","D","D","D","D","D","D","M","M","F","F"],["O","O","O","O","M","M","M","M","M","M","M","M","M","F","F"]],
  hasUniqueSolution: true,
}

export default level
