// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "39",
  regions: [["A","A","A","A","A","C","C","D","D","D","B","B"],["A","A","A","C","C","C","D","D","D","B","B","D"],["E","A","A","C","C","C","D","D","D","D","D","D"],["E","A","A","A","C","D","D","D","D","D","C","D"],["E","E","E","E","C","C","D","D","D","D","C","D"],["E","F","H","E","C","D","D","D","C","C","C","C"],["E","F","H","E","C","C","C","C","C","G","C","C"],["E","F","H","E","E","E","E","C","G","G","C","C"],["L","L","L","L","E","E","E","C","C","G","I","I"],["L","K","L","L","L","J","J","J","C","G","G","I"],["K","K","K","L","L","J","J","J","C","G","J","I"],["K","K","L","L","L","L","L","J","J","J","J","J"]],
  hasUniqueSolution: true,
}

export default level
