// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '39',
  regions: [
    ['A', 'A', 'A', 'A', 'A', 'C', 'C', 'F', 'F', 'F', 'L', 'L'],
    ['A', 'A', 'A', 'C', 'C', 'C', 'F', 'F', 'F', 'L', 'L', 'F'],
    ['K', 'A', 'A', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'F'],
    ['K', 'A', 'A', 'A', 'C', 'F', 'F', 'F', 'F', 'F', 'C', 'F'],
    ['K', 'K', 'K', 'K', 'C', 'C', 'F', 'F', 'F', 'F', 'C', 'F'],
    ['K', 'D', 'G', 'K', 'C', 'F', 'F', 'F', 'C', 'C', 'C', 'C'],
    ['K', 'D', 'G', 'K', 'C', 'C', 'C', 'C', 'C', 'J', 'C', 'C'],
    ['K', 'D', 'G', 'K', 'K', 'K', 'K', 'C', 'J', 'J', 'C', 'C'],
    ['B', 'B', 'B', 'B', 'K', 'K', 'K', 'C', 'C', 'J', 'H', 'H'],
    ['B', 'I', 'B', 'B', 'B', 'E', 'E', 'E', 'C', 'J', 'J', 'H'],
    ['I', 'I', 'I', 'B', 'B', 'E', 'E', 'E', 'C', 'J', 'E', 'H'],
    ['I', 'I', 'B', 'B', 'B', 'B', 'B', 'E', 'E', 'E', 'E', 'E']
  ],
  hasUniqueSolution: true
}

export default level
