// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "390",
  regions: [["I","I","I","I","B","B","B","C","C","C"],["H","I","I","I","B","B","B","E","E","C"],["H","I","I","I","B","B","B","E","C","C"],["H","H","I","I","B","B","B","E","E","E"],["H","H","I","A","B","G","G","G","E","E"],["D","D","A","A","G","G","G","G","G","F"],["D","D","A","F","F","G","G","G","G","F"],["D","D","A","F","F","F","F","F","F","F"],["D","F","F","F","F","F","F","F","F","F"],["D","D","D","D","J","J","J","J","F","F"]],
  hasUniqueSolution: false,
}

export default level
