// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "391",
  regions: [["F","F","F","E","E","D"],["F","E","E","E","E","D"],["F","B","B","B","E","D"],["B","B","B","C","A","A"],["B","B","B","C","C","A"],["B","B","C","C","C","A"]],
  hasUniqueSolution: true,
}

export default level
