// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "392",
  regions: [["A","A","A","A","H","H","H","H","H"],["A","H","H","H","H","H","H","I","I"],["A","H","F","H","I","I","I","I","E"],["G","F","F","F","F","F","F","I","E"],["G","G","C","D","F","D","D","E","E"],["G","C","C","D","D","D","D","E","E"],["G","C","B","D","E","E","E","E","E"],["G","D","B","D","E","D","E","E","E"],["D","D","D","D","D","D","D","E","E"]],
  hasUniqueSolution: true,
}

export default level
