// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "393",
  regions: [["E","E","E","E","E","E","E","E","E","E","E","K","K","K","K","K","B","B"],["I","I","E","E","R","R","E","E","E","E","E","Q","K","K","K","K","B","B"],["I","I","G","R","R","R","R","E","E","E","E","Q","Q","Q","Q","K","B","B"],["G","G","G","R","R","R","R","R","E","E","Q","Q","Q","K","K","K","K","K"],["G","G","G","G","R","R","R","R","R","R","Q","Q","Q","K","K","K","K","K"],["G","G","G","G","R","R","R","R","A","R","Q","Q","Q","K","K","K","K","K"],["G","L","L","G","G","A","A","A","A","R","R","R","R","K","K","D","K","D"],["G","L","L","G","G","R","R","R","R","R","R","G","G","K","D","D","D","D"],["L","L","L","G","G","R","R","G","G","G","G","G","M","K","K","K","D","D"],["L","L","L","G","G","G","G","G","F","F","G","G","M","M","K","K","D","D"],["L","L","L","J","J","J","J","G","F","F","M","M","M","M","K","K","K","D"],["L","L","O","O","J","J","J","J","F","F","M","M","N","N","N","N","D","D"],["L","L","L","O","J","J","J","J","J","F","F","M","N","C","C","C","D","D"],["L","L","L","O","J","J","J","J","J","M","M","M","N","C","N","N","N","D"],["L","L","O","O","H","J","J","J","J","M","M","M","N","N","N","N","N","D"],["L","L","O","H","H","J","J","J","J","M","M","M","N","N","D","D","D","D"],["L","O","O","H","H","J","J","P","P","P","P","P","P","P","P","D","D","P"],["L","O","O","H","H","H","H","P","P","P","P","P","P","P","P","P","P","P"]],
  hasUniqueSolution: false,
}

export default level
