// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "394",
  regions: [["C","C","C","C","H","E","E","E","E","E"],["J","C","C","H","H","E","A","A","A","E"],["J","C","H","H","H","E","A","A","A","F"],["C","C","C","C","H","E","E","E","A","F"],["C","B","B","C","H","E","A","A","A","F"],["C","C","C","C","H","H","H","H","A","I"],["G","G","H","C","H","D","H","I","A","I"],["G","G","H","H","H","D","H","I","A","I"],["G","H","H","I","I","H","H","I","I","I"],["G","H","I","I","I","I","I","I","I","I"]],
  hasUniqueSolution: true,
}

export default level
