// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "395",
  regions: [["H","B","B","B","A","C","C","C"],["H","B","B","A","A","A","C","C"],["H","B","B","B","A","A","A","C"],["H","H","H","A","A","G","G","C"],["H","G","H","H","G","G","C","C"],["H","G","G","H","G","D","C","C"],["F","G","G","G","G","D","D","D"],["F","G","G","G","E","E","D","D"]],
  hasUniqueSolution: true,
}

export default level
