// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "396",
  regions: [["I","I","I","I","I","C","C","C","C","C"],["I","B","B","B","I","C","C","C","C","F"],["B","B","H","C","C","C","F","F","F","F"],["B","B","H","J","J","C","J","F","F","F"],["B","H","H","J","J","J","J","J","F","F"],["B","B","A","G","G","F","F","F","F","D"],["E","B","A","A","G","F","F","F","D","D"],["E","B","E","E","E","E","F","F","D","D"],["E","E","E","E","E","E","E","E","E","D"],["E","E","E","E","E","D","D","D","D","D"]],
  hasUniqueSolution: true,
}

export default level
