// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "397",
  regions: [["A","A","A","A","A","D","B","B","B","B"],["A","A","A","A","D","D","B","H","B","B"],["F","A","A","A","A","J","H","H","H","B"],["F","J","J","A","J","J","J","I","H","B"],["F","J","J","J","J","E","E","I","H","B"],["F","J","J","G","J","G","E","H","H","B"],["F","J","F","G","J","G","E","H","B","B"],["F","F","F","G","J","G","E","H","H","C"],["G","F","G","G","J","G","E","E","H","C"],["G","G","G","G","G","G","E","E","C","C"]],
  hasUniqueSolution: true,
}

export default level
