// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "398",
  regions: [["F","F","F","F","F","F","F","G","G","G","G","N","N","N"],["F","F","F","I","I","I","F","F","G","G","G","N","H","N"],["F","F","F","K","K","K","K","K","G","G","G","N","H","N"],["F","E","F","F","K","K","K","G","G","N","N","N","H","H"],["F","E","F","F","K","M","M","G","G","G","N","N","H","H"],["F","F","J","F","K","K","M","L","L","L","L","L","L","H"],["B","F","J","J","M","K","M","M","M","M","L","L","L","L"],["B","C","C","J","M","M","M","C","M","M","L","M","L","D"],["B","C","C","J","J","J","C","C","C","M","M","M","L","D"],["B","C","C","J","C","C","C","B","C","C","C","C","C","D"],["B","C","C","C","C","C","C","B","C","C","C","C","C","D"],["B","B","C","C","B","B","B","B","B","C","A","A","C","D"],["B","C","C","C","C","B","B","B","B","B","A","A","A","D"],["B","B","B","B","B","B","A","A","A","A","A","D","D","D"]],
  hasUniqueSolution: true,
}

export default level
