// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "399",
  regions: [["A","A","A","A","J","J","J","C","L","L","G","G","G","G","F","F","F"],["A","A","A","J","J","B","C","C","L","G","G","G","G","G","G","F","F"],["A","J","J","J","B","B","J","C","C","C","C","O","G","J","G","G","G"],["A","J","J","J","J","J","J","J","J","C","J","O","O","J","J","J","G"],["A","J","J","A","A","H","H","J","J","C","J","J","J","J","G","G","G"],["A","J","J","A","H","H","H","H","J","J","J","J","J","J","J","J","G"],["A","A","A","A","H","H","J","J","J","I","I","P","J","J","G","G","G"],["H","H","H","H","H","H","J","I","I","I","I","P","J","J","G","N","N"],["H","I","I","I","I","H","J","I","G","G","G","G","J","G","G","Q","Q"],["H","M","M","I","I","I","I","I","Q","Q","G","G","G","G","G","G","Q"],["M","M","I","I","I","M","M","I","I","Q","Q","Q","Q","Q","Q","G","Q"],["M","M","M","I","M","M","I","I","I","Q","K","E","E","Q","Q","Q","Q"],["D","D","M","I","I","M","I","I","K","K","K","E","E","E","E","Q","Q"],["D","M","M","M","M","M","I","I","K","Q","K","K","Q","E","Q","Q","Q"],["D","M","M","M","D","M","K","K","K","Q","K","Q","Q","E","E","E","Q"],["D","M","D","M","D","D","K","K","Q","Q","K","K","Q","Q","Q","E","Q"],["D","D","D","D","D","D","D","D","D","Q","Q","Q","Q","Q","Q","Q","Q"]],
  hasUniqueSolution: true,
}

export default level
