// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "4",
  regions: [["E","D","E","I","I","I","I","I","I","A","C","C","C","C","C","C"],["E","D","E","E","E","I","I","I","A","A","A","C","B","B","H","C"],["E","D","E","E","E","E","I","I","I","C","C","C","C","C","H","C"],["E","D","E","E","F","E","I","I","I","I","C","C","C","H","H","H"],["E","E","E","F","F","E","I","G","G","I","C","H","C","C","H","H"],["E","E","E","F","G","E","G","G","G","I","C","H","H","H","H","H"],["E","E","K","K","G","G","G","G","I","I","C","H","H","C","C","H"],["E","E","E","K","K","I","I","I","I","I","C","C","C","C","H","H"],["E","K","E","K","K","K","I","I","I","I","I","I","C","C","C","H"],["E","K","K","K","L","K","K","I","J","J","C","C","C","C","H","H"],["E","K","K","K","L","K","I","I","I","J","C","H","C","C","H","H"],["E","E","E","K","L","I","I","C","C","C","C","H","H","H","H","H"],["E","K","K","K","L","I","I","I","I","I","C","C","H","M","H","H"],["K","K","K","L","L","I","I","I","O","I","N","H","H","M","M","H"],["P","P","K","L","L","L","L","O","O","O","N","N","N","M","M","L"],["P","P","P","P","P","L","L","L","L","M","M","M","M","M","M","H"]],
  hasUniqueSolution: true,
}

export default level
