// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '4',
  regions: [
    ['D', 'O', 'D', 'B', 'B', 'B', 'B', 'B', 'B', 'L', 'K', 'K', 'K', 'K', 'K', 'K'],
    ['D', 'O', 'D', 'D', 'D', 'B', 'B', 'B', 'L', 'L', 'L', 'K', 'A', 'A', 'M', 'K'],
    ['D', 'O', 'D', 'D', 'D', 'D', 'B', 'B', 'B', 'K', 'K', 'K', 'K', 'K', 'M', 'K'],
    ['D', 'O', 'D', 'D', 'G', 'D', 'B', 'B', 'B', 'B', 'K', 'K', 'K', 'M', 'M', 'M'],
    ['D', 'D', 'D', 'G', 'G', 'D', 'B', 'J', 'J', 'B', 'K', 'M', 'K', 'K', 'M', 'M'],
    ['D', 'D', 'D', 'G', 'J', 'D', 'J', 'J', 'J', 'B', 'K', 'M', 'M', 'M', 'M', 'M'],
    ['D', 'D', 'E', 'E', 'J', 'J', 'J', 'J', 'B', 'B', 'K', 'M', 'M', 'K', 'K', 'M'],
    ['D', 'D', 'D', 'E', 'E', 'B', 'B', 'B', 'B', 'B', 'K', 'K', 'K', 'K', 'M', 'M'],
    ['D', 'E', 'D', 'E', 'E', 'E', 'B', 'B', 'B', 'B', 'B', 'B', 'K', 'K', 'K', 'M'],
    ['D', 'E', 'E', 'E', 'H', 'E', 'E', 'B', 'N', 'N', 'K', 'K', 'K', 'K', 'M', 'M'],
    ['D', 'E', 'E', 'E', 'H', 'E', 'B', 'B', 'B', 'N', 'K', 'M', 'K', 'K', 'M', 'M'],
    ['D', 'D', 'D', 'E', 'H', 'B', 'B', 'K', 'K', 'K', 'K', 'M', 'M', 'M', 'M', 'M'],
    ['D', 'E', 'E', 'E', 'H', 'B', 'B', 'B', 'B', 'B', 'K', 'K', 'M', 'P', 'M', 'M'],
    ['E', 'E', 'E', 'H', 'H', 'B', 'B', 'B', 'I', 'B', 'C', 'M', 'M', 'P', 'P', 'M'],
    ['F', 'F', 'E', 'H', 'H', 'H', 'H', 'I', 'I', 'I', 'C', 'C', 'C', 'P', 'P', 'H'],
    ['F', 'F', 'F', 'F', 'F', 'H', 'H', 'H', 'H', 'P', 'P', 'P', 'P', 'P', 'P', 'M']
  ],
  hasUniqueSolution: true
}

export default level
