// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '40',
  regions: [
    ['G', 'G', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
    ['G', 'C', 'C', 'C', 'C', 'A', 'A', 'A', 'D', 'A', 'A', 'B', 'B', 'A', 'A'],
    ['G', 'G', 'C', 'C', 'A', 'A', 'A', 'D', 'D', 'A', 'A', 'A', 'B', 'A', 'A'],
    ['G', 'G', 'A', 'A', 'A', 'A', 'D', 'D', 'A', 'A', 'B', 'B', 'B', 'A', 'A'],
    ['E', 'G', 'G', 'A', 'D', 'D', 'D', 'D', 'D', 'D', 'B', 'B', 'B', 'A', 'A'],
    ['E', 'G', 'G', 'A', 'D', 'D', 'D', 'D', 'G', 'D', 'B', 'B', 'F', 'A', 'A'],
    ['E', 'G', 'G', 'G', 'G', 'D', 'D', 'G', 'G', 'G', 'G', 'G', 'F', 'A', 'A'],
    ['E', 'E', 'E', 'E', 'G', 'G', 'G', 'G', 'G', 'H', 'G', 'G', 'F', 'A', 'A'],
    ['I', 'I', 'E', 'G', 'G', 'E', 'G', 'H', 'H', 'H', 'H', 'G', 'F', 'A', 'A'],
    ['E', 'E', 'E', 'K', 'E', 'E', 'H', 'H', 'H', 'J', 'J', 'F', 'F', 'F', 'F'],
    ['E', 'E', 'E', 'E', 'K', 'E', 'E', 'H', 'J', 'J', 'J', 'J', 'J', 'J', 'F'],
    ['K', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'L', 'L', 'L', 'L', 'J', 'F', 'F'],
    ['K', 'K', 'M', 'K', 'M', 'K', 'N', 'N', 'N', 'N', 'L', 'J', 'J', 'J', 'F'],
    ['M', 'K', 'M', 'K', 'M', 'N', 'N', 'L', 'L', 'L', 'L', 'J', 'O', 'J', 'F'],
    ['M', 'M', 'M', 'M', 'M', 'M', 'N', 'N', 'N', 'J', 'J', 'J', 'O', 'O', 'F']
  ],
  hasUniqueSolution: true
}

export default level
