// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '40',
  regions: [
    ['M', 'M', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H'],
    ['M', 'N', 'N', 'N', 'N', 'H', 'H', 'H', 'I', 'H', 'H', 'K', 'K', 'H', 'H'],
    ['M', 'M', 'N', 'N', 'H', 'H', 'H', 'I', 'I', 'H', 'H', 'H', 'K', 'H', 'H'],
    ['M', 'M', 'H', 'H', 'H', 'H', 'I', 'I', 'H', 'H', 'K', 'K', 'K', 'H', 'H'],
    ['F', 'M', 'M', 'H', 'I', 'I', 'I', 'I', 'I', 'I', 'K', 'K', 'K', 'H', 'H'],
    ['F', 'M', 'M', 'H', 'I', 'I', 'I', 'I', 'M', 'I', 'K', 'K', 'E', 'H', 'H'],
    ['F', 'M', 'M', 'M', 'M', 'I', 'I', 'M', 'M', 'M', 'M', 'M', 'E', 'H', 'H'],
    ['F', 'F', 'F', 'F', 'M', 'M', 'M', 'M', 'M', 'A', 'M', 'M', 'E', 'H', 'H'],
    ['B', 'B', 'F', 'M', 'M', 'F', 'M', 'A', 'A', 'A', 'A', 'M', 'E', 'H', 'H'],
    ['F', 'F', 'F', 'G', 'F', 'F', 'A', 'A', 'A', 'C', 'C', 'E', 'E', 'E', 'E'],
    ['F', 'F', 'F', 'F', 'G', 'F', 'F', 'A', 'C', 'C', 'C', 'C', 'C', 'C', 'E'],
    ['G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'L', 'L', 'L', 'L', 'C', 'E', 'E'],
    ['G', 'G', 'D', 'G', 'D', 'G', 'J', 'J', 'J', 'J', 'L', 'C', 'C', 'C', 'E'],
    ['D', 'G', 'D', 'G', 'D', 'J', 'J', 'L', 'L', 'L', 'L', 'C', 'O', 'C', 'E'],
    ['D', 'D', 'D', 'D', 'D', 'D', 'J', 'J', 'J', 'C', 'C', 'C', 'O', 'O', 'E']
  ],
  hasUniqueSolution: true
}

export default level
