// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "400",
  regions: [["L","L","G","G","G","G","G","G","G","G","G","B"],["L","G","G","J","J","J","B","B","G","D","B","B"],["L","L","H","H","H","J","J","B","G","D","B","B"],["J","L","J","J","J","J","J","B","B","B","B","B"],["J","J","J","J","B","B","B","B","B","A","B","I"],["C","C","J","J","J","J","A","B","B","A","A","I"],["J","J","J","J","J","J","A","B","B","A","E","I"],["J","J","J","J","J","A","A","A","B","A","E","I"],["J","J","J","K","A","A","A","A","A","A","E","I"],["J","F","F","K","F","A","I","I","I","E","E","I"],["J","F","F","F","F","A","I","E","E","E","I","I"],["I","I","I","I","I","I","I","I","I","I","I","I"]],
  hasUniqueSolution: true,
}

export default level
