// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "401",
  regions: [["D","D","D","A","A","A","E","E","E"],["D","A","D","D","A","E","E","E","E"],["D","A","A","A","A","A","A","E","E"],["D","A","A","H","H","A","E","E","E"],["G","G","A","H","A","A","A","F","F"],["G","G","H","H","H","H","I","I","I"],["G","H","H","H","H","H","H","H","I"],["G","H","H","B","I","I","H","H","I"],["G","C","C","B","B","I","I","I","I"]],
  hasUniqueSolution: true,
}

export default level
