// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "402",
  regions: [["D","D","D","D","D","D","D","D","E","A"],["D","D","D","D","D","D","D","D","E","A"],["D","D","D","D","D","D","E","D","E","E"],["D","D","D","D","D","F","E","E","E","H"],["J","J","D","D","D","F","C","F","F","H"],["B","J","J","F","D","F","C","F","H","H"],["B","J","J","F","F","F","F","F","F","H"],["B","B","J","J","I","F","F","H","H","H"],["G","I","I","I","I","F","F","F","F","H"],["G","G","G","G","I","I","F","F","F","H"]],
  hasUniqueSolution: true,
}

export default level
