// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "403",
  regions: [["D","A","A","A","A","G","G","G"],["D","D","D","A","A","A","A","G"],["D","D","D","D","A","A","A","G"],["D","D","B","B","H","C","G","G"],["D","B","B","B","H","C","C","F"],["D","D","B","B","E","E","E","F"],["D","B","B","B","E","E","E","F"],["D","E","E","E","E","E","F","F"]],
  hasUniqueSolution: true,
}

export default level
