// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "404",
  regions: [["C","C","C","C","C","C","C","C","D"],["C","C","C","C","A","C","D","D","D"],["C","C","H","H","A","A","A","A","A"],["I","I","H","H","A","A","G","G","A"],["I","I","H","H","B","A","G","G","G"],["I","I","H","H","B","B","G","G","G"],["I","I","H","H","B","B","G","G","G"],["E","I","H","H","H","H","F","G","F"],["E","E","H","H","H","F","F","F","F"]],
  hasUniqueSolution: false,
}

export default level
