// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "405",
  regions: [["K","K","K","K","K","A","A","A","A","B","B","B","B","B","B","B"],["K","I","I","I","K","A","A","A","B","B","B","B","H","B","B","B"],["K","I","I","I","I","I","I","A","B","H","H","H","H","H","B","B"],["K","I","F","F","I","I","I","A","B","B","H","H","B","B","B","B"],["I","I","F","I","I","J","A","A","B","B","H","G","G","G","B","G"],["N","I","F","I","J","J","J","A","A","B","B","G","G","G","B","G"],["N","I","F","I","J","I","I","A","A","A","B","B","G","G","G","G"],["I","I","I","I","I","I","A","A","B","B","B","G","G","L","G","G"],["I","O","O","I","E","E","E","E","E","E","G","L","L","L","G","G"],["I","I","I","I","E","C","C","G","G","G","G","L","G","G","G","G"],["I","I","E","I","E","C","C","C","C","C","G","G","G","G","G","G"],["I","I","E","E","E","C","M","C","C","C","C","G","P","G","P","G"],["I","I","E","C","C","C","M","M","C","C","G","P","P","G","P","G"],["I","I","E","E","I","I","M","M","D","D","G","G","P","P","P","G"],["I","I","I","I","I","M","M","D","D","G","G","P","P","G","G","G"],["I","I","I","M","M","M","D","D","G","G","G","G","G","G","G","G"]],
  hasUniqueSolution: true,
}

export default level
