// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "406",
  regions: [["A","A","L","J","J","J","J","J","J","K","K","K","K"],["A","A","L","J","J","J","E","K","K","K","K","K","K"],["A","A","L","L","J","J","E","K","G","G","G","G","K"],["A","A","A","L","J","J","J","G","G","G","G","G","G"],["A","A","A","L","J","J","J","G","M","G","G","G","G"],["A","A","A","L","J","J","J","G","M","M","G","G","G"],["A","L","L","L","J","B","B","G","B","G","G","G","G"],["D","D","F","F","F","B","B","B","B","I","I","I","I"],["D","D","F","F","B","B","B","B","B","I","I","I","I"],["D","D","F","F","B","B","B","C","C","I","I","I","I"],["D","D","B","B","B","B","B","C","I","I","I","I","I"],["D","D","B","B","B","B","B","C","C","H","H","H","H"],["D","D","B","B","B","B","B","C","H","H","H","H","H"]],
  hasUniqueSolution: false,
}

export default level
