// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "407",
  regions: [["G","G","G","D","I","I","I","I","C"],["G","G","G","D","I","I","I","I","C"],["E","E","E","D","D","D","D","D","C"],["E","E","D","D","D","D","D","C","C"],["E","E","A","A","A","D","F","C","C"],["E","A","A","A","A","D","F","C","C"],["E","A","A","A","H","D","F","F","C"],["E","B","B","A","H","F","F","F","C"],["B","B","B","A","H","F","F","F","C"]],
  hasUniqueSolution: false,
}

export default level
