// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "408",
  regions: [["K","K","K","K","K","K","K","K","K","K","J","D"],["E","K","K","K","E","K","K","K","B","B","J","D"],["E","E","K","K","E","E","K","A","H","B","J","D"],["C","E","E","E","E","E","E","A","H","H","J","D"],["C","E","E","L","E","E","A","A","H","J","J","D"],["C","L","E","L","E","A","A","H","H","J","D","D"],["G","L","E","L","E","E","A","A","J","J","D","I"],["G","L","L","L","L","E","A","E","E","J","D","I"],["G","G","G","L","E","E","E","E","E","J","J","I"],["G","F","G","L","L","E","E","F","E","J","J","F"],["F","F","F","L","L","E","F","F","F","F","F","F"],["F","F","F","F","F","F","F","F","F","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
