// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "409",
  regions: [["D","D","D","F","F","F","F"],["D","E","E","E","F","F","F"],["D","E","E","B","C","F","F"],["A","E","B","B","C","B","F"],["A","E","E","B","B","B","F"],["E","E","E","B","B","B","B"],["E","G","G","B","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
