// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '41',
  regions: [
    ['D', 'D', 'D', 'D', 'F', 'F'],
    ['D', 'A', 'A', 'D', 'C', 'C'],
    ['A', 'A', 'E', 'D', 'D', 'C'],
    ['A', 'A', 'E', 'A', 'A', 'C'],
    ['A', 'A', 'A', 'A', 'A', 'A'],
    ['A', 'A', 'B', 'B', 'B', 'A']
  ],
  hasUniqueSolution: true
}

export default level
