// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "410",
  regions: [["D","E","E","E","E","E","E","E","E","E","B","B","B"],["D","D","E","K","K","K","K","E","E","E","E","B","B"],["E","D","D","E","E","E","K","E","B","E","B","B","B"],["E","D","M","M","E","E","E","E","B","E","E","E","B"],["E","E","E","E","E","I","I","I","B","B","B","E","B"],["E","E","E","A","E","I","I","L","B","B","E","E","B"],["E","L","E","A","E","A","A","L","B","B","B","B","B"],["E","L","A","A","A","A","L","L","L","L","H","B","H"],["E","L","L","L","L","A","A","J","J","L","B","B","H"],["E","E","L","L","L","L","A","A","L","L","L","B","B"],["L","L","L","C","L","L","L","L","L","L","L","L","B"],["L","L","L","C","C","F","F","L","G","G","B","B","B"],["L","L","L","L","L","L","F","L","L","B","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
