// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "411",
  regions: [["G","G","G","G","G","G","G","I","I","C"],["A","A","A","C","C","C","C","C","I","C"],["A","A","A","C","J","F","J","C","C","C"],["A","J","J","J","J","F","J","C","H","H"],["E","E","J","J","J","J","J","C","H","H"],["E","E","E","E","E","J","D","D","H","H"],["E","J","J","J","J","J","D","D","H","D"],["J","B","B","J","J","J","D","D","H","D"],["J","J","B","J","J","J","J","D","H","D"],["J","J","J","J","J","J","J","D","D","D"]],
  hasUniqueSolution: true,
}

export default level
