// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "412",
  regions: [["A","A","A","A","A","A","A","A","F"],["D","D","A","F","A","A","F","F","F"],["D","D","A","F","F","F","F","F","F"],["E","A","A","A","H","H","F","F","F"],["E","A","B","A","H","H","H","G","G"],["E","E","B","C","H","H","H","G","H"],["E","E","B","C","C","H","H","H","H"],["E","B","B","I","I","I","H","H","H"],["B","B","B","I","I","I","H","H","H"]],
  hasUniqueSolution: false,
}

export default level
