// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "413",
  regions: [["L","B","B","B","F","F","F","H","H","H","H","F","H"],["L","L","B","F","F","F","H","H","D","H","D","H","H"],["L","J","B","I","I","F","H","H","D","D","D","D","D"],["J","J","I","I","I","F","F","F","F","F","D","D","D"],["J","E","E","E","E","F","F","F","F","D","D","G","D"],["E","E","E","F","F","F","F","F","D","D","G","G","D"],["E","K","K","F","F","F","M","F","D","G","G","G","G"],["E","E","K","K","F","M","M","F","D","D","C","G","C"],["M","E","K","K","E","E","M","F","F","D","C","C","C"],["M","E","E","E","E","M","M","F","F","D","D","D","D"],["M","M","E","E","E","M","M","F","F","F","F","F","D"],["M","M","M","M","E","M","F","F","M","F","F","A","D"],["M","M","M","M","M","M","M","M","M","M","M","A","D"]],
  hasUniqueSolution: true,
}

export default level
