// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "414",
  regions: [["C","F","D","G","G","G","G","B","B"],["C","F","D","D","D","G","G","G","B"],["C","E","D","D","G","G","G","H","B"],["C","E","D","D","G","G","G","H","B"],["C","E","E","D","G","G","B","B","B"],["C","C","E","D","D","G","G","G","B"],["C","C","E","E","I","G","B","B","B"],["A","C","E","B","I","I","B","B","B"],["A","A","A","B","B","B","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
