// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "415",
  regions: [["B","B","C","C","D"],["B","B","C","C","D"],["A","A","E","E","D"],["A","A","E","E","D"],["A","A","D","D","D"]],
  hasUniqueSolution: false,
}

export default level
