// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "416",
  regions: [["E","E","E","E","E","R","R","R","R","R","R","R","R","R","R","R","R","R"],["E","E","K","K","K","K","K","K","K","R","R","R","R","G","G","G","F","R"],["E","E","E","K","E","E","K","K","H","R","I","R","G","G","G","F","F","F"],["A","A","E","E","E","E","E","K","H","I","I","R","G","G","M","F","F","F"],["A","A","A","K","K","K","E","K","K","I","G","G","G","G","M","F","F","F"],["A","A","A","A","K","K","K","K","K","I","I","G","G","O","O","F","G","F"],["A","A","D","D","K","K","K","K","K","I","I","I","G","O","G","F","G","F"],["A","A","A","A","K","K","I","K","I","I","I","I","G","G","G","F","G","F"],["I","I","A","A","K","K","I","I","I","K","I","I","G","C","G","G","G","G"],["I","A","A","N","N","K","K","K","K","K","I","C","C","C","C","C","C","G"],["I","I","A","I","I","I","I","I","K","I","I","C","C","C","C","C","G","G"],["I","I","I","I","I","I","L","I","I","I","L","C","C","C","L","C","G","C"],["I","I","I","B","I","I","L","L","L","L","L","C","C","C","L","C","C","C"],["I","I","P","B","I","L","L","L","L","Q","L","L","C","L","L","L","C","C"],["I","I","P","B","I","I","L","L","L","Q","L","L","C","L","C","C","C","C"],["I","B","B","B","B","B","J","L","L","Q","Q","L","L","L","L","L","C","C"],["I","I","J","B","J","J","J","Q","Q","Q","Q","L","C","C","L","L","C","C"],["I","I","J","J","J","J","Q","Q","Q","Q","C","C","C","C","C","C","C","C"]],
  hasUniqueSolution: true,
}

export default level
