// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "417",
  regions: [["B","B","B","B","B","D","D","G"],["B","B","B","B","B","B","G","G"],["H","H","B","G","G","G","G","F"],["A","A","G","G","C","C","G","F"],["A","A","A","G","E","E","E","F"],["E","A","E","E","E","F","F","F"],["F","A","E","E","F","F","F","F"],["E","E","E","E","F","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
