// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "418",
  regions: [["E","C","C","C","C","C","C","C"],["E","C","C","C","B","B","B","C"],["E","E","C","C","B","C","C","C"],["D","E","E","C","C","C","G","G"],["D","C","E","C","A","C","C","C"],["C","C","E","C","A","F","F","C"],["H","C","C","C","A","F","C","C"],["H","H","H","A","A","A","A","C"]],
  hasUniqueSolution: true,
}

export default level
