// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "419",
  regions: [["F","F","F","F","F","F","D","H","E","E","J","J","J","J"],["F","F","F","F","G","G","D","H","J","E","E","E","E","J"],["F","M","F","F","G","G","D","D","J","J","J","E","J","J"],["F","M","M","G","G","D","D","D","J","J","E","E","J","J"],["F","M","M","M","G","G","G","D","J","E","E","E","J","J"],["M","M","G","G","G","B","D","D","J","E","J","E","E","J"],["M","M","M","M","A","B","A","D","J","J","J","E","E","J"],["M","M","M","M","A","A","A","D","J","J","J","J","J","J"],["M","M","M","K","A","D","D","D","K","J","J","J","J","I"],["M","K","M","K","A","D","D","K","K","K","J","N","I","I"],["M","K","K","K","K","K","D","L","L","K","J","N","K","I"],["M","M","M","M","K","D","D","K","K","K","K","N","K","I"],["M","M","M","M","K","K","K","K","K","K","K","K","K","K"],["M","M","M","K","K","K","K","K","C","C","K","K","K","K"]],
  hasUniqueSolution: true,
}

export default level
