// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '42',
  regions: [
    ['D', 'D', 'D', 'D', 'C', 'C', 'B'],
    ['F', 'F', 'F', 'C', 'G', 'C', 'B'],
    ['F', 'G', 'G', 'B', 'B', 'B', 'B'],
    ['E', 'G', 'B', 'B', 'B', 'A', 'B'],
    ['E', 'G', 'G', 'B', 'B', 'A', 'B'],
    ['E', 'G', 'G', 'G', 'B', 'A', 'A'],
    ['E', 'E', 'A', 'A', 'A', 'A', 'A']
  ],
  hasUniqueSolution: true
}

export default level
