// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "420",
  regions: [["D","D","C","C","C"],["D","B","C","C","A"],["D","B","B","A","A"],["D","D","B","E","A"],["B","B","B","E","A"]],
  hasUniqueSolution: true,
}

export default level
