// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "421",
  regions: [["G","G","G","G","B","B","B","B","B","B","B"],["I","G","G","G","B","B","B","A","D","D","B"],["I","I","I","G","B","A","A","A","D","B","B"],["G","G","G","G","G","G","A","D","D","B","B"],["G","G","G","F","G","G","H","H","D","D","B"],["G","G","F","F","G","G","J","J","J","J","B"],["G","F","F","F","G","G","G","G","G","J","J"],["G","F","F","G","G","G","E","E","G","K","J"],["F","F","C","C","C","C","K","G","G","K","J"],["F","F","C","C","C","K","K","G","K","K","J"],["F","C","C","C","C","K","K","K","K","J","J"]],
  hasUniqueSolution: true,
}

export default level
