// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "422",
  regions: [["J","J","J","J","I","I","I","D","D","D"],["J","H","J","J","J","J","I","I","I","D"],["E","H","J","J","A","A","I","I","D","D"],["E","E","J","J","J","A","A","A","D","D"],["C","E","A","A","J","A","A","A","A","D"],["C","E","D","A","A","A","A","A","F","D"],["C","B","B","A","A","A","F","A","F","D"],["C","C","B","B","F","F","F","F","F","F"],["C","B","B","B","F","G","F","F","F","F"],["C","C","C","F","F","G","G","G","G","F"]],
  hasUniqueSolution: true,
}

export default level
