// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "423",
  regions: [["C","C","C","C","D"],["B","B","B","C","D"],["A","B","C","C","C"],["A","A","C","C","C"],["E","E","C","C","C"]],
  hasUniqueSolution: true,
}

export default level
