// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "424",
  regions: [["G","G","G","G","G","F","F","F"],["G","D","G","G","F","F","F","E"],["G","D","D","G","F","E","E","E"],["G","G","D","D","F","E","A","A"],["G","E","D","D","E","E","A","A"],["G","E","E","D","E","H","A","A"],["B","B","E","E","E","H","C","C"],["B","B","B","B","B","H","H","H"]],
  hasUniqueSolution: true,
}

export default level
