// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "425",
  regions: [["G","G","D","D","D","D","D","D","D","E"],["G","G","D","C","D","D","D","J","E","E"],["G","G","D","C","D","D","J","J","E","E"],["G","D","D","C","E","E","J","E","E","E"],["D","D","I","I","I","E","E","E","E","E"],["B","D","I","B","I","E","E","E","E","E"],["B","D","B","B","E","E","E","E","E","E"],["B","B","B","A","A","A","A","E","E","E"],["B","H","F","F","H","A","A","E","A","E"],["H","H","H","H","H","H","A","A","A","E"]],
  hasUniqueSolution: true,
}

export default level
