// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "426",
  regions: [["B","B","C","C","C"],["C","B","C","C","D"],["C","C","C","E","D"],["C","E","E","C","A"],["C","E","E","A","A"]],
  hasUniqueSolution: true,
}

export default level
