// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "427",
  regions: [["B","I","A","A","A","A","A","A","A"],["B","I","A","I","A","A","C","C","C"],["B","I","I","I","I","A","A","C","G"],["B","I","H","H","C","C","C","C","G"],["B","B","D","D","D","C","C","C","G"],["B","B","B","G","G","G","G","C","G"],["B","B","G","G","E","E","G","G","G"],["B","G","G","G","E","E","E","E","G"],["B","B","B","B","F","F","E","G","G"]],
  hasUniqueSolution: true,
}

export default level
