// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "428",
  regions: [["C","C","J","J","J","J","J","J","H","H","B","B","B","B","B","B"],["C","C","C","J","J","J","J","H","H","H","H","H","H","H","B","B"],["C","C","C","C","J","H","J","J","H","J","H","H","O","H","B","B"],["C","A","C","J","J","H","H","J","J","J","H","O","O","B","B","B"],["C","A","P","P","J","P","H","H","H","H","H","H","B","B","B","B"],["C","C","P","P","P","P","H","G","F","F","F","F","F","B","B","B"],["C","C","C","P","P","P","N","G","F","N","F","F","B","B","N","B"],["C","P","P","P","P","P","N","N","F","N","N","F","F","F","N","N"],["C","C","C","P","P","P","P","N","N","N","F","F","N","F","N","N"],["P","P","P","P","N","N","P","N","N","N","N","N","N","N","N","K"],["P","P","P","N","N","N","N","N","N","N","N","M","N","N","K","K"],["P","P","P","N","N","N","N","N","N","M","M","M","N","N","N","K"],["P","P","P","P","N","M","M","N","N","M","M","M","N","I","K","K"],["P","P","P","P","N","N","M","M","M","M","M","I","I","I","K","D"],["P","P","L","L","M","M","M","M","I","M","M","I","K","K","K","D"],["P","P","P","L","L","M","I","I","I","I","I","I","E","E","E","D"]],
  hasUniqueSolution: true,
}

export default level
