// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "429",
  regions: [["F","F","F","F","F","F","F","F","F","F"],["F","I","F","F","A","F","F","F","H","F"],["F","I","I","A","A","F","B","B","H","F"],["F","I","I","G","G","F","B","B","B","F"],["I","I","I","G","G","B","B","C","C","E"],["I","G","I","G","G","B","B","J","J","E"],["I","G","G","G","G","G","B","J","J","J"],["I","G","G","D","B","B","B","J","J","J"],["D","D","D","D","B","B","J","J","J","J"],["D","D","D","D","B","B","B","J","J","J"]],
  hasUniqueSolution: true,
}

export default level
