// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '43',
  regions: [
    ['F', 'F', 'I', 'I', 'I', 'I', 'I', 'I', 'I'],
    ['F', 'E', 'E', 'E', 'E', 'E', 'G', 'C', 'I'],
    ['B', 'B', 'E', 'D', 'D', 'D', 'G', 'A', 'I'],
    ['B', 'D', 'E', 'E', 'D', 'D', 'C', 'C', 'I'],
    ['B', 'D', 'D', 'D', 'D', 'I', 'I', 'I', 'I'],
    ['B', 'D', 'D', 'A', 'D', 'A', 'A', 'I', 'I'],
    ['B', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'I'],
    ['A', 'A', 'A', 'A', 'A', 'I', 'I', 'I', 'I'],
    ['H', 'H', 'H', 'H', 'A', 'A', 'I', 'I', 'I']
  ],
  hasUniqueSolution: true
}

export default level
