// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "430",
  regions: [["H","H","H","C","A","A","A","D"],["E","H","H","C","C","A","D","D"],["E","H","E","E","A","A","A","A"],["E","E","E","E","E","B","B","A"],["G","E","E","E","E","B","A","A"],["G","E","E","E","B","B","A","F"],["G","G","G","E","E","B","B","F"],["G","G","G","G","E","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
