// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "431",
  regions: [["K","K","K","K","K","K","K","K","K","O","O","E","E","E","E"],["K","K","K","K","H","H","K","K","K","K","O","E","E","E","E"],["A","A","K","M","H","H","H","H","H","K","O","O","O","O","E"],["A","A","A","M","H","M","H","M","H","H","O","G","O","E","E"],["A","M","M","M","M","M","M","M","M","H","H","G","O","O","E"],["A","A","M","M","M","M","M","H","H","H","G","G","G","O","E"],["A","A","M","M","N","G","G","G","G","G","G","G","D","E","E"],["A","A","J","J","N","N","G","L","G","G","L","L","D","I","C"],["A","J","J","N","N","N","L","L","L","L","L","L","L","I","C"],["A","J","J","N","N","N","N","N","L","L","L","F","C","C","C"],["A","A","J","J","J","J","J","N","N","N","L","F","F","F","C"],["J","A","A","J","J","J","J","J","N","L","L","F","F","F","C"],["J","J","J","J","N","N","N","N","N","B","F","F","F","B","C"],["J","J","J","N","N","N","B","N","B","B","F","B","B","B","C"],["J","J","N","N","B","B","B","B","B","B","B","B","C","C","C"]],
  hasUniqueSolution: true,
}

export default level
