// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "432",
  regions: [["C","C","C","C","C"],["C","C","C","A","A"],["D","A","A","A","A"],["D","B","A","E","A"],["B","B","B","E","E"]],
  hasUniqueSolution: true,
}

export default level
