// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "433",
  regions: [["D","D","D","D","D","J","J","J","J","J","J"],["D","F","D","C","J","J","J","H","H","E","J"],["D","F","F","C","J","E","E","E","E","E","J"],["D","D","F","J","J","I","I","I","J","E","E"],["D","F","F","F","J","I","J","B","J","J","E"],["D","F","D","F","J","I","I","I","J","J","E"],["D","D","D","F","J","J","J","J","J","J","J"],["D","B","B","F","F","J","B","J","J","J","A"],["D","G","B","B","F","B","B","B","B","J","A"],["D","G","B","B","F","F","B","B","B","A","A"],["D","D","B","B","B","B","B","B","K","K","K"]],
  hasUniqueSolution: true,
}

export default level
