// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "434",
  regions: [["F","H","I","I","I","I","I","I","C","G"],["F","H","I","I","E","E","E","E","C","G"],["F","H","I","I","I","A","A","E","E","G"],["F","H","H","A","A","A","A","A","E","G"],["F","H","A","A","A","G","G","G","E","G"],["F","J","G","G","A","A","G","G","G","G"],["F","J","G","G","G","G","G","G","G","G"],["F","F","F","G","D","G","G","B","B","G"],["F","F","F","F","D","G","G","D","B","D"],["F","D","B","D","D","D","D","D","D","D"]],
  hasUniqueSolution: true,
}

export default level
