// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "435",
  regions: [["I","I","J","J","J","B","B","B","B","B","B","B"],["I","I","J","J","B","B","G","B","K","K","B","L"],["I","I","A","B","B","G","G","B","B","L","L","L"],["I","I","A","A","G","G","G","G","B","L","L","L"],["I","I","I","A","G","G","G","L","L","L","L","L"],["I","I","I","I","I","I","G","L","L","L","L","G"],["I","D","D","D","D","D","G","L","G","L","L","G"],["I","I","I","E","E","G","G","G","G","G","G","G"],["I","F","E","E","E","E","H","H","G","G","G","G"],["I","F","F","F","F","E","E","G","G","G","C","C"],["I","I","I","I","I","E","G","G","G","G","G","C"],["I","I","I","I","I","I","I","I","I","G","G","G"]],
  hasUniqueSolution: true,
}

export default level
