// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "436",
  regions: [["H","H","H","H","H","I","I","I","I","I","I","I","I","I","I","I"],["H","C","I","I","I","I","P","I","J","J","I","J","F","F","F","I"],["H","C","I","J","J","I","P","I","J","J","J","J","F","F","I","I"],["H","C","C","C","J","I","I","I","J","A","J","F","F","F","F","I"],["H","C","C","J","J","I","J","J","J","A","J","J","A","G","F","I"],["K","K","C","C","J","J","J","C","J","A","J","J","A","G","F","L"],["K","C","C","D","D","D","C","C","J","A","A","A","A","L","L","L"],["K","K","C","C","C","C","C","J","J","J","A","J","A","A","A","L"],["M","K","C","J","J","J","C","J","J","J","J","J","A","A","A","L"],["M","K","C","C","J","J","J","J","J","A","J","J","J","J","A","L"],["O","C","C","C","C","J","J","J","J","A","A","A","J","J","A","L"],["O","E","E","E","J","J","N","N","J","A","A","A","A","A","A","L"],["O","O","E","E","J","J","J","N","J","J","J","N","N","N","N","L"],["O","O","N","E","E","J","N","N","N","J","J","J","J","N","L","L"],["O","O","O","E","J","J","J","J","N","N","N","N","N","N","L","B"],["O","J","J","J","J","J","J","J","J","J","J","J","N","N","N","B"]],
  hasUniqueSolution: true,
}

export default level
