// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "437",
  regions: [["D","D","D","D","D","D","D","D","D","D"],["H","H","D","D","D","D","B","B","B","D"],["H","H","H","D","A","D","G","G","B","G"],["H","D","D","D","A","D","G","G","G","G"],["H","H","J","D","A","D","F","G","F","G"],["H","H","J","J","A","A","F","F","F","G"],["H","H","J","J","C","A","F","G","G","G"],["J","J","J","I","C","F","F","G","F","F"],["E","J","I","I","C","I","F","F","F","F"],["E","E","I","I","I","I","I","I","I","F"]],
  hasUniqueSolution: true,
}

export default level
