// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "438",
  regions: [["C","A","A","E","E","E"],["C","A","F","E","E","E"],["C","A","F","E","A","E"],["D","F","F","F","E","F"],["D","D","F","F","F","F"],["D","B","B","B","F","F"]],
  hasUniqueSolution: true,
}

export default level
