// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "439",
  regions: [["M","M","M","M","M","E","E","E","G","G","G","G","G"],["M","M","M","M","M","M","M","E","E","J","A","A","G"],["M","M","M","J","J","J","M","J","E","J","J","A","G"],["F","M","J","J","J","J","J","J","J","J","J","G","G"],["F","M","M","J","D","D","J","L","J","J","B","C","C"],["M","M","M","M","D","D","J","L","L","L","B","B","C"],["M","M","D","M","D","D","D","D","B","B","B","B","C"],["H","H","D","D","D","C","C","D","C","C","B","B","C"],["H","D","D","D","D","C","C","C","C","C","B","C","C"],["H","K","K","D","K","K","C","C","I","C","B","C","C"],["H","K","K","D","K","C","C","K","I","C","C","C","C"],["H","K","K","K","K","K","K","K","K","K","C","C","C"],["H","K","K","K","K","K","K","K","C","C","C","C","C"]],
  hasUniqueSolution: true,
}

export default level
