// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '44',
  regions: [
    ['G', 'G', 'G', 'G', 'G', 'G', 'G'],
    ['C', 'B', 'B', 'B', 'G', 'D', 'G'],
    ['C', 'C', 'B', 'B', 'E', 'D', 'D'],
    ['A', 'C', 'B', 'B', 'E', 'B', 'D'],
    ['A', 'D', 'B', 'B', 'B', 'B', 'D'],
    ['F', 'F', 'B', 'B', 'D', 'B', 'D'],
    ['F', 'F', 'F', 'D', 'D', 'D', 'D']
  ],
  hasUniqueSolution: true
}

export default level
