// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '44',
  regions: [
    ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
    ['C', 'B', 'B', 'B', 'A', 'F', 'A'],
    ['C', 'C', 'B', 'B', 'D', 'F', 'F'],
    ['E', 'C', 'B', 'B', 'D', 'B', 'F'],
    ['E', 'F', 'B', 'B', 'B', 'B', 'F'],
    ['G', 'G', 'B', 'B', 'F', 'B', 'F'],
    ['G', 'G', 'G', 'F', 'F', 'F', 'F']
  ],
  hasUniqueSolution: true
}

export default level
