// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "440",
  regions: [["C","B","B","B","B","B","E"],["C","C","B","B","A","A","E"],["F","F","A","A","A","E","E"],["F","D","E","E","E","E","E"],["F","D","D","G","E","E","E"],["D","D","G","G","E","E","E"],["D","G","G","G","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
