// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "441",
  regions: [["I","I","I","I","I","I","H","H","H","H","O","O","O","O","O"],["I","G","I","I","G","I","I","I","H","H","O","O","O","O","O"],["G","G","G","G","G","G","G","I","H","H","O","K","K","K","O"],["C","C","G","G","M","G","G","O","O","H","O","K","K","O","O"],["G","G","G","G","M","F","O","O","O","O","O","K","K","K","O"],["E","E","E","E","E","F","O","O","B","B","O","B","K","K","K"],["E","E","E","F","F","F","O","B","B","B","B","B","D","N","N"],["E","F","F","F","F","O","O","O","B","B","B","D","D","N","N"],["E","E","B","B","B","O","O","O","O","B","B","D","D","N","N"],["L","E","L","B","O","O","B","O","B","B","B","D","D","D","N"],["L","L","L","B","B","O","B","O","B","B","B","D","D","A","A"],["L","L","L","L","B","B","B","B","B","B","B","B","D","D","A"],["L","L","B","L","L","L","B","B","B","B","B","B","D","D","D"],["L","L","B","B","B","B","B","J","J","J","J","J","J","J","D"],["L","B","B","B","J","J","J","J","J","J","J","J","J","D","D"]],
  hasUniqueSolution: true,
}

export default level
