// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "442",
  regions: [["C","C","E","G","G","G","G","G","G"],["C","D","E","E","E","I","I","I","G"],["D","D","D","D","D","I","F","F","G"],["D","A","A","F","F","F","F","F","G"],["D","A","A","A","A","F","F","F","F"],["D","A","A","F","F","F","B","B","F"],["H","A","A","A","F","B","B","B","F"],["H","A","H","A","F","F","B","B","F"],["H","H","H","F","F","F","F","B","F"]],
  hasUniqueSolution: true,
}

export default level
