// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "443",
  regions: [["A","A","A","A","C","C","F","D"],["A","A","A","A","C","C","F","D"],["H","H","A","C","C","C","C","D"],["H","A","A","E","C","C","C","D"],["H","H","A","E","E","E","C","E"],["A","G","A","A","E","E","E","E"],["A","G","A","A","A","A","A","E"],["A","A","A","A","A","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
