// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "444",
  regions: [["C","C","C","C","C","C","C"],["C","C","C","A","D","D","C"],["C","F","G","A","A","D","C"],["C","F","G","E","E","E","E"],["F","F","B","B","B","B","E"],["B","B","B","B","E","E","E"],["B","B","B","E","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
