// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "445",
  regions: [["K","K","H","H","H","H","H","H","H","F","F","F"],["K","K","H","H","H","H","L","I","I","I","I","F"],["H","H","H","H","H","I","L","L","I","J","F","F"],["H","C","H","H","I","I","I","I","I","J","F","F"],["C","C","C","H","I","I","F","F","F","F","F","G"],["C","C","C","H","H","H","F","H","H","H","H","G"],["C","H","H","H","H","H","H","H","H","H","H","G"],["C","C","H","H","C","C","C","H","E","E","E","G"],["C","C","H","C","C","A","A","H","E","G","G","G"],["C","C","C","C","C","C","H","H","E","E","B","B"],["D","C","D","D","C","C","C","H","H","E","E","E"],["D","D","D","C","C","H","H","H","H","H","E","E"]],
  hasUniqueSolution: true,
}

export default level
