// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "446",
  regions: [["I","C","C","H","H","J","E","E","E","E"],["I","C","C","H","D","H","H","E","E","A"],["C","C","H","H","D","H","J","E","E","A"],["C","B","B","H","H","J","J","E","A","A"],["C","B","B","G","G","J","F","E","A","A"],["C","B","B","F","J","J","F","A","A","F"],["C","B","F","F","J","J","F","A","F","F"],["C","B","B","F","J","J","F","F","F","F"],["C","B","B","F","F","J","F","F","F","F"],["C","C","F","F","F","F","F","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
