// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "447",
  regions: [["G","G","G","G","G","G","G","G"],["G","B","G","G","F","G","G","F"],["G","B","B","F","F","F","F","F"],["B","B","F","F","H","H","E","F"],["D","B","B","F","H","F","E","F"],["D","D","F","F","H","F","F","F"],["D","A","F","F","F","F","F","F"],["A","A","A","C","C","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
