// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "448",
  regions: [["B","G","A","A","A","A","A","A","I"],["B","A","A","H","F","F","F","I","I"],["B","A","H","H","H","F","F","I","I"],["B","A","A","H","H","F","I","I","I"],["A","A","A","A","F","F","I","I","I"],["A","E","E","D","F","F","I","I","I"],["A","A","A","D","F","F","F","I","I"],["A","F","F","F","F","C","F","F","I"],["A","G","G","G","F","C","C","I","I"]],
  hasUniqueSolution: true,
}

export default level
