// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "449",
  regions: [["G","G","G","G","G","C","C","C"],["G","G","G","G","H","C","C","C"],["G","G","G","B","H","C","C","C"],["G","B","B","B","H","H","C","C"],["E","B","B","A","H","H","H","H"],["E","A","A","A","D","D","H","H"],["F","F","A","A","D","D","H","D"],["F","F","F","A","A","D","D","D"]],
  hasUniqueSolution: true,
}

export default level
