// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '45',
  regions: [
    ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'D', 'D'],
    ['F', 'H', 'F', 'H', 'H', 'F', 'E', 'E', 'E', 'E'],
    ['F', 'H', 'H', 'H', 'F', 'F', 'J', 'J', 'J', 'E'],
    ['F', 'H', 'H', 'H', 'F', 'F', 'F', 'J', 'E', 'E'],
    ['F', 'F', 'H', 'H', 'F', 'G', 'F', 'J', 'J', 'J'],
    ['H', 'F', 'H', 'C', 'C', 'G', 'F', 'J', 'B', 'B'],
    ['H', 'H', 'H', 'H', 'I', 'G', 'F', 'J', 'J', 'B'],
    ['H', 'H', 'H', 'I', 'I', 'A', 'A', 'A', 'J', 'J'],
    ['H', 'H', 'I', 'I', 'A', 'A', 'J', 'J', 'J', 'J'],
    ['H', 'H', 'I', 'J', 'J', 'J', 'J', 'J', 'J', 'J']
  ],
  hasUniqueSolution: true
}

export default level
