// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '45',
  regions: [
    ['C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'A', 'A'],
    ['C', 'H', 'C', 'H', 'H', 'C', 'B', 'B', 'B', 'B'],
    ['C', 'H', 'H', 'H', 'C', 'C', 'D', 'D', 'D', 'B'],
    ['C', 'H', 'H', 'H', 'C', 'C', 'C', 'D', 'B', 'B'],
    ['C', 'C', 'H', 'H', 'C', 'E', 'C', 'D', 'D', 'D'],
    ['H', 'C', 'H', 'F', 'F', 'E', 'C', 'D', 'G', 'G'],
    ['H', 'H', 'H', 'H', 'J', 'E', 'C', 'D', 'D', 'G'],
    ['H', 'H', 'H', 'J', 'J', 'I', 'I', 'I', 'D', 'D'],
    ['H', 'H', 'J', 'J', 'I', 'I', 'D', 'D', 'D', 'D'],
    ['H', 'H', 'J', 'D', 'D', 'D', 'D', 'D', 'D', 'D']
  ],
  hasUniqueSolution: true
}

export default level
