// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "450",
  regions: [["I","I","I","A","A","A","G","G","G"],["I","I","A","A","B","B","G","B","G"],["I","H","H","A","B","B","G","B","G"],["B","C","H","C","B","B","B","B","G"],["B","C","H","C","B","B","G","G","G"],["B","C","C","C","C","B","D","D","E"],["B","C","F","B","C","B","B","D","E"],["B","B","F","B","B","B","B","B","E"],["B","B","B","B","B","B","B","E","E"]],
  hasUniqueSolution: true,
}

export default level
