// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "451",
  regions: [["C","B","F","F","F","F","F","F","F","F"],["C","B","B","B","F","F","F","F","F","J"],["C","C","E","E","E","E","E","E","E","J"],["C","C","E","E","E","E","E","E","J","J"],["E","E","E","D","D","D","A","J","J","H"],["D","D","D","D","A","A","A","J","J","H"],["I","D","I","A","A","A","A","A","J","H"],["I","I","I","A","A","A","A","A","H","H"],["I","I","I","A","A","A","G","G","H","H"],["I","I","I","I","I","G","G","G","H","H"]],
  hasUniqueSolution: false,
}

export default level
