// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "452",
  regions: [["D","D","D","D","D","D","D","D","D"],["D","D","D","D","D","G","G","G","H"],["D","D","D","D","D","G","H","H","H"],["D","B","B","D","G","G","G","G","H"],["D","B","D","D","G","F","A","G","H"],["D","G","G","G","G","F","A","A","H"],["D","C","G","I","G","A","A","A","A"],["D","C","C","I","I","I","I","I","A"],["D","D","C","E","E","E","I","I","I"]],
  hasUniqueSolution: true,
}

export default level
