// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "46",
  regions: [["C","E","E","E","E","E","E","A","A","A","A"],["C","E","D","B","B","D","E","E","A","A","E"],["C","C","D","D","D","D","E","A","A","E","E"],["C","G","D","D","D","D","E","E","A","E","E"],["C","G","G","G","G","G","E","E","E","E","E"],["C","C","G","G","G","G","E","F","F","E","E"],["I","I","G","G","G","G","G","F","J","J","J"],["I","I","I","H","H","F","G","F","F","F","J"],["K","K","I","I","F","F","F","F","J","J","J"],["K","F","F","I","I","F","J","J","J","F","J"],["K","F","F","F","F","F","F","F","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
