// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '46',
  regions: [
    ['J', 'A', 'A', 'A', 'A', 'A', 'A', 'F', 'F', 'F', 'F'],
    ['J', 'A', 'B', 'D', 'D', 'B', 'A', 'A', 'F', 'F', 'A'],
    ['J', 'J', 'B', 'B', 'B', 'B', 'A', 'F', 'F', 'A', 'A'],
    ['J', 'E', 'B', 'B', 'B', 'B', 'A', 'A', 'F', 'A', 'A'],
    ['J', 'E', 'E', 'E', 'E', 'E', 'A', 'A', 'A', 'A', 'A'],
    ['J', 'J', 'E', 'E', 'E', 'E', 'A', 'H', 'H', 'A', 'A'],
    ['C', 'C', 'E', 'E', 'E', 'E', 'E', 'H', 'K', 'K', 'K'],
    ['C', 'C', 'C', 'I', 'I', 'H', 'E', 'H', 'H', 'H', 'K'],
    ['G', 'G', 'C', 'C', 'H', 'H', 'H', 'H', 'K', 'K', 'K'],
    ['G', 'H', 'H', 'C', 'C', 'H', 'K', 'K', 'K', 'H', 'K'],
    ['G', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
  ],
  hasUniqueSolution: true
}

export default level
