// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "47",
  regions: [["B","B","F","F","A","A","A","D","E","E","E","C"],["B","F","F","F","A","F","D","D","D","E","C","C"],["F","F","F","F","F","F","D","D","D","E","E","C"],["F","F","F","H","F","H","H","H","D","D","E","E"],["F","F","H","H","F","H","H","H","H","G","E","K"],["F","F","F","H","F","H","H","H","G","G","K","K"],["F","F","H","H","H","H","H","G","G","G","G","K"],["F","H","H","H","I","H","H","H","H","G","G","K"],["I","I","H","I","I","I","I","I","H","G","G","K"],["I","I","H","I","J","J","I","I","H","K","G","K"],["I","I","H","I","J","L","I","I","I","K","G","K"],["I","I","I","I","J","L","I","K","K","K","K","K"]],
  hasUniqueSolution: true,
}

export default level
