// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '47',
  regions: [
    ['I', 'I', 'K', 'K', 'E', 'E', 'E', 'L', 'G', 'G', 'G', 'F'],
    ['I', 'K', 'K', 'K', 'E', 'K', 'L', 'L', 'L', 'G', 'F', 'F'],
    ['K', 'K', 'K', 'K', 'K', 'K', 'L', 'L', 'L', 'G', 'G', 'F'],
    ['K', 'K', 'K', 'H', 'K', 'H', 'H', 'H', 'L', 'L', 'G', 'G'],
    ['K', 'K', 'H', 'H', 'K', 'H', 'H', 'H', 'H', 'D', 'G', 'A'],
    ['K', 'K', 'K', 'H', 'K', 'H', 'H', 'H', 'D', 'D', 'A', 'A'],
    ['K', 'K', 'H', 'H', 'H', 'H', 'H', 'D', 'D', 'D', 'D', 'A'],
    ['K', 'H', 'H', 'H', 'B', 'H', 'H', 'H', 'H', 'D', 'D', 'A'],
    ['B', 'B', 'H', 'B', 'B', 'B', 'B', 'B', 'H', 'D', 'D', 'A'],
    ['B', 'B', 'H', 'B', 'J', 'J', 'B', 'B', 'H', 'A', 'D', 'A'],
    ['B', 'B', 'H', 'B', 'J', 'C', 'B', 'B', 'B', 'A', 'D', 'A'],
    ['B', 'B', 'B', 'B', 'J', 'C', 'B', 'A', 'A', 'A', 'A', 'A']
  ],
  hasUniqueSolution: true
}

export default level
