// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '48',
  regions: [
    ['B', 'B', 'B', 'B', 'B', 'B', 'C', 'C', 'A', 'A', 'A', 'A', 'A'],
    ['B', 'D', 'D', 'B', 'B', 'B', 'C', 'C', 'C', 'A', 'A', 'A', 'A'],
    ['B', 'D', 'D', 'C', 'C', 'B', 'C', 'C', 'A', 'A', 'A', 'A', 'A'],
    ['D', 'D', 'D', 'C', 'C', 'C', 'C', 'C', 'C', 'A', 'A', 'A', 'A'],
    ['D', 'D', 'D', 'D', 'D', 'D', 'E', 'C', 'A', 'A', 'F', 'F', 'A'],
    ['D', 'E', 'E', 'E', 'E', 'D', 'E', 'C', 'C', 'A', 'F', 'F', 'F'],
    ['D', 'D', 'G', 'E', 'E', 'D', 'E', 'E', 'E', 'E', 'F', 'F', 'F'],
    ['G', 'G', 'G', 'E', 'E', 'E', 'E', 'H', 'E', 'E', 'E', 'F', 'F'],
    ['G', 'I', 'I', 'H', 'E', 'E', 'E', 'H', 'H', 'H', 'E', 'J', 'F'],
    ['G', 'G', 'I', 'H', 'H', 'H', 'H', 'H', 'H', 'J', 'J', 'J', 'F'],
    ['G', 'I', 'I', 'I', 'K', 'H', 'H', 'H', 'H', 'L', 'J', 'J', 'J'],
    ['G', 'I', 'G', 'I', 'K', 'H', 'J', 'H', 'H', 'L', 'J', 'M', 'J'],
    ['G', 'G', 'G', 'G', 'G', 'G', 'J', 'J', 'J', 'J', 'J', 'M', 'J']
  ],
  hasUniqueSolution: true
}

export default level
