// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '48',
  regions: [
    ['M', 'M', 'M', 'M', 'M', 'M', 'G', 'G', 'I', 'I', 'I', 'I', 'I'],
    ['M', 'L', 'L', 'M', 'M', 'M', 'G', 'G', 'G', 'I', 'I', 'I', 'I'],
    ['M', 'L', 'L', 'G', 'G', 'M', 'G', 'G', 'I', 'I', 'I', 'I', 'I'],
    ['L', 'L', 'L', 'G', 'G', 'G', 'G', 'G', 'G', 'I', 'I', 'I', 'I'],
    ['L', 'L', 'L', 'L', 'L', 'L', 'A', 'G', 'I', 'I', 'C', 'C', 'I'],
    ['L', 'A', 'A', 'A', 'A', 'L', 'A', 'G', 'G', 'I', 'C', 'C', 'C'],
    ['L', 'L', 'F', 'A', 'A', 'L', 'A', 'A', 'A', 'A', 'C', 'C', 'C'],
    ['F', 'F', 'F', 'A', 'A', 'A', 'A', 'B', 'A', 'A', 'A', 'C', 'C'],
    ['F', 'H', 'H', 'B', 'A', 'A', 'A', 'B', 'B', 'B', 'A', 'J', 'C'],
    ['F', 'F', 'H', 'B', 'B', 'B', 'B', 'B', 'B', 'J', 'J', 'J', 'C'],
    ['F', 'H', 'H', 'H', 'E', 'B', 'B', 'B', 'B', 'K', 'J', 'J', 'J'],
    ['F', 'H', 'F', 'H', 'E', 'B', 'J', 'B', 'B', 'K', 'J', 'D', 'J'],
    ['F', 'F', 'F', 'F', 'F', 'F', 'J', 'J', 'J', 'J', 'J', 'D', 'J']
  ],
  hasUniqueSolution: true
}

export default level
