// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '49',
  regions: [
    ['K', 'K', 'K', 'K', 'K', 'B', 'B', 'B', 'B', 'J', 'J'],
    ['K', 'K', 'K', 'G', 'B', 'B', 'J', 'B', 'J', 'J', 'J'],
    ['K', 'K', 'K', 'G', 'J', 'J', 'J', 'B', 'J', 'E', 'J'],
    ['K', 'K', 'K', 'G', 'A', 'A', 'J', 'J', 'J', 'E', 'E'],
    ['K', 'K', 'K', 'K', 'K', 'D', 'J', 'D', 'J', 'D', 'D'],
    ['D', 'D', 'D', 'K', 'K', 'D', 'D', 'D', 'D', 'D', 'D'],
    ['D', 'D', 'D', 'D', 'D', 'D', 'D', 'H', 'D', 'D', 'D'],
    ['D', 'D', 'D', 'H', 'D', 'H', 'D', 'H', 'D', 'D', 'D'],
    ['F', 'F', 'F', 'H', 'H', 'H', 'D', 'H', 'H', 'H', 'D'],
    ['F', 'I', 'I', 'H', 'H', 'H', 'H', 'H', 'D', 'D', 'D'],
    ['F', 'I', 'H', 'H', 'H', 'H', 'H', 'H', 'D', 'C', 'C']
  ],
  hasUniqueSolution: true
}

export default level
