// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '5',
  regions: [
    ['D', 'D', 'D', 'D', 'A', 'A', 'B', 'B', 'B', 'B'],
    ['D', 'B', 'B', 'D', 'D', 'A', 'A', 'A', 'H', 'B'],
    ['D', 'D', 'B', 'D', 'D', 'C', 'C', 'A', 'A', 'B'],
    ['F', 'D', 'B', 'B', 'D', 'A', 'A', 'A', 'E', 'B'],
    ['F', 'J', 'B', 'B', 'B', 'B', 'B', 'B', 'E', 'B'],
    ['F', 'J', 'G', 'B', 'B', 'B', 'B', 'B', 'B', 'B'],
    ['J', 'J', 'G', 'G', 'G', 'G', 'B', 'B', 'B', 'B'],
    ['J', 'J', 'J', 'G', 'G', 'I', 'B', 'H', 'H', 'H'],
    ['J', 'J', 'J', 'J', 'G', 'I', 'B', 'B', 'G', 'G'],
    ['J', 'J', 'J', 'G', 'G', 'G', 'G', 'G', 'G', 'G']
  ],
  hasUniqueSolution: true
}

export default level
