// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '5',
  regions: [
    ['C', 'C', 'C', 'C', 'B', 'B', 'F', 'F', 'F', 'F'],
    ['C', 'F', 'F', 'C', 'C', 'B', 'B', 'B', 'E', 'F'],
    ['C', 'C', 'F', 'C', 'C', 'A', 'A', 'B', 'B', 'F'],
    ['G', 'C', 'F', 'F', 'C', 'B', 'B', 'B', 'J', 'F'],
    ['G', 'D', 'F', 'F', 'F', 'F', 'F', 'F', 'J', 'F'],
    ['G', 'D', 'I', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
    ['D', 'D', 'I', 'I', 'I', 'I', 'F', 'F', 'F', 'F'],
    ['D', 'D', 'D', 'I', 'I', 'H', 'F', 'E', 'E', 'E'],
    ['D', 'D', 'D', 'D', 'I', 'H', 'F', 'F', 'I', 'I'],
    ['D', 'D', 'D', 'I', 'I', 'I', 'I', 'I', 'I', 'I']
  ],
  hasUniqueSolution: true
}

export default level
