// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '50',
  regions: [
    ['C', 'C', 'C', 'C', 'C', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'A'],
    ['C', 'K', 'C', 'C', 'C', 'B', 'B', 'I', 'I', 'I', 'B', 'B', 'M', 'L', 'L', 'L', 'A'],
    ['C', 'K', 'K', 'I', 'I', 'I', 'B', 'I', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'M', 'M'],
    ['C', 'C', 'K', 'K', 'K', 'I', 'I', 'I', 'B', 'I', 'I', 'B', 'M', 'M', 'M', 'F', 'F'],
    ['C', 'O', 'O', 'K', 'K', 'K', 'K', 'I', 'I', 'I', 'I', 'M', 'M', 'M', 'M', 'M', 'F'],
    ['C', 'K', 'K', 'K', 'K', 'K', 'E', 'E', 'I', 'I', 'M', 'M', 'F', 'M', 'F', 'M', 'F'],
    ['C', 'K', 'C', 'C', 'C', 'K', 'E', 'I', 'I', 'M', 'M', 'F', 'F', 'F', 'F', 'F', 'F'],
    ['C', 'C', 'C', 'E', 'E', 'E', 'E', 'I', 'I', 'E', 'M', 'M', 'M', 'F', 'F', 'F', 'F'],
    ['H', 'H', 'C', 'C', 'E', 'E', 'E', 'I', 'I', 'E', 'N', 'N', 'M', 'M', 'M', 'F', 'F'],
    ['E', 'E', 'E', 'E', 'E', 'E', 'I', 'I', 'I', 'E', 'N', 'E', 'F', 'F', 'F', 'F', 'F'],
    ['E', 'E', 'E', 'D', 'E', 'I', 'I', 'E', 'I', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'F'],
    ['D', 'D', 'D', 'D', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'F', 'E', 'E', 'F', 'E', 'F'],
    ['D', 'P', 'P', 'D', 'D', 'E', 'F', 'F', 'E', 'E', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
    ['D', 'D', 'P', 'D', 'G', 'G', 'F', 'F', 'E', 'E', 'E', 'E', 'F', 'F', 'J', 'F', 'F'],
    ['D', 'P', 'P', 'D', 'D', 'G', 'G', 'F', 'F', 'F', 'Q', 'Q', 'F', 'F', 'J', 'F', 'F'],
    ['D', 'D', 'D', 'D', 'G', 'G', 'G', 'J', 'J', 'F', 'F', 'F', 'F', 'J', 'J', 'J', 'F'],
    ['D', 'D', 'D', 'J', 'J', 'J', 'J', 'J', 'J', 'J', 'J', 'J', 'J', 'J', 'F', 'F', 'F']
  ],
  hasUniqueSolution: true
}

export default level
