// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '50',
  regions: [
    ['G', 'G', 'G', 'G', 'G', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'A'],
    ['G', 'F', 'G', 'G', 'G', 'D', 'D', 'H', 'H', 'H', 'D', 'D', 'C', 'B', 'B', 'B', 'A'],
    ['G', 'F', 'F', 'H', 'H', 'H', 'D', 'H', 'D', 'D', 'D', 'D', 'C', 'C', 'C', 'C', 'C'],
    ['G', 'G', 'F', 'F', 'F', 'H', 'H', 'H', 'D', 'H', 'H', 'D', 'C', 'C', 'C', 'L', 'L'],
    ['G', 'E', 'E', 'F', 'F', 'F', 'F', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'L'],
    ['G', 'F', 'F', 'F', 'F', 'F', 'K', 'K', 'H', 'H', 'C', 'C', 'L', 'C', 'L', 'C', 'L'],
    ['G', 'F', 'G', 'G', 'G', 'F', 'K', 'H', 'H', 'C', 'C', 'L', 'L', 'L', 'L', 'L', 'L'],
    ['G', 'G', 'G', 'K', 'K', 'K', 'K', 'H', 'H', 'K', 'C', 'C', 'C', 'L', 'L', 'L', 'L'],
    ['I', 'I', 'G', 'G', 'K', 'K', 'K', 'H', 'H', 'K', 'J', 'J', 'C', 'C', 'C', 'L', 'L'],
    ['K', 'K', 'K', 'K', 'K', 'K', 'H', 'H', 'H', 'K', 'J', 'K', 'L', 'L', 'L', 'L', 'L'],
    ['K', 'K', 'K', 'M', 'K', 'H', 'H', 'K', 'H', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'L'],
    ['M', 'M', 'M', 'M', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'L', 'K', 'K', 'L', 'K', 'L'],
    ['M', 'N', 'N', 'M', 'M', 'K', 'L', 'L', 'K', 'K', 'L', 'L', 'L', 'L', 'L', 'L', 'L'],
    ['M', 'M', 'N', 'M', 'P', 'P', 'L', 'L', 'K', 'K', 'K', 'K', 'L', 'L', 'Q', 'L', 'L'],
    ['M', 'N', 'N', 'M', 'M', 'P', 'P', 'L', 'L', 'L', 'O', 'O', 'L', 'L', 'Q', 'L', 'L'],
    ['M', 'M', 'M', 'M', 'P', 'P', 'P', 'Q', 'Q', 'L', 'L', 'L', 'L', 'Q', 'Q', 'Q', 'L'],
    ['M', 'M', 'M', 'Q', 'Q', 'Q', 'Q', 'Q', 'Q', 'Q', 'Q', 'Q', 'Q', 'Q', 'L', 'L', 'L']
  ],
  hasUniqueSolution: true
}

export default level
