// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '51',
  regions: [
    ['C', 'C', 'C', 'C', 'C', 'C', 'C'],
    ['C', 'C', 'C', 'C', 'C', 'C', 'G'],
    ['C', 'C', 'C', 'E', 'G', 'G', 'G'],
    ['C', 'F', 'F', 'E', 'E', 'E', 'G'],
    ['F', 'F', 'D', 'E', 'E', 'B', 'B'],
    ['F', 'F', 'D', 'B', 'B', 'B', 'B'],
    ['F', 'B', 'B', 'B', 'A', 'A', 'A']
  ],
  hasUniqueSolution: true
}

export default level
