// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '52',
  regions: [
    ['A', 'A', 'C', 'C', 'B', 'B'],
    ['C', 'C', 'C', 'C', 'B', 'C'],
    ['C', 'C', 'C', 'C', 'C', 'C'],
    ['C', 'E', 'C', 'C', 'D', 'D'],
    ['C', 'E', 'F', 'D', 'D', 'D'],
    ['E', 'E', 'F', 'F', 'F', 'D']
  ],
  hasUniqueSolution: true
}

export default level
