// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '53',
  regions: [
    ['H', 'C', 'C', 'C', 'C', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
    ['H', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'A', 'G', 'G', 'B', 'B'],
    ['H', 'H', 'H', 'C', 'C', 'C', 'A', 'A', 'A', 'G', 'G', 'G', 'G'],
    ['D', 'D', 'H', 'H', 'C', 'C', 'C', 'C', 'A', 'A', 'A', 'G', 'G'],
    ['D', 'D', 'D', 'H', 'H', 'H', 'H', 'C', 'C', 'A', 'G', 'G', 'E'],
    ['D', 'H', 'H', 'H', 'I', 'I', 'I', 'I', 'F', 'F', 'G', 'E', 'E'],
    ['D', 'D', 'D', 'H', 'D', 'D', 'I', 'I', 'I', 'I', 'G', 'G', 'G'],
    ['D', 'H', 'H', 'H', 'D', 'D', 'I', 'I', 'K', 'I', 'I', 'G', 'I'],
    ['D', 'H', 'D', 'D', 'D', 'D', 'I', 'I', 'K', 'K', 'I', 'I', 'I'],
    ['D', 'L', 'D', 'D', 'J', 'J', 'J', 'J', 'J', 'K', 'I', 'I', 'I'],
    ['D', 'L', 'L', 'D', 'D', 'J', 'J', 'J', 'J', 'K', 'I', 'I', 'I'],
    ['D', 'L', 'D', 'D', 'D', 'D', 'M', 'M', 'J', 'J', 'J', 'I', 'I'],
    ['D', 'D', 'D', 'D', 'D', 'D', 'M', 'J', 'J', 'J', 'J', 'I', 'I']
  ],
  hasUniqueSolution: true
}

export default level
