// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '53',
  regions: [
    ['H', 'B', 'B', 'B', 'B', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D'],
    ['H', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'D', 'I', 'I', 'M', 'M'],
    ['H', 'H', 'H', 'B', 'B', 'B', 'D', 'D', 'D', 'I', 'I', 'I', 'I'],
    ['E', 'E', 'H', 'H', 'B', 'B', 'B', 'B', 'D', 'D', 'D', 'I', 'I'],
    ['E', 'E', 'E', 'H', 'H', 'H', 'H', 'B', 'B', 'D', 'I', 'I', 'L'],
    ['E', 'H', 'H', 'H', 'G', 'G', 'G', 'G', 'C', 'C', 'I', 'L', 'L'],
    ['E', 'E', 'E', 'H', 'E', 'E', 'G', 'G', 'G', 'G', 'I', 'I', 'I'],
    ['E', 'H', 'H', 'H', 'E', 'E', 'G', 'G', 'A', 'G', 'G', 'I', 'G'],
    ['E', 'H', 'E', 'E', 'E', 'E', 'G', 'G', 'A', 'A', 'G', 'G', 'G'],
    ['E', 'K', 'E', 'E', 'F', 'F', 'F', 'F', 'F', 'A', 'G', 'G', 'G'],
    ['E', 'K', 'K', 'E', 'E', 'F', 'F', 'F', 'F', 'A', 'G', 'G', 'G'],
    ['E', 'K', 'E', 'E', 'E', 'E', 'J', 'J', 'F', 'F', 'F', 'G', 'G'],
    ['E', 'E', 'E', 'E', 'E', 'E', 'J', 'F', 'F', 'F', 'F', 'G', 'G']
  ],
  hasUniqueSolution: true
}

export default level
