// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '54',
  regions: [
    ['H', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'J'],
    ['H', 'L', 'G', 'I', 'L', 'I', 'I', 'D', 'D', 'L', 'L', 'J'],
    ['I', 'L', 'G', 'I', 'L', 'I', 'I', 'I', 'I', 'I', 'L', 'J'],
    ['I', 'I', 'G', 'I', 'I', 'I', 'E', 'E', 'B', 'L', 'L', 'J'],
    ['E', 'I', 'I', 'I', 'I', 'E', 'E', 'B', 'B', 'L', 'B', 'J'],
    ['E', 'E', 'I', 'I', 'I', 'E', 'E', 'B', 'B', 'B', 'B', 'J'],
    ['C', 'E', 'I', 'E', 'I', 'E', 'E', 'B', 'J', 'J', 'J', 'J'],
    ['C', 'E', 'I', 'E', 'I', 'E', 'K', 'K', 'J', 'J', 'J', 'J'],
    ['C', 'E', 'E', 'E', 'I', 'E', 'E', 'K', 'K', 'K', 'K', 'K'],
    ['C', 'E', 'E', 'E', 'E', 'E', 'E', 'K', 'C', 'K', 'K', 'K'],
    ['C', 'E', 'C', 'E', 'A', 'A', 'A', 'K', 'C', 'F', 'K', 'K'],
    ['C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'F', 'K', 'K']
  ],
  hasUniqueSolution: true
}

export default level
