// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '54',
  regions: [
    ['A', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'G'],
    ['A', 'C', 'D', 'F', 'C', 'F', 'F', 'B', 'B', 'C', 'C', 'G'],
    ['F', 'C', 'D', 'F', 'C', 'F', 'F', 'F', 'F', 'F', 'C', 'G'],
    ['F', 'F', 'D', 'F', 'F', 'F', 'I', 'I', 'E', 'C', 'C', 'G'],
    ['I', 'F', 'F', 'F', 'F', 'I', 'I', 'E', 'E', 'C', 'E', 'G'],
    ['I', 'I', 'F', 'F', 'F', 'I', 'I', 'E', 'E', 'E', 'E', 'G'],
    ['J', 'I', 'F', 'I', 'F', 'I', 'I', 'E', 'G', 'G', 'G', 'G'],
    ['J', 'I', 'F', 'I', 'F', 'I', 'H', 'H', 'G', 'G', 'G', 'G'],
    ['J', 'I', 'I', 'I', 'F', 'I', 'I', 'H', 'H', 'H', 'H', 'H'],
    ['J', 'I', 'I', 'I', 'I', 'I', 'I', 'H', 'J', 'H', 'H', 'H'],
    ['J', 'I', 'J', 'I', 'K', 'K', 'K', 'H', 'J', 'L', 'H', 'H'],
    ['J', 'J', 'J', 'J', 'J', 'J', 'J', 'J', 'J', 'L', 'H', 'H']
  ],
  hasUniqueSolution: true
}

export default level
