// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '55',
  regions: [
    ['E', 'E', 'E', 'E', 'E', 'A', 'E'],
    ['E', 'B', 'B', 'B', 'E', 'A', 'E'],
    ['C', 'D', 'D', 'D', 'E', 'E', 'E'],
    ['C', 'D', 'C', 'D', 'D', 'D', 'E'],
    ['C', 'C', 'C', 'C', 'D', 'E', 'E'],
    ['C', 'F', 'D', 'D', 'D', 'E', 'E'],
    ['C', 'F', 'F', 'F', 'G', 'G', 'E']
  ],
  hasUniqueSolution: true
}

export default level
