// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '55',
  regions: [
    ['F', 'F', 'F', 'F', 'F', 'D', 'F'],
    ['F', 'A', 'A', 'A', 'F', 'D', 'F'],
    ['C', 'B', 'B', 'B', 'F', 'F', 'F'],
    ['C', 'B', 'C', 'B', 'B', 'B', 'F'],
    ['C', 'C', 'C', 'C', 'B', 'F', 'F'],
    ['C', 'E', 'B', 'B', 'B', 'F', 'F'],
    ['C', 'E', 'E', 'E', 'G', 'G', 'F']
  ],
  hasUniqueSolution: true
}

export default level
