// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '56',
  regions: [
    ['D', 'E', 'E', 'E', 'E', 'E', 'E', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
    ['D', 'E', 'B', 'B', 'C', 'E', 'E', 'E', 'E', 'E', 'A', 'A', 'E', 'A'],
    ['D', 'E', 'C', 'C', 'C', 'C', 'C', 'E', 'A', 'E', 'A', 'E', 'E', 'A'],
    ['D', 'D', 'C', 'E', 'C', 'C', 'E', 'E', 'A', 'A', 'A', 'E', 'A', 'A'],
    ['D', 'C', 'C', 'E', 'E', 'E', 'E', 'E', 'E', 'A', 'E', 'E', 'A', 'A'],
    ['D', 'C', 'G', 'E', 'G', 'E', 'E', 'G', 'E', 'E', 'E', 'F', 'A', 'A'],
    ['D', 'C', 'G', 'G', 'G', 'G', 'G', 'G', 'E', 'E', 'G', 'F', 'A', 'A'],
    ['D', 'D', 'G', 'G', 'D', 'D', 'D', 'G', 'G', 'E', 'G', 'F', 'H', 'A'],
    ['D', 'D', 'D', 'D', 'D', 'I', 'D', 'G', 'G', 'G', 'G', 'G', 'H', 'A'],
    ['D', 'D', 'D', 'D', 'D', 'I', 'D', 'D', 'D', 'G', 'J', 'G', 'G', 'G'],
    ['D', 'L', 'D', 'D', 'D', 'I', 'D', 'K', 'D', 'G', 'J', 'G', 'G', 'J'],
    ['L', 'L', 'L', 'D', 'I', 'I', 'I', 'K', 'J', 'J', 'J', 'J', 'J', 'J'],
    ['M', 'M', 'L', 'D', 'D', 'I', 'K', 'K', 'K', 'K', 'K', 'K', 'J', 'J'],
    ['D', 'D', 'D', 'D', 'D', 'K', 'K', 'N', 'N', 'N', 'K', 'J', 'J', 'J']
  ],
  hasUniqueSolution: true
}

export default level
