// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '56',
  regions: [
    ['L', 'M', 'M', 'M', 'M', 'M', 'M', 'G', 'G', 'G', 'G', 'G', 'G', 'G'],
    ['L', 'M', 'F', 'F', 'A', 'M', 'M', 'M', 'M', 'M', 'G', 'G', 'M', 'G'],
    ['L', 'M', 'A', 'A', 'A', 'A', 'A', 'M', 'G', 'M', 'G', 'M', 'M', 'G'],
    ['L', 'L', 'A', 'M', 'A', 'A', 'M', 'M', 'G', 'G', 'G', 'M', 'G', 'G'],
    ['L', 'A', 'A', 'M', 'M', 'M', 'M', 'M', 'M', 'G', 'M', 'M', 'G', 'G'],
    ['L', 'A', 'E', 'M', 'E', 'M', 'M', 'E', 'M', 'M', 'M', 'I', 'G', 'G'],
    ['L', 'A', 'E', 'E', 'E', 'E', 'E', 'E', 'M', 'M', 'E', 'I', 'G', 'G'],
    ['L', 'L', 'E', 'E', 'L', 'L', 'L', 'E', 'E', 'M', 'E', 'I', 'K', 'G'],
    ['L', 'L', 'L', 'L', 'L', 'B', 'L', 'E', 'E', 'E', 'E', 'E', 'K', 'G'],
    ['L', 'L', 'L', 'L', 'L', 'B', 'L', 'L', 'L', 'E', 'D', 'E', 'E', 'E'],
    ['L', 'H', 'L', 'L', 'L', 'B', 'L', 'N', 'L', 'E', 'D', 'E', 'E', 'D'],
    ['H', 'H', 'H', 'L', 'B', 'B', 'B', 'N', 'D', 'D', 'D', 'D', 'D', 'D'],
    ['C', 'C', 'H', 'L', 'L', 'B', 'N', 'N', 'N', 'N', 'N', 'N', 'D', 'D'],
    ['L', 'L', 'L', 'L', 'L', 'N', 'N', 'J', 'J', 'J', 'N', 'D', 'D', 'D']
  ],
  hasUniqueSolution: true
}

export default level
