// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '57',
  regions: [
    ['J', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'K'],
    ['J', 'J', 'J', 'B', 'B', 'G', 'D', 'G', 'D', 'D', 'K', 'K'],
    ['J', 'J', 'J', 'B', 'B', 'G', 'G', 'G', 'D', 'A', 'A', 'K'],
    ['J', 'J', 'B', 'B', 'K', 'K', 'K', 'D', 'D', 'D', 'K', 'K'],
    ['L', 'J', 'B', 'B', 'K', 'K', 'D', 'D', 'D', 'K', 'K', 'K'],
    ['L', 'J', 'B', 'B', 'B', 'K', 'K', 'D', 'D', 'D', 'K', 'K'],
    ['L', 'L', 'L', 'L', 'L', 'L', 'K', 'K', 'K', 'K', 'K', 'K'],
    ['L', 'L', 'E', 'L', 'L', 'L', 'L', 'K', 'H', 'K', 'K', 'K'],
    ['L', 'L', 'E', 'E', 'E', 'E', 'E', 'K', 'H', 'H', 'H', 'K'],
    ['I', 'L', 'L', 'L', 'E', 'E', 'E', 'F', 'F', 'H', 'K', 'K'],
    ['I', 'L', 'L', 'L', 'L', 'E', 'E', 'C', 'F', 'H', 'K', 'H'],
    ['I', 'I', 'I', 'I', 'I', 'E', 'E', 'C', 'H', 'H', 'H', 'H']
  ],
  hasUniqueSolution: true
}

export default level
