// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '57',
  regions: [
    ['F', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'A'],
    ['F', 'F', 'F', 'D', 'D', 'B', 'E', 'B', 'E', 'E', 'A', 'A'],
    ['F', 'F', 'F', 'D', 'D', 'B', 'B', 'B', 'E', 'C', 'C', 'A'],
    ['F', 'F', 'D', 'D', 'A', 'A', 'A', 'E', 'E', 'E', 'A', 'A'],
    ['G', 'F', 'D', 'D', 'A', 'A', 'E', 'E', 'E', 'A', 'A', 'A'],
    ['G', 'F', 'D', 'D', 'D', 'A', 'A', 'E', 'E', 'E', 'A', 'A'],
    ['G', 'G', 'G', 'G', 'G', 'G', 'A', 'A', 'A', 'A', 'A', 'A'],
    ['G', 'G', 'H', 'G', 'G', 'G', 'G', 'A', 'I', 'A', 'A', 'A'],
    ['G', 'G', 'H', 'H', 'H', 'H', 'H', 'A', 'I', 'I', 'I', 'A'],
    ['K', 'G', 'G', 'G', 'H', 'H', 'H', 'J', 'J', 'I', 'A', 'A'],
    ['K', 'G', 'G', 'G', 'G', 'H', 'H', 'L', 'J', 'I', 'A', 'I'],
    ['K', 'K', 'K', 'K', 'K', 'H', 'H', 'L', 'I', 'I', 'I', 'I']
  ],
  hasUniqueSolution: true
}

export default level
