// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '58',
  regions: [
    ['G', 'G', 'G', 'E', 'E', 'E', 'E', 'E'],
    ['G', 'H', 'G', 'E', 'E', 'G', 'E', 'E'],
    ['G', 'H', 'G', 'G', 'G', 'G', 'E', 'E'],
    ['G', 'G', 'E', 'E', 'E', 'G', 'E', 'C'],
    ['G', 'A', 'A', 'D', 'E', 'E', 'E', 'C'],
    ['G', 'G', 'A', 'D', 'D', 'D', 'B', 'B'],
    ['G', 'G', 'A', 'F', 'D', 'F', 'F', 'B'],
    ['G', 'A', 'A', 'F', 'F', 'F', 'F', 'B']
  ],
  hasUniqueSolution: true
}

export default level
