// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "58",
  regions: [["A","A","A","B","B","B","B","B"],["A","C","A","B","B","A","B","B"],["A","C","A","A","A","A","B","B"],["A","A","B","B","B","A","B","D"],["A","G","G","E","B","B","B","D"],["A","A","G","E","E","E","F","F"],["A","A","G","H","E","H","H","F"],["A","G","G","H","H","H","H","F"]],
  hasUniqueSolution: true,
}

export default level
