// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '59',
  regions: [
    ['J', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G'],
    ['J', 'G', 'G', 'J', 'J', 'J', 'G', 'E', 'E', 'G', 'L', 'G', 'G'],
    ['J', 'J', 'J', 'J', 'J', 'G', 'G', 'E', 'E', 'B', 'L', 'G', 'G'],
    ['J', 'J', 'M', 'M', 'J', 'J', 'G', 'E', 'E', 'B', 'L', 'G', 'G'],
    ['M', 'J', 'J', 'M', 'J', 'E', 'E', 'E', 'L', 'L', 'L', 'G', 'G'],
    ['M', 'M', 'M', 'M', 'J', 'J', 'L', 'E', 'E', 'E', 'L', 'G', 'G'],
    ['M', 'H', 'M', 'I', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'G'],
    ['M', 'H', 'M', 'I', 'C', 'L', 'C', 'L', 'L', 'K', 'K', 'L', 'G'],
    ['M', 'H', 'A', 'I', 'C', 'C', 'C', 'C', 'K', 'K', 'K', 'L', 'G'],
    ['M', 'H', 'A', 'F', 'F', 'H', 'C', 'D', 'L', 'L', 'L', 'L', 'G'],
    ['M', 'H', 'A', 'A', 'H', 'H', 'C', 'D', 'C', 'L', 'C', 'L', 'G'],
    ['M', 'H', 'H', 'A', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'G'],
    ['M', 'H', 'H', 'H', 'H', 'H', 'H', 'A', 'G', 'G', 'G', 'G', 'G']
  ],
  hasUniqueSolution: true
}

export default level
