// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "59",
  regions: [["C","A","A","A","A","A","A","A","A","A","A","A","A"],["C","A","A","C","C","C","A","B","B","A","F","A","A"],["C","C","C","C","C","A","A","B","B","D","F","A","A"],["C","C","E","E","C","C","A","B","B","D","F","A","A"],["E","C","C","E","C","B","B","B","F","F","F","A","A"],["E","E","E","E","C","C","F","B","B","B","F","A","A"],["E","M","E","G","F","F","F","F","F","F","F","F","A"],["E","M","E","G","L","F","L","F","F","H","H","F","A"],["E","M","I","G","L","L","L","L","H","H","H","F","A"],["E","M","I","J","J","M","L","K","F","F","F","F","A"],["E","M","I","I","M","M","L","K","L","F","L","F","A"],["E","M","M","I","M","M","L","L","L","L","L","L","A"],["E","M","M","M","M","M","M","I","A","A","A","A","A"]],
  hasUniqueSolution: true,
}

export default level
