// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '6',
  regions: [
    ['E', 'E', 'E', 'E', 'G', 'G', 'G', 'F', 'F', 'F', 'F', 'F', 'A', 'A', 'A', 'F'],
    ['E', 'E', 'C', 'C', 'I', 'C', 'G', 'F', 'B', 'B', 'F', 'A', 'A', 'A', 'F', 'F'],
    ['E', 'C', 'C', 'C', 'G', 'G', 'G', 'G', 'G', 'F', 'F', 'A', 'F', 'F', 'F', 'F'],
    ['E', 'E', 'C', 'D', 'G', 'G', 'N', 'G', 'F', 'F', 'F', 'F', 'F', 'H', 'H', 'F'],
    ['E', 'E', 'G', 'D', 'G', 'G', 'N', 'G', 'H', 'H', 'F', 'H', 'H', 'H', 'F', 'F'],
    ['O', 'O', 'G', 'G', 'G', 'G', 'N', 'G', 'G', 'H', 'H', 'H', 'H', 'H', 'H', 'F'],
    ['O', 'O', 'G', 'G', 'G', 'G', 'N', 'N', 'G', 'G', 'H', 'H', 'J', 'J', 'H', 'H'],
    ['O', 'O', 'G', 'O', 'I', 'G', 'O', 'N', 'G', 'G', 'G', 'H', 'H', 'J', 'J', 'L'],
    ['O', 'O', 'O', 'O', 'I', 'O', 'O', 'N', 'N', 'G', 'H', 'H', 'H', 'J', 'J', 'L'],
    ['O', 'O', 'O', 'O', 'O', 'O', 'N', 'N', 'H', 'H', 'H', 'H', 'H', 'J', 'J', 'L'],
    ['O', 'N', 'N', 'O', 'N', 'O', 'N', 'N', 'H', 'K', 'K', 'K', 'H', 'J', 'J', 'L'],
    ['O', 'O', 'N', 'N', 'N', 'N', 'N', 'N', 'H', 'M', 'M', 'K', 'J', 'J', 'L', 'L'],
    ['O', 'O', 'N', 'N', 'N', 'P', 'P', 'N', 'H', 'M', 'K', 'K', 'K', 'J', 'J', 'L'],
    ['O', 'O', 'O', 'N', 'P', 'P', 'P', 'N', 'N', 'N', 'N', 'P', 'K', 'K', 'J', 'J'],
    ['O', 'P', 'O', 'O', 'P', 'P', 'P', 'N', 'P', 'P', 'N', 'P', 'P', 'P', 'J', 'J'],
    ['P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P']
  ],
  hasUniqueSolution: true
}

export default level
