// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '6',
  regions: [
    ['J', 'J', 'J', 'J', 'G', 'G', 'G', 'K', 'K', 'K', 'K', 'K', 'P', 'P', 'P', 'K'],
    ['J', 'J', 'N', 'N', 'A', 'N', 'G', 'K', 'B', 'B', 'K', 'P', 'P', 'P', 'K', 'K'],
    ['J', 'N', 'N', 'N', 'G', 'G', 'G', 'G', 'G', 'K', 'K', 'P', 'K', 'K', 'K', 'K'],
    ['J', 'J', 'N', 'I', 'G', 'G', 'L', 'G', 'K', 'K', 'K', 'K', 'K', 'H', 'H', 'K'],
    ['J', 'J', 'G', 'I', 'G', 'G', 'L', 'G', 'H', 'H', 'K', 'H', 'H', 'H', 'K', 'K'],
    ['F', 'F', 'G', 'G', 'G', 'G', 'L', 'G', 'G', 'H', 'H', 'H', 'H', 'H', 'H', 'K'],
    ['F', 'F', 'G', 'G', 'G', 'G', 'L', 'L', 'G', 'G', 'H', 'H', 'D', 'D', 'H', 'H'],
    ['F', 'F', 'G', 'F', 'A', 'G', 'F', 'L', 'G', 'G', 'G', 'H', 'H', 'D', 'D', 'M'],
    ['F', 'F', 'F', 'F', 'A', 'F', 'F', 'L', 'L', 'G', 'H', 'H', 'H', 'D', 'D', 'M'],
    ['F', 'F', 'F', 'F', 'F', 'F', 'L', 'L', 'H', 'H', 'H', 'H', 'H', 'D', 'D', 'M'],
    ['F', 'L', 'L', 'F', 'L', 'F', 'L', 'L', 'H', 'C', 'C', 'C', 'H', 'D', 'D', 'M'],
    ['F', 'F', 'L', 'L', 'L', 'L', 'L', 'L', 'H', 'O', 'O', 'C', 'D', 'D', 'M', 'M'],
    ['F', 'F', 'L', 'L', 'L', 'E', 'E', 'L', 'H', 'O', 'C', 'C', 'C', 'D', 'D', 'M'],
    ['F', 'F', 'F', 'L', 'E', 'E', 'E', 'L', 'L', 'L', 'L', 'E', 'C', 'C', 'D', 'D'],
    ['F', 'E', 'F', 'F', 'E', 'E', 'E', 'L', 'E', 'E', 'L', 'E', 'E', 'E', 'D', 'D'],
    ['E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E']
  ],
  hasUniqueSolution: true
}

export default level
