// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "60",
  regions: [["C","C","C","C","C","C","C","C","A","A","A","A","A","A","A","A","A","F"],["C","B","B","C","C","D","K","C","C","C","E","A","F","F","F","F","A","F"],["C","B","C","C","C","D","K","K","C","C","E","A","A","A","A","F","F","F"],["C","B","C","C","D","D","K","K","K","K","E","A","F","F","A","F","F","I"],["C","C","C","C","C","K","K","K","K","F","E","F","F","A","A","F","F","I"],["C","L","L","L","C","K","C","C","K","F","F","F","F","F","F","F","I","I"],["G","G","L","H","C","C","C","K","K","F","F","F","F","F","F","F","I","I"],["L","L","L","H","C","C","K","K","K","F","F","F","I","I","I","I","I","I"],["L","L","L","J","K","C","C","K","K","K","K","F","F","F","I","I","I","I"],["L","J","L","J","K","K","K","K","K","K","K","K","F","F","F","I","I","F"],["L","J","J","J","L","L","L","L","L","K","N","K","K","N","F","I","F","F"],["L","L","J","J","L","L","K","K","K","K","N","N","N","N","F","I","F","F"],["L","L","J","J","L","M","M","K","K","K","N","F","F","F","F","F","F","F"],["L","L","J","J","L","M","M","M","K","K","N","F","F","N","F","F","F","F"],["L","L","J","L","L","L","M","O","N","N","N","N","N","N","N","N","N","F"],["L","J","J","L","M","M","M","O","O","O","N","P","N","N","P","P","P","F"],["L","L","J","L","M","O","M","M","O","N","N","P","P","P","P","Q","F","F"],["L","L","L","L","O","O","O","O","O","R","R","Q","Q","Q","Q","Q","Q","F"]],
  hasUniqueSolution: true,
}

export default level
