// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '60',
  regions: [
    ['C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'G'],
    ['C', 'I', 'I', 'C', 'C', 'O', 'M', 'C', 'C', 'C', 'R', 'H', 'G', 'G', 'G', 'G', 'H', 'G'],
    ['C', 'I', 'C', 'C', 'C', 'O', 'M', 'M', 'C', 'C', 'R', 'H', 'H', 'H', 'H', 'G', 'G', 'G'],
    ['C', 'I', 'C', 'C', 'O', 'O', 'M', 'M', 'M', 'M', 'R', 'H', 'G', 'G', 'H', 'G', 'G', 'P'],
    ['C', 'C', 'C', 'C', 'C', 'M', 'M', 'M', 'M', 'G', 'R', 'G', 'G', 'H', 'H', 'G', 'G', 'P'],
    ['C', 'K', 'K', 'K', 'C', 'M', 'C', 'C', 'M', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'P', 'P'],
    ['L', 'L', 'K', 'J', 'C', 'C', 'C', 'M', 'M', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'P', 'P'],
    ['K', 'K', 'K', 'J', 'C', 'C', 'M', 'M', 'M', 'G', 'G', 'G', 'P', 'P', 'P', 'P', 'P', 'P'],
    ['K', 'K', 'K', 'F', 'M', 'C', 'C', 'M', 'M', 'M', 'M', 'G', 'G', 'G', 'P', 'P', 'P', 'P'],
    ['K', 'F', 'K', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'G', 'G', 'G', 'P', 'P', 'G'],
    ['K', 'F', 'F', 'F', 'K', 'K', 'K', 'K', 'K', 'M', 'D', 'M', 'M', 'D', 'G', 'P', 'G', 'G'],
    ['K', 'K', 'F', 'F', 'K', 'K', 'M', 'M', 'M', 'M', 'D', 'D', 'D', 'D', 'G', 'P', 'G', 'G'],
    ['K', 'K', 'F', 'F', 'K', 'N', 'N', 'M', 'M', 'M', 'D', 'G', 'G', 'G', 'G', 'G', 'G', 'G'],
    ['K', 'K', 'F', 'F', 'K', 'N', 'N', 'N', 'M', 'M', 'D', 'G', 'G', 'D', 'G', 'G', 'G', 'G'],
    ['K', 'K', 'F', 'K', 'K', 'K', 'N', 'A', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'G'],
    ['K', 'F', 'F', 'K', 'N', 'N', 'N', 'A', 'A', 'A', 'D', 'E', 'D', 'D', 'E', 'E', 'E', 'G'],
    ['K', 'K', 'F', 'K', 'N', 'A', 'N', 'N', 'A', 'D', 'D', 'E', 'E', 'E', 'E', 'Q', 'G', 'G'],
    ['K', 'K', 'K', 'K', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'Q', 'Q', 'Q', 'Q', 'Q', 'Q', 'G']
  ],
  hasUniqueSolution: true
}

export default level
