// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "61",
  regions: [["A","A","A","D","D","B","B","B","B","B","B","B"],["E","E","E","D","D","B","D","B","C","F","B","B"],["E","E","E","E","D","D","D","B","C","F","F","H"],["E","I","E","E","E","E","D","D","F","F","F","H"],["E","I","I","I","I","E","E","D","D","D","F","H"],["I","I","L","L","G","E","E","E","D","K","F","H"],["I","L","L","K","G","G","G","E","D","G","H","H"],["I","L","L","K","K","K","G","D","D","G","H","H"],["I","I","L","K","K","K","G","G","G","G","G","K"],["I","L","L","L","L","K","K","J","J","K","G","K"],["L","L","L","K","K","K","K","K","J","K","K","K"],["L","L","L","L","L","L","L","K","K","K","K","K"]],
  hasUniqueSolution: true,
}

export default level
