// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '61',
  regions: [
    ['B', 'B', 'B', 'J', 'J', 'K', 'K', 'K', 'K', 'K', 'K', 'K'],
    ['D', 'D', 'D', 'J', 'J', 'K', 'J', 'K', 'H', 'G', 'K', 'K'],
    ['D', 'D', 'D', 'D', 'J', 'J', 'J', 'K', 'H', 'G', 'G', 'E'],
    ['D', 'A', 'D', 'D', 'D', 'D', 'J', 'J', 'G', 'G', 'G', 'E'],
    ['D', 'A', 'A', 'A', 'A', 'D', 'D', 'J', 'J', 'J', 'G', 'E'],
    ['A', 'A', 'I', 'I', 'F', 'D', 'D', 'D', 'J', 'C', 'G', 'E'],
    ['A', 'I', 'I', 'C', 'F', 'F', 'F', 'D', 'J', 'F', 'E', 'E'],
    ['A', 'I', 'I', 'C', 'C', 'C', 'F', 'J', 'J', 'F', 'E', 'E'],
    ['A', 'A', 'I', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'C'],
    ['A', 'I', 'I', 'I', 'I', 'C', 'C', 'L', 'L', 'C', 'F', 'C'],
    ['I', 'I', 'I', 'C', 'C', 'C', 'C', 'C', 'L', 'C', 'C', 'C'],
    ['I', 'I', 'I', 'I', 'I', 'I', 'I', 'C', 'C', 'C', 'C', 'C']
  ],
  hasUniqueSolution: true
}

export default level
