// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '62',
  regions: [
    ['D', 'D', 'H', 'H', 'H', 'H', 'H', 'H'],
    ['D', 'D', 'D', 'D', 'D', 'C', 'H', 'H'],
    ['D', 'F', 'F', 'F', 'E', 'E', 'E', 'H'],
    ['B', 'F', 'C', 'C', 'H', 'G', 'H', 'H'],
    ['B', 'F', 'C', 'C', 'H', 'G', 'H', 'H'],
    ['B', 'C', 'C', 'C', 'H', 'H', 'H', 'H'],
    ['C', 'C', 'A', 'C', 'A', 'A', 'A', 'H'],
    ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'H']
  ],
  hasUniqueSolution: true
}

export default level
