// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "64",
  regions: [["N","N","N","N","N","N","N","N","N","B","B","B","B","B","B","B","B"],["N","N","N","N","C","C","N","J","N","N","B","H","H","B","H","H","B"],["C","C","C","C","C","N","N","J","J","J","J","J","H","H","H","B","B"],["C","C","C","C","C","N","J","J","J","J","J","H","H","H","H","B","O"],["C","C","N","N","N","N","N","J","L","L","L","L","H","H","H","B","O"],["C","A","N","N","N","A","A","J","L","D","D","L","H","H","B","B","O"],["C","A","A","A","N","A","A","A","L","D","Q","B","B","B","B","B","B"],["C","C","A","A","A","A","A","A","L","L","Q","B","Q","P","I","I","B"],["C","A","A","A","A","A","A","Q","Q","Q","Q","B","Q","P","P","I","B"],["C","C","C","G","G","G","A","Q","Q","A","Q","Q","Q","P","P","I","B"],["G","C","C","G","G","A","A","A","A","A","A","A","Q","P","I","I","B"],["G","G","G","G","G","G","C","A","A","A","G","A","A","P","P","I","P"],["A","G","G","G","G","G","G","G","G","G","G","A","A","A","P","P","P"],["A","G","A","A","A","A","G","A","A","A","A","A","A","A","P","K","K"],["A","A","A","A","A","A","A","A","P","P","P","A","F","A","P","K","K"],["M","M","A","E","E","E","A","P","P","F","F","F","F","P","P","P","K"],["E","E","E","E","E","A","A","A","P","P","P","P","P","P","P","P","P"]],
  hasUniqueSolution: true,
}

export default level
