// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "65",
  regions: [["G","G","B","B","B","B","B","L","L","L","L","L","L","L"],["G","N","N","N","B","N","B","B","L","B","B","B","B","L"],["G","G","G","N","N","N","B","B","L","B","B","B","B","L"],["G","N","N","N","B","N","N","B","B","B","L","L","B","L"],["G","G","N","B","B","B","B","B","B","B","L","M","M","L"],["G","N","N","N","N","D","B","B","B","L","L","L","L","L"],["N","N","N","N","D","D","B","B","L","L","L","F","F","L"],["N","N","N","D","D","B","B","B","B","F","L","F","F","C"],["E","E","E","D","D","B","F","F","F","F","F","F","F","C"],["E","I","E","F","D","D","F","K","F","F","K","K","K","C"],["E","I","F","F","F","F","F","K","K","K","K","K","K","K"],["E","E","A","F","A","A","F","K","K","J","J","K","K","K"],["E","A","A","A","A","A","F","F","F","F","J","K","K","K"],["E","E","E","H","H","H","J","J","J","J","J","J","J","J"]],
  hasUniqueSolution: true,
}

export default level
