// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "66",
  regions: [["B","B","B","B","B","B","B"],["B","B","B","A","B","B","B"],["B","B","G","A","A","A","E"],["B","G","G","E","E","E","E"],["G","G","G","E","E","D","E"],["G","G","C","C","F","D","D"],["C","C","C","C","F","D","D"]],
  hasUniqueSolution: true,
}

export default level
