// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "67",
  regions: [["G","G","G","G","G","G","G","G","G"],["G","C","G","C","G","G","A","A","E"],["C","C","G","C","C","C","A","A","G"],["D","C","C","C","C","A","A","A","G"],["D","D","D","B","B","I","I","I","G"],["D","D","D","I","I","I","I","E","E"],["F","D","D","I","D","E","I","E","E"],["F","F","D","D","D","E","I","E","H"],["D","D","D","E","E","E","E","E","H"]],
  hasUniqueSolution: true,
}

export default level
