// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "68",
  regions: [["E","B","B","B","B","B","B","I","I"],["E","E","B","B","B","G","G","G","I"],["E","E","B","G","G","G","D","D","I"],["E","E","E","G","F","G","G","G","I"],["E","F","F","F","F","G","F","G","G"],["E","E","E","E","F","F","F","H","H"],["E","E","A","A","A","A","F","F","H"],["E","A","A","C","C","A","F","H","H"],["E","E","E","A","A","A","F","F","H"]],
  hasUniqueSolution: true,
}

export default level
