// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "69",
  regions: [["E","E","E","E","E"],["C","C","C","B","E"],["C","A","A","B","B"],["C","A","A","D","D"],["A","A","A","A","A"]],
  hasUniqueSolution: true,
}

export default level
