// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '7',
  regions: [
    ['B', 'B', 'B', 'B', 'B', 'B', 'B', 'H', 'H', 'H', 'H', 'A', 'H'],
    ['B', 'B', 'B', 'D', 'D', 'B', 'B', 'B', 'B', 'D', 'H', 'A', 'H'],
    ['B', 'C', 'F', 'F', 'D', 'D', 'D', 'D', 'D', 'D', 'H', 'H', 'H'],
    ['E', 'C', 'F', 'D', 'D', 'D', 'D', 'F', 'D', 'D', 'D', 'H', 'H'],
    ['E', 'C', 'F', 'F', 'F', 'F', 'F', 'F', 'D', 'D', 'D', 'D', 'H'],
    ['G', 'C', 'F', 'F', 'F', 'F', 'F', 'D', 'D', 'D', 'D', 'D', 'H'],
    ['G', 'G', 'G', 'F', 'F', 'J', 'F', 'F', 'D', 'D', 'D', 'D', 'H'],
    ['G', 'F', 'F', 'F', 'F', 'J', 'J', 'F', 'D', 'F', 'H', 'H', 'H'],
    ['G', 'G', 'F', 'F', 'I', 'I', 'J', 'F', 'F', 'F', 'F', 'H', 'L'],
    ['G', 'J', 'J', 'F', 'F', 'J', 'J', 'J', 'J', 'J', 'K', 'L', 'L'],
    ['G', 'J', 'F', 'F', 'J', 'J', 'J', 'J', 'K', 'K', 'K', 'K', 'L'],
    ['G', 'J', 'J', 'F', 'F', 'F', 'F', 'J', 'K', 'M', 'L', 'L', 'L'],
    ['G', 'J', 'J', 'J', 'J', 'J', 'J', 'J', 'K', 'M', 'M', 'M', 'M']
  ],
  hasUniqueSolution: true
}

export default level
