// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '7',
  regions: [
    ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'B', 'B', 'B', 'B', 'J', 'B'],
    ['F', 'F', 'F', 'G', 'G', 'F', 'F', 'F', 'F', 'G', 'B', 'J', 'B'],
    ['F', 'E', 'H', 'H', 'G', 'G', 'G', 'G', 'G', 'G', 'B', 'B', 'B'],
    ['D', 'E', 'H', 'G', 'G', 'G', 'G', 'H', 'G', 'G', 'G', 'B', 'B'],
    ['D', 'E', 'H', 'H', 'H', 'H', 'H', 'H', 'G', 'G', 'G', 'G', 'B'],
    ['L', 'E', 'H', 'H', 'H', 'H', 'H', 'G', 'G', 'G', 'G', 'G', 'B'],
    ['L', 'L', 'L', 'H', 'H', 'K', 'H', 'H', 'G', 'G', 'G', 'G', 'B'],
    ['L', 'H', 'H', 'H', 'H', 'K', 'K', 'H', 'G', 'H', 'B', 'B', 'B'],
    ['L', 'L', 'H', 'H', 'C', 'C', 'K', 'H', 'H', 'H', 'H', 'B', 'A'],
    ['L', 'K', 'K', 'H', 'H', 'K', 'K', 'K', 'K', 'K', 'I', 'A', 'A'],
    ['L', 'K', 'H', 'H', 'K', 'K', 'K', 'K', 'I', 'I', 'I', 'I', 'A'],
    ['L', 'K', 'K', 'H', 'H', 'H', 'H', 'K', 'I', 'M', 'A', 'A', 'A'],
    ['L', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'I', 'M', 'M', 'M', 'M']
  ],
  hasUniqueSolution: true
}

export default level
