// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "70",
  regions: [["D","C","C","C","E","E","G","G","G","G","G"],["D","D","C","C","C","G","G","A","A","A","G"],["D","D","C","G","G","G","G","G","G","A","G"],["D","K","C","C","C","G","G","F","F","A","A"],["C","K","C","C","G","G","G","G","G","G","A"],["C","C","C","C","C","J","B","B","A","A","A"],["H","H","H","C","J","J","J","B","A","I","I"],["C","C","C","C","C","B","B","B","A","A","I"],["C","C","C","B","C","B","B","B","A","A","I"],["C","C","B","B","C","C","C","B","B","A","A"],["C","B","B","B","B","B","B","B","B","A","A"]],
  hasUniqueSolution: true,
}

export default level
