// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "71",
  regions: [["C","C","C","C","A","A","A","C","C","C"],["D","C","D","C","C","C","C","C","C","C"],["D","D","D","C","J","C","H","C","B","C"],["D","D","J","J","J","H","H","C","B","C"],["D","J","J","C","C","H","C","C","B","B"],["D","G","J","J","C","C","C","C","C","C"],["D","J","J","C","C","C","G","G","C","C"],["D","J","C","C","C","C","C","C","E","C"],["I","J","I","I","I","I","I","E","E","E"],["I","I","I","F","F","I","I","I","E","E"]],
  hasUniqueSolution: true,
}

export default level
