// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "72",
  regions: [["M","M","M","M","M","A","A","L","L","L","L","L","L"],["M","A","M","M","M","A","L","L","E","E","E","E","L"],["M","A","M","M","M","A","A","L","L","L","L","E","G"],["M","A","A","A","A","A","L","L","L","L","L","E","G"],["M","M","M","J","J","H","L","C","C","G","L","G","G"],["M","J","J","J","L","H","L","C","C","G","G","G","G"],["M","J","L","L","L","L","L","L","C","C","F","F","G"],["L","J","L","L","L","L","L","L","C","C","F","F","G"],["L","L","L","D","L","L","L","L","L","F","F","F","G"],["L","D","D","D","D","D","D","D","F","F","I","I","B"],["L","L","L","D","D","D","K","D","D","F","K","K","B"],["D","L","L","L","D","K","K","K","D","F","K","K","B"],["D","D","D","D","D","D","D","K","K","K","K","B","B"]],
  hasUniqueSolution: true,
}

export default level
