// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "73",
  regions: [["B","B","B","B","B","B","B","B","B"],["B","B","B","B","A","B","C","C","B"],["B","D","D","A","A","C","C","C","B"],["B","D","D","A","C","C","F","C","B"],["B","B","I","I","C","C","F","F","H"],["B","E","G","G","G","C","C","F","H"],["B","E","G","E","C","C","F","F","H"],["B","E","E","E","C","C","C","C","C"],["E","E","E","E","C","C","C","C","C"]],
  hasUniqueSolution: true,
}

export default level
