// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "74",
  regions: [["M","M","L","L","L","L","A","A","A","A","B","B","B","B"],["M","M","M","L","L","M","M","M","M","A","B","H","H","H"],["N","M","M","M","M","M","M","M","M","C","B","B","H","H"],["N","N","M","M","M","N","M","C","M","C","B","H","H","H"],["N","N","N","M","N","N","M","C","C","C","H","H","H","H"],["N","N","N","N","N","N","M","M","C","H","L","K","H","H"],["N","N","N","F","N","N","N","M","C","C","C","K","H","H"],["N","N","N","F","F","N","M","M","C","C","K","K","H","H"],["N","N","F","F","F","N","M","C","C","K","K","K","K","H"],["F","N","F","D","D","M","M","C","K","K","K","K","H","H"],["F","F","F","F","F","M","K","K","K","K","I","I","I","H"],["F","F","J","J","F","F","K","J","K","K","I","I","I","I"],["F","F","G","J","J","J","J","J","J","J","G","I","I","E"],["F","F","G","G","G","G","G","G","G","G","G","I","I","E"]],
  hasUniqueSolution: true,
}

export default level
