// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "75",
  regions: [["H","H","H","H","H","H","H","H","H","O","O","O","O","O","O","G"],["H","H","H","H","H","H","H","O","O","O","O","L","L","O","O","G"],["H","H","O","O","O","O","O","O","O","L","O","O","L","O","L","G"],["H","H","O","O","O","M","O","O","L","L","L","L","L","O","L","G"],["H","H","O","O","O","M","L","L","L","L","L","N","L","L","L","G"],["H","H","H","H","M","M","M","M","L","N","N","N","N","N","G","G"],["H","E","E","E","M","F","F","M","M","M","B","B","B","N","N","G"],["E","E","E","E","M","M","F","F","F","F","B","B","B","N","G","G"],["E","E","M","M","M","F","F","F","K","F","F","F","B","N","B","B"],["K","K","M","M","M","K","K","K","K","K","F","F","B","B","B","A"],["K","K","K","M","M","K","B","B","K","K","F","B","B","B","A","A"],["I","K","K","M","K","K","B","B","B","B","F","B","J","J","A","A"],["I","K","K","K","K","I","I","B","B","B","B","B","D","J","A","A"],["I","K","I","I","I","I","I","I","I","B","B","B","D","J","A","A"],["I","K","I","C","I","P","I","I","I","B","B","B","D","J","J","J"],["I","I","I","C","I","P","P","I","I","B","B","D","D","D","D","G"]],
  hasUniqueSolution: true,
}

export default level
