// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "76",
  regions: [["B","B","C","D","D","D"],["B","C","C","C","C","E"],["B","C","B","C","C","C"],["B","B","B","C","A","A"],["F","B","E","E","E","A"],["F","F","E","E","E","E"]],
  hasUniqueSolution: true,
}

export default level
