// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "77",
  regions: [["F","F","F","F","F","E","E","E","C"],["F","B","F","B","I","E","E","C","C"],["B","B","B","B","I","E","E","C","C"],["B","D","D","D","E","E","C","C","C"],["D","D","D","D","C","C","C","C","H"],["D","G","G","D","A","A","A","G","H"],["D","D","G","G","A","G","A","G","G"],["D","D","G","G","G","G","G","G","G"],["D","D","D","D","G","G","G","G","G"]],
  hasUniqueSolution: true,
}

export default level
