// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "78",
  regions: [["E","E","E","E","E","E","E","E","E","E","E","E","E"],["E","E","E","E","D","E","E","A","A","E","E","I","I"],["E","D","D","D","D","E","A","A","A","J","I","I","I"],["E","D","D","D","D","E","E","A","J","J","J","J","I"],["E","D","E","E","E","E","E","E","H","H","H","J","I"],["E","D","D","D","D","D","D","C","C","C","H","J","I"],["E","M","M","M","M","M","C","C","C","C","H","J","I"],["E","H","M","H","H","H","H","C","H","C","H","J","J"],["E","H","H","A","L","H","H","H","H","H","H","J","J"],["E","H","H","L","L","L","L","H","H","G","H","H","J"],["H","H","L","L","F","F","L","F","H","G","G","H","H"],["H","F","F","F","F","F","F","F","G","G","K","K","H"],["H","F","F","F","B","B","F","F","G","G","G","H","H"]],
  hasUniqueSolution: true,
}

export default level
