// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "79",
  regions: [["B","B","A","D","D","E","A"],["B","B","D","E","E","E","A"],["C","B","D","D","G","G","G"],["C","B","B","B","B","G","G"],["F","F","F","B","G","G","G"],["F","F","F","F","F","F","G"],["F","F","F","F","G","G","G"]],
  hasUniqueSolution: true,
}

export default level
