// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '8',
  regions: [
    ['B', 'B', 'B', 'B', 'B', 'B', 'A', 'A', 'G', 'G', 'G', 'G', 'G', 'G', 'G'],
    ['B', 'B', 'A', 'B', 'B', 'B', 'B', 'A', 'G', 'E', 'E', 'E', 'E', 'G', 'G'],
    ['C', 'B', 'A', 'B', 'D', 'A', 'A', 'A', 'G', 'E', 'J', 'E', 'G', 'G', 'G'],
    ['C', 'B', 'A', 'A', 'D', 'A', 'A', 'F', 'F', 'E', 'J', 'E', 'G', 'N', 'N'],
    ['K', 'B', 'B', 'A', 'A', 'A', 'J', 'F', 'J', 'J', 'J', 'E', 'G', 'G', 'N'],
    ['K', 'B', 'A', 'A', 'J', 'J', 'J', 'F', 'J', 'J', 'G', 'G', 'G', 'G', 'N'],
    ['K', 'B', 'B', 'A', 'J', 'A', 'J', 'J', 'J', 'G', 'G', 'J', 'N', 'N', 'N'],
    ['K', 'B', 'H', 'A', 'A', 'A', 'A', 'J', 'J', 'J', 'J', 'J', 'N', 'N', 'N'],
    ['K', 'H', 'H', 'K', 'I', 'I', 'A', 'J', 'K', 'J', 'J', 'J', 'J', 'J', 'N'],
    ['K', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'J', 'J', 'J', 'J', 'N'],
    ['K', 'K', 'O', 'O', 'O', 'O', 'O', 'J', 'J', 'J', 'J', 'N', 'N', 'N', 'N'],
    ['K', 'O', 'O', 'K', 'O', 'O', 'O', 'J', 'L', 'L', 'N', 'N', 'M', 'N', 'N'],
    ['K', 'O', 'K', 'K', 'O', 'O', 'O', 'N', 'L', 'N', 'N', 'M', 'M', 'N', 'N'],
    ['K', 'O', 'K', 'O', 'O', 'O', 'O', 'N', 'N', 'N', 'M', 'M', 'N', 'N', 'N'],
    ['K', 'K', 'K', 'K', 'O', 'O', 'O', 'O', 'O', 'M', 'M', 'M', 'M', 'M', 'N']
  ],
  hasUniqueSolution: true
}

export default level
