// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '8',
  regions: [
    ['F', 'F', 'F', 'F', 'F', 'F', 'H', 'H', 'D', 'D', 'D', 'D', 'D', 'D', 'D'],
    ['F', 'F', 'H', 'F', 'F', 'F', 'F', 'H', 'D', 'I', 'I', 'I', 'I', 'D', 'D'],
    ['B', 'F', 'H', 'F', 'K', 'H', 'H', 'H', 'D', 'I', 'O', 'I', 'D', 'D', 'D'],
    ['B', 'F', 'H', 'H', 'K', 'H', 'H', 'E', 'E', 'I', 'O', 'I', 'D', 'L', 'L'],
    ['M', 'F', 'F', 'H', 'H', 'H', 'O', 'E', 'O', 'O', 'O', 'I', 'D', 'D', 'L'],
    ['M', 'F', 'H', 'H', 'O', 'O', 'O', 'E', 'O', 'O', 'D', 'D', 'D', 'D', 'L'],
    ['M', 'F', 'F', 'H', 'O', 'H', 'O', 'O', 'O', 'D', 'D', 'O', 'L', 'L', 'L'],
    ['M', 'F', 'C', 'H', 'H', 'H', 'H', 'O', 'O', 'O', 'O', 'O', 'L', 'L', 'L'],
    ['M', 'C', 'C', 'M', 'G', 'G', 'H', 'O', 'M', 'O', 'O', 'O', 'O', 'O', 'L'],
    ['M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'O', 'O', 'O', 'O', 'L'],
    ['M', 'M', 'N', 'N', 'N', 'N', 'N', 'O', 'O', 'O', 'O', 'L', 'L', 'L', 'L'],
    ['M', 'N', 'N', 'M', 'N', 'N', 'N', 'O', 'J', 'J', 'L', 'L', 'A', 'L', 'L'],
    ['M', 'N', 'M', 'M', 'N', 'N', 'N', 'L', 'J', 'L', 'L', 'A', 'A', 'L', 'L'],
    ['M', 'N', 'M', 'N', 'N', 'N', 'N', 'L', 'L', 'L', 'A', 'A', 'L', 'L', 'L'],
    ['M', 'M', 'M', 'M', 'N', 'N', 'N', 'N', 'N', 'A', 'A', 'A', 'A', 'A', 'L']
  ],
  hasUniqueSolution: true
}

export default level
