// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "80",
  regions: [["D","G","G","F","F","F","F"],["D","G","C","F","F","F","F"],["G","G","C","C","C","F","F"],["G","G","G","G","C","F","F"],["B","B","G","C","C","A","F"],["G","B","G","C","E","A","F"],["G","G","G","G","E","A","F"]],
  hasUniqueSolution: true,
}

export default level
