// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "81",
  regions: [["G","G","G","G","G","G","G","G","L","L","L","L"],["G","H","E","G","G","B","G","G","L","L","K","L"],["G","H","E","E","G","B","B","L","L","K","K","L"],["G","E","E","G","G","B","G","K","K","K","L","L"],["G","E","E","E","G","G","G","G","K","K","L","L"],["G","E","J","E","E","A","A","K","K","K","K","L"],["J","E","J","E","E","A","A","K","K","L","L","L"],["J","J","J","J","J","A","K","K","I","I","L","L"],["J","K","K","J","J","A","K","I","I","C","L","L"],["J","J","K","K","K","K","K","K","I","C","C","C"],["J","K","K","K","K","K","K","K","D","C","F","C"],["J","J","J","J","D","D","D","D","D","C","F","C"]],
  hasUniqueSolution: true,
}

export default level
