// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "82",
  regions: [["C","C","C","C","C","G","G"],["C","A","A","C","G","G","E"],["C","A","C","C","C","G","E"],["C","A","A","C","F","G","B"],["A","A","D","F","F","G","B"],["A","D","D","D","F","B","B"],["D","D","F","F","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
