// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "83",
  regions: [["K","K","K","K","K","K","K","E","E","E","M","M","M"],["I","H","K","D","D","D","K","A","I","E","E","E","E"],["H","H","K","K","D","K","K","A","I","E","E","E","E"],["H","H","K","K","C","C","K","K","I","I","B","B","E"],["H","H","K","K","K","C","K","K","I","B","B","B","E"],["H","H","H","H","H","C","K","I","I","B","B","E","E"],["H","G","G","H","H","C","C","C","C","C","B","B","E"],["G","G","G","G","H","H","J","J","C","C","B","B","B"],["G","G","G","G","H","L","L","J","C","B","B","B","B"],["G","H","G","G","H","J","J","J","C","B","F","F","B"],["G","H","G","H","H","H","J","J","C","C","C","F","B"],["G","H","G","G","G","H","H","J","C","J","C","C","B"],["H","H","H","H","H","H","J","J","J","J","J","B","B"]],
  hasUniqueSolution: true,
}

export default level
