// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "84",
  regions: [["K","K","K","K","K","K","L","L","L","L","L","L","L","L","L","L"],["H","H","H","H","K","K","K","O","O","L","L","L","L","L","L","L"],["H","I","H","K","K","K","K","O","L","L","L","L","L","L","L","M"],["H","I","H","K","K","K","K","O","L","L","K","L","L","L","M","M"],["H","H","D","D","D","K","O","O","O","L","K","L","G","F","F","M"],["H","H","H","N","D","K","O","O","O","K","K","L","G","G","G","M"],["H","N","N","N","K","K","K","O","K","K","K","L","G","G","G","M"],["H","H","N","N","K","N","K","K","K","G","G","G","G","G","G","M"],["H","H","N","K","K","N","E","E","K","K","K","G","K","G","M","M"],["H","N","N","N","N","N","N","E","E","K","K","G","K","G","M","M"],["H","H","H","N","H","N","N","E","E","E","K","K","K","G","G","G"],["J","H","H","H","H","N","N","N","N","E","E","K","G","G","G","E"],["J","H","J","J","H","J","N","C","N","P","E","G","G","G","E","E"],["J","H","H","J","J","J","J","C","P","P","E","G","E","G","E","C"],["J","J","J","J","B","B","J","C","C","P","E","E","E","E","E","C"],["B","B","B","B","B","A","A","A","C","C","C","C","C","C","C","C"]],
  hasUniqueSolution: true,
}

export default level
