// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "85",
  regions: [["C","C","E","E","D"],["C","C","E","E","D"],["E","E","E","D","D"],["E","B","B","A","A"],["E","B","B","B","A"]],
  hasUniqueSolution: true,
}

export default level
