// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "86",
  regions: [["E","E","E","E","E","C","C"],["A","A","A","A","E","E","C"],["B","B","G","A","A","C","C"],["B","B","G","B","C","C","C"],["F","B","B","B","B","C","C"],["F","B","D","D","D","D","C"],["F","B","C","C","C","C","C"]],
  hasUniqueSolution: true,
}

export default level
