// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "87",
  regions: [["A","I","D","D","D","M","M","M","M","M","M","M","M","N"],["A","I","I","I","D","D","M","M","M","B","B","B","B","N"],["A","I","I","D","D","D","D","M","M","J","J","B","N","N"],["A","I","I","I","I","I","D","M","J","J","B","B","B","N"],["A","A","I","L","D","D","D","M","M","J","J","J","J","J"],["A","A","I","L","L","L","H","H","H","H","H","H","E","J"],["A","A","I","I","I","I","H","K","H","E","H","E","E","J"],["A","I","I","I","K","I","K","K","K","E","E","E","E","J"],["A","A","A","I","K","K","K","K","K","K","F","F","G","J"],["A","A","I","I","A","K","K","K","K","K","F","F","G","G"],["A","A","A","A","A","K","K","K","K","K","K","F","F","G"],["A","C","A","A","A","A","K","K","K","K","K","K","F","F"],["C","C","A","C","C","A","K","K","K","K","F","K","F","F"],["C","C","C","C","C","K","K","K","K","F","F","F","F","F"]],
  hasUniqueSolution: true,
}

export default level
