// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "88",
  regions: [["E","E","E","C","C"],["E","E","E","B","C"],["D","D","A","B","C"],["D","D","A","A","A"],["D","A","A","A","A"]],
  hasUniqueSolution: true,
}

export default level
