// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "89",
  regions: [["H","K","K","K","K","K","K","I","I","I","I"],["H","K","K","K","K","K","D","I","B","B","C"],["H","H","H","H","K","K","D","I","B","B","C"],["H","K","K","H","K","J","J","C","C","C","C"],["H","H","K","K","K","J","J","F","F","F","C"],["H","E","K","K","J","J","F","F","C","C","C"],["H","E","E","J","J","F","F","C","C","C","G"],["A","J","J","J","J","G","F","C","C","C","G"],["A","A","A","A","G","G","F","G","C","G","G"],["A","G","G","G","G","G","G","G","G","G","G"],["A","A","G","G","G","G","G","G","G","G","G"]],
  hasUniqueSolution: true,
}

export default level
