// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "9",
  regions: [["E","E","E","E","F","F","F","A","A","I","I","I","I","I","I"],["E","E","D","E","F","A","A","A","A","A","C","C","I","B","B"],["E","E","D","D","F","F","F","F","F","F","F","C","I","I","I"],["E","E","D","F","F","M","M","F","F","F","J","J","I","I","I"],["E","F","F","F","M","M","M","F","F","F","F","J","J","I","I"],["M","F","F","M","M","M","G","G","G","G","F","J","I","I","I"],["M","M","M","M","G","G","G","O","J","G","J","J","J","J","I"],["M","H","H","H","G","O","O","O","J","G","J","J","J","J","I"],["M","M","G","G","G","O","O","J","J","J","J","I","I","I","I"],["M","M","G","G","O","O","O","O","J","O","J","J","J","J","I"],["M","M","M","M","O","O","O","O","O","O","O","J","J","J","K"],["O","O","N","M","O","O","O","L","L","L","O","O","J","J","K"],["O","N","N","M","M","O","O","O","O","L","O","O","O","J","J"],["O","N","N","M","O","O","O","L","L","L","O","O","J","J","O"],["O","O","O","O","O","O","L","L","L","O","O","O","O","O","O"]],
  hasUniqueSolution: true,
}

export default level
