// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: '9',
  regions: [
    ['O', 'O', 'O', 'O', 'F', 'F', 'F', 'K', 'K', 'H', 'H', 'H', 'H', 'H', 'H'],
    ['O', 'O', 'A', 'O', 'F', 'K', 'K', 'K', 'K', 'K', 'L', 'L', 'H', 'J', 'J'],
    ['O', 'O', 'A', 'A', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'L', 'H', 'H', 'H'],
    ['O', 'O', 'A', 'F', 'F', 'C', 'C', 'F', 'F', 'F', 'N', 'N', 'H', 'H', 'H'],
    ['O', 'F', 'F', 'F', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'N', 'N', 'H', 'H'],
    ['C', 'F', 'F', 'C', 'C', 'C', 'D', 'D', 'D', 'D', 'F', 'N', 'H', 'H', 'H'],
    ['C', 'C', 'C', 'C', 'D', 'D', 'D', 'M', 'N', 'D', 'N', 'N', 'N', 'N', 'H'],
    ['C', 'E', 'E', 'E', 'D', 'M', 'M', 'M', 'N', 'D', 'N', 'N', 'N', 'N', 'H'],
    ['C', 'C', 'D', 'D', 'D', 'M', 'M', 'N', 'N', 'N', 'N', 'H', 'H', 'H', 'H'],
    ['C', 'C', 'D', 'D', 'M', 'M', 'M', 'M', 'N', 'M', 'N', 'N', 'N', 'N', 'H'],
    ['C', 'C', 'C', 'C', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'N', 'N', 'N', 'I'],
    ['M', 'M', 'B', 'C', 'M', 'M', 'M', 'G', 'G', 'G', 'M', 'M', 'N', 'N', 'I'],
    ['M', 'B', 'B', 'C', 'C', 'M', 'M', 'M', 'M', 'G', 'M', 'M', 'M', 'N', 'N'],
    ['M', 'B', 'B', 'C', 'M', 'M', 'M', 'G', 'G', 'G', 'M', 'M', 'N', 'N', 'M'],
    ['M', 'M', 'M', 'M', 'M', 'M', 'G', 'G', 'G', 'M', 'M', 'M', 'M', 'M', 'M']
  ],
  hasUniqueSolution: true
}

export default level
