// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "90",
  regions: [["E","E","E","E","E","E","E","E","E","E"],["D","E","E","E","I","I","E","G","G","E"],["D","D","F","E","E","I","E","G","G","E"],["D","I","F","F","E","I","E","E","E","E"],["D","I","I","I","I","I","I","I","I","E"],["D","D","D","A","I","B","B","B","I","I"],["D","A","A","A","I","J","B","C","C","I"],["H","A","A","C","I","J","B","B","C","I"],["H","A","C","C","C","B","B","C","C","I"],["A","A","C","C","C","C","C","C","C","I"]],
  hasUniqueSolution: true,
}

export default level
