// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "91",
  regions: [["G","G","G","E","E","C","C"],["F","G","G","G","E","E","C"],["F","D","D","G","G","C","C"],["F","F","F","F","G","C","C"],["F","F","F","F","G","G","C"],["F","F","F","F","B","C","C"],["F","A","A","F","B","C","C"]],
  hasUniqueSolution: true,
}

export default level
