// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "92",
  regions: [["C","C","C","H","H","H","J","J","J","J"],["C","H","C","H","H","H","H","J","J","J"],["C","H","C","H","H","H","H","J","J","F"],["H","H","H","H","D","J","J","J","J","F"],["H","H","G","D","D","J","G","J","J","F"],["H","H","G","G","D","D","G","G","J","A"],["H","H","G","G","G","G","G","G","A","A"],["G","H","G","E","I","I","I","I","A","I"],["G","H","G","E","E","G","I","I","I","I"],["G","G","G","G","G","G","G","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
