// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "93",
  regions: [["G","G","G","G","H","H","H","H","H","H","H","E"],["G","L","L","G","G","G","G","H","F","F","E","E"],["L","L","L","G","H","H","H","H","H","F","E","E"],["L","L","L","G","G","G","G","H","H","F","F","F"],["L","L","G","G","G","H","H","H","H","F","B","B"],["J","L","L","L","L","L","H","C","H","F","F","B"],["J","J","I","I","K","K","C","C","H","F","B","B"],["J","J","I","I","I","I","C","F","F","F","B","D"],["J","J","J","J","C","C","C","F","C","F","B","D"],["J","J","J","C","C","C","F","F","C","B","B","D"],["J","J","C","C","C","C","C","C","C","C","B","C"],["A","A","C","C","C","C","C","C","C","C","C","C"]],
  hasUniqueSolution: true,
}

export default level
