// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "94",
  regions: [["H","G","G","G","G","G","G","G","C"],["H","H","B","F","G","C","C","C","C"],["H","H","B","F","G","G","C","C","C"],["H","H","H","F","F","G","G","C","C"],["H","H","H","F","F","F","G","C","C"],["H","H","E","E","F","C","C","C","C"],["I","H","F","F","F","F","C","C","C"],["I","H","F","F","A","F","F","C","C"],["I","A","A","A","A","D","D","C","C"]],
  hasUniqueSolution: true,
}

export default level
