// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "95",
  regions: [["H","H","H","H","H","J","J","J","J","C"],["H","J","J","J","J","J","A","A","A","C"],["H","H","H","J","A","A","A","A","A","C"],["E","E","E","J","A","A","A","F","F","C"],["E","J","E","J","J","A","A","A","A","C"],["E","J","J","J","A","A","A","A","A","A"],["J","J","I","J","J","J","A","A","A","A"],["B","J","I","D","D","J","J","J","A","A"],["B","B","I","I","D","D","G","G","G","A"],["B","I","I","D","D","G","G","G","A","A"]],
  hasUniqueSolution: true,
}

export default level
