// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "96",
  regions: [["H","H","H","H","H","H","H","H","H","H","H","H","H","H","H","H"],["L","L","H","H","H","H","H","L","L","H","H","K","K","K","K","H"],["L","H","H","H","L","H","L","L","L","H","H","H","H","H","K","H"],["L","H","H","L","L","L","L","L","L","L","B","H","K","K","K","H"],["L","L","L","L","E","E","E","L","L","L","B","H","H","P","K","H"],["L","L","G","G","L","O","E","L","L","B","B","H","P","P","K","H"],["L","L","L","L","L","O","O","O","L","B","H","H","P","K","K","H"],["L","O","O","L","O","O","A","O","L","B","H","M","P","K","K","K"],["D","O","N","N","O","O","A","A","M","M","M","M","M","M","M","K"],["D","O","O","N","O","O","O","A","A","J","J","M","M","K","M","K"],["C","C","O","N","O","F","O","O","A","M","M","M","M","K","M","K"],["C","O","O","O","O","F","O","M","M","M","I","I","M","K","K","K"],["C","O","O","O","F","F","F","F","I","I","I","I","M","K","K","K"],["C","O","O","O","F","O","F","I","I","I","M","M","M","K","K","K"],["C","C","O","O","O","O","I","I","I","I","I","I","M","M","I","I"],["C","C","C","O","O","I","I","I","I","I","I","I","I","I","I","I"]],
  hasUniqueSolution: true,
}

export default level
