// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "97",
  regions: [["F","F","F","B","B","B","B"],["F","D","D","G","G","B","B"],["F","D","G","G","G","B","B"],["F","D","G","G","B","B","B"],["E","A","A","G","B","B","B"],["E","E","A","A","A","A","B"],["A","A","A","C","C","A","A"]],
  hasUniqueSolution: true,
}

export default level
