// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "98",
  regions: [["D","G","A","A","A","A","E","E","E"],["D","G","G","A","H","H","E","E","E"],["G","G","G","H","H","H","H","E","E"],["G","G","G","H","H","F","H","E","E"],["C","C","G","H","F","F","H","H","E"],["C","G","G","H","B","F","E","E","E"],["G","G","G","H","B","B","E","B","E"],["I","I","I","I","B","B","B","B","B"],["I","I","I","B","B","B","B","B","B"]],
  hasUniqueSolution: true,
}

export default level
