// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
import type { Level } from '../../generator/types'

const level: Level = {
  id: "99",
  regions: [["B","B","B","B","B","E","E","E","E","L","L","K","K"],["B","H","H","H","B","C","C","C","E","E","K","K","K"],["B","H","H","H","C","C","C","C","C","E","E","E","K"],["B","J","G","H","H","C","C","E","E","E","E","K","K"],["B","J","G","G","H","H","H","H","D","E","D","I","I"],["J","J","G","G","H","H","D","H","D","D","D","I","I"],["J","G","G","H","H","M","D","D","D","D","I","I","I"],["J","G","H","H","M","M","M","D","D","I","I","D","I"],["G","G","G","H","H","M","M","D","I","C","D","D","I"],["G","G","G","H","H","H","M","D","D","D","D","I","I"],["G","G","M","M","H","M","M","D","D","A","A","I","I"],["G","G","M","H","H","M","D","D","F","A","I","I","A"],["M","M","M","M","M","M","M","F","F","A","A","A","A"]],
  hasUniqueSolution: true,
}

export default level
